### ISSUE TITLE
Optimisation question for applying lots of filters in a chain

### ISSUE THREAD

**Issue by alittle433** [MetalPetal/MetalPetal#100]
Currently I have a project thats doing real-time video editing, I'm using metal petal and custom filters to produce different effects, filters and adjustments for the pixel buffers. My question is that when monitoring the performance of chaining multiple filters (up to 15 for every frame) it can be taxing. What is the best way to go about chaining filters so that I can do it all in one render pass.

**Comment by YuAo** [comment]
First you need to analyze the performance bottleneck. Is it the command encoding process? or memory bandwidth? or on the GPU side, i.e. shader performance? 

Then act based on your findings.

---

It is recommended to have as few render passes as possible. It can reduce the cost of command encoding, memory read/write/bandwidth. But if the shader performance is your bottleneck, having fewer render passes may not do much help.

A simple way to reduce the number of render passes is to convert your filters to `MTIRenderCommand`s. There can be more than one render command in one render pass. You'll need to use `[[color(n)]]` in your shaders to read pixel values across render commands. However if your shader requires the sampling of neighborhood pixels, for example a blur filter, you'll need a new render pass.
