### ISSUE TITLE
Picture in picture

### ISSUE THREAD

**Issue by kallipigous** [MetalPetal/MetalPetal#103]
I've been tasked with combining two videos together (they are the same length). Effectively one video stays full screen and another (from a different angle) is placed in one of the corners (offset a little from the edge). It occurs to me I could export out a series of stills of the little video and overlay them with a Multilayer Composite filter. I'm presuming this filter needs the two images to to be the same size so I'd have to render out a full size image with a little poster with an alpha channel?

Is there a way of doing this in one pass?

Cheers

Toby

**Comment by YuAo** [comment]
You can use a video as the "background" of a multilayer compositing filter and another video as a "layer", you can set the layer's position and size. You don't have to render out a full size image with a little poster.

**Comment by kallipigous** [comment]
Thank you. I was trying to work out how multilayer compositing worked. I’ll have a play.
