### ISSUE TITLE
renderImage SIGNAL SIGABRT 

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#104]
Hi. I often get an error - _validateRenderPassDescriptor:782: failed assertion `Either set rendertargets in RenderPassDescriptor or set renderTargetWidth and renderTargetHeight.'_

When I call this method `- (BOOL)renderImage:(MTIImage *)image toDrawableWithRequest:
(MTIDrawableRenderingRequest *)request error:(NSError **)error 
NS_SWIFT_NAME(render(_:toDrawableWithRequest:));`

 I added a screenshot of stack trace 
<img width="524" alt="Снимок экрана 2019-09-13 в 12 01 55" src="https://user-images.githubusercontent.com/29518174/64843494-b2e18d80-d61e-11e9-9ab4-25f96a48eeb9.png">

Could you tell me what could be the problem? Thanks for your attention.

**Comment by YuAo** [comment]
https://github.com/MetalPetal/MetalPetal/issues/60#issuecomment-456837693
