### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by jrabek** [MetalPetal/MetalPetal#105]
Thanks for the great framework!

Is there any interest in supporting Carthage?  I would be happy to make a PR for adding the necessary shared scheme.

**Comment by YuAo** [comment]
Thanks. But we have no plan of supporting Carthage currently.

There's a script to generate dynamic `.frameworks` for you. You need to first install CocoaPods/Rome, then run [/Rome/build_frameworks.sh](https://github.com/MetalPetal/MetalPetal/blob/master/Rome/build_frameworks.sh)
