### ISSUE TITLE
MTIAlphaType 为什么不支持MTIAlphaTypePremultiplied类型

### ISSUE THREAD

**Issue by gmfxch** [MetalPetal/MetalPetal#106]
试了下直接给图片加模糊滤镜，结果断在了Assert里面

代码
    UIImage  *oriImage = [UIImage imageNamed:@"picture.png"];
    MTIImage *inputImage = [[MTIImage alloc] initWithCIImage:[CIImage imageWithCGImage:oriImage.CGImage]];
    MTIMPSGaussianBlurFilter  *filter = [[MTIMPSGaussianBlurFilter alloc] init];
    filter.radius = 20;
    filter.inputImage = inputImage;
    MTIImage *outputImage = filter.outputImage;

断在了这里 NSParameterAssert({
            /* Alpha Type Assert */
            BOOL canAcceptAlphaType = YES;
            for (MTIImage *image in inputImages) {
                if (![kernel.alphaTypeHandlingRule canAcceptAlphaType:image.alphaType]) {
                    canAcceptAlphaType = NO;
                    break;
                }
            }
            canAcceptAlphaType;
        });

试了很多图片，jpg和png格式的都试过，AlphaType都是MTIAlphaTypePremultiplied类型，目前是不支持这种么？

**Comment by YuAo** [comment]
Please read the documentation: https://github.com/MetalPetal/MetalPetal#alpha-type-handling

You can call `unpremultiplyingAlpha()` or `premultiplyingAlpha()` on a MTIImage to convert the alpha type of the image.
