### ISSUE TITLE
MTIContext not initializing

### ISSUE THREAD

**Issue by malemo** [MetalPetal/MetalPetal#107]
Hello, 

I'm trying to run a sample code you provide in the description:

       var toOutPut: CIImage!
       let inputImage = MTIImage(ciImage: ouputex).unpremultiplyingAlpha()

       let filter = MTISaturationFilter()
       filter.saturation = 0
       filter.inputImage = inputImage
        
       let outputImage = filter.outputImage
       
       let options = MTIContextOptions()

       guard let device = MTLCreateSystemDefaultDevice(),
        let myContext = try? MTIContext(device: device, options: options) else {
            print("failed to create context")
            return	
        }

       do {
           try toOutPut =  myContext.makeCIImage(from: outputImage!)
       } catch {
           print(error)
       }

It does not initialize myContext, throws a return and I see the "failed to create context message".

What could be the issue?

**Comment by YuAo** [comment]
Looks like the device you're using does not support metal.

**Comment by malemo** [comment]
I've updated to mac os 15.0 which should support metal in simulator

still get this error : error 'Error: MPS does not support the iOS simulator.'

**Comment by YuAo** [comment]
I don't have macOS 10.15 now. Will investigate after upgrade. The suggestion is to run and test your app on a real device.

**Comment by malemo** [comment]
screenshot here:
https://imgur.com/a/oVEAj0O
