### ISSUE TITLE
Surface Blur not working as expected

### ISSUE THREAD

**Issue by malemo** [MetalPetal/MetalPetal#108]
May be I'm doing something wrong but this implementation is very different from Photoshop Surface blur.

Original Image: https://imgur.com/a/2wKecWH

Radius 5 to 10 (with threshold 35) works more or less fine

When I set radius 25, threshold 35 this is what i see: https://imgur.com/a/xaMn50m

In photoshop even with maximum radius 100 the image looks smooth and blurred

Am I missing some settings or something?

My code: 

                let inputImage = MTIImage(ciImage: ouputex).unpremultiplyingAlpha()

               let filter  = MTISurfaceBlurFilter(radius: 25)
               filter.threshold = 35
               filter.inputImage = inputImage;

               let outputImage = filter.outputImage

               let options = MTIContextOptions()

               var out: CIImage!
               out = ouputex
               guard let device = MTLCreateSystemDefaultDevice(),
               let myContext = try? MTIContext(device: device, options: options) else {return}

               do {
                   out = try myContext.makeCIImage(from: outputImage!)

               } catch {
                   print(error)
               }                
                toOutPut(output: out!, ex: ouputex)

**Comment by YuAo** [comment]
Looks like a problem of precision. The current implementation of surface blur in MetalPetal uses `half` float. Changing the `half`s in the shader to `float`s should make the result much better. I'll try to apply the change to the Surface Blur repo when I have time.

**Comment by malemo** [comment]
you are right, changing half to float does make a difference, now it works fine. thank you.

one other thing I noticed is that this filter reduces the overall image saturation a bit, any idea why this is happening?

**Comment by YuAo** [comment]
@malemo not sure about the reducing saturation. If you have any clues/ideas please let me know.
