### ISSUE TITLE
Error: MPS does not support the iOS simulator.'

### ISSUE THREAD

**Issue by malemo** [MetalPetal/MetalPetal#109]
Running on iPhone Device iOS 13.1.2 it works fine.

However, while trying to run on iPhone Simulator (iOS 13) I face this error:
https://imgur.com/a/oVEAj0O

I use xCode 11, macOs 10.15 GM

Has anybody experienced this issue?

**Comment by dannydaddy3** [comment]
Yeah, the same thing.
In last commits to the project there were added some fixes for Xcode 10 simulators lately, and now this problem happens with Xcode 11 simulators, so I think that fix needed for new Xcode 11 as well..

**Comment by YuAo** [comment]
MetalPerformanceShaders is not supported on the simulator currently. However it is possible for MetalPetal to run on the simulator with some workaround. I'll take a look in the next few days.

Please notice. Simulator's features differ significantly from modern Apple GPUs. With some filter I may need to use the macOS branch to make it work on a simulator. Do not use simluators to develop render pipeline or filters.

**Comment by dannydaddy3** [comment]
@YuAo 
Well, sometimes I need to just open app in simulator to make screenshots for AppStore for example, and it's impossible to do because of crash. For this case, it would be good to allow using app, although filters wouldn't work

**Comment by YuAo** [comment]
Added basic simulator support. b0cc46253def3cb5ca2830e6c7cdcb6f824dc6d9
@dannydaddy3 You can also opt-out the support if anything goes wrong. ref:  a763bebe44d491c16c61fc737f9e1590bce64362

**Comment by YuAo** [comment]
Released 1.6.0 with Simulator render support.

**Comment by vjdaemp** [comment]
I am still having an issue running on the simulator.

For example, add the following lines to sample app's `TripleBufferingViewController.swift` :

```
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    let device = MTLCreateSystemDefaultDevice()
        
    let supported = MTIHighPassSkinSmoothingFilter.isSupported(on: device!)
        
    print ("MPS supported? \(supported)")
        
}
```

Run app in simulator, open the triple buffering view controller, and then observe the following error in console:

```
/Library/Caches/com.apple.xbs/Sources/MetalImage_Sim/MetalImage-122.5.5/MPSCore/Utility/MPSDevice.mm, line 77: error 'Error: MPS does not support the iOS simulator.'
/Library/Caches/com.apple.xbs/Sources/MetalImage_Sim/MetalImage-122.5.5/MPSCore/Utility/MPSDevice.mm:77: failed assertion `Error: MPS does not support the iOS simulator.'

```

Looks like a simulator bug ? I wonder what would happen if this is ran on a real device that does not support MPS.  Apple GPUs in family A8 and above support MPS.

**Comment by YuAo** [comment]
@vjdaemp `MetalPerformanceShaders.framework` does not support the iOS simulator. It works well on a real device.

**Comment by vjdaemp** [comment]
@YuAo Thanks for the clarification.
