### ISSUE TITLE
Support YUV CVPixelBuffer output 

### ISSUE THREAD

**Issue by notedit** [MetalPetal/MetalPetal#11]
When use none BGRA color format(for example  nv12 or i420),  it is boring to to color format convert. Hope  MetalPetal can support this

**Comment by omarojo** [comment]
Output to CVPixelBuffer at the end of the chain, would be great. So we can use that output for other stuff like making videos or publishing to a live stream or something else.

**Comment by YuAo** [comment]
MTIContext object supports rendering a MTIImage to a CVPixelBuffer. However it can only render to a BGRA pixel buffer now.

**Comment by YuAo** [comment]
Will consider the "render to YUV" feature.

**Comment by notedit** [comment]
i see CoreImage support render to yuv CVPixelBuffer.  but it cost too much cpu.  more than 100% cpu will be used.
```
  [ciContext render:outimage toCVPixelBuffer:outPixelBuffer];
```
is there any way to reduce the cpu use?

**Comment by notedit** [comment]
it seems  it is because of  https://github.com/YuAo/YUCIHighPassSkinSmoothing,  move the discussion to  https://github.com/YuAo/YUCIHighPassSkinSmoothing/issues/11

**Comment by YuAo** [comment]
@omarojo Render to YUV pixel buffer is implemented on supported hardware (MTLFeatureSet_iOS_GPUFamily3_v1). ref: 2226c0f3161a4f70e99b818aad2a49cb720162a9

Not fully tested, use with caution.

Here's an example:
```
NSError *error;
CVPixelBufferRef pixelBuffer;
CVPixelBufferCreate(kCFAllocatorDefault, outputImage.size.width, outputImage.size.height, kCVPixelFormatType_420YpCbCr8BiPlanarFullRange, (__bridge CFDictionaryRef)(@{(id)kCVPixelBufferIOSurfacePropertiesKey: @{}}), &pixelBuffer);
[context renderImage:outputImage toCVPixelBuffer:pixelBuffer error:&error];
//use the pixelBuffer
//....
//release the pixelBuffer
CVPixelBufferRelease(pixelBuffer);
```
