### ISSUE TITLE
Tone Curve Filter is NOT accurate

### ISSUE THREAD

**Issue by malemo** [MetalPetal/MetalPetal#111]
I'm trying to replicate a Tone curve from photoshop. 

         let mtiIMG = MTIImage(ciImage: sourceIMG).unpremultiplyingAlpha()

        let vec1 = MTIVector(value: CGPoint(x: 0.35, y: 0))
        let vec2 = MTIVector(value: CGPoint(x: 0.5, y: 1))
        let vec3 = MTIVector(value: CGPoint(x: 0.65, y: 0))
  
        
        let crv = MTIRGBToneCurveFilter()
        crv.rgbCompositeControlPoints.append(vec1)
        crv.rgbCompositeControlPoints.append(vec2)
        crv.rgbCompositeControlPoints.append(vec3)
        crv.inputImage = mtiIMG

        let outputImage21 = crv.outputImage

and the results are completely different from that of photoshop curve.

Am I missing something?

**Comment by YuAo** [comment]
Yes. The curve you create is not complete - no y value is defined for x = 0 and x = 1.
