### ISSUE TITLE
Save MTIImage to disk [enhancement]

### ISSUE THREAD

**Issue by vjdaemp** [MetalPetal/MetalPetal#112]
I'd like to request quick method to write MTIImage to disk.  There are MTIImage's that I'd like to temporarily store to disk to reduce memory load. I am currently converting to MTIImage to UIImage to Data, and then writing to disk. Would be nice if there was a more direct way to achieve this.

**Comment by dannydaddy3** [comment]
I need the same feature. 
I can have up to ~100 images to filter, and the only way to store them is on disk. 
So for now converting MTIImage -> UIImage -> Data and back Data -> UIImage -> MTIImage for each image to apply filter will take a lot more work. 

@YuAo could you please add this feature? And maybe you could advice something for filtering big number of images that lay on disk, what would be the most efficient way with MetalPetal?

**Comment by dannydaddy3** [comment]
Hi, @YuAo!
I'm just wondering when do you plan to add this feature? Really need it!

**Comment by omarojo** [comment]
You guys want a function that does what you are already doing, integrated into MetalPetal?

I don't think the feature you guys are asking for should be part of MetalPetal. That’s why the library does not have classes to record video or take pictures, is not ir’s job to do that. It limits itself to be a rendering engine.

But Maybe @YuAo can suggest an approach tho.

**Comment by dannydaddy3** [comment]
@omarojo Ok, so, there's only one way to convert Data to MTIImage (Data->UIImage->CIImage/CGImage->MTIImage - 3 steps) and 100% no more straight and fast way to do this? Maybe somehow encode/decode MTIImage contents? 
Because it "seems" it has to be faster way than this, but I'm not that good at Metal so don't really know for sure. 

Could you clarify this?

**Comment by dannydaddy3** [comment]
Because @YuAo assign this task to himself, I thought that it IS possible. But let's wait what he says

**Comment by vjdaemp** [comment]
@omarojo No, we are asking @YuAo to add a feature (if possible) to go from MTIImage to Data more efficiently.

Like @dannydaddy3 , I believe that Metal may provide a more efficient way to convert from MTIImage to Data. There may be some private metal components we need to access that MetalPetal does not expose publicly.

We need @YuAo 's feedback to determine if:

1. Our current method is most efficient, and no MetalPetal update is required.
2. There is a more efficient method that does not require MetalPetal update
3. There is a more efficient method, but it requires a MetalPetal update for us to get access to the Data.

**Comment by YuAo** [comment]
It's all about trade off. 

In fact you are doing pretty good. Turning RAM consuming GPU textures to compressed image data on disk:
MTIImage -> GPU Texture -> CGImage(UIImage) -> Encoding -> Data -> Disk.

However, if you are willing to pay more disk space, you may able to do it faster. 

There are two steps in saving a UIImage to disk:
1. Encode the image to JPEG or PNG data.
2. Save the data to disk.

The first step is very slow. It takes about 60ms on iPhone X to encode a 1080p image to jpeg data, about 300ms when using png.

You can skip the first step, and save the image buffer directly to disk. This not only eliminate the time needed to encode the image but also eliminate the time needed to decode the image data when you want to load the image back.

You can save the image buffer directly by:
1. Rendering a MTIImage to a CVPixelBuffer.
2. Lock the CVPixelBuffer's base address. (CVPixelBufferLockBaseAddress)
3. Create a data object from the buffer. (Using CVPixelBufferGetBaseAddress, CVPixelBufferGetDataSize). You can use Data(bytesNoCopy:....) to create the data object without copying the data.
4. Save the data to disk. 
6. Unlock the CVPixelBuffer's base address.
7. Save the image's info (height,width,rowBytes,format,etc...).

Then you can create a MTIImage from the saved data using `MTIImage(bitmapData:width:height:bytesPerRow:pixelFormat:alphaType:)`

However, without any compression, you need more disk space. For example, a 1080p jpeg image is usually less than 1MB. A 1080p 4-channel 8-bit image buffer takes 1080x1920x4 = 7.9MB. And saving larger data to disk will take some more time.

If you are using png files currently, the no-encoding-decoding approach is probably better.
If you are using jpeg files currently, you may want to do some benchmarks to decide which approach is better for your case.

```
// no-encoding-decoding

// save
var pixelBuffer: CVPixelBuffer!
CVPixelBufferCreate(kCFAllocatorDefault, width, height, kCVPixelFormatType_32BGRA, [kCVPixelBufferIOSurfacePropertiesKey as String: [:]] as CFDictionary, &pixelBuffer)

try context.render(outputImage, to: pixelBuffer)

CVPixelBufferLockBaseAddress(pixelBuffer, .readOnly)
defer {
    CVPixelBufferUnlockBaseAddress(pixelBuffer, .readOnly)
}

let bytesPerRow = CVPixelBufferGetBytesPerRow(pixelBuffer)

let data = Data(bytesNoCopy: CVPixelBufferGetBaseAddress(pixelBuffer)!, count: CVPixelBufferGetDataSize(pixelBuffer), deallocator: Data.Deallocator.none)

try data.write(to: tempURL)

// load
let loadedData = try Data(contentsOf: tempURL)
let loadedMTIImage = MTIImage(bitmapData: loadedData, width: width, height: height, bytesPerRow: UInt(bytesPerRow), pixelFormat: .bgra8Unorm, alphaType: .alphaIsOne)

// use
filter.inputImage = loadedMTIImage
let filteredLoadedImage = filter.outputImage!
let outputCGImage = try context.makeCGImage(from: filteredLoadedImage)
```

```
// encoding-decoding

// save
let cgImage = try context.makeCGImage(from: outputImage)
let uiImage = UIImage(cgImage: cgImage)
let data = uiImage.jpegData(compressionQuality: 0.9)
try data?.write(to: tempURL)

// load
let loadedImage = UIImage(contentsOfFile: tempURL.path)
let loadedCGImage = loadedImage!.cgImage!
let loadedMTIImage = MTIImage(cgImage: loadedCGImage, options: [.SRGB: false], isOpaque: true)

// use
filter.inputImage = loadedMTIImage
let filteredLoadedImage = filter.outputImage!
let outputCGImage = try context.makeCGImage(from: filteredLoadedImage)
```

**Comment by vjdaemp** [comment]
@YuAo Thank you very much for the detailed response. I will follow recommended approach and perform benchmarking to determine which method is best for my application.
