### ISSUE TITLE
Flipped coordinates

### ISSUE THREAD

**Issue by swiftlili** [MetalPetal/MetalPetal#113]
When I use MTIimage.cropped(to: CGRect),  the Y coordinates is flipped... the x0 and y0 are on the top left corner, which is different from Core image where x0 and y0 are in the bottom left corner. How can I flip coordinate plane?

I have an MTI image which needs to be cropped to certain CGRect. I tried this approach ( mtiimage.size.height - y, for y coordinates it does not work)

**Comment by YuAo** [comment]
```
CGPoint CGPointFlipped(CGPoint point, CGRect bounds) {
    return CGPointMake(point.x, CGRectGetMaxY(bounds)-point.y);
}

CGRect CGRectFlipped(CGRect rect, CGRect bounds) {
    return CGRectMake(CGRectGetMinX(rect),
                      CGRectGetMaxY(bounds)-CGRectGetMaxY(rect),
                      CGRectGetWidth(rect),
                      CGRectGetHeight(rect));
}
```

**Comment by swiftlili** [comment]
Thanks @YuAo  , i'm new to swift, would really appreciate if you tell me where should i put those functions and where to call them. 

Should i put it in MTICropFilter.m?

`//
//  MTICropFilter.m
//  MetalPetal
//
//  Created by Yu Ao on 28/10/2017.
//

#import "MTICropFilter.h"
#import "MTIRenderPipelineKernel.h"
#import "MTIFunctionDescriptor.h"
#import "MTIRenderPassOutputDescriptor.h"
#import "MTIImage.h"

MTICropRegion MTICropRegionMake(CGRect rect, MTICropRegionUnit unit) {
    return (MTICropRegion) {
        .bounds = rect,
        .unit = unit
    };
}

@implementation MTICropFilter
@synthesize outputPixelFormat = _outputPixelFormat;
@synthesize inputImage = _inputImage;

- (instancetype)init {
    if (self = [super init]) {
        _cropRegion = MTICropRegionMake((CGRect){0, 0, 1, 1}, MTICropRegionUnitPercentage);
        _scale = 1;
    }
    return self;
}

+ (MTIRenderPipelineKernel *)kernel {
    static MTIRenderPipelineKernel *kernel;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        kernel = [[MTIRenderPipelineKernel alloc] initWithVertexFunctionDescriptor:[[MTIFunctionDescriptor alloc] initWithName:MTIFilterPassthroughVertexFunctionName]
                                                        fragmentFunctionDescriptor:[[MTIFunctionDescriptor alloc] initWithName:MTIFilterPassthroughFragmentFunctionName]
                                                                  vertexDescriptor:nil
                                                              colorAttachmentCount:1
                                                             alphaTypeHandlingRule:MTIAlphaTypeHandlingRule.passthroughAlphaTypeHandlingRule];
    });
    return kernel;
}




- (MTIImage *)outputImage {
    if (!self.inputImage || (self.cropRegion.bounds.size.width <= 0 || self.cropRegion.bounds.size.height <= 0)) {
        return nil;
    }
    
    CGRect cropRect = CGRectZero;
    switch (self.cropRegion.unit) {
        case MTICropRegionUnitPixel: {
            cropRect = self.cropRegion.bounds;
        } break;
        case MTICropRegionUnitPercentage: {
            cropRect = CGRectMake(self.cropRegion.bounds.origin.x * self.inputImage.size.width,
                                  self.cropRegion.bounds.origin.y * self.inputImage.size.height,
                                  self.cropRegion.bounds.size.width * self.inputImage.size.width,
                                  self.cropRegion.bounds.size.height * self.inputImage.size.height);
        } break;
        default: {
            NSAssert(NO, @"Unsupported MTICropRegionUnit");
            return nil;
        } break;
    }
    
    

    CGRect rect = CGRectMake(-1, -1, 2, 2);
    CGFloat l = CGRectGetMinX(rect);
    CGFloat r = CGRectGetMaxX(rect);
    CGFloat t = CGRectGetMinY(rect);
    CGFloat b = CGRectGetMaxY(rect);
    
    CGFloat minX = cropRect.origin.x/self.inputImage.size.width;
    CGFloat minY = cropRect.origin.y/self.inputImage.size.height;
    CGFloat maxX = CGRectGetMaxX(cropRect)/self.inputImage.size.width;
    CGFloat maxY = CGRectGetMaxY(cropRect)/self.inputImage.size.height;
    
    
    
    
    MTIVertices *geometry = [[MTIVertices alloc] initWithVertices:(MTIVertex []){
        { .position = {l, t, 0, 1} , .textureCoordinate = { minX, maxY } },
        { .position = {r, t, 0, 1} , .textureCoordinate = { maxX, maxY } },
        { .position = {l, b, 0, 1} , .textureCoordinate = { minX, minY } },
        { .position = {r, b, 0, 1} , .textureCoordinate = { maxX, minY } }
    } count:4 primitiveType:MTLPrimitiveTypeTriangleStrip];
    
    double (*roundingFunction)(double);
    switch (self.roundingMode) {
        case MTICropFilterRoundingModePlain:
        roundingFunction = round;
        break;
        case MTICropFilterRoundingModeFloor:
        roundingFunction = floor;
        break;
        case MTICropFilterRoundingModeCeiling:
        roundingFunction = ceil;
        break;
        default:
        roundingFunction = round;
        break;
    }
    
    NSUInteger outputWidth = roundingFunction(cropRect.size.width * self.scale);
    NSUInteger outputHeight = roundingFunction(cropRect.size.height * self.scale);
    
    if (outputWidth == self.inputImage.size.width && outputHeight == self.inputImage.size.height && cropRect.origin.x == 0 && cropRect.origin.y == 0) {
        return self.inputImage;
    }
    
    MTIRenderPassOutputDescriptor *outputDescriptor = [[MTIRenderPassOutputDescriptor alloc] initWithDimensions:(MTITextureDimensions){.width = outputWidth, .height = outputHeight, .depth = 1} pixelFormat:self.outputPixelFormat];
    
    MTIRenderCommand *command = [[MTIRenderCommand alloc] initWithKernel:MTICropFilter.kernel geometry:geometry images:@[self.inputImage] parameters:@{}];
    return [MTIRenderCommand imagesByPerformingRenderCommands:@[command]
                                            outputDescriptors:@[outputDescriptor]].firstObject;
}

@end
`

**Comment by YuAo** [comment]
You can just change your `mtiimage.size.height - y` to `mitimage.size.height - yourRect.maxY`

**Comment by swiftlili** [comment]
sorry, I don't understand

let's say I have a:
`let rec = CGRect(x: 0, y: 0, width: 500, height: 500)`

when I do:
`myMTIimage = MTIImage(ciImage: sourceCI).unpremultiplyingAlpha().cropped(to: rec)`

the image is cropped from top left zero point coordinates

When I change the y origin of the rec it goes out of bounds. 

I want 0,0 to be on the bottom left instead

is there a way to may be change MTIContext coordinates plane, like CIContext has  translateby and offset
`context.translateBy(x: 0, y: mtiimage.size.height)` and `context.scaleBy(x: 1.0, y: -1.0)`

**Comment by YuAo** [comment]
You can't change the coordinate system of `MTIContext`, it is designed to have a top-left origin.

Also I don't think you can change the `CIContext`'s origin. `CIContext` does not have the `translateBy` and `scaleBy` methods.

For cropping, you can easily flip the rect, using the code I posted before. For instance,
```
var rect = CGRect(x: 0, y: 0, width: 500, height: 500)
rect.y = mtiimage.size.height - rect.maxY
```

If you'd like to flip a `MTIImage`, you can call `let flippedImage = mtiimage.oriented(.down)`

**Comment by swiftlili** [comment]
Thank you, I got it working by flipping `rect.origin.y ` 

For the `translateBy` and `scale`, I meant to say CGContext has those methods, not CIContext
