### ISSUE TITLE
The MTIImage results show a darker color

### ISSUE THREAD

**Issue by liangjie90** [MetalPetal/MetalPetal#114]
MTIImage *waterMarkImage = [[MTIImage alloc] initWithCGImage:[UIImage imageNamed:@"water_mark"].CGImage options:nil];

I loaded the image this way and it showed a darker color than the original

**Comment by omarojo** [comment]
instantiate the MTIimage with SRGB to true.

**Comment by YuAo** [comment]
try
```
[[MTIImage alloc] initWithCGImage:[UIImage imageNamed:@"water_mark"].CGImage options:@{MTKTextureLoaderOptionSRGB: @(NO)} isOpaque:NO];
```

Actually you the value of MTKTextureLoaderOptionSRGB should be determined by your render pipeline. Currently MetalPetal does not insert any color conversion pipeline for you, so you probably what to process and display sRGB images, you should set the MTKTextureLoaderOptionSRGB to NO to tell the texture loader to load your input image without using a sRGB texture.

**Comment by sealband** [comment]
This help me a lot and save time
