### ISSUE TITLE
Question: combine of CPU & GPU image processing 

### ISSUE THREAD

**Issue by flappyBug** [MetalPetal/MetalPetal#117]
I need to implement an complicated image processing algorithm, which has some part can be accelerated by GPU but some part better using CPU, so I need a way to read and manipulate the raw pixel buffer as a bitmap . Do I have better solution other than using `MTIImage(cvPixelBuffer:alphaType: )` and `MTIContext.render(image, to: pixelBuffer)`  to transfer between `MTIImage` and `CVPixelBuffer`?

**Comment by YuAo** [comment]
Can you use a computer kernel?
If your CPU algorithm cannot be implemented using a compute processing pipeline, you have to wait for the GPU to finish its work then do your CPU image processing. Be sure to lock the base address of a pixel buffer before accessing it using CPU (and unlock afterwards).
