### ISSUE TITLE
Would you consider adding mesh wraping？

### ISSUE THREAD

**Issue by KerwinCheung** [MetalPetal/MetalPetal#118]
I‘m trying to make functionality of Image Warp , but I didn't want to use OpenGL and I haven't touched it before.
When I learned about Metal, I felt that the learning materials are so poor that I can only learn from apple.
Can you give me some advice on learning Metal？
Thanks～

**Comment by YuAo** [comment]
What kind of warp would you like to make? Mesh transform?

**Comment by KerwinCheung** [comment]
yeah～
Actually I am trying to make  Animated feature effect of PLOTAVERSE.
I have several plans,and i have tried. The effect is not ideal.
I want to learn Metal by the way.
By trying OpenGL mesh wrapping, I know that it is not implemented using openGL or Metal.
But I still look forward to your completion of this lib.
