### ISSUE TITLE
try? context.makeCGImage(from: output)

### ISSUE THREAD

**Issue by ApeHC** [MetalPetal/MetalPetal#119]
guard let interImage = image.makeMTIImage() else { return }
        let sufaceBlurFilter = MTISurfaceBlurFilter.init(radius: 27)
        sufaceBlurFilter.inputImage = interImage
        guard let device = MTLCreateSystemDefaultDevice(), let context = try? MTIContext(device: device, options: MTIContextOptions()) else { return }
        guard let output = sufaceBlurFilter.outputImage else { return }
        DispatchQueue.global().async {
            //sleep(3)
            let afterImage = try? context.makeCGImage(from: output)
            DispatchQueue.main.async {
                if afterImage != nil {
                    onCompareProcess!(afterImage!)
                }
            }
        }

try? context.makeCGImage(from: output) 这个方法会阻塞主线程

**Comment by YuAo** [comment]
As far as I can see, it doesn't.
`try? context.makeCGImage(from: output)` should be fast in your situation. If you measure its execution time it should be less than 5ms and all the operations take place in the queue you specified.

**Comment by ApeHC** [comment]
ok, Thanks to answer
