### ISSUE TITLE
UnsharpMaskFilter not working as expected

### ISSUE THREAD

**Issue by Filterd** [MetalPetal/MetalPetal#120]
I have a simple chain of brightness, contrast, saturation then MTIMPSUnsharpMaskFilter.

But there appears to be no change when changing the parameters of the unsharp filter.

i'm setting the parameters as this: 
`let sharpFilter = MTIMPSUnsharpMaskFilter()
sharpFilter.scale = Float(0.5)
sharpFilter.radius = Float(1000)
sharpFilter.threshold = Float(0)`

(I have tried various numbers for the radius)

If I swap out the sharp filter for a different filter - such as pixellate - then that filter works as expected.

Here is a screenshot of the render flow as shown by Metalpetal. I notice the radius parameter doesn't appear here.

https://www.dropbox.com/s/of61stelewmimwz/renderresult.png?dl=0

Any thoughts? 

Many thanks.

**Comment by YuAo** [comment]
The filter does work. It uses `MPSImageGaussianBlur` in `MetalPerformanceShaders.framework` for the blur so the radius parameter does not currently show on the debug graph.

You are using a very large radius, you'll end up not increasing the sharpness of the image but increasing the contrast.

You can paste the following code to the demo `ImageRendererViewController.m` to see the change:

```
- (void)drawInMTKView:(MTKView *)view {
    MTIMPSUnsharpMaskFilter *filter = [[MTIMPSUnsharpMaskFilter alloc] init];
    filter.radius = (int)(CFAbsoluteTimeGetCurrent()) % 2 == 0 ? 5 : 1000;
    filter.scale = 0.5;
    filter.threshold = 0;
    filter.inputImage = self.inputImage;
    MTIImage *outputImage = filter.outputImage;
    MTIDrawableRenderingRequest *request = [[MTIDrawableRenderingRequest alloc] init];
    request.drawableProvider = self.renderView;
    request.resizingMode = MTIDrawableRenderingResizingModeAspect;
    NSError *error;
    [self.context renderImage:outputImage toDrawableWithRequest:request error:&error];
}
```

**Comment by YuAo** [comment]
If you'd like to increase the sharpness, try a small `radius` and a bigger `scale`.  Like `radius`: 2, `scale`: 2.
