### ISSUE TITLE
Show list of images on MTIImageView as video

### ISSUE THREAD

**Issue by leximester** [MetalPetal/MetalPetal#121]
Hi!

I have 150 images and I would like to modify(its kind of animation) and show them in real time on the MTIImageView as a video using GPU. Is it possible with MetalPetal? I do not want to generate a video from images because users could modify the images or is the video generation also possible under 1-2 secs?  Thanks

**Comment by YuAo** [comment]
Yes, it's possible.

For your reference:
https://github.com/YuAo/YUDisplacementTransition
https://github.com/alexiscn/MTTransitions

**Comment by leximester** [comment]
Thanks for the links but I need a simple "transition" without any animation. (I make the animation in another way from frame to frame) so I just need to show the frames like a simple video. Do you know this type of transition? Or I have to write a new shader? Sorry for the many questions but I just started to work with Metal in this week :)

**Comment by YuAo** [comment]
How about using a time to change the image view's image
