### ISSUE TITLE
How to avoid stretching (i.e. aspect ratio changes) when resizing MTIImageView

### ISSUE THREAD

**Issue by jrabek** [MetalPetal/MetalPetal#122]
Thanks again for the great framework.

When using an `MTIImageView` in place of a `AVCaptureVideoPreviewLayer` to preview the filter results, what is the correct way to setup the `MTIImageView` so that the aspect ratio does not change when animating the size of the `MTIImageView`?

I setup a` UIView` to use as a preview that has a `MTIImageView` as a subview.

I set the `resizingMode` to be `MTIDrawableRenderingResizingModeAspectFill` but when animating the `MTIImageView`'s superview, the layer inside the `MTIImageView` will immediately resize to the new size (i.e. the size at the end of the animation) with an incorrect aspect ratio (stretching instead of filling with the correct aspect ratio) and then when the animation finishes the aspect ratio is correct.

```
@property (nonatomic) MTIImageView *previewImageView;
```

```
    // - (instancetype)initWithFrame:(CGRect)frame 
    _previewImageView = [[MTIImageView alloc] initWithFrame:frame];
    _previewImageView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    _previewImageView.resizingMode = MTIDrawableRenderingResizingModeAspectFill;
    [self addSubview:_previewImageView];
```

```
   // - (void)captureOutput:(AVCaptureOutput *)unused(captureOutput) didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection
            ...
            MTIImage *inputImage = [[MTIImage alloc] initWithCVPixelBuffer:pixelBuffer alphaType:MTIAlphaTypeAlphaIsOne];
            MTIImage *filterOutputImage = inputImage;
            ...
            dispatch_async(dispatch_get_main_queue(), ^{
           	strongify(self);
                self.previewImageView.image = filterOutputImage;
            });
```

**Comment by YuAo** [comment]
The metal layer's update is different from common CALayers. Try something like this:
```
((UIView *)[self.previewImageView valueForKeyPath:@"renderView"]).contentMode = UIViewContentModeScaleAspectFit;
```
Let me know if the above code works for you.

**Comment by jrabek** [comment]
Thanks for the suggestion @YuAo !  That works perfectly.

**Comment by jrabek** [comment]
Also thanks for the super quick response!

**Comment by YuAo** [comment]
You can now set the content mode of the `MTIImageView`. `valueForKeyPath:@"renderView"` is no longer needed. Ref https://github.com/MetalPetal/MetalPetal/releases/tag/1.8.0

**Comment by omarojo** [comment]
I'm having the same issue. 
I have an iPad with a MTIImageView inside a UIView (which is anchored to the size of the screen).
If I rotate the iPad the interface rotates, the UIView (containing the MTIImageView) also rotates, but the rendering gets all stretched out. 

```
renderView = MTIThreadSafeImageView(frame: self.renderContainerView.bounds)
renderView.autoresizingMask = [.flexibleHeight, .flexibleWidth, .flexibleTopMargin, .flexibleLeftMargin, .flexibleRightMargin,.flexibleBottomMargin]
renderView.context = g8.context!
renderView.resizingMode = .aspect
self.renderContainerView.contentMode = .scaleToFill
self.renderView.contentMode = .scaleToFill
g8.renderView = renderView
self.renderContainerView.insertSubview(renderView, at: 0)
```
Im using a Crop Filter to apply a 9:16 aspect ratio to the final image being rendered. (among other aspect ratios).  

Here a video: https://youtu.be/cZ4i6EdDeD8

As you can see, the render starts at 9:16 when rotated.. is fine.. but when rotated back to portrait mode... the render is stretched. The whole thing is very erratic, I'm unable to predict exactly how it get's stretched.

**Comment by YuAo** [comment]
I don't think it's the same problem. Looks like the layout of your view is messed up. Maybe you should use the view debug tool to ensure the layout.

**Comment by omarojo** [comment]
@YuAo 
I did check that before. 
I don't think it is a layout issue. Since the MTIImageView is the size of the screen, as well as the UIView Containing it. 

![image](https://user-images.githubusercontent.com/995265/73313379-ae45fc00-41f0-11ea-855c-3a7656bb1be3.png)

**Comment by YuAo** [comment]
Cannot reproduce. Can you modify the demo project `CameraViewController.swift` to reproduce the issue?

**Comment by omarojo** [comment]
@YuAo  I fixed it by using `MTIImageView` instead of `MTIThreadSafeImageView`

**Comment by YuAo** [comment]
@omarojo Can you upload a code sample that can reproduce the problem, looks like a bug.
