### ISSUE TITLE
Memory leaks when converting MTIImage to CIImage

### ISSUE THREAD

**Issue by leximester** [MetalPetal/MetalPetal#123]
Hi again! Thanks for the quick response.

I have another problem/question. I'm merging two images with MTIBlendFilter. I need to save them to disk so I'm converting MTIImages to UIImages but it's run out from memory. Any idea what is wrong with my code? Thanks

`-` `(void)applyLiveAnimator`
`{
    self.pickedBlendFilter = [[MTIBlendFilter alloc] initWithBlendMode:MTIBlendModeNormal];
    self.pickedBlendFilter.inputImage = [[[MTIImage alloc] initWithCGImage:[self.originalImage CGImage] options:@{MTKTextureLoaderOptionSRGB: @(NO)} isOpaque:NO] imageWithCachePolicy:MTIImageCachePolicyTransient];`

    MTIImage *maskImage = [[[MTIImage alloc] initWithCGImage:[self.animatorMask CGImage] options:@{MTKTextureLoaderOptionSRGB: @(NO)}] imageWithCachePolicy:MTIImageCachePolicyTransient];
    self.pickedBlendFilter.inputBackgroundImage = maskImage;

    MTIContextOptions *options = [[MTIContextOptions alloc] init];
    NSError *error;

    MTIContext *context = [[MTIContext alloc] initWithDevice:MTLCreateSystemDefaultDevice() options:options error:&error];
    self.context = context;

    MTIImage *outputImg;
    @autoreleasepool {

        for (int i = 0; i < 40; i++)
        {
            outputImg  = [self.pickedBlendFilter.outputImage imageWithCachePolicy:MTIImageCachePolicyTransient];
            CIImage *test = [context createCIImageFromImage:outputImg error:nil];

            [context reclaimResources];
            NSLog(@"%d", i);
        }
    }
}

**Comment by YuAo** [comment]
1. `@autoreleasepool` should be inside the `for` loop.
2. If you need to save images to disk, create `CGImage`s. Use `CGImageDestinationRef` to save the an image to disk.
3. Profile using Instruments.

**Comment by leximester** [comment]
I already tried the things that you wrote. But did not help. Before this loop the app uses 250mb of ram after its ~700mb.
This line causes the memory leak:          
  ` test = [context createCGImageFromImage:outputImg error:nil];`

``` 
for (int i = 0; i < 40; i++)
    {
        @autoreleasepool {

            outputImg  = [self.pickedBlendFilter.outputImage imageWithCachePolicy:MTIImageCachePolicyTransient];
            test = [context createCGImageFromImage:outputImg error:nil];

            [context reclaimResources];
            NSLog(@"%d", i);
        }
    }
```
<img width="1282" alt="Képernyőfotó 2020-01-14 - 17 31 34" src="https://user-images.githubusercontent.com/5308151/72362664-d9f6bb80-36f3-11ea-8ae4-4ee7a3cc0971.png">

**Comment by YuAo** [comment]
Do you release the CGImage? `CGImageRelease`

**Comment by leximester** [comment]
Thank you, that was the problem :)
