### ISSUE TITLE
Installation without CocoaPods

### ISSUE THREAD

**Issue by unixb0y** [MetalPetal/MetalPetal#124]
Hello, we use Carthage and would really appreciate if there was a way to embed MetalPetal with Carthage. I used Rome to build a .framework, which worked for debugging but when submitting a beta, Xcode threw errors about wrong architecture etc. and I had to remove one using this command.

lipo -remove x86_64 MetalPetal -o MetalPetal

By the way, a usage example of your .sh script would be cool. I used the instructions from the CocoaPods/Rome GitHub, maybe I wouldn't have faced any issues by using your script. But I really don't know how to use it. It expects a podfile somewhere which I obviously don't have since the whole project is Carthage.

This procedure is also quite annoying since I'll have to come here and check for updates instead of just being able to do `carthage update`.

Thanks in advance!

**Comment by YuAo** [comment]
No plan of supporting Carthage currently.

Will support Swift Package Manager when the implementation of [SE-0271](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md) is done.

You can use the Rome script this way:
```
cd MetalPetal/Rome/
sh ./build_frameworks.sh
```
The framework file can be found in the `MetalPetal/Rome/Products` folder when the process completes.

**Comment by unixb0y** [comment]
@YuAo The framework created like this does work, but is not uploadable to AppStore Connect since it contains unsupported architectures..

**Comment by YuAo** [comment]
How about `lipo -remove x86_64 MetalPetal -o MetalPetal`?
