### ISSUE TITLE
Code signing "MetalPetal.framework" failed.

### ISSUE THREAD

**Issue by Umity** [MetalPetal/MetalPetal#125]
Hi, i used Rome and i added it to my project but i cant pass this now.. Any suggestion?

**Comment by YuAo** [comment]
Any detail? Logs from Xcode may help.

**Comment by Umity** [comment]
Oh thank you so much for answering me.
Let me tell my main problem first; i could not install as cocoapod. because i have already a framework installed in my project, it is like:
-MymainProject.xcodeproj
...-Framework.xcodeproj

in my example do you know how can i install as pod?

**Comment by YuAo** [comment]
You should open an issue in [CocoaPods](https://github.com/CocoaPods/CocoaPods) repo for any CocoaPods related questions.

**Comment by Umity** [comment]
i know.. but i dont think they may help.. i really need to make this happen as i love and need your framework.

when i try to install as cocoapod, i get this error:
[!] Using Swift static libraries with custom module maps is currently not supported. Please build `MetalPetal` as a framework or remove the custom module map.

when i try to install as framework, it works fine but cant upload to appstore..

**Comment by YuAo** [comment]
No idea from your description. Maybe you can post a sample project, so I can take a closer look.

**Comment by Umity** [comment]
sure, whats your email?

**Comment by YuAo** [comment]
I think you can post it here or on your github. So anyone with the similar issue could benefit from our problem solving process.

**Comment by Umity** [comment]
it is too big, i promise i will come here and tell the solution.

On Sunday, January 19, 2020, Yu Ao <notifications@github.com> wrote:
> I think you can post it here or on your github. So anyone with the
similar issue could benefit from our problem solving process.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/C6Fvw4fvUI73gzLiQfRrP3zSQ_dm229rNb78I1QPMkrAIU7jYv5oiy2-ZtPtSPXUUqllxJDI-HjjiMMKWG0JpOE68c5e-lmlZgxL7C0gil-n8p54tdut1adp_5vDl_62VCnOpPPwNBOpSCLqD7RHhNm97ctSTaJSujz4xUuFvR0h_IHR8Csb7lBDHxZ_OWtoS9aDot6aca4tFjRCVWBQkcU8MRKBJyKTuXeHUtALxg=s0-d-e1-ft#https://github.com/notifications/beacon/AAHLCMY7AUJDKSUHJWE7Y6LQ6RJDTA5CNFSM4KIY6KHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJKSICI.gif>

**Comment by YuAo** [comment]
Then you should consider providing a minimal problem reproducible project, removing all unnecessary files/codes/assets for this problem, making it easier to investigate/find the solution/test, etc.

For example, here's a demo project with MetalPetal.framework built with Rome. This project has no problem building or archiving.
[Archive.zip](https://github.com/MetalPetal/MetalPetal/files/4082741/Archive.zip)

**Comment by Umity** [comment]
Yes, yours dont have any problem, really.
i tried to copy the framework folder from yours to mine, still getting
errors…

i dont know how are you doing it?
cant i just copy the folder to mine? the framework folder,
MetalPetal.framework folder.


On Sunday, January 19, 2020, Yu Ao <notifications@github.com> wrote:
> Then you should consider providing a minimal problem reproducible
project, removing all unnecessary files/codes/assets for this problem,
making it easier to investigate/find the solution/test, etc.
>
> For example, here's a demo project with MetalPetal.framework built with
Rome. This project has no problem building or archiving.
> Archive.zip
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/WfnX5Y6-s8gTAYgqoKlz2UOPLkI-6KsDnG201iHyPApOvxQ53_N31ofzj2CG5iS1OGV0rFft7MobjIiTDR3DU1DRZR5kU5ewYj8Otl4UzQk1D127qUK7oOqMz6uKrrzqBpfuUxhN86iFL_-Gr57eZevKjD4aqVutEfQtEYR6qt0tbigQlCJ1wguGdUp43uPEa3X8LXGY-LLkf9uQCMGNreWiop-c4WRDL-lWg1BXMw=s0-d-e1-ft#https://github.com/notifications/beacon/AAHLCM4DZEEUMVDSNJXE2SLQ6RMABA5CNFSM4KIY6KHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJKSZ4Q.gif>

**Comment by Umity** [comment]
Please help ...

**Comment by YuAo** [comment]
You can check your project setting against the working demo. Or post the detail error log. 
If you don't know how to find the build log see https://help.apple.com/xcode/mac/11.0/index.html?localePath=en.lproj#/dev21d56ecd4

**Comment by Umity** [comment]
Thank you very much for your patience with me.. my app works awesomely in my device, the problem is occuring when i am trying to post update to my app, i mean when "archiving". 

this is the error message that i am working to fix but i am unable to:


Ld /Users/umit/Documents/APPS/v5/DFX\ 4/Examples/Build/Intermediates/ArchiveIntermediates/iOS\ Example/IntermediateBuildFilesPath/DFX.build/Release-iphoneos/DFX\ iOS.build/Objects-normal/arm64/Binary/DFX normal arm64 (in target 'DFX iOS' from project 'DFX')
    cd /Users/umit/Documents/APPS/v5/DFX\ 4
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios9.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -L/Users/umit/Documents/APPS/v5/DFX\ 4/Examples/Build/Intermediates/ArchiveIntermediates/iOS\ Example/BuildProductsPath/Release-iphoneos -F/Users/umit/Documents/APPS/v5/DFX\ 4/Examples/Build/Intermediates/ArchiveIntermediates/iOS\ Example/BuildProductsPath/Release-iphoneos -F/Users/umit/Documents/APPS/v5/DFX\ 4 -filelist /Users/umit/Documents/APPS/v5/DFX\ 4/Examples/Build/Intermediates/ArchiveIntermediates/iOS\ Example/IntermediateBuildFilesPath/DFX.build/Release-iphoneos/DFX\ iOS.build/Objects-normal/arm64/DFX.LinkFileList -install_name @rpath/DFX.framework/DFX -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/umit/Documents/APPS/v5/DFX\ 4/Examples/Build/Intermediates/ArchiveIntermediates/iOS\ Example/IntermediateBuildFilesPath/DFX.build/Release-iphoneos/DFX\ iOS.build/Objects-normal/arm64/DFX_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/umit/Documents/APPS/v5/DFX\ 4/Examples/Build/Intermediates/ArchiveIntermediates/iOS\ Example/BuildProductsPath/Release-iphoneos -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/umit/Documents/APPS/v5/DFX\ 4/Examples/Build/Intermediates/ArchiveIntermediates/iOS\ Example/IntermediateBuildFilesPath/DFX.build/Release-iphoneos/DFX\ iOS.build/Objects-normal/arm64/DFX.swiftmodule -framework MetalPetal -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/umit/Documents/APPS/v5/DFX\ 4/Examples/Build/Intermediates/ArchiveIntermediates/iOS\ Example/IntermediateBuildFilesPath/DFX.build/Release-iphoneos/DFX\ iOS.build/Objects-normal/arm64/DFX_dependency_info.dat -o /Users/umit/Documents/APPS/v5/DFX\ 4/Examples/Build/Intermediates/ArchiveIntermediates/iOS\ Example/IntermediateBuildFilesPath/DFX.build/Release-iphoneos/DFX\ iOS.build/Objects-normal/arm64/Binary/DFX


ld: bitcode bundle could not be generated because '/Users/umit/Documents/APPS/v5/DFX 4/MetalPetal.framework/MetalPetal' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/umit/Documents/APPS/v5/DFX 4/MetalPetal.framework/MetalPetal' for architecture arm64

**Comment by YuAo** [comment]
Try turning off bitcode.

**Comment by Umity** [comment]
I did of course m, but this time xcode giving error when uploading.
here is the msg:
Code signing "MetalPetal.framework" failed.
View distribution logs for more information.

**Comment by Umity** [comment]
ad this is from the IDEDistrubtionPipeline.log:
```
2020-01-20 09:41:03 +0000  Writing entitlements for <IDEDistributionItem: 0x7f8160d66ed0; bundleID='org.cocoapods.MetalPetal', path='<DVTFilePath:0x7f816131a020:'/Users/umit/Library/Developer/Xcode/Archives/2020-01-20/iOS Example 20.01.2020 12.40.xcarchive/Products/Applications/DFX!.app/Frameworks/DFX.framework/Frameworks/MetalPetal.framework'>', codeSigningInfo='<_DVTCodeSigningInformation_Path: 0x7f8160d63b30; isSigned='1', isAdHocSigned='1', signingCertificate='(null)', entitlements='(null)', teamID='(null)', identifier='org.cocoapods.MetalPetal', executablePath='<DVTFilePath:0x7f816131c8d0:'/Users/umit/Library/Developer/Xcode/Archives/2020-01-20/iOS Example 20.01.2020 12.40.xcarchive/Products/Applications/DFX!.app/Frameworks/DFX.framework/Frameworks/MetalPetal.framework/MetalPetal'>', hardenedRuntime='0'>'> to: /var/folders/r5/qhg4fbs52nn_mt975dh5jrbw0000gn/T/XcodeDistPipeline.~~~o7673N/entitlements~~~IYUlvb
2020-01-20 09:41:03 +0000  Running /usr/bin/codesign '-vvv' '--force' '--sign' '3CBEC548250C99AC780AD8673CC90DB4F817FBE9' '--entitlements' '/var/folders/r5/qhg4fbs52nn_mt975dh5jrbw0000gn/T/XcodeDistPipeline.~~~o7673N/entitlements~~~IYUlvb' '--preserve-metadata=identifier,flags,runtime' '/var/folders/r5/qhg4fbs52nn_mt975dh5jrbw0000gn/T/XcodeDistPipeline.~~~o7673N/Root/Payload/DFX!.app/Frameworks/DFX.framework/Frameworks/MetalPetal.framework'
2020-01-20 09:41:05 +0000  /var/folders/r5/qhg4fbs52nn_mt975dh5jrbw0000gn/T/XcodeDistPipeline.~~~o7673N/Root/Payload/DFX!.app/Frameworks/DFX.framework/Frameworks/MetalPetal.framework: replacing existing signature
2020-01-20 09:41:05 +0000  /var/folders/r5/qhg4fbs52nn_mt975dh5jrbw0000gn/T/XcodeDistPipeline.~~~o7673N/Root/Payload/DFX!.app/Frameworks/DFX.framework/Frameworks/MetalPetal.framework: code object is not signed at all
```

"MetalPetal.framework: code object is not signed at all"
how can i sign then?? I have to sort this problem which is for me literally as important as my life.

**Comment by YuAo** [comment]
https://help.apple.com/xcode/mac/11.0/index.html?localePath=en.lproj#/dev51a648b07

Add a framework or library. No.5 Choose `Embed & Sign`

**Comment by Umity** [comment]
all embed and signed

**Comment by YuAo** [comment]
Run `codesign -vv YourArchive.xcarchive/Products/Applications/YourApp.app/Frameworks/MetalPetal.framework/MetalPetal` to validate the signature.

Run `codesign -d --verbose=4 YourArchive.xcarchive/Products/Applications/YourApp.app/Frameworks/MetalPetal.framework/MetalPetal` to check the entitlements.

**Comment by Umity** [comment]
OK, i tried this via the terminal app and it says as error:
"invalid Info.plist (plist or signature have been modified)
In architecture: x86_64
"

**Comment by Umity** [comment]
first command:
```
/Users/umit/Library/Developer/Xcode/Archives/2020-01-20/iOS Example 20.01.2020 12.58.xcarchive/Products/Applications/DFX!.app/Frameworks/MetalPetal.framework/MetalPetal: valid on disk
/Users/umit/Library/Developer/Xcode/Archives/2020-01-20/iOS Example 20.01.2020 12.58.xcarchive/PrDFXoducts/Applications/DFX!.app/Frameworks/MetalPetal.framework/MetalPetal: satisfies its Designated Requirement
```

and this output is after the codesign -d --verbose=4
```
Identifier=org.cocoapods.MetalPetal
Format=bundle with Mach-O universal (i386 armv7 x86_64 arm64)
CodeDirectory v=20400 size=10684 flags=0x0(none) hashes=327+3 location=embedded
VersionPlatform=2
VersionMin=589824
VersionSDK=852480
Hash type=sha256 size=32
CandidateCDHash sha1=b438a920afb9c7b2836c27d4bebca4f56f6fb0a7
CandidateCDHashFull sha1=b438a920afb9c7b2836c27d4bebca4f56f6fb0a7
CandidateCDHash sha256=f3a219cff28bd9efa358f36bef6a7afceef782ec
CandidateCDHashFull sha256=f3a219cff28bd9efa358f36bef6a7afceef782ec53762415ac9526522e761ac3
Hash choices=sha1,sha256
CMSDigest=4c815fa34df1fcacfd6f284e3ac997465e5b419ee0d16bca38732ddde4caf7b8
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=434176
Executable Segment flags=0x0
Page size=4096
CDHash=f3a219cff28bd9efa358f36bef6a7afceef782ec
Signature size=4821
Authority=Apple Development: XY YZ (69A5Z6565PC)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=20 Jan 2020 12:58:10
Info.plist entries=21
TeamIdentifier=76PL87YC79
Sealed Resources version=2 rules=10 files=1
Internal requirements count=1 size=188
```

after doing them, trying to upload to the appstore again, and same result: 
Code signing "MetalPetal.framework" failed.

**Comment by YuAo** [comment]
How about adding a Build Phase. Run Script after `Embed Frameworks`.

```
set -e
cd "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/MetalPetal.framework/" 
lipo -remove x86_64 MetalPetal -o MetalPetal
lipo -remove i386 MetalPetal -o MetalPetal
```

**Comment by Umity** [comment]
and then this time i get this error:
fatal error: lipo: -remove x86_64 specified but fat file: MetalPetal does not contain that architecture
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by Umity** [comment]
I think i managed,
1. i have open framework, which is just a swift xcode project, i deleted the framework there.
2. I pressed control and pull to the framework xcode project area, and this made it work.

I checked location, the frameworks are still in different locations. But yes, for now, it looks working and uploaded to the appstore.

this library is more than amazing and i had to do this, if you give me your email i can explain why it was so important, if you dont, please be sure you saved my life.
