### ISSUE TITLE
Crash since iOS 13.3.1

### ISSUE THREAD

**Issue by unixb0y** [MetalPetal/MetalPetal#126]
I use the [`MetalFilters`](https://github.com/alexiscn/MetalFilters) library to filter images which in turn uses `MetalPetal`. I am experiencing a crash with some specific filters which occurs in MetalPetal, so that's why I'm opening an issue over here and not on MetalFilter's GitHub.  

The issue only happens in iOS 13.3.1 devices, not on 13.3. 

I am not sure how to gather more info about the crash than sending you a stack trace and linking the 'filters' with which the App crashes.

At this line of code, the App crashes (in the `MTFilterManager.filterImage(_:with:)` method):
```
let cgImage = try? context?.makeCGImage(from: outputImage)
```

with the following stack trace.

![Screenshot 2020-02-12 at 00 44 58](https://user-images.githubusercontent.com/6874233/74290555-80090600-4d32-11ea-8fe5-d626f2bddf5d.png)

The filters are:

- [MTHudsonFilter](https://github.com/alexiscn/MetalFilters/blob/master/MetalFilters/Filters/MTHudsonFilter.swift)

- [MTHefeFilter](https://github.com/alexiscn/MetalFilters/blob/master/MetalFilters/Filters/MTHefeFilter.swift)

- [MTSutroFilter](https://github.com/alexiscn/MetalFilters/blob/master/MetalFilters/Filters/MTSutroFilter.swift)

- [MTToasterFilter](https://github.com/alexiscn/MetalFilters/blob/master/MetalFilters/Filters/MTToasterFilter.swift)

Maybe the following screenshots will also help:

![Screenshot 2020-02-12 at 01 02 43](https://user-images.githubusercontent.com/6874233/74290869-70d68800-4d33-11ea-9d2b-506eeedd19fb.png)
![Screenshot 2020-02-12 at 01 02 22](https://user-images.githubusercontent.com/6874233/74290876-746a0f00-4d33-11ea-9d9b-579223093826.png)

**Comment by YuAo** [comment]
I cannot get the MetalFilters demo working because some resources cannot be loaded.

Crashed here "Fatal error: Unexpectedly found nil while unwrapping an Optional value"
<img width="676" alt="Screen Shot 2020-02-12 at 13 37 02" src="https://user-images.githubusercontent.com/1234944/74306189-d1e67600-4d9c-11ea-8c07-cb539c7edfb8.png">
