### ISSUE TITLE
MTICoreImageKernel not found

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#127]
Im trying to use your latest upgrades to the library where you incorporated **MTICoreImageKernel**.
by pointing the pod to the latest git url.

pod 'MetalPetal', :git => 'https://github.com/MetalPetal/MetalPetal.git'

**Even to a specific commit -- but no luck** 
pod 'MetalPetal', :git => 'https://github.com/MetalPetal/MetalPetal.git', commit: 'ff216004fb4b54d426fb22fd554bd2cbde54abd8'

it keeps installing 1.7.0 and the MTICoreImageExtension file is not downloaded. 

Any idea ?

**Comment by YuAo** [comment]
This is a Swift only extension.

https://github.com/MetalPetal/MetalPetal/blob/22e5a4f28bb5c8511938efb1364221e9aac18d8c/Frameworks/MetalPetal/MTICoreImageExtension.swift

```
pod 'MetalPetal/Swift',  :git => 'https://github.com/MetalPetal/MetalPetal.git'
```
