### ISSUE TITLE
Stickers (GIFs, Texts) to MTIImage

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#128]
Hola again, 

Im trying to implement Stickers to be overlaid into a MTIImage. My first approach was to design my own Filters for Text (or GIFs). And based in your [post](https://github.com/MetalPetal/MetalPetal/issues/89#issuecomment-506138193) I was able to add Text using a `MTIMultilayerCompositingFilter` 

But it is becoming very hard to implement proper editing UI, to change the text, control location and scale of the elements, re-render and replace layers in the CompositingFilter, specially because the MTIImageView could have different `resizingModes` and cropping.

I was thinking... what if I use a thirdparty Sticker lib, place all stickers in a UIView with the same aspectRatio as the main MTIImage being rendered, and  **convert UIView to MTIImage** super quickly with a CADisplayLink, then feed it into a layer of `MTIMultilayerCompositingFilter`  

maybe that's also the wrong approach 😅

**Comment by YuAo** [comment]
Sorry, no suggestion here. I think this is a decision you should make based on your app's design, UI, performance requirements, image quality requirements, time constraints, etc.
