### ISSUE TITLE
Looking for Color Balance Filter

### ISSUE THREAD

**Issue by RafikFarhad** [MetalPetal/MetalPetal#129]
Hello all,
I need to recreate the Color Balance effect on a photo. I searched a lot but did not find any good solution. In my solution the effect I've been getting is not similar with the Photoshop efftct. So anyone can give me any hint or solution to achieve this?

**Comment by YuAo** [comment]
How about the GIMP implementation?
https://github.com/GNOME/gimp/blob/5d79fba8238a27b8691556489898d33b3fa0dda0/app/operations/gimpoperationcolorbalance.c

**Comment by RafikFarhad** [comment]
Actually I tried the GIMP Implementation but the output do not match with the PhotoShop output. BTW thanks for your comment.
