### ISSUE TITLE
Crash [CIContext clearCaches]

### ISSUE THREAD

**Issue by zhuozhuo** [MetalPetal/MetalPetal#130]
Version : 1.5.0

iOS: 12.3.1

Hello, I met a crash, must show, convenient to see what reason?

```
CoreImage`-[CIContext clearCaches]:
    0x1e915c65c <+0>:  pacibsp 
    0x1e915c660 <+4>:  stp    x29, x30, [sp, #-0x10]!
    0x1e915c664 <+8>:  mov    x29, sp
    0x1e915c668 <+12>: adrp   x8, 450
    0x1e915c66c <+16>: add    x1, x8, #0x1a2            ; =0x1a2 
    0x1e915c670 <+20>: bl     0x1800bb6a0
    0x1e915c674 <+24>: cbz    x0, 0x186578690           ; <+52>
    0x1e915c678 <+28>: ldr    x8, [x0]
    0x1e915c67c <+32>: autdza x8
    0x1e915c680 <+36>: add    x9, x8, #0x260            ; =0x260 
->  0x1e915c684 <+40>: ldr    x8, [x8, #0x260]
    0x1e915c688 <+44>: movk   x9, #0xac25, lsl #48
    0x1e915c68c <+48>: blraa  x8, x9
    0x1e915c690 <+52>: ldp    x29, x30, [sp], #0x10
    0x1e915c694 <+56>: retab  

```

**Comment by zhuozhuo** [comment]
<img width="645" alt="屏幕快照 2020-03-02 下午3 51 26" src="https://user-images.githubusercontent.com/4192811/75655949-e3d17f80-5c9d-11ea-8e09-3abec6de60a1.png">

**Comment by YuAo** [comment]
Please attach a symbolicated crash log. Or update your call stack screenshot with the "Show stack frames without debug symbols and between libraries" option turned off.

**Comment by zhuozhuo** [comment]
The reason has been found, because the recording process is only capped at 50M, resulting in the clearCaches method being used every time the memory warning is reached.

**Comment by YuAo** [comment]
It shouldn’t cause any crash though. Would like to see the full call-stack trace.

**Comment by zhuozhuo** [comment]
Thanks for your reply. I checked the crash record of the test machine, but could not find the crash record. Replaykit recording process exceeds 50M memory limit, killed by system may not crash log. Since the test Demo does not use Git management, it is difficult to modify the code replication. If it happens again, I will give you the feedback.
