### ISSUE TITLE
mix with CoreImage

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#131]
Hello! Is it possible to integrate the filters from CoreImage in Metal so that they are processed in the GPU and use in a chain with MTIFiltres. This question does not apply to this library, but I'm interested in knowing your opinion. Thanks!

**Comment by YuAo** [comment]
Yes. You can use `MTICoreImageKernel` or `MTICoreImageUnaryFilter`.

https://github.com/MetalPetal/MetalPetal/blob/master/Frameworks/MetalPetal/MTICoreImageExtension.swift
