### ISSUE TITLE
CILightTunnel doesn't work - output size is out of bounds

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#132]
For some reason the CILightTunnel filter doesn't work. Other CIFilters work fine, but this one is crashing. The output of the filter has a huge size. 

Getting Error:
**validateTextureDimensions, line 1227: error 'MTLTextureDescriptor has width (18446744073709551615) greater than the maximum allowed size of 16384.'
validateTextureDimensions:1227: failed assertion `MTLTextureDescriptor has width (18446744073709551615) greater than the maximum allowed size of 16384.'**

inputImage.extent
- width : 1080.0
- height : 1080.0

lightTunnelCI.outputImage.extent
- width : 1.8446744073709552e+19
- height : 1.8446744073709552e+19

Here is the code:
[MetalPetalTests.zip](https://github.com/MetalPetal/MetalPetal/files/4284687/MetalPetalTests.zip)

```
import UIKit
import MetalPetal

class ViewController: UIViewController {

    @IBOutlet weak var renderView: MTIImageView!
    var context: MTIContext!
    
    var inputImage: MTIImage!
    
    var lightTunnerlCI: MTICoreImageUnaryFilter!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        do {
            try context = MTIContext(device: MTLCreateSystemDefaultDevice()!)
            renderView.context = context
        }catch{
            print ("no context")
        }
        
        inputImage = MTIImage(cgImage: UIImage(named: "testImage")!.cgImage!, options: [.SRGB: false], isOpaque: true)
        
        self.lightTunnerlCI = MTICoreImageUnaryFilter()
        
        if let ciFilter = CIFilter(name: "CILightTunnel") {
            lightTunnerlCI.filter = ciFilter
        }
        lightTunnerlCI.filter?.setValue(100, forKey: kCIInputRadiusKey)
        let center = CIVector(x: 540, y: 540)
        lightTunnerlCI.filter?.setValue(center, forKey: kCIInputCenterKey)
        lightTunnerlCI.filter?.setValue(10, forKey: "inputRotation")

        lightTunnerlCI.inputImage = inputImage
        renderView.image = lightTunnerlCI.outputImage!
    }
}
```

**Comment by YuAo** [comment]
Looks like you are rendering a CIImage with infinite extent, which is obviously impossible.

You can either set the `outputImageSize` of the `MTICoreImageUnaryFilter` or write a custom CIFilter to crop the output to your desired size.

**Comment by omarojo** [comment]
Woohoo ! That worked.
Thank you. 👍

I wonder why that specific CIFilter outputs such a huge image even when the input is much smaller. The other CIFilters dont do that.

**Comment by YuAo** [comment]
> I wonder why that specific CIFilter outputs such a huge image even when the input is much smaller. The other CIFilters dont do that.

The light tunnel effect can be extended infinitely.

> Conceptually, this means that you can request image data from an arbitrary region in the 2D plane and get back a meaningful result.
> https://www.objc.io/issues/21-camera-and-photos/core-image-intro/

FYI: A lot of filters in CoreImage output infinite size image. (especially for filters in`kCICategoryTileEffect`, `kCICategoryGenerator`)
