### ISSUE TITLE
CGImage rendering problem 

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#133]
If i create `MTIImage ` from `CGImage`  and it was created using `CGImageSourceCreateThumbnailAtIndex` render incorrect.  No matter what options you add. If I use the function `CGImageSourceCreateImageAtIndex`for creating CGImage all is well. I think when I use `CGImageSourceCreateThumbnailAtIndex` he creates thumbnail  changing certain parameter in to original CGImage.  I can not understand what the problem is. Can you tell me what the problem is, why the picture changes color? It is very important for me to use this particular method  `- (instancetype) initWithCGImage: (CGImageRef) cgImage options: (NSDictionary <MTKTextureLoaderOption, id> *) options`.  because he is the fastest. Of course i can wrap my `CGImage to CIIImage` and init using `- (instancetype)initWithCIImage:(CIImage *)ciImage`  or load using `UIImage` and get `CGImage` from `UIImage` it all works well, but this creates additional costs for memory. I added a screenshot below.  I also added a project that you can run. The folder also has the original image
![IMG_780394CFBB49-1](https://user-images.githubusercontent.com/29518174/76141526-207aed80-6087-11ea-98ed-cd5b6e12dc08.jpeg)
Xcode project [MTIExample.zip](https://github.com/MetalPetal/MetalPetal/files/4301687/MTIExample.zip)

**Comment by YuAo** [comment]
Looks like a bug of `MTKTextureLoader`.

Here's a workaround: Draw the cgImage's content to a `CVPixelBuffer` and use the pixel buffer to create a `MTIImage`.

```
    CVPixelBufferRef pixelBuffer;
    CVPixelBufferCreate(kCFAllocatorDefault, CGImageGetWidth(cgImage), CGImageGetHeight(cgImage), kCVPixelFormatType_32BGRA, (__bridge CFDictionaryRef)@{(id)kCVPixelBufferIOSurfacePropertiesKey: @{}}, &pixelBuffer);
    if (!pixelBuffer) {
        //handle error
    }
    
    CFAutorelease(pixelBuffer);
    
    CGColorSpaceRef colorspace = CGColorSpaceCreateDeviceRGB();
    if (!colorspace) {
        //handle error
    }
    CVPixelBufferLockBaseAddress(pixelBuffer, 0);
    CGContextRef context = CGBitmapContextCreate(CVPixelBufferGetBaseAddress(pixelBuffer), CGImageGetWidth(cgImage), CGImageGetHeight(cgImage), 8, CVPixelBufferGetBytesPerRow(pixelBuffer), colorspace, kCGBitmapByteOrder32Little | kCGImageAlphaPremultipliedFirst);
    CGColorSpaceRelease(colorspace);
    if (!context) {
        //handle error
        CVPixelBufferUnlockBaseAddress(pixelBuffer, 0);
    }
    CGContextDrawImage(context, CGRectMake(0, 0, CGImageGetWidth(cgImage), CGImageGetHeight(cgImage)), cgImage);
    CGContextRelease(context);
    CVPixelBufferUnlockBaseAddress(pixelBuffer, 0);
    
    MTIImage *image = [[MTIImage alloc] initWithCVPixelBuffer:pixelBuffer alphaType:MTIAlphaTypePremultiplied];
```
