### ISSUE TITLE
Project with MetalPetal can't be started on iOS 10, 11, 12 simulator

### ISSUE THREAD

**Issue by Igor-Poltavtsev** [MetalPetal/MetalPetal#134]
### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Steps to Reproduce
Start app on iOS 10, 11, 12 simulator.

### Expected behavior
App able to start and all parts work, except MetalPetal.

### Actual behavior
App get crash on start:
`dyld: Symbol not found: _OBJC_CLASS_$_MTLHeapDescriptor
  Referenced from: /Users/Igor/Library/Developer/CoreSimulator/Devices/9D277DE8-9F3D-4A95-B225-F11E1A2B65F5/data/Containers/Bundle/Application/7EDAAF53-2A7C-4811-94C2-8F62072B1ACA/Unfold.app/Frameworks/MetalPetal.framework/MetalPetal
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Metal.framework/Metal
 in /Users/Igor/Library/Developer/CoreSimulator/Devices/9D277DE8-9F3D-4A95-B225-F11E1A2B65F5/data/Containers/Bundle/Application/7EDAAF53-2A7C-4811-94C2-8F62072B1ACA/Unfold.app/Frameworks/MetalPetal.framework/MetalPetal
(lldb) `

**Comment by YuAo** [comment]
Looks like a bug of the simulator runtime.

The simulator runtimes prior to iOS 13 do not have the `MTLHeapDescriptor` symbol defined.  An app is likely to crash when runs on iOS 10, 11, 12 simulators if it contains `MTLHeapDescriptor` related functions, even if it does not use MetalPetal.

And unfortunately we can not fix this on our side. AFAIK there's no way to conditional compile only for iOS 10, 11, 12 simulators.

If you do not use heaps. You can try deleting the `MTIHeapTexturePool` class (in `MTITexturePool.mm` file), it should make the iOS 10, 11, 12 simulators happy.

**Comment by Igor-Poltavtsev** [comment]
Thank you, I commented lines 351-357 in Pods/MetalPetal/Core/MTITexturePool.mm and it works.
`
351        MTLHeapDescriptor *heapDescriptor = [[MTLHeapDescriptor alloc] init];
352        heapDescriptor.size = key.size;
353        heapDescriptor.resourceOptions = key.resourceOptions;
354        if (textureDescriptor.hazardTrackingMode == MTLHazardTrackingModeDefault) {
355            heapDescriptor.hazardTrackingMode = MTLHazardTrackingModeTracked;
356        }
357        heap = [_device newHeapWithDescriptor:heapDescriptor];
`

**Comment by donobono** [comment]
Hello @YuAo 

I meet this issue, too. 
I can avoid this crash by deleting that codes as you mentioned, but can you make old version  simulators happy more easily by adding #if !(TARGET_OS_SIMULATOR) and #endif to project? :)

Thanks!

**Comment by YuAo** [comment]
@donobono That would make the `MTIHeapTexturePool` unavailable on all simulators. I think a better approach would be referencing the `MTLHeapDescriptor` dynamically using the Objective-C runtime.

Can you try this?
```
#if TARGET_OS_SIMULATOR
MTLHeapDescriptor *heapDescriptor = [[NSClassFromString(@"MTLHeapDescriptor") alloc] init];
if (!heapDescriptor) {
    if (error) {
        *error = MTIErrorCreate(MTIErrorFailedToCreateHeap, nil);
    }
    return nil;
}
#else 
MTLHeapDescriptor *heapDescriptor = [[MTLHeapDescriptor alloc] init];
#endif
```
