### ISSUE TITLE
MTIComputePipelineKernel work example 

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#135]
Write a simple code that should output a red square
1 - my kernel function 
<img width="1397" alt="Снимок экрана 2020-04-02 в 11 35 40" src="https://user-images.githubusercontent.com/29518174/78218013-874cc480-74d6-11ea-9c80-b7999ca9b9f7.png">
2 - my custom filter implementation  
<img width="1335" alt="Снимок экрана 2020-04-02 в 11 36 34" src="https://user-images.githubusercontent.com/29518174/78218041-929ff000-74d6-11ea-885d-4342941cb976.png">
3 - my custom filter input image 
<img width="1058" alt="Снимок экрана 2020-04-02 в 11 39 49" src="https://user-images.githubusercontent.com/29518174/78218193-cda22380-74d6-11ea-97af-7a24225a8b00.png">
4 - and render this 
<img width="1296" alt="Снимок экрана 2020-04-02 в 11 40 43" src="https://user-images.githubusercontent.com/29518174/78218231-e27eb700-74d6-11ea-8398-30808fa0233b.png">

In the final version I get a black screen, that is, nothing happens, no warnings from MetalPetal. Can you please tell me how to generate  particle texture using Metal Petal. If I'm doing something wrong tell me what the problem is.  I add the finished project, which you can run to test my code.
[ParticleExample.zip](https://github.com/MetalPetal/MetalPetal/files/4419280/ParticleExample.zip)

**Comment by YuAo** [comment]
- Make sure you are using the latest version of MetalPetal. i.e. **1.10.1**
- You did not bind any input texture. If you do not want to use any input image. You should pass `@[]` to `applyToInputImages:`
- Output texture index should be right after all input textures.

With one input image:
```
kernel void firstPass(texture2d<half, access::read> inTexture [[texture(0)]],
                      texture2d<half, access::write> outTexture [[texture(1)]],
                      uint2 id [[thread_position_in_grid]]) {
    outTexture.write(half4(1.0, 0.0, 0.0, 1.), id);
}
```

No input image:
```
kernel void firstPass(texture2d<half, access::write> outTexture [[texture(0)]],
                      uint2 id [[thread_position_in_grid]]) {
    outTexture.write(half4(1.0, 0.0, 0.0, 1.), id);
}
```
