### ISSUE TITLE
Building for mac Catalyst fails

### ISSUE THREAD

**Issue by sabiland** [MetalPetal/MetalPetal#136]
Building for mac catalyst fails.

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Steps to Reproduce
Build for mac Catalyst

### Expected behavior
Successful build.

### Actual behavior
Build error: "'MTLFeatureSet_iOS_GPUFamily3_v1' is unavailable: not available on macCatalyst"

**Comment by YuAo** [comment]
Can’t reproduce. Please add a link to the source file and line.

**Comment by YuAo** [comment]
All checks looking good: https://github.com/MetalPetal/MetalPetal/runs/555298148
Closing issue.

**Comment by sabiland** [comment]
Hi YuAo, here is the file with exception:

`//
//  MTIPixelFormat.m
//  MetalPetal
//
//  Created by Yu Ao on 11/10/2017.
//

#import "MTIPixelFormat.h"
#import <AssertMacros.h>

MTLPixelFormat const MTIPixelFormatUnspecified = MTLPixelFormatInvalid;

MTLPixelFormat const MTIPixelFormatYCBCR8_420_2P = 500;
MTLPixelFormat const MTIPixelFormatYCBCR8_420_2P_sRGB = 520;

BOOL MTIDeviceSupportsYCBCRPixelFormat(id<MTLDevice> device) {
    #if TARGET_OS_SIMULATOR
    return NO;
    #elif TARGET_OS_IPHONE
    // This line: "'MTLFeatureSet_iOS_GPUFamily3_v1' is unavailable: not available on macCatalyst"
    return [device supportsFeatureSet:MTLFeatureSet_iOS_GPUFamily3_v1];
    #else
    return NO;
    #endif
}`

**Comment by sabiland** [comment]
This is my POD file:

```
pod 'MetalPetal'
pod 'MetalPetalSurfaceBlur', :git => 'https://github.com/MetalPetal/SurfaceBlur.git'
pod 'MetalPetal/Swift'
```

Is this not master branch ?

**Comment by YuAo** [comment]
https://guides.cocoapods.org/syntax/podfile.html#pod

Search "master branch"

**Comment by sabiland** [comment]
Thx. This is correct way?

```
pod 'MetalPetal', :git => 'https://github.com/MetalPetal/MetalPetal.git', :branch => 'master'
pod 'MetalPetal/Swift', :git => 'https://github.com/MetalPetal/MetalPetal.git', :branch => 'master'
```

**Comment by sabiland** [comment]
Uau great it works now on Mac Catalyst? Great, thx!
