### ISSUE TITLE
Extent origin is always .zero

### ISSUE THREAD

**Issue by seanwin** [MetalPetal/MetalPetal#137]
### Checklist
- [ x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ x ] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Hi, first of all, thank you so much for creating this library. 

I am running into issue when chaining multiple filters together when one of the filters is adjusting the extent. For example, one filter may simply be to translate y by 50. Normally when using CIImage, after applying this filter, the extent may be (0, -50, width, height), however I notice when using MTIImage, it is always (0, 0, width, height). 

After looking into library, I see that MTIImage extent always return (0, 0) for origin. I am wondering if you have a workaround and what the reasoning behind this is? Seems like you lose information by hardcoding origin. Unfortunately if this is not resolved I have to transition whole app back to using CIImage/CIFilter since some custom filters are unusable.

Thanks for your time.

**Comment by YuAo** [comment]
Thanks for the feedback.

We do not currently have mechanisms like ROI or a canvas/world coordinate system, so a MTIImage's origin is always (0,0).

For workarounds:
If you are dealing with image translation, rotation, etc, you can use `MTIMultilayerCompositingFilter`.
For other use cases you may need to convert the coordinates or crop the image.

**Comment by seanwin** [comment]
Thanks for fast reply, I will take a look 👍🏻
