### ISSUE TITLE
Possible to import and edit videos?

### ISSUE THREAD

**Issue by OlyRice** [MetalPetal/MetalPetal#138]
Hello, really interested in your library and thanks for putting it together. I have spent the last few years developing with GPUImage and I am looking to move to this. I notice it mentions live photo and video editing but are you able to import a video and then edit it?

Thanks

**Comment by omarojo** [comment]
You have to implement that yourself. And read your video frame by frame, apply the filter and feed it into an AssetWritter to reencode it. You should check out the demos included with the library.



Omar Juarez • MDM. BSc.
Interactive Developer
generatecreative.co

**Comment by YuAo** [comment]
The demo project provides an example of processing videos using a companion library `VideoIO`.

https://github.com/MetalPetal/MetalPetal/blob/master/MetalPetalDemo/VideoProcessorViewController.swift

**Comment by OlyRice** [comment]
Thanks for the input guys, 

One more quick question. With GPUImage to edit a video you pick a video and then apply a chain of filters, the problem is you have to apply them from start to finish. With this library is it possible to vary the filters by time. For example in a 10min video the first 5 minutes is 1 filter and the second 5 is another filter?

 I'm guessing you can if you have access to frame by frames.

**Comment by YuAo** [comment]
Yes.

**Comment by OlyRice** [comment]
Great thanks for the info
