### ISSUE TITLE
Request: iOS Photo app's "Definition" filter

### ISSUE THREAD

**Issue by Umity** [MetalPetal/MetalPetal#142]
This is actually a feature request. 

I love the CLAHE on MetalPetal but sometimes the result has unwanted output image (too much unnecessary white areas for example..).

is it possible to reduce it? Or do you think can we implement iOS Photo app's Definition filter?

**Comment by YuAo** [comment]
Try `MTIMPSDefinitionFilter`?

**Comment by Umity** [comment]
Oh, i just discovered definition was there.  it is great.
whats the min/max values?

**Comment by YuAo** [comment]
`0` means "original" image.
There's no upper bound of the parameter. You'll need to try the filter and select a max value that fits your needs.
