### ISSUE TITLE
How to smoothly switch between two filter effects

### ISSUE THREAD

**Issue by zhangbenwei** [MetalPetal/MetalPetal#143]
### Checklist
- [x ] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x ] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
If you are dealing with still images you can:
- Create a `CGImage` from the filtered image.
- Display that image in a `UIImageView` or `NSImageView`.
- Apply transition to your view using `CATransition` or view animations.

If you are dealing with real-time images, you may need to use a "transition filter" which takes two image and an intensity, for example a `MTIBlendFilter` with `.normal` blend mode, then change the intensity over time.
