### ISSUE TITLE
New Filter Request: Forward Warp

### ISSUE THREAD

**Issue by vjdaemp** [MetalPetal/MetalPetal#144]
I'd like to request a new filter, "Forward Warp"

The Forward Warp filter pushes pixels forward as you drag.

Inputs:
- Center Point (x,y) - Center region of pixels to push (in pixels)
- Radius (in pixels) - Radius pixels to push (in pixels)
- Angle (degrees) - Direction of push

If you do not feel this should be provided in standard set of filters, do you have tips on how to implement this via custom shader?

**Comment by YuAo** [comment]
How do you want the pixels to transform via a "Forward Warp"?

For example with parameter:
center: 50,50
radius: 30
angle: π

Where do you expect the pixel at 45,50 go?

**Comment by vjdaemp** [comment]
The “Forward Warp” tool pushes the pixels of an image forward as you drag. There is an example of this effect in Photoshop's Liquify tool

**Input parameters:**

- `Center` (x,y) = Center point of region to warp (start drag point)
- `Radius` (in pixels) = Radius of circular region to warp
- `Direction` (angle) = Direction to warp target region (direction of drag)
- `Strength` = Number of pixels to push
- `Density` (min = 0, max = 1) = \When set to 0, all pixels in target region are pushed the same amount of pixels. When set to 1, pixels closest to center are pushed the most. Pixels furthest from center are moved the least

**_For example, with parameters:_**

- `Center` = (50,50)
- `Radius` = (30)
- `Direction` = 90 degrees   (assuming 90 degrees is to the right)
- `Strength` = 5
- `Density` = 0

I would expect pixel at 45,50 go to 50,50

Does this description make sense?

**Comment by vjdaemp** [comment]
@YuAo Hello, do you have any pointers to implement this type of warp? Did I provide enough information about the transform?

**Comment by YuAo** [comment]
Hi, @vjdaemp sorry, too busy these days.

I think this can be done using a grid mesh.

```
import MetalPetal

struct ForwardWarpParameters {
    var center: SIMD2<Float> = .zero
    var radius: Float = 0
    var direction: Float = 0
    var strength: Float = 0
    var density: Float = 0
}

class ForwardWarpFilter: MTIFilter {
    var parameters: ForwardWarpParameters = ForwardWarpParameters()
    
    var outputPixelFormat: MTLPixelFormat = .unspecified
    
    var inputImage: MTIImage?
    
    var outputImage: MTIImage? {
        guard let inputImage = inputImage else {
            return nil
        }
        let mesh = GridMesh(width: Int(inputImage.dimensions.width), height: Int(inputImage.dimensions.height), cellSize: 4) { position in
            let distanceToCenter = distance(parameters.center, position);
            // Find the target position for the warp.
            if (distanceToCenter < parameters.radius) {
                //direction and strength
                var targetOffset = SIMD2<Float>(cos(parameters.direction), sin(parameters.direction)) * parameters.strength
                //density
                let distanceFactor = distanceToCenter/parameters.radius
                targetOffset = targetOffset * (1 - parameters.density * distanceFactor)
                return (position - targetOffset)
            } else {
                return position
            }
        }
        let geometry = MTIVertices(vertexBuffer: mesh.vertexBuffer,
                                   vertexCount: UInt(mesh.vertexCount),
                                   indexBuffer: mesh.indexBuffer,
                                   indexCount: UInt(mesh.indexCount),
                                   primitiveType: .triangle)
        let renderCommand = MTIRenderCommand(kernel: .passthrough, geometry: geometry, images: [inputImage], parameters: [:])
        return MTIRenderCommand.images(byPerforming: [renderCommand], outputDescriptors: [MTIRenderPassOutputDescriptor(dimensions: inputImage.dimensions, pixelFormat: outputPixelFormat)]).first
    }
}
```

For `GridMesh`, see https://gist.github.com/YuAo/a144281d5619d725744cb0d3edaff04a


<img width="538" alt="Screen Shot 2020-06-26 at 14 47 42" src="https://user-images.githubusercontent.com/1234944/85828926-0000ab80-b7bc-11ea-8f28-9486daf73a9b.png">

**Comment by vjdaemp** [comment]
Thank you @YuAo. I will give this a try and report back.

**Comment by rainc** [comment]
@vjdaemp or @YuAo do you have an example project demonstrating this filter?
