### ISSUE TITLE
Are min/max values for filters documented anywhere?

### ISSUE THREAD

**Issue by OlyRice** [MetalPetal/MetalPetal#145]
Hi, don't know if I am being stupid but are the values for the filters listed anywhere in documentation or source code?

For example if I want to find the min/max value for the Saturation filter so that I can apply these values to slider where can I find them? Had a look through the Filters folder in the framework but was unable to find any info.

Thanks

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
Currently no. You'll need to read the source code for min/max values.
