### ISSUE TITLE
New filters in the future?

### ISSUE THREAD

**Issue by sabiland** [MetalPetal/MetalPetal#146]
Before MetalPetal I used GPUImage 2 (and tried GPUImage 3). But because GPUImage 3 is not production-usable, I switched to MetalPetal few months ago.

I am wondering if MetalPetal plans to add some new filters/effects in the near future?

**Comment by OlyRice** [comment]
I made the switch as well for similar reasons and i'm looking forward to getting some apps out with this framework,

**Comment by YuAo** [comment]
I'm not planning adding new built-in filters in the near future. However you can alway open a feature request.
