### ISSUE TITLE
Is it possible to mesh-transform image in with MetalPetal?

### ISSUE THREAD

**Issue by malemo** [MetalPetal/MetalPetal#148]
I'm using Vision to do detect face landmark points. How can I mesh-transform the image using those landmark points to slim the face for instance. 

Any leads would be greatly appreciated.

Something like [this](https://i.stack.imgur.com/KA08G.jpg) (transformation should be adjustable with slider)

**Comment by YuAo** [comment]
Yes. All you need to do is generate the mesh, put the mesh data in a `MTIGeometry`/`MTIVertices`then use the `MTIRenderCommand` API to issue draw calls.

**Comment by malemo** [comment]
@YuAo thank you, for your reply. Any place you can suggest I can see some sample code as to how this is done: ie mesh generation, putting data in MTIGeometry etc. I've searched all over the Net for this. Not much info out there.

**Comment by YuAo** [comment]
@malemo  A simple method would be using triangulation.

- Use the detected landmarks for vertices' `position` and `texture coordinates`.
- Adjust the vertex's `position` based on your needs. For example: move a face's outer landmarks inward to "slim" face.
- Use `Delaunay Triangulation` to form triangles from points. Use the triangulation result as the `index buffer`.

**Comment by smhk** [comment]
hello @YuAo !

I am confused:  how do I give the "original" verts, and then the "modified" verts?

Example, the "original" verts are a plain grid 100x100.

Now, I move many of the verts slightly.  (Distorting the image.)

In fact how do I "tell" PetalMetal the origina and then modified verts?

Thank you very much.

**Comment by smhk** [comment]
thanks. I asked a question about this here: https://github.com/MetalPetal/MetalPetal/issues/231
