### ISSUE TITLE
MTKView inside MTIImageView not resizing properly after applying rotation transformation to MTIImageView

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#149]
[**iPhone 6 - iOS 12.4.3**] MTKView inside MTIImageView not resizing properly after applying rotation transformation to MTIImageView

### Checklist
- [x ] If possible, I've reproduced the issue using the `master` branch of this repo
- [x ] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Steps to Reproduce
the internal MTKView inside MTIImageView is not adjusting it's size when I rotate the MTIImageView by applying a transformation.

1- Lock the main container view from automatic rotation when phone rotates. 
2- MTIImageView has all it's resizing constraints to equal the full screen.
3- Crop the mtiImage to render into the proper landscape or portrait aspect ratio, depending of the the phone orientation.
4- Manually apply a rotation transformation to the MTIImageView depending on the phone orientation, including updating the MTIImageView's frame.

For some reason the bug happens only with 9:16 and 16:9.
But 3:4/4:3  and 1:1 **work fine.** 

### Expected behavior
Rendered image should adjust to the container, when MTIImageView is rotated. 
Look at video for iPhone XSMax(13.3), that is how it should work.

### Actual behavior
*iPhone 6 (iOS 12.4.6)* ❌
- When using aspect ratio 9:16 and the phone is rotated to landscape (16:9). The MTKView inside the the MTIImageView does not adjust it's bounds properly. 
- video: https://youtu.be/exzLAQ0NN7s

*iPhone XS Max (iOS 13.3)* 👍
- it works as expected. with no problem. 
- video: https://youtu.be/MB9IUm9lCoI

Download Demo here:
- https://github.com/omarojo/mtiimageviewbug
or
- [MetalPetalTests.zip](https://github.com/MetalPetal/MetalPetal/files/4613631/MetalPetalTests.zip)

**SNIPPET CODE that Rotates the MTIImageView**

```
       let o = UIDevice.current.orientation
        
        var angle:Double = 0;
        if (o == .landscapeLeft ){angle = .pi/2}
        else if (o == .landscapeRight ){angle = -.pi/2}
        else if (o == .portraitUpsideDown || o == .faceUp ){ return}
        DispatchQueue.main.async {
            let rot = CGAffineTransform(rotationAngle: (CGFloat)(angle))
            self.renderView.transform = rot
            self.renderView.frame = CGRect(x: 0, y: 0, width: self.view.bounds.width, height: self.view.bounds.height)
            self.renderView.center = self.view.center
            self.renderView.setNeedsDisplay()
        }

```

**Comment by YuAo** [comment]
Looks like a bug of `MTKView`. The view's position and size is current if you look it in the view debugger, however the drawable size it reports is incorrect.

You can resolve this issue by using the `MTIThreadSafeImageView` which calculates the drawable size on its own.

**Comment by omarojo** [comment]
@YuAo  That seems to work for the default **9:16** aspect ratio and `resizingMode` set to  `.aspect`

But if you change the aspect ratio to: **3:4** and `resizingMode` set to `.aspectFill`
then the issue comes back. 😭😫

[line 19]`var outputAspectRatio: G8OutputAspectRatio = .ar4by3`

[line 35]`renderView.resizingMode = .aspectFill`

**Comment by YuAo** [comment]
Yes... There's actually a bug in `MTIThreadSafeImageView` that prevents the drawable size to be updated in some situation. 

However this does not apply to the `MTIImageView` case, still looks like an Apple bug.

**Comment by YuAo** [comment]
@omarojo Fixed.   https://github.com/MetalPetal/MetalPetal/commit/c3b087769e74b4e86d727743b95c9eedde38f5de

**Comment by omarojo** [comment]
Amazing 😀it works !! 

Thank you.
