### ISSUE TITLE
[MTLDebugDevice newLibraryWithFile:error:]:1549: failed assertion `filepath must not be nil.'

### ISSUE THREAD

**Issue by zhangbenwei** [MetalPetal/MetalPetal#155]
Replace this paragraph with a short description of the incorrect behavior.

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Steps to Reproduce
Replace this paragraph with an explanation of how to reproduce the incorrect behavior.

### Expected behavior
Describe what you expect to happen.

### Actual behavior
Describe or copy/paste the behavior you observe.

**Comment by YuAo** [comment]
Could you be more specific about how you install the framework? If you are using CocoaPods, be sure to include `use_frameworks!` in your Podfile.
