### ISSUE TITLE
How to draw image with dynamic filter?

### ISSUE THREAD

**Issue by larryonoff** [MetalPetal/MetalPetal#157]
Hello,

How to draw image with dynamic filter, e.g moving snowflakes? Is there any examples doing it?

I've found an **Static Image Rendering** in demo app, but it looks that it's just layers sequence.

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
I think a "dynamic filter" is just a filter with a parameter whose value changes over time.

You may need something to "drive" your filters and image updates. For example, a `CADisplayLink`.

You can refer to Apple's CoreImage article - ["Customizing Image Transitions"](https://developer.apple.com/documentation/coreimage/customizing_image_transitions), as well as the `TripleBufferingViewController`(driven by `MTKView`'s draw method) in the demo.

**Comment by larryonoff** [comment]
@YuAo thank you! you're correct about "dynamic filter". I thought that there may be something from MetalPetal framework. But `CADisplayLink` I think is a great solution
