### ISSUE TITLE
Create CGImage from MTIImage?

### ISSUE THREAD

**Issue by cloveri** [MetalPetal/MetalPetal#158]
### Checklist
- [x ] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x ] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)
```
- (CGImageRef)createCGImageFromImage:(MTIImage *)image sRGB:(BOOL)sRGB error:(NSError * __autoreleasing *)inOutError {
    CGImageRef outImage = NULL;
    __unused MTIRenderTask *renderTask = [self startTaskToCreateCGImage:&outImage fromImage:image sRGB:sRGB error:inOutError];
    return outImage;
}
 ```
The function returns  ''outImage" , without waiting for the task to complete.
Will the error result be returned because the "commandBuffer" has not been completed?

**Comment by YuAo** [comment]
Yes and no.

Firstly, it is ok to return a `CGImage` before the command buffer is completed. The `CGImage` here is backed by a `CVPixelBuffer` which is backed by an `IOSurface` which is shared with a `MTLTexture`. When you actually begin to access the image data, for example, draw the image in a `CGContext`, the underlying mechanism of the `CVPixelBuffer`/`IOSurface` (`CVPixelBufferLockBaseAddress`) will wait and ensure that all GPU writes to that buffer is completed.

The `inOutError` here is the error that occurs during the command encoding phase. It's more like a "CPU error". A `nil` error indicates that the GPU commands is encoded without any error and is committed for GPU execution.

The error reported by `MTIRenderTask` is more like a "GPU error". It's the error that occurs during the command buffer execution. You need to wait until the command buffer is executed to check this error. You won't be able to get the command buffer execution error using the `create/makeCGImage` method. If you care about the command buffer execution error, use the `startTaskToCreateCGImage` method.
