### ISSUE TITLE
Animated change MTIImageView frame

### ISSUE THREAD

**Issue by 97mik** [MetalPetal/MetalPetal#159]
When I change MTIImageView frame by using UIView.animate, image immediately rerender (without transition animation). How can I animate this like in classic UIImageView?

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
I don't see any easy way of performing UI animation on a `MTKView` which is used by `MTIImageView` internally for presenting textures.

I think you can take a snapshot of the view using `UIView. snapshotView(afterScreenUpdates:)` then apply the animation to that snapshot?

**Comment by 97mik** [comment]
Solve by putting MTIImageView with original aspect ratio into UIView with clipToBounds: true, and animate UIView size.
