### ISSUE TITLE
I can not reference xxx.h in .metal

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#167]
I install this framework using pod,but got an error.
```
platform:ios,'10.0'

target 'MetalPetal相关实验' do
  pod 'SnapKit', '~> 4.2.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'MetalPetal', '~> 1.10.6'
end

```
XCode can not find xxx.h,when i write shaders

### Checklist
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Steps to Reproduce
Make a new ios project using XCode
Install the framework using pod like below
```
platform:ios,'10.0'

target 'MetalPetalTest' do
  pod 'MetalPetal', '~> 1.10.6'
end
```
Reference #include "MTIShaderLib.h" in some .metal
Build the project.
And you will see the error

### Expected behavior
I want to write a shader of some function.

### Actual behavior
XCode can not find xxx.h

**Comment by YuAo** [comment]
See https://github.com/MetalPetal/MetalPetal#build-custom-filter

**Comment by StromanStroman** [comment]
It's done,thank you
