### ISSUE TITLE
MTIImage does not display

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#168]
Replace this paragraph with a short description of the incorrect behavior.

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Steps to Reproduce
I use a mtiimageview to display a mtiimage just as your demo "BlendModeViewController.m",but I got an error
"<MTIImageView: 0x123f3f530; frame = (0 0; 768 1024); layer = <CALayer: 0x2825efce0>>: Failed to render image <MTIImage: 0x28301a3c0; width = 690; height = 830; depth = 1; cachePolicy = 1; promise = <MTICGImagePromise: 0x28301a480>> - Error Domain=MTIErrorDomain Code=1002 "MTIErrorFunctionNotFound" UserInfo={MTIFunctionDescriptor=<MTIFunctionDescriptor: 0x282b3e550; name = passthroughVertex; constantValues = (null); libraryURL = (null)>, NSLocalizedDescription=MTIErrorFunctionNotFound}"

### Expected behavior
I expect that mtiimageview can display a mtiimage normally

### Actual behavior
mtiimageview can not display a mtiimage normally,and I got an error,I was perplexed。

**Comment by YuAo** [comment]
See https://github.com/MetalPetal/MetalPetal#cocoapods

Make sure to `use_frameworks!`

**Comment by StromanStroman** [comment]
> See https://github.com/MetalPetal/MetalPetal#cocoapods
> 
> Make sure to `use_frameworks!`

It's done,thank you.
I suggest that you make it easier like other library,for example SnapKit,afnetworking.
User can use it no matter use_frameworks! exist or not.

**Comment by YuAo** [comment]
@StromanStroman That's not possible when there are metal files to be complied in the framework (with the current version of Xcode and CocoaPods). Extra configurations have to be applied to make it work with the "static library" option. 

There's a `MetalPetal/Static` sub pod which can work without `use_frameworks!`. However I'm not going to provide any support for this configuration.

**Comment by StromanStroman** [comment]
> @StromanStroman That's not possible when there are metal files to be complied in the framework (with the current version of Xcode and CocoaPods). Extra configurations have to be applied to make it work with the "static library" option.
> 
> There's a `MetalPetal/Static` sub pod which can work without `use_frameworks!`. However I'm not going to provide any support for this configuration.

OK,I know it,thank you agian
