### ISSUE TITLE
how to implement a print function?

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#170]
I need a print function.
I print a path,which consist of many vertexes, into a texture,looks like a path or a curve.
Or you can think of it as a drawing board or something like that.

What's the best way of implementing this function useing metalpetal?

**Comment by YuAo** [comment]
How about implementing the `MTIGeometry` protocol and issue your own drawcalls.

**Comment by StromanStroman** [comment]
> I don't really understand your question.
> 
> If you'd like to draw custom vertices, you should implement the `MTIGeometry` protocol and issue your own drawcalls.
> 
> If you want something like a sketch/draw board let the user move his/her finger to draw something you should use an "Image Accumulator" which can be done with `MTIContext.renderedBuffer(for:)`.

I will try Image Accumulator

**Comment by StromanStroman** [comment]
> I don't really understand your question.
> 
> If you'd like to draw custom vertices, you should implement the `MTIGeometry` protocol and issue your own drawcalls.
> 
> If you want something like a sketch/draw board let the user move his/her finger to draw something you should use an "Image Accumulator" which can be done with `MTIContext.renderedBuffer(for:)`.

Maybe MTIContext.renderedBuffer(for:) is of swift,and I found "- (MTIImage *)renderedBufferForImage:(MTIImage *)targetImage" in Objective-C version.
But I don't quite understand how to use it ,what it used for,is there some example for using "- (MTIImage *)renderedBufferForImage:(MTIImage *)targetImage" in metalpetal?

**Comment by YuAo** [comment]
Added to the demo project.

**Comment by StromanStroman** [comment]
Excuse me!How to use - (MTIImage *)renderedBufferForImage:(MTIImage *)targetImage?
I did not see its usage in demo

**Comment by YuAo** [comment]
See the sketch board demo. Ref https://github.com/MetalPetal/MetalPetal/blob/master/MetalPetalDemo/SketchViewController.swift
