### ISSUE TITLE
How to reuse a vertex buffer?

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#172]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

I just read the whole code of MTIContext and MTIVertices,etc.
I found that there is no reuseable vertexbuffer which can update its contents.
All have is to init a new vertexbuffer everytime,which will result in great overhead.
What I need is a vertexbuffer,which bind to MTIContext,enough length bytes,can be just update content.
Is there any thing like i write in metalpetal?

**Comment by StromanStroman** [comment]
Can I change the length of a same buffer dynamically?

**Comment by YuAo** [comment]
Use `MTIDataBuffer`. You may want to see the "Triple Buffering" code in the demo project.

**Comment by StromanStroman** [comment]
> Use `MTIDataBuffer`. You may want to see the "Triple Buffering" code in the demo project.

No,I just want one buffer in the whole app life.

**Comment by YuAo** [comment]
What do you mean by "one buffer"? If you only use "one buffer" then you'll have to make the CPU wait for the GPU, that would be very inefficient.

**Comment by StromanStroman** [comment]
The one buffer is just used for contain custom vertexes,it is just be used in every draw.
My requirement is not so complex as you think.
Just one draw a time,I do not need care "Triple Buffering" at least for now.
What I care about is the overhead to alloc a different size buffer.

**Comment by StromanStroman** [comment]
I found - (nullable id<MTLBuffer>)bufferForDevice:(id<MTLDevice>)device NS_SWIFT_NAME(buffer(for:)); may be work.
But I sitll not found a way for updating a buffer's size dynamically.

**Comment by YuAo** [comment]
Use `MTIDataBuffer`. You can update the buffer's content using `unsafeAccess` method. You can create a `MTIVertices` object from a `MTIDataBuffer` or you can use it directly in your custom geometry like the "Triple Buffering" demo did.

**Comment by StromanStroman** [comment]
Thank you

**Comment by YuAo** [comment]
You cannot change the buffer's length. You'll have to recreate one or reserve enough size. 

Mainly because:
- The length of a GPU buffer cannot be updated. 
- The CPU memory shared with the GPU must be page aligned, so if you want to update the CPU buffer's length you'll have to recreate the CPU buffer with `vm_alloc` and copy the old content to the newly allocated buffer.
