### ISSUE TITLE
How to make blend?

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#173]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Just like below
MTLRenderPipelineColorAttachmentDescriptor *blendDescriptor = descriptor.colorAttachments[0];
        blendDescriptor.blendingEnabled = YES;
        blendDescriptor.alphaBlendOperation = MTLBlendOperationAdd;
        blendDescriptor.rgbBlendOperation = MTLBlendOperationAdd;
        blendDescriptor.sourceRGBBlendFactor = MTLBlendFactorOneMinusSourceAlpha;
        blendDescriptor.destinationRGBBlendFactor = MTLBlendFactorOne;
        blendDescriptor.sourceAlphaBlendFactor = MTLBlendFactorSourceAlpha;
        blendDescriptor.destinationAlphaBlendFactor = MTLBlendFactorOneMinusSourceAlpha;
How to do?
Any interfaces to use?

**Comment by YuAo** [comment]
We do not support blending at render pipeline level by default. 

You may enable blending if you implement your own `MTIImagePromise`.
You can also choose to use programmable blending by register your custom blending functions to `MTIBlendModes`.
