### ISSUE TITLE
How to debug shader?

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#174]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Like the sample demo of apple's document.
I want to see every texel value,every variable value in shader,how can i do that?

**Comment by YuAo** [comment]
https://developer.apple.com/documentation/metal/shader_authoring/developing_and_debugging_metal_shaders

**Comment by StromanStroman** [comment]
How to make it in metalpetal?

**Comment by YuAo** [comment]
I don't think you need to do anything special with MetalPetal.

**Comment by StromanStroman** [comment]
You mean metalpetal does not suppurt shader debug?

**Comment by YuAo** [comment]
I mean I don't think you need to do anything special to enable shader debugging with MetalPetal.

**Comment by YuAo** [comment]
Debugging with the demo.
![Screen Shot 2020-07-14 at 13 38 54](https://user-images.githubusercontent.com/1234944/87388453-6caae100-c5d7-11ea-8580-d6a09d3db4e8.png)

**Comment by StromanStroman** [comment]
I checked it again,it works.Maybe something wrong with my project.

**Comment by StromanStroman** [comment]
I found that what I can only see is the display stage.
What should I do if I want to debug shader in Intermediate stage,or some filter's shader in filter chain?
