### ISSUE TITLE
Using Core Image Filters with MetalPetal

### ISSUE THREAD

**Issue by freggy145** [MetalPetal/MetalPetal#175]
Hey, 

Sorry for this newbie question, but how can I use one of the CIFilters with MetalPetal? The docs say that All Core Image Filters are supported but I'm having a hard time figuring out how can I construct `CILanczosScaleTransform` filter with MetalPetal. 

Thanks for the help!

**Comment by YuAo** [comment]
Added two tests about lanczos scale filter. https://github.com/MetalPetal/MetalPetal/commit/1c3e017e35e6070ab4c0da564d8490c52b5d86c1
