### ISSUE TITLE
How to input float4x4 into shader?

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#176]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

I read the demo.
I read MTIColorMatrixFilter.
But that is not the way I want.
What I want is just put matrix type into parameters.
How to do it?

**Comment by YuAo** [comment]
**Read** README.
Using `MTIVector` if you are using Objective-C. Using `float4x4` directly if you are using Swift.
https://github.com/MetalPetal/MetalPetal/blob/master/README.md#shader-function-arguments-encoding

**Comment by StromanStroman** [comment]
thank you very much

**Comment by StromanStroman** [comment]
Are you chinese?If that,we can communicate with each other in chinese.
