### ISSUE TITLE
id<mtltexture>如何转换到Mtiimage？

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#179]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

我自己想管理一个mtltexture的创建和销毁，只不过，在渲染的时候我会把它转换成mtiimage临时用一下。
有没有这样的方法？
我不想有任何除了我自己管理的纹理之外的内存变化。

**Comment by YuAo** [comment]
https://github.com/MetalPetal/MetalPetal/blob/master/Frameworks/MetalPetal/MTIImage.h#L82
