### ISSUE TITLE
Why rendering to YUV is supported A9+ only?

### ISSUE THREAD

**Issue by gltdv** [MetalPetal/MetalPetal#182]
Why would rendering image to pixel buffer only work for 'MTLFeatureSet_iOS_GPUFamily3_v1`?

Forcing it to Family2 (iPhone 6) causing a crash at
```
id<MTLRenderPipelineState> renderPipelineState = [self.device newRenderPipelineStateWithDescriptor:renderPipelineDescriptor options:MTLPipelineOptionArgumentInfo reflection:&reflection error:&error];
```

**Comment by YuAo** [comment]
The older apple GPUs simply do not support this feature.

**Comment by gltdv** [comment]
Thanks for the update. Is this documented anywhere?

**Comment by YuAo** [comment]
No.

**Comment by gltdv** [comment]
Thanks again @YuAo.

Video output is `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange` which is used to create `CVPixelBuffer` which is then used to create `MTIImage`.

It doesn't make sense that we cannot render `MTIImage` back to `CVPixelBuffer` with format `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange`.
