### ISSUE TITLE
mtiimage to mtltexture?

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#184]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Is there a method using for turning mtiimage to mtltexture?
I'v read 
- (nullable MTIRenderTask *)startTaskToRenderImage:(MTIImage *)image
                                         toTexture:(id<MTLTexture>)texture
                              destinationAlphaType:(MTIAlphaType)destinationAlphaType
                                             error:(NSError **)error
                                        completion:(nullable void (^)(MTIRenderTask *task))completion NS_SWIFT_NAME(startTask(toRender:to:destinationAlphaType:completion:));
It's too complex.
I do not care MTIRenderTask，MTIAlphaType etc.
I just want a method that only one input——mtiimage,just one output——mtltexture.

**Comment by YuAo** [comment]
If you don't care about the alpha channel's value you can pass `.alphaIsOne` to the `destinationAlphaType` argument.
If you don't care about CPU/GPU data synchronization you can ignore the returned `MTIRenderTask` object and the `completion` block. However if you want to access the texture's data on CPU or use that texture in a different GPU command queue, you may want to wait until the render task is completed.
