### ISSUE TITLE
MTIImage from CGImage causes signal SIGABRT crash

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#185]
The latest v1.13.0 is causing a SIGABRT error specifically in all calls that convert UIImage.cgimage to MTIImage
either using `MTIImage(cgImage: cimg.cgImage!, options: [MTKTextureLoader.Option.SRGB : false], isOpaque: true)`
or the new ` UIImage(named: loadTexture).map({ MTIImage(image: $0, isOpaque: true) })`

MetalPetal 1.12.0 works fine tho. 

Unfortunately I tried to isolate the crash in a clean project, and it 1.13.0 works fine with those methods. 
Do you have any recommendations that may be causing this to happen ? Im getting this error all across different parts of the app where I try to create a MTIImage from a CGImage.

**Comment by YuAo** [comment]
Try a clean build? Do you have any call stack traces?

**Comment by omarojo** [comment]
hahaha you kidding me. Cleaning the project worked ! 
🎉🎉👏👏🤙😂😂
Thanks

**Comment by YuAo** [comment]
I think it's related to this issue: https://github.com/CocoaPods/CocoaPods/issues/8073

If you are using CocoaPods and Xcode 10/11's new build system, you may need to do a clean build after source files in a pod changed. 
It seems that they've fixed this with Xcode 12 beta.
