### ISSUE TITLE
Add glitch filters

### ISSUE THREAD

**Issue by jerry317** [MetalPetal/MetalPetal#186]
Hello, is it possible to add glitch filters in the future update?
Or how to implement glitch filters with the current version.

**Comment by YuAo** [comment]
Glitch will not be in the built-in filters. There are a lot of ways implementing glitch. You can find a lot of shaders about glitch on "shadertoy.com" https://www.shadertoy.com/results?query=glitch

**Comment by isamercan** [comment]
> Glitch will not be in the built-in filters. There are a lot of ways implementing glitch. You can find a lot of shaders about glitch on "shadertoy.com" https://www.shadertoy.com/results?query=glitch

@YuAo is it possible to use shadertoy's shaders use in MetalPetal?

**Comment by YuAo** [comment]
@isamercan Not directly, you need to translate the WebGL shader to MSL. It is possible to do the translation automatically using tools like [glslang](https://github.com/KhronosGroup/glslang) and [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross).

**Comment by isamercan** [comment]
> 
ok I see. Its a progress and thank you so much. What if I want to get ready to use MSL. where can i find? For example Glitch, sparkle, dust effects.
