### ISSUE TITLE
Is there a way to replace black color with transparent color in MTIImage?

### ISSUE THREAD

**Issue by furysheep** [MetalPetal/MetalPetal#188]
# Checklist
- [X] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [X] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

I have searched all filters but didn't find a suitable one.

**Comment by YuAo** [comment]
`MTIChromaKeyBlendFilter`(https://github.com/MetalPetal/MetalPetal/blob/1f0da098b564e2730f6ca90d2bf625975960b57e/Frameworks/MetalPetal/Filters/MTIChromaKeyBlendFilter.h)?

This filter replaces `color` in the `inputImage` with the `inputBackgroundImage`.

**Comment by ricsantos** [comment]
Hi, thanks for the great library!

I'm trying to achieve this also (convert a mask that is black/white to transparent/white). This is my function:

```
func makeTransparent(mask: UIImage) -> UIImage {
    let ciMask = CIImage(cgImage: mask.cgImage!)
    let mtiImage = MTIImage(ciImage: ciMask, isOpaque: true)

    let contextOptions = MTIContextOptions()
    let context = try! MTIContext(device: MTLCreateSystemDefaultDevice()!, options: contextOptions)

    let opacityFilter = MTIChromaKeyBlendFilter()
    opacityFilter.inputImage = mtiImage
    opacityFilter.inputBackgroundImage = MTIImage(color: MTIColor.clear, sRGB: true, size: mask.size)
    opacityFilter.color = MTIColor.black

    let outputImage = try! context.makeCGImage(from: opacityFilter.outputImage!)
    return UIImage(cgImage: outputImage)
}
```

It takes an image, and am trying to export an image with transparency instead of black.

Any help would be appreciated, thank you.

**Comment by vjdaemp** [comment]
@YuAo , I tried using your suggestion to use `MTIChromaKeyBlendFilter ` to replace 'background color' in `MTIImage` with 'clear color'. It is working when displaying the resulting `MTIImage` in `MTIImageView`, but not when saving as `UIImage`.  Do you have any suggestions?

Note: This is happening with my modifications made to sample app (`SketchViewController`).  I am trying to save only the brush strokes (and not the background).  

I modified the background so that it is red.

```
            let background = MTIImage(color: MTIColor.init(red: 1, green: 0, blue: 0, alpha: 1), sRGB: false, size: self.brushImage.size)
            compositingFilter.inputBackgroundImage = background
            compositingFilter.layers = [MultilayerCompositingFilter.Layer(content: self.brushImage)]
            let _ = try? self.imageView.context!.startTask(toRender: compositingFilter.outputImage!)

```

Then I used  `MTIChromaKeyBlendFilter ` to make the red background transparent, and converted to `UIImage` so that only brush stokes (with transparent background) are written to `UIImage`:

```
    private func saveDrawing() {
        
        let filter = MTIChromaKeyBlendFilter()
        filter.inputBackgroundImage = MTIImage(color: MTIColor.init(red: 0, green: 0, blue: 0, alpha: 0), sRGB: true, size: imageView.image!.size)
        filter.inputImage = imageView.image
        filter.color = MTIColor.init(red: 1, green: 0, blue: 0, alpha: 1)
        
        
        let result = filter.outputImage
        imageView.image = result
        
        let outputImage = try! self.imageView.context!.makeCGImage(from: result!)
        let finalImage = UIImage(cgImage: outputImage)
        
        UIImageWriteToSavedPhotosAlbum(finalImage, nil, nil, nil)
    }
```

**Comment by YuAo** [comment]
@vjdaemp `UIImageWriteToSavedPhotosAlbum` always saves the opaque image.  Use `Photos.framework` to save the image.

**Comment by vjdaemp** [comment]
ah, yes I forgot about that -- thanks @YuAo
