### ISSUE TITLE
Most energy efficient way to render?

### ISSUE THREAD

**Issue by gltdv** [MetalPetal/MetalPetal#189]
Hello,

I'm rendering real time camera filter and noticed an increase in CPU usage by doing:
```
someMTIImageView.image = filterOutputImage;
```

The CPU usage is coming mostly from `[MTIIMageView setIamge]` to `[MTIPersistImageResolutionHolder dealloc]`.

1) Is there an efficient way to render a filter output?
2) Can we render to `CAMetalLayer` instead of `MTIImage`?

**Comment by YuAo** [comment]
The CPU load should be in `setImage:` or `-[MTIPersistImageResolutionHolder dealloc]`. Can you attach a sample project or an instruments screenshot? Can you reproduce this in the camera demo?

You can render directly to a `CAMetalLayer`, please refer to `MTIThreadSafeImageView`'s implementation [MTIThreadSafeImageView.m](https://github.com/MetalPetal/MetalPetal/blob/master/Frameworks/MetalPetal/UI/MTIThreadSafeImageView.m)

**Comment by gltdv** [comment]
Thank you @YuAo,

> The CPU usage is coming mostly from [MTIIMageView setIamge] to [MTIPersistImageResolutionHolder dealloc].
- This likely is a result of `reclaimResources`.
- By removing `reclaimResources` from capture loop, `drawInMTKView` became the top CPU time consumer. Is that expected?

> You can render directly to a CAMetalLayer, please refer to MTIThreadSafeImageView's implementation
- `MTIThreadSafeImageView` performance is very close to `MTIImage`.
- In both cases, rendering a filtered image introduces ~2.7% CPU usage on iPhone 11.

**Comment by YuAo** [comment]
> By removing reclaimResources from capture loop, drawInMTKView became the top CPU time consumer. Is that expected?

Yes.

> In both cases, rendering a filtered image introduces ~2.7% CPU usage on iPhone 11.

This is expected too. The CPU is used to issue GPU render commands.

**Comment by gltdv** [comment]
Thank you @YuAo
