### ISSUE TITLE
glitter effect

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#19]
Hello, I wanted to ask how to implement this library glitter filter. The Glitter filter creates a glittering or sparkling light effect. . A luminance map creates the glitter based on bright areas in the image.
![htb1nqm4rfxxxxxlxfxxq6xxfxxxa](https://user-images.githubusercontent.com/29518174/36249453-965e2f2e-125c-11e8-95e5-2d8c22ae7837.jpg). Please, if this library can not do this, tell me how to do it in IOS. Any references, lessons I will be grateful for. Thanks. PS - Sorry for my English:)

**Comment by YuAo** [comment]
Masaki Kawase, Frame Buffer Postprocessing Effects in DOUBLE-S.T.E.A.L (Wreckless), GDC 2003

http://slideplayer.com/slide/3406110/

Slides - Page 18 - Star (light streaks)

**Comment by alyfreym** [comment]
Thanks.
