### ISSUE TITLE
Is it possible to achieve Teal kind a look on MetalPetal? [Question] [Example added]

### ISSUE THREAD

**Issue by GustasBr** [MetalPetal/MetalPetal#190]
Hey,

I'm trying to achieve this kind a look like in example. I don't know how it's done because I saw those filters online but I really want to make something similar. I know for sure that it's not highlights/shadows split toning because as you see in the video it's like a second colour layer on top of the photo. I tried to achieve this in Lightroom but I can't because LR modifies colours that your photo has. (what I mean is that if the photo has blue colour then it's going to look great. But if it's not then it's impossible to get teal colours inside your image). It's really hard to explain what I want to say so please take a look at the GIF and final image.

**Final image:**
![IMG_0307](https://user-images.githubusercontent.com/18195248/89341045-61644600-d6a9-11ea-87c1-67aaa59681dc.JPG)

**GIF:**

![ezgif com-optimize](https://user-images.githubusercontent.com/18195248/89341804-8a390b00-d6aa-11ea-9265-3bbad8edb284.gif)

**Original image:**
![IMG_0238](https://user-images.githubusercontent.com/18195248/89342134-03d0f900-d6ab-11ea-98ed-5dafa4db0a77.jpg)

**Comment by YuAo** [comment]
Did you try blending a solid color image with the input using one of the `MTIBlendMode`s. 

I cannot give you any advices on designing filters, you should ask a designer for help.
