### ISSUE TITLE
Two input textures mixed into one in custom filter (iPhone 11 only)

### ISSUE THREAD

**Issue by dannydaddy3** [MetalPetal/MetalPetal#191]
Hello, @YuAo I have a weird bug that happens ONLY on iPhone 11 (checked on iPhone 6s, iPhone XS and it works normally). I need to find a way to fix it. 

I have my custom MTIFilter. I added simplified code for filter below that takes 3 input textures and simply returns second texture without any modifications. As I said it works normally on all devices, but on iPhone 11 I have strange output where image is mixed of 2 textures somehow. Like if Metal would read part of texture from one image and part from another. And it's randomly mixed every time. 

Here's how the output looks: Instead of just **blurredTexture** content as output, I have mixed result of two textures (Unfortunately when I tested on my friend's device I forgot to take a screenshot, so I visualised an example of how it looked)
<img width="287" alt="Screenshot 2020-08-05 at 01 31 45" src="https://user-images.githubusercontent.com/15005840/89353123-70092800-d6be-11ea-857c-a1e521d2c96b.png">

PhotoBlurEdgesFilter.swift
```
import MetalPetal

class PhotoBlurEdgesFilter: NSObject, MTIFilter {
  
  var inputImage: MTIImage?
  var blurredImage: MTIImage?
  var depthImage: MTIImage?
  
  var offsetX: Float = 0
  
  var outputPixelFormat: MTLPixelFormat = .invalid
  
  static let kernel: MTIRenderPipelineKernel = {
    let lib = MTIDefaultLibraryURLForBundle(Bundle.main)
    let vertexFunc = MTIFunctionDescriptor.passthroughVertex
    let fragmentFunc = MTIFunctionDescriptor(name: "photoBlurEdgesFragment", libraryURL: lib)
    return MTIRenderPipelineKernel(vertexFunctionDescriptor: vertexFunc, fragmentFunctionDescriptor: fragmentFunc)
  }()
  
  var outputImage: MTIImage? {
    guard let input = inputImage, let blurred = blurredImage, let depth = depthImage else { return nil }
    return PhotoBlurEdgesFilter.kernel.apply(toInputImages: [input, blurred, depth],
                                             parameters: ["offsetX": offsetX],
                                             outputTextureDimensions: MTITextureDimensions(cgSize: input.size),
                                             outputPixelFormat: outputPixelFormat)
  }
}
```

PhotoBlurEdgesFilter.metal
```
#include <metal_stdlib>
#include "MTIShaderLib.h"

using namespace metal;

namespace metalpetal {
  
  fragment float4 photoBlurEdgesFragment(VertexOut vertexIn [[stage_in]],
                                         texture2d<float, access::sample> sourceTexture [[texture(0)]],
                                         texture2d<float, access::sample> blurredTexture [[texture(1)]],
                                         texture2d<float, access::sample> depthTexture [[texture(2)]],
                                         sampler sourceSampler [[sampler(0)]],
                                         sampler blurredSampler [[sampler(1)]],
                                         sampler depthSampler [[sampler(2)]],
                                         constant float &offsetX [[buffer(0)]])
  {
    return blurredTexture.sample(blurredSampler, vertexIn.textureCoordinate);
  }
}
```

By the way blurredTexture is a result of a MTIMPSGaussianBlurFilter, may be this could affect it. 
And weird enough, I have a radius for MTIMPSGaussianBlurFilter set to 1.5, and when I change it to 2.5 or more, it partly fix problem. And also I tried to add `.withCachePolicy(.persistent)` to gaussian filter output, and it also partly helped. (by partly I mean it fixed bug in my custom filter I showed, but the same bug appeared on another custom filter... where cache policy didn't seem to help)

@YuAo could you tell would could cause the problem on iPhone 11 and any ways how I can fix it? 

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
Cannot reproduce on a iPhone 11 running iOS 13. 

I tested the filter using the CameraViewController demo. 

change:
https://github.com/MetalPetal/MetalPetal/blob/master/MetalPetalDemo/CameraViewController.swift#L129-L134

to:
```
    // line 129
    if self.isFilterEnabled {
            let blurFilter = MTIMPSGaussianBlurFilter()
            blurFilter.radius = 1.5
            blurFilter.inputImage = inputImage
            let filter = PhotoBlurEdgesFilter()
            filter.blurredImage = blurFilter.outputImage
            filter.depthImage = MTIImage.black
            filter.inputImage = inputImage
            if let image = filter.outputImage?.withCachePolicy(.persistent) {
                outputImage = image
            }
        }
```

**Comment by dannydaddy3** [comment]
@YuAo I couldn't reproduce it on demo as well, but this is simplified version of the filter, in my project I have several filters reused and used in chain, so it's hard to reproduce it on demo.

I managed to fix this problem by replacing MTIMPSGaussianBlurFilter with my custom gaussian filter, and it works normally (also just removing MTIMPSGaussianBlurFilter fixes the problem). So it's actually possible that problem caused by some MPS related thing, maybe there were some changes since iPhone 11 

If you have no clue what could possibly mess up textures like this, I think we can close issue for now

**Comment by dannydaddy3** [comment]
Update: 

@YuAo I just checked new Metal WWDC 2020 videos, here's what I found:

Please watch it starting from 5:00
https://developer.apple.com/videos/play/tech-talks/608/ 

The new feature available only for A13 Bionic (iPhone 11 and newer) called Sparse Heaps and Sparse Textures. This allows two textures share the same memory. I guess this is exactly what causing my two textures mixing in shader. 

Here's more info I found: 
https://developer.apple.com/documentation/metal/textures/managing_texture_memory/creating_sparse_heaps_and_sparse_textures 
https://developer.apple.com/documentation/metal/textures/managing_texture_memory?language=objc

I'm not really good at understanding such low level stuff, @YuAo could you please see this and find how this "sparse texture" feature can be turned off? 

I really need to fix this cause I have this bug on production for all users with A13 Bionic chip..

**Comment by YuAo** [comment]
MetalPetal does not use heaps by default, unless you tell it to use `MTIHeapTexturePool`. So it's not a problem with heap.

**Comment by YuAo** [comment]
Any updates? @dannydaddy3

**Comment by dannydaddy3** [comment]
@YuAo I don't have my own iPhone 11 for testing, so I can't check it unfortunately. As a workaround for iPhone 11 and newer I just replaced MTIMPSGaussianBlurFilter with my custom gaussian filter and it fixed the problem. 

I think we can close the issue for now, and reopen it in case someone has the same problem
