### ISSUE TITLE
Is there any common ways to send data from shader function to MTIFilter back?

### ISSUE THREAD

**Issue by larryonoff** [MetalPetal/MetalPetal#192]
Is there any common ways to send data from shader function to MTIFilter? I would like to implement some kind of https://github.com/FlexMonkey/ParticleCam/blob/master/ParticleCam/Shaders.metal

**Comment by YuAo** [comment]
I think you can use `MTIDataBuffer`. A `MTIDataBuffer` can be binded to a shader parameter with type `device T *`, you can write the buffer in the shader.  And you can safely pass this buffer to another filter.

You can also access the buffer's content on CPU using the `unsafeAccess` method. However, you must ensure all the GPU reads/writes to this buffer is completed. For example, after calling the `waitUntilCompleted` method of the `MTIRenderTask`.

**Comment by larryonoff** [comment]
> I think you can use `MTIDataBuffer`. A `MTIDataBuffer` can be binded to a shader parameter with type `device T *`, you can write the buffer in the shader. And you can safely pass this buffer to another filter.
> 
> You can also access the buffer's content on CPU using the `unsafeAccess` method. However, you must ensure all the GPU reads/writes to this buffer is completed. For example, after calling the `waitUntilCompleted` method of the `MTIRenderTask`.

Thank you for the answer!

Is there any existing filters / code in MetalPetal that I can check?

**Comment by YuAo** [comment]
Sorry there are currently no demos.

**Comment by YuAo** [comment]
Demo added. 668ef046bcd0edc8ff7ed6ca5de9c17df0a26283

**Comment by larryonoff** [comment]
@YuAo wow. thanks!
