### ISSUE TITLE
Operators to apply array of filters

### ISSUE THREAD

**Issue by larryonoff** [MetalPetal/MetalPetal#193]
I have an array of `MTIUnaryFilter`. It would be great having operator that connects them all with MTIImage in a way below

```swift
        let lutFilter = MTIColorLookupFilter(...)

        let filters: [MTIUnaryFilter] = [
            adjustments.clarityFilter,
            adjustments.contrastFilter,
...
            adjustments.vibranceFilter
        ].compactMap { $0 }

        return FilterGraph.makeImage { output in
            if let lutFilter = lutFilter {
                image => lutFilter.inputPorts.inputImage

                lutFilter
                    => filters
                    => output
            } else {
               imag
                    => filters
                    => output
            }
      }
```

It also would be great to connect LUT filter in a shorter way, e.g.

```swift
                image
                    => lutFilter
                    => filters
                    => output
```

**Comment by YuAo** [comment]
For the first problem, you can add a extension to `AnyIOPort` to make it support a sequence of `MTIUnaryFilter`
```Swift
extension AnyIOPort {
    class UnaryFilterGroup<T: Sequence> where T.Element == MTIUnaryFilter {
        var filters: T
        var inputImage: MTIImage?
        var outputImage: MTIImage? {
            filters.reduce(inputImage) { (result, filter) -> MTIImage? in
                filter.inputImage = result
                return filter.outputImage
            }
        }
        init(_ filters: T) {
            self.filters = filters
        }
        struct Port: InputPort, OutputPort {
            public let object: UnaryFilterGroup<T>
            public let keyPath: KeyPath<UnaryFilterGroup<T>, MTIImage?> = \.outputImage
            public let writableKeyPath: ReferenceWritableKeyPath<UnaryFilterGroup<T>, MTIImage?> = \.inputImage
        }
    }
    public init<T: Sequence>(sequence: T) where T.Element == MTIUnaryFilter, Value == MTIImage? {
        self.init(UnaryFilterGroup.Port(object: UnaryFilterGroup(sequence)))
    }
}
```
Then you can: `inputImage => AnyIOPort(sequence: [saturationFilter, exposureFilter, contrastFilter]) => output`

---

For the second problem. You are required to use `inputPorts.inputImage` because the `MTIColorLookupFilter` is a two inputs filter. We don't know which input you are referring by using only `=>` operator. However, you can declare it to be a `MTIUnaryFilter` to make the `FilterGraph` api ignore the `inputColorLookupTable`.
```
extension MTIColorLookupFilter: MTIUnaryFilter {}
```

**Comment by larryonoff** [comment]
Thank. Really helpful!

**Comment by isamercan** [comment]
@YuAo thanks for a great extension. I have declared for `MTIUnaryFilter` for the `MTIBlendFilter` too.
`extension MTIBlendFilter: MTIUnaryFilter {}`

```
 sourceImage => AnyIOPort(sequence: [blendFilter, lookupFilter, pixellateFilter, roundCornerFilter])
                                => output
```


> For the first problem, you can add a extension to `AnyIOPort` to make it support a sequence of `MTIUnaryFilter`
> 
> ```swift
> extension AnyIOPort {
>     class UnaryFilterGroup<T: Sequence> where T.Element == MTIUnaryFilter {
>         var filters: T
>         var inputImage: MTIImage?
>         var outputImage: MTIImage? {
>             filters.reduce(inputImage) { (result, filter) -> MTIImage? in
>                 filter.inputImage = result
>                 return filter.outputImage
>             }
>         }
>         init(_ filters: T) {
>             self.filters = filters
>         }
>         struct Port: InputPort, OutputPort {
>             public let object: UnaryFilterGroup<T>
>             public let keyPath: KeyPath<UnaryFilterGroup<T>, MTIImage?> = \.outputImage
>             public let writableKeyPath: ReferenceWritableKeyPath<UnaryFilterGroup<T>, MTIImage?> = \.inputImage
>         }
>     }
>     public init<T: Sequence>(sequence: T) where T.Element == MTIUnaryFilter, Value == MTIImage? {
>         self.init(UnaryFilterGroup.Port(object: UnaryFilterGroup(sequence)))
>     }
> }
> ```
> 
> Then you can: `inputImage => AnyIOPort(sequence: [saturationFilter, exposureFilter, contrastFilter]) => output`
> 
> For the second problem. You are required to use `inputPorts.inputImage` because the `MTIColorLookupFilter` is a two inputs filter. We don't know which input you are referring by using only `=>` operator. However, you can declare it to be a `MTIUnaryFilter` to make the `FilterGraph` api ignore the `inputColorLookupTable`.
> 
> ```swift
> extension MTIColorLookupFilter: MTIUnaryFilter {}
> ```
