### ISSUE TITLE
Can no longer subclass MTIImageView

### ISSUE THREAD

**Issue by justinmiller62** [MetalPetal/MetalPetal#194]
In version 1.10.6 of the framework I could subclass MTIImageView but in the latest couple of versions I can no longer do that. I get the following error.

Cannot inherit from non-open class 'MTIImageView'  outside of its defining module

**Comment by YuAo** [comment]
Yes. We prefer "composition over inheritance". 

Can you describe the situation where you have to subclass `MTIImageView`?
