### ISSUE TITLE
Memory Leak due to commit

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#195]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Every time after commandbuffer commit,I found memory usage increase xxxMb,can not decrease as before.
Why?

**Comment by YuAo** [comment]
How about `MTIContext.reclaimResources()` after each `MTIContext.render(....)`?

**Comment by StromanStroman** [comment]
> How about `MTIContext.reclaimResources()` after each `MTIContext.render(....)`?

Not solved.

**Comment by YuAo** [comment]
Can you attach a demo project?

**Comment by YuAo** [comment]
@StromanStroman Any more inputs?

**Comment by StromanStroman** [comment]
Sorry,I can not provide any code for it's of commerical.
Our team is still searching the reason of that.

**Comment by YuAo** [comment]
Closing this issue. Reopen if you find that's related to MetalPetal.
