### ISSUE TITLE
Cannot compile MetalPetal demo

### ISSUE THREAD

**Issue by larryonoff** [MetalPetal/MetalPetal#196]
Cannot compile MetalPetal demo for device. It works fine on simulator.

Please see an error enclosed to the issue:

<img width="830" alt="Screen Shot 2020-08-17 at 13 38 43" src="https://user-images.githubusercontent.com/372616/90387576-1b3ab980-e08f-11ea-85fd-e4f1d695e9a9.png">

**Comment by YuAo** [comment]
Fixed via f2400072203e9cb6182595f786d4535198690540
