### ISSUE TITLE
Banding issue

### ISSUE THREAD

**Issue by Umity** [MetalPetal/MetalPetal#197]
Hi guys, 

I have a problem with the lut feature, but i am not blaming MetalPetal for this. As I also experienced the same problem with the other libraries. 

The problem is banding on some luts. I know how to create luts and i know what to use or not. What i dont understand why they happen? And how to get rid of it? Working with p3 colorspace is the remedy? So, thats why i decided to open the thread here. and i am attaching a final output images that showing the banding. You cant see this kind of problems on high quality software. 

On the other hand, if i convert the 3dlut image to cube by using https://github.com/YuAo/ColorLookupTable2Cube then that cube file working perfectly on photoshop without banding.

and here are the images that have bandings:
https://imgur.com/67CPAGg
https://imgur.com/7q77DSx

**Comment by Umity** [comment]
Hi @YuAo 
it was just an extreme lut, created it with many tricks, include highlights/shadows from lightroom (i know not ideal).

But as i said, this was just an extreme example. And, even after smoothing with blur, i can see the bandings. 

Let me give you a very smooth lut, even with this, you will notice the bandings. they will be soft, but still there.
https://www.dropbox.com/s/9ntty51r6nhkdba/ARN6.png?dl=0

Can you please also try the filters from VSCO and Youni. When you apply the filters from that apps, you will see butter smooth results. 

I couldnt understand the reason yet. I suspect something about colorspace, at the end, that apps may convert the output to sRGB.

**Comment by YuAo** [comment]
Hi, @Umity I found a computer with Photoshop 2020. Saw the same banding issue:

<img width="846" alt="Screen Shot 2020-08-24 at 19 54 24" src="https://user-images.githubusercontent.com/1234944/91042157-e78a0180-e643-11ea-8797-753cccadcf20.png">

**Comment by Umity** [comment]
@YuAo thank you, but i am out of my computer few days more, please don’t close this yet, i will prove there’s something wrong.

**Comment by Umity** [comment]
Hello again @YuAo 

I just created a lut with Lightroom, a very simple one, just pulled blue curves to up left and green curves to down right, not much, just a bit. And i also used your Lutconverter app, so i created a .cube file too. I applied it to the same image, and I am attaching the images for your judgment.

Here is the original photo file: https://www.dropbox.com/s/eqn7io0u09xigbl/IMG_0713.HEIC?dl=0
this is the comparison file, left side is created on Photoshop, right side your library: https://www.dropbox.com/s/tetz5x23czoufii/compare.jpg?dl=0

and here is the lut: https://www.dropbox.com/s/xkyg3w6z98qcavu/ARN1%202.png?dl=0  (very smooth)

what do you think? There is a clear banding there.

**Comment by YuAo** [comment]
Still looks like a lut problem. The color of the result image in Photoshop and MetalPetal looks different.
Did you save the LUT image in sRGB color space?

I tried several color space combinations and with `CGColorSpace.adobeRGB1998` I got the result closest to the Photoshop's.
```
let inputImage = MTIImage(image: UIImage(named: "example.jpg"), colorSpace: CGColorSpace(name: CGColorSpace.adobeRGB1998), isOpaque: true)
let lookupImage = MTIImage(image: UIImage(named: "ARN12.png"), colorSpace: CGColorSpace(name: CGColorSpace.adobeRGB1998), isOpaque: true)
```

<img width="1050" alt="Screen Shot 2020-08-31 at 23 50 23" src="https://user-images.githubusercontent.com/1234944/91739603-bfbb1080-ebe4-11ea-97e9-3300e1208282.png">

You should make sure the LUT's color space matches the color space you process the image with.
MetalPetal is currently by default assuming the input images are in sRGB color space.

**Comment by Umity** [comment]
@YuAo thank you. yes i am saving as sRGB.

what do you think about using .adobeRGB1998? Do you recommend it over srgb?

**Comment by gpapoyan95** [comment]
Hi @Umity!
Can you please provide the code part of applying the lookup table?
Thanks

**Comment by YuAo** [comment]
@Umity I can't give you advices about color space you should choose. The key here is to process the image in the color space you use to create the color lookup table. The color lookup table is just a color map function. If the function is applied to a color space other than which you create the function with, the result is incorrect.

**Comment by YuAo** [comment]
@Umity After another investigation, I found that when you open a file directly using Photoshop, Photoshop create the document using the file's color space instead of the preset working color space. 

In you case, the input file is in Display P3 color space, so all the operation in Photoshop operate in the Display P3 color space. If you load the file in Display P3 in MetalPetal you should get the same result `let inputImage = MTIImage(image: UIImage(named: "example.jpg"), colorSpace: CGColorSpace(name: CGColorSpace.displayP3), isOpaque: true)`.

You can still load the color lookup table using default settings in sRGB colorspace. Color lookup tables in Photoshop are not color matched.

In MetalPetal, when no colorspace is specified, the input image is color matched to the "DeviceRGB" color space (in fact sRGB currently).

Maybe we should change this behavior to "no color matching", when no colorspace is specified on the input.

**Comment by Umity** [comment]
P3 is important for quality and no, I was not sure about color tables are not matched in PS but good to know. 

what happens if I set renderContext.makeCGImage(from: filteredImage, colorSpace: CGColorSpace(name: CGColorSpace.displayP3))
and then the device is not p3? Shall we set this or MetalPetal auto changing to sRGB?

**Comment by YuAo** [comment]
> and then the device is not p3? Shall we set this or MetalPetal auto changing to sRGB?

This is the same situation where you view a photo taken in Display P3 on the device without Display P3 display. I think it is ok to set this as long as you want to process the image in Display P3 color space.
