### ISSUE TITLE
How to get mipmap MTIImage?

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#198]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

How to create a mipmap MTIImage?
How to specifiy mipmap level?

**Comment by StromanStroman** [comment]
Can you show me an example?

**Comment by YuAo** [comment]
We don't support mipmap currently.

**Comment by StromanStroman** [comment]
Do you mean if I have to use mipmap texture,I must make a mipmap mtltexture using raw metal,then turn the mtltexture to mtiimage?

**Comment by YuAo** [comment]
Yes
