### ISSUE TITLE
Memory pressure crash of images of different sizes

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#199]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

I rapidly change image size,every time I reclaimResources,but there are still sharp memory footprint.These sharps lead to crash due to memory pressure.
I don’t know why so will you tell me the season?

**Comment by StromanStroman** [comment]
<img width="511" alt="截屏2020-09-16 17 54 50" src="https://user-images.githubusercontent.com/13552268/93327110-73123f00-f84c-11ea-893d-c2529433ba13.png">

**Comment by StromanStroman** [comment]
I mean I do not have any idea.
I've used reclaimResources.
I researched MTIDeviceTexturePool。
Every time I request a new texture from MTIDeviceTexturePool I removed all objects,but nothing changes.
Can you give me a hint?

**Comment by StromanStroman** [comment]
It looks like input requests are faster than render speed.

**Comment by StromanStroman** [comment]
I found         return [[MTITransientImagePromiseResolution alloc] initWithTexture:renderTarget.texture invalidationHandler:^(id consumer) {
            //Root render result is consumed, releasing the texture.
            [renderTarget releaseTexture];
        }];
in MTIImageRenderingContext.mm line:298
It causes availble memory decrease.
How to solve it?

**Comment by YuAo** [comment]
The suggestion is to check if you are giving GPU too much work. The resources won't be released by GPU until the command buffer is finished. To minimize the memory usage, consider using `MTIRenderTask`, call `waitUntilCompleted` before next render.

If this is not the case, please attach a demo project that can be used reproduce the issue.
