### ISSUE TITLE
Main-thread hung when rendering to MTIImageView

### ISSUE THREAD

**Issue by gltdv** [MetalPetal/MetalPetal#201]
Hello,

Rendering to an `MTIImageView` through:
```
weakify(self);
dispatch_async(dispatch_get_main_queue(), ^{
    strongify(self);
    self.someMTIImageView.image = someImage;
});
```

But seeing:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/68713914/94208077-d9671500-fe7d-11ea-8668-ccae62e6240e.png">

Any clue what could be wrong?

Thank you.

**Comment by YuAo** [comment]
Looks like something related to the GPU Debug library. Can you try again with the "GPU Frame Capture" feature turns off. Xcode -> Edit Scheme -> Run -> Options -> GPU Frame Capture
