### ISSUE TITLE
App freezes for 1-2 minutes when using custom filter with many arguments

### ISSUE THREAD

**Issue by dannydaddy3** [MetalPetal/MetalPetal#202]
Hello, @YuAo 

I encountered a weird problem with my custom MTIFilter. When I execute my filter for the first time the whole app is freezing literally for 1-2 minutes. After that it unfreezes and the filter continues to work fast without any problems, even if I reopen my app everything's good. But If I don't wait for 1-2 minutes until it unfreezes, then each time when I use this filter the whole app just hang.

My fragment shader has 8 texture entries and 20 buffer parameters. (I have read that maximum args for buffer allowed is 31, so it's ok) The problem occurs on iPhone SE (iOS 14, A9 chip) and on iPhone 6s (iOS 13, , A9 chip). On iPhone XS everything's working good. 

My CPU usage is 0% and other processes CPU is 100% when app hangs, I checked system trace and found out that `MTLCompilerService` is active almost all the time on freeze. 

<img width="661" alt="Screenshot 2020-09-30 at 07 49 15" src="https://user-images.githubusercontent.com/15005840/94645178-dd6abb00-02f3-11eb-8d05-32cc580cde36.png">
<img width="370" alt="Screenshot 2020-09-30 at 07 47 22" src="https://user-images.githubusercontent.com/15005840/94645204-f1aeb800-02f3-11eb-8310-0fb37a404ec2.png">

I already disabled GPU Frame Capture, it didn't help.
I guess that problem could be related to the amount of parameters I use for the filter, I already packed 20 buffer params into one structure as in your example, but it didn't help. I guess the problem could be with 8 textures, I wonder how could I pack textures in structure the same way, I didn't find the proper way. I guess GPU processor could jump to CPU and block it somehow. And I don't really understand if this problem is gonna be preserved on release build on the App Store. 

Also, here's the article I found, but I don't understand how to apply this with MetalPetal (if it could help)
https://developer.apple.com/documentation/metal/buffers/managing_groups_of_resources_with_argument_buffers

Can you tell if I could pack textures more efficiently to the fragment shader or maybe there're other possible solutions? 

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by dannydaddy3** [comment]
I tried to localise the problem, but no luck. There's a chance that it's a simple Metal bug. 
I just rewrote this filter and left only 3 input textures, for that I need to execute filter several times now instead of one time, but at least without freeze 

I close the issue, but it would be good to have an ability to add several textures to shader more efficiently.

**Comment by YuAo** [comment]
Hi @dannydaddy3 I can't reproduce the issue on an iPhone 5s (A8 chip) using 8 or 9 textures. 

Can you confirm it's the number of the texture that causes the problem?  For example, can you run a shader that simply adds 8 textures and see if it freezes?

**Comment by dannydaddy3** [comment]
No, I checked it with 10 textures using simple filter, but it worked normally. 

In my filter I also tried commenting some if statements and it worked with maybe 1 sec freeze or without it. 

So I think it's some compiler bug
