### ISSUE TITLE
MTICoreImageUnaryFilter black padding problem 

### ISSUE THREAD

**Issue by joysolutionacat** [MetalPetal/MetalPetal#204]
I use MTICoreImageUnaryFilter() with CIFilter(name: "CIGaussianBlur") and radius 20. when i change this radius black padding increase or decrease. if i use only CIFilter and after that i crop with outputImage?.cropped(to: source!.extent) then its work properly. but when i use  MTICoreImageUnaryFilter() then black padding added . i use other filter like box,motion,zoom and many more . the result is same . i add input and output image here please check this .

### Checklist
- [ x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ ] If possible, I've reproduced the issue using the `master` branch of this repo
- [ x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

input image 
![Binaural-Beats](https://user-images.githubusercontent.com/71757189/95195601-994a4f80-07f8-11eb-9f53-1c922b1bf458.jpg)
output image
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-06 at 17 13 32](https://user-images.githubusercontent.com/71757189/95195622-a109f400-07f8-11eb-98d5-f038ed1aaeba.png)

**Comment by YuAo** [comment]
See: https://developer.apple.com/documentation/coreimage/ciimage/1437628-clampedtoextent
