### ISSUE TITLE
MTIErrorFunctionNotFound Why?

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#206]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Excuse me!How to load my custom shader,using MTIFunctionDescriptor.
I put a shader xxxx.metal into the main bundle.
And I load it with NSURL *shaderURL = MTIDefaultLibraryURLForBundle([NSBundle mainBundle]);
Then I got an error below.
Printing description of error: 
Error Domain=MTIErrorDomain Code=1002 "MTIErrorFunctionNotFound" UserInfo={MTIFunctionDescriptor=<MTIFunctionDescriptor: 0x2835d8e70; name = PerspectiveTransformFilterVertex; constantValues = (null); libraryURL = file:///private/var/containers/Bundle/Application/ACD67A4A-DBED-48E3-A3BB-80EF48E37E38/%E5%9B%BE%E5%BD%A2%E5%8F%98%E6%8D%A2.app/default.metallib>, NSLocalizedDescription=MTIErrorFunctionNotFound} 
Why?

I found MTIUnaryImageRenderingFilter working normal,why?

**Comment by StromanStroman** [comment]
in 1.13.0

**Comment by YuAo** [comment]
You can print the function names in a metallib using the follow code:

```Swift
let device: MTLDevice = MTLCreateSystemDefaultDevice()!
let library = try! device.makeLibrary(URL: Bundle.main.url(forResource: "default", withExtension: "metallib")!)
print(library.functionNames)
```

Double check that you've provided the correct function name.

If your function is not listed in `library.functionNames`, check the function definition.

**Comment by StromanStroman** [comment]
It does have value,just below.
2020-10-10 09:50:43.460825+0800 图形变换[354:10465] 现有的函数函数 (
    "metalpetal::PerspectiveTransformFilter::PerspectiveTransformFilterVertex"
)
I did not type a wrong name.
It works normally in simulator,but not in device.

**Comment by YuAo** [comment]
The function name should be "metalpetal::PerspectiveTransformFilter::PerspectiveTransformFilterVertex" not "PerspectiveTransformFilterVertex".

**Comment by StromanStroman** [comment]
It works in devices.
But I do not understand It still works in simulators even I just write "PerspectiveTransformFilterVertex"
Why?

**Comment by YuAo** [comment]
> Prior to Metal 2.2, the compiler ignores the namespace identifier is ignored on kernel, vertex, or fragment functions and you don’t include it when referring to a function from the Metal Framework API. As of Meal 2.2, you must include the namespace identifier when referring to a function function from the Metal Framework API.

https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf

MetalPetal automatically fixes the function name for Simulator builds. (though I don't think this is a good idea)

**Comment by StromanStroman** [comment]
Thank you very much.
I've learned a lot.
Point is I must master the Metal-Shading-Language-Specification.pdf
