### ISSUE TITLE
How to mask an image and output with transparency

### ISSUE THREAD

**Issue by ricsantos** [MetalPetal/MetalPetal#209]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Problem

I have an opaque image, and an opaque mask image. Using MetalPetal and it's MTIBlendWithMaskFilter I can create an output image, which correctly masks the input image, but is opaque with a black background.

I would like the output image to have an alpha channel, eg instead of black pixels have transparent pixels.

```
func mt_blend(image: UIImage, with mask: UIImage) -> UIImage {
    let ciMaskImage = CIImage(cgImage: mask.cgImage!)
    let mtiMaskImage = MTIImage(ciImage: ciMaskImage, isOpaque: true)
    let mtiMask = MTIMask(content: mtiMaskImage)
    
    let ciImage = CIImage(cgImage: image.cgImage!)
    let mtiImage = MTIImage(ciImage: ciImage, isOpaque: true)

    let contextOptions = MTIContextOptions()
    let context = try! MTIContext(device: MTLCreateSystemDefaultDevice()!, options: contextOptions)

    let blendFilter = MTIBlendWithMaskFilter()
    blendFilter.inputMask = mtiMask
    blendFilter.inputBackgroundImage = mtiMaskImage
    blendFilter.inputImage = mtiImage
    
    let outputImage = try! context.makeCGImage(from: opacityFilter.outputImage!)
    return UIImage(cgImage: outputImage)
}
```

I've tried calling `unpremultiplyingAlpha()` on the filters output image but that doesn't change the result. Perhaps I shouldn't be using this particular filter.

See SO post: https://stackoverflow.com/questions/64218840

Any help is much appreciated.

**Comment by YuAo** [comment]
Looks like this issues is resolved via https://stackoverflow.com/questions/64218840
Closing now.

**Comment by ricsantos** [comment]
Yep, as posted in the accepted SO answer, what I needed to do was set the background image of the filter to a clear image. Easy when you know how!

`blendFilter.inputBackgroundImage = MTIImage.init(color: MTIColor.clear, sRGB: false, size: mtiImage.size)`
