### ISSUE TITLE
How to get aspect MTIImage ?

### ISSUE THREAD

**Issue by PatrickSCLin** [MetalPetal/MetalPetal#21]
sorry, I'm newbie with MetalPetal.
currently I can get aspect MTIImage very easy if I render the texture which from MKTView
but for some reasons, I hope I can get an aspect MTImage directly, How should I do ?

**Comment by PatrickSCLin** [comment]
I've try MTITransformFilter or MTIMultilayerCompositingFilter, but wrong result when MTIImage with other orientation

**Comment by YuAo** [comment]
You can use `MTIMultilayerCompositingFilter`.

First you need a background image, like `MTIImage.blackImage`/`MTIImage(color:SRGB:)` or any other image you'd like to use as a background. Set that image to `MTIMultilayerCompositingFilter`'s `inputBackgroundImage`.

Then you need a layer. Create a `MTILayer` with your `MTIImage` as `content`. Find out the `position`(center) and `size` of the layer under the `layoutUnit`. You can use `AVMakeRectWithAspectRatioInsideRect`'s help.

**Comment by PatrickSCLin** [comment]
yes, do you have slack or email ?

**Comment by YuAo** [comment]
I'd like to keep the discussion here, since someone else may have the same problem.

**Comment by PatrickSCLin** [comment]
Hi, It does work! but orientation of content is still not correct.

Origin Image, It's from device, with a orientation flag
![screen shot 2018-05-02 at 11 30 19 pm](https://user-images.githubusercontent.com/2464698/39533439-a48fb9c8-4e61-11e8-9b58-c5396e5a21f8.png)

outputImage from orientationFilter
![screen shot 2018-05-02 at 11 30 19 pm copy](https://user-images.githubusercontent.com/2464698/39533541-e9492964-4e61-11e8-839b-9a9333b9909e.png)

After compositing
![screen shot 2018-05-02 at 11 29 51 pm](https://user-images.githubusercontent.com/2464698/39533577-fdd57b12-4e61-11e8-9519-43063bd57a2a.png)

```
fileprivate func processImage(_ sampleBuffer: CMSampleBuffer) -> MTIImage? {
    guard let pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return nil }
    let orientationKey = CMGetAttachment(sampleBuffer, RPVideoSampleOrientationKey as CFString, nil) as? UInt32
    let render_orientation = CGImagePropertyOrientation(rawValue: orientationKey ?? 0) ?? .up
    let inputImage = MTIImage(cvPixelBuffer: pixelBuffer, renderingAPI: .coreImage, alphaType: .alphaIsOne)
    self.orientation = render_orientation
    self.orientationFilter.inputImage = inputImage
    self.orientationFilter.orientation = MTIImageOrientation(cgImagePropertyOrientation: render_orientation)
    if let orientationImage = self.orientationFilter.outputImage {
        let render_size = orientationImage.size
        let expected_size = CGSize(width: min(self.size.width, self.size.height), height: max(self.size.width, self.size.height))
        let aspected_rect = AVMakeRect(aspectRatio: render_size, insideRect: CGRect(x: 0, y: 0, width: expected_size.width, height: expected_size.height))
        let size = aspected_rect.size
        let position = CGPoint(x: aspected_rect.midX, y: aspected_rect.midY)
        self.compositingFilter.inputBackgroundImage = MTIImage(color: MTIColor.init(red: 0, green: 0, blue: 0, alpha: 1), sRGB: false, size: expected_size)
        self.compositingFilter.layers = [
            MTILayer(content: inputImage, layoutUnit: .pixel, position: position, size: size, rotation: 0, opacity: 1, blendMode: .normal)
        ]
        print("position: \(position.debugDescription), size: \(size.debugDescription), rect: \(aspected_rect.debugDescription)")
        return self.compositingFilter.outputImage
    }
    return nil
}
```

**Comment by YuAo** [comment]
Use https://github.com/MetalPetal/MetalPetal/blob/master/Frameworks/MetalPetal/Filters/MTIImage%2BFilters.m#L22 to get a oriented image.

The `orientation` property of the filter represents the orientation of the canvas. (Rotate the canvas to that orientation). So you cannot use the image orientation on that filter directly.

**Comment by PatrickSCLin** [comment]
I can get orientated image now! but orientation of content is still wrong when image is not portrait

![screen shot 2018-05-03 at 11 57 59 am](https://user-images.githubusercontent.com/2464698/39559550-ad6821c6-4ec9-11e8-872a-04288e3480ab.png)

I found MTIImageOrientation is different with CGImagePropertyOrientation
```
case kCGImagePropertyOrientationLeft:
    imageOrientation = MTIImageOrientationRight;
    break;
case kCGImagePropertyOrientationRight:
    imageOrientation = MTIImageOrientationLeft;
    break;
```

```
fileprivate func processImage(_ sampleBuffer: CMSampleBuffer) -> MTIImage? {
    guard let pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return nil }
    let orientationKey = CMGetAttachment(sampleBuffer, RPVideoSampleOrientationKey as CFString, nil) as? UInt32
    let render_orientation = CGImagePropertyOrientation(rawValue: orientationKey ?? 0) ?? .up
    let inputImage = MTIImage(cvPixelBuffer: pixelBuffer, alphaType: .alphaIsOne).oriented(render_orientation)
    let render_size = inputImage.size
    let expected_size = CGSize(width: min(self.size.width, self.size.height), height: max(self.size.width, self.size.height))
    let aspected_rect = AVMakeRect(aspectRatio: render_size, insideRect: CGRect(x: 0, y: 0, width: expected_size.width, height: expected_size.height))
    let size = aspected_rect.size
    let position = CGPoint(x: aspected_rect.midX, y: aspected_rect.midY)
    self.compositingFilter.inputBackgroundImage = MTIImage(color: MTIColor.init(red: 0, green: 0, blue: 0, alpha: 1), sRGB: false, size: expected_size)
    self.compositingFilter.layers = [
        MTILayer(content: inputImage, layoutUnit: .pixel, position: position, size: size, rotation: 0, opacity: 1, blendMode: .normal)
    ]
    return self.compositingFilter.outputImage
}
```

**Comment by YuAo** [comment]
The `oriented` method should work exactly as the CIImage's `oriented` method. You can try to first get the correctly oriented image. Then apply aspect fit. I suggest you test your image orientation using core image, to see if the orientation you provide is correct.

**Comment by PatrickSCLin** [comment]
if I modify code to this way then result is correct

replay 
`MTIImage(cvPixelBuffer: pixelBuffer, alphaType: .alphaIsOne).oriented(render_orientation)`
to
`MTIUnaryImageRenderingFilter.image(byProcessingImage: MTIImage(cvPixelBuffer: pixelBuffer, alphaType: .alphaIsOne), orientation: MTIImageOrientation(cgImagePropertyOrientation: render_orientation), parameters: [:], outputPixelFormat: .invalid)`

```
fileprivate func processImage(_ sampleBuffer: CMSampleBuffer) -> MTIImage? {
    guard let pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return nil }
    let orientationKey = CMGetAttachment(sampleBuffer, RPVideoSampleOrientationKey as CFString, nil) as? UInt32
    let render_orientation = CGImagePropertyOrientation(rawValue: orientationKey ?? 0) ?? .up
    let inputImage = MTIUnaryImageRenderingFilter.image(byProcessingImage: MTIImage(cvPixelBuffer: pixelBuffer, alphaType: .alphaIsOne), orientation: MTIImageOrientation(cgImagePropertyOrientation: render_orientation), parameters: [:], outputPixelFormat: .invalid)
    let render_size = inputImage.size
    let expected_size = CGSize(width: min(self.size.width, self.size.height), height: max(self.size.width, self.size.height))
    let aspected_rect = AVMakeRect(aspectRatio: render_size, insideRect: CGRect(x: 0, y: 0, width: expected_size.width, height: expected_size.height))
    let size = aspected_rect.size
    let position = CGPoint(x: aspected_rect.midX, y: aspected_rect.midY)
    self.compositingFilter.inputBackgroundImage = MTIImage(color: MTIColor.init(red: 0, green: 0, blue: 0, alpha: 1), sRGB: false, size: expected_size)
    self.compositingFilter.layers = [
        MTILayer(content: inputImage, layoutUnit: .pixel, position: position, size: size, rotation: 0, opacity: 1, blendMode: .normal)
    ]
    return self.compositingFilter.outputImage
}
```

**Comment by RonaldoBandeira** [comment]
Thanks @YuAo for your outstanding work on this library. It's really useful at CV/ML stuff where I need pre/post processing images. And it seems a great code to learn Metal
