### ISSUE TITLE
Color banding issue with iOS devices

### ISSUE THREAD

**Issue by mpogra** [MetalPetal/MetalPetal#211]
Hello Team,

First of all, thanks for this awesome work, I just started using it and it's going very well. 

The color change after applying is not smooth. Please see the following details 

.cube and .png both have the same settings and made by photoshop (.png made by .cube itself) 

And here are the results with the same source code 

1. in iPadOS (Mac device) and iPad Simulators, both (.cube and .png) are working fine and producing the same results.
2. in iOS devices (iPad 7 and iPad mini 4 and iPad Pro),  the `cube.png` works fine but with the `.cube` file the color change is not smooth.   (please see attached) 

Please note that I have also tested with different types of the .cube files but getting the same results using this test image. 

Resources (Attached)

1. Source code
2. `.cube` file (renamed to `.txt` for attachment support)
3. `.png` cube file 
4. iPadOS output png
5. iPad(iOS) result png
6. Test image 

Please suggest. Thanks 

[SampleCubeLutSource.zip](https://github.com/MetalPetal/MetalPetal/files/5480496/SampleCubeLutSource.zip)

[Brannan.txt](https://github.com/MetalPetal/MetalPetal/files/5480547/Brannan.txt)

![colorCube](https://user-images.githubusercontent.com/10540903/97972374-6e005380-1dea-11eb-840e-75a68df2be2d.png)
![iPad(iOS)_Result](https://user-images.githubusercontent.com/10540903/97972386-72c50780-1dea-11eb-96ca-d7d97ffb42b5.png)
![iPadOS(Mac)_Result](https://user-images.githubusercontent.com/10540903/97972389-73f63480-1dea-11eb-825f-c6679e1f7e78.png)
![originalImage](https://user-images.githubusercontent.com/10540903/97974066-14e5ef00-1ded-11eb-9ee7-e5ad99461858.jpg)

**Comment by YuAo** [comment]
You need to make sure that the image and color lookup table is loaded in the color space you design the lut. See https://github.com/MetalPetal/MetalPetal/issues/197

**Comment by YuAo** [comment]
The 3D texture you are using is in RGBA32Float format. iOS does not support sample a RGBA32Float texture with a sampler with a linear filter. So colors are rounded to the nearest values in the lut.
https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf

**Comment by sleman** [comment]
How come loading the texture from .png cube file works? The .png cube is is only 8bit I know but why is the quality much better?

**Comment by mpogra** [comment]
Thanks for the update.

**Comment by kallipigous** [comment]
Out of interest did you try applying the cube to the default look up image first and then applying that to the image?
