### ISSUE TITLE
Array value in my compute kernel function 

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#213]
Hello!

i need to pass in my kernel function array of simd_float3x2 values

example kernel function

`kernel void myKernel(texture2d<float, access::sample> colorTexture [[ texture(0) ]]`
`                                     constant array<simd_float3x2, 5> &values [[buffer(0)]]){
}`

example my kernel params 

`{"values":[MTIVector vectorWithArrayValues] // for example
}`

it is not supported at the moment. Perhaps this can be done with existing functions. But until I figured out how to do it. I will be very grateful for the advice. thanks!

**Comment by YuAo** [comment]
@alyfreym I think you can directly wrap the bytes in a `NSData` or `MTIDataBuffer`.
