### ISSUE TITLE
 [CAMetalLayer nextDrawable] returning nil because allocation failed for MTIImageView

### ISSUE THREAD

**Issue by larryonoff** [MetalPetal/MetalPetal#214]
MTIImageView doesn't draw an image. It reports the following error:  [CAMetalLayer nextDrawable] returning nil because allocation failed.

See the image, not sure that GitHub didn't crop / scale it.
![IMG_7989](https://user-images.githubusercontent.com/372616/100240504-b0c5cf00-2f43-11eb-9e36-8fcf30c82bae.JPG)

What can be reasons of this error?

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ ] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version      | 1.14.0
 Integration Method      |CocoaPods
 Platform & Version      |iOS 14.2
 Device                  | iPhone Xs Max

### Steps to Reproduce
Don't have steps yet. I would like to ask possible issues.

### Expected behavior
Filter is applied.

### Actual behavior
Filter not applied

**Comment by YuAo** [comment]
It seems that the error is not reported by MetalPetal. Where did you see this error? Debug console?

**Comment by larryonoff** [comment]
> It seems that the error is not reported by MetalPetal. Where did you see this error? Debug console?

I have more details now. `MTIImageView.drawInMTKView` reports the error in Debug console. The image I provided is fine. The error occurs for large images. I've limited images to CGSize(width: 1920.0, height: 1920.0) as current solution.

**Comment by YuAo** [comment]
How large is the image? Have you measured the render performance? 
The gpu tasks hold strong references to the drawables, if tasks take too long to finish, they will drain the drawable pool.

**Comment by YuAo** [comment]
Closing this issue. If you have further questions feel free to leave a comment.
