### ISSUE TITLE
Eraser for Sketch Board

### ISSUE THREAD

**Issue by vjdaemp** [MetalPetal/MetalPetal#215]
Is it possible to create an "eraser brush" for the Sketch board in current implementation of MetalPetal?  The "eraser brush" would remove current marks rendered to screen.

**Comment by YuAo** [comment]
Yes, I think you can do that by registering a custom "clear" blend mode, then set the layer's blend mode to "clear" in `draw(with touch: UITouch)` method to erase pixels on the canvas.
