### ISSUE TITLE
How could I improve the quality of the metal image

### ISSUE THREAD

**Issue by callmeyellowbin** [MetalPetal/MetalPetal#216]
Hi, I am trying to show image by MetalPetal using MTIBlendWithMaskFilter. However, the quality of the image is a little far from what I expected. 

The maskImage and inputImage are:

![WX20201201-165312](https://user-images.githubusercontent.com/30124163/100717968-bf096480-33f5-11eb-8165-b0c4385abd58.png)

And I got the following result image.

![WechatIMG4](https://user-images.githubusercontent.com/30124163/100718011-c9c3f980-33f5-11eb-8e32-7ed7b543ecce.jpeg)

The maskImage and inputImage are one of the pixel buffer of a video, I try to crop and get left and right image, and then mask them into one image. The quality is also a little low and I would like to know how to improve the quality.

Could you please give some suggestions? Thanks a lot!

### Checklist
- √ I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- √ I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
I don't think this is related to MetalPetal, can you attach a demo project?

**Comment by callmeyellowbin** [comment]
I just edit the maskBlendFilter input based on `ImageRendererViewController.m`
```
- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = UIColor.blackColor;
...

    MTIImage *maskImage = [[MTIImage alloc] initWithCGImage:[UIImage imageNamed:@"mask_image"].CGImage options:nil isOpaque:YES];
    self.maskBlendFilter.inputMask = [[MTIMask alloc] initWithContent:maskImage];
    
    self.maskBlendFilter.inputImage = [[MTIImage alloc] initWithCGImage:[UIImage imageNamed:@"input_image"].CGImage options:nil isOpaque:YES];
    self.maskBlendFilter.inputBackgroundImage = [[MTIImage alloc] initWithColor:MTIColorClear sRGB:NO size:self.view.frame.size];
}
```

The mask_image is:

![mask6](https://user-images.githubusercontent.com/30124163/100733851-c20e5000-3409-11eb-9db6-618b66c1cc00.png)

The input_image is:

![mask5](https://user-images.githubusercontent.com/30124163/100733878-cc304e80-3409-11eb-92d6-008d66f463d5.png)

And When I get the output image of maskBlendFilter, the result is shown above. It looks like a bit different from the input image.

```
- (MTIImage *)maskBlendTestOutputImage {
    MTIImage *outputImage = self.maskBlendFilter.outputImage;
    return outputImage;
}
```

**Comment by YuAo** [comment]
`inputBackgroundImage` is too small. You should create the image using the inputImage's size.
