### ISSUE TITLE
Building for iOS Simulator, but the linked and embedded framework 'MetalPetal.framework' was built for iOS.

### ISSUE THREAD

**Issue by callmeyellowbin** [MetalPetal/MetalPetal#217]
Hi, I put MetalPetal.framework into my project and run in my iPhone successfully. However, when I run in simulator, the error occurred. The XCode version is 12.0. Is there any soultion?

### Checklist
- √ I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- √ I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
You need to integrate MetalPetal using either CocoaPods or Swift Package Manager. Please refer to the "Install" section  https://github.com/MetalPetal/MetalPetal/blob/master/README.md#install

**Comment by callmeyellowbin** [comment]
I try to use CocoaPods but minimum deployment target of my project is 9.0, which is lower than 10.0 that MetalPetal requires. What's worse, my project is based on Objective-C. As a result, I can't use neither CocoaPods nor Swift Package Manager. Is there any other soultion to solve this problem?

**Comment by YuAo** [comment]
@callmeyellowbin Sorry, we do not support deploying back to iOS 9. Maybe you can fork this repo, change the minimum deployment target in the podspec then use the forked source in you Podfile?
