### ISSUE TITLE
New pixel formats for HDR videos

### ISSUE THREAD

**Issue by gazadge** [MetalPetal/MetalPetal#218]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Context
MetalPetal already supports a great range of pixel formats including the typical ones being used by iPhone cameras to capture videos (`kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange` and
`kCVPixelFormatType_420YpCbCr8BiPlanarFullRange`).

With the iPhone 12 series being introduced app users are now able to capture videos in `kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange` pixel format expecting their videos being captured / played back / exported in HDR. 

### Problem
Using MetalPetal for processing HDR videos without converting to lower dynamic ranges within the pipeline is not possible as
`kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange` is not yet supported in MetalPetal. 

See the supported CVPixelFormats here: https://github.com/MetalPetal/MetalPetal/blob/b5254c1191cbad91585307ba3025706354675085/Frameworks/MetalPetal/MTICVPixelBufferPromise.m#L77-L112

@YuAo are you planning to add this capability to MetalPetal? 
Also what do you think would be the right approach to process video/images in this new format considering the key concepts of MetalPetal?

**Comment by dyah10** [comment]
We're also looking for MetalPetal support of `kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange`.

**Comment by YuAo** [comment]
You can use MTIImage(ciImage: CIImage(cvImageBuffer: pixelbuffer), isOpaque: true) as a workaround for now.

**Comment by YuAo** [comment]
@dyah10 @gazadge Can you give this a try 07684fcb25d6a914e61e62e9dabeb03a6061451a.

In order to preserve the 10 bit pixel format, I think you should change the `workingPixelFormat` of your `MTIContext` to maybe `MTLPixelFormatBGR10_XR` or `MTLPixelFormatRGBA16Float`? I do not have any suggestions about processing HDR videos for you currently.

**Comment by gazadge** [comment]
@YuAo thank you for looking into this so fast! 

I'll check your changes in https://github.com/MetalPetal/MetalPetal/commit/07684fcb25d6a914e61e62e9dabeb03a6061451a on Monday, and get back to you on how it worked.

Yes, I think `MTLPixelFormatBGR10_XR` should be enough, I'll let you know where I get with that.

**Comment by dyah10** [comment]
Thank you so much @YuAo. We'll try this!

**Comment by gazadge** [comment]
Hey @YuAo ,

The changes in [07684fc](https://github.com/MetalPetal/MetalPetal/commit/07684fcb25d6a914e61e62e9dabeb03a6061451a) were very useful! Thanks again for that!

I found a couple of things I had to change to make this work:
1. Using `MTLPixelFormatBGR10_XR` instead of `MTLPixelFormatBGRA8Unorm`
2. Using `MTLPixelFormatBGR10_XR_sRGB` instead of `MTLPixelFormatBGRA8Unorm_sRGB`. 
3. Extending the APIs of MTIImageView so the colorSpace and wantsExtendedDynamicRangeContent properties of its CAMetalLayer can be customized (so colorSpace and wantsExtendedDynamicRangeContent can be set on MTIImageView). Similarly as it's done in `MTIThreadSafeImageView`:
https://github.com/MetalPetal/MetalPetal/blob/27c11f666bd61299f63351572b9f09cff4e0ca4d/Frameworks/MetalPetal/UI/MTIThreadSafeImageView.m#L208-L222

Exposing `wantsExtendedDynamicRangeContent` might be risky as it's not yet available on iOS (it's available on MacOS and Catalyst), however setting this true was necessary to be able to display the rendered content of MTIImageView properly.

How does this sound to you? I'll be able to create a PR with the details only later, but until that let me know what you think of the proposed changes.

**Comment by YuAo** [comment]
Hi, @gazadge thanks for the feedback!

Can you elaborate on 1 and 2? Is changing the working pixel format of `MTIContext` enough?

And for

> Extending the APIs of MTIImageView so the colorSpace and wantsExtendedDynamicRangeContent properties of its CAMetalLayer can be customized

There's no public API for `MTKView` to change its `wantsExtendedDynamicRangeContent`. Are you suggesting that we force cast the `MTKView`'s layer to a `CAMetalLayer`?

BTW, I think we should also expose `wantsExtendedDynamicRangeContent` for `MTIThreadSafeImageView`.

**Comment by psredzinski** [comment]
Hello @YuAo, I've had the same issue with camera, but I've also have something different for loading videos recorded on iPhone 12 Pro. 

I am getting CVPixelBuffer from AVPlayerItemVideoOutput after loading an iPhone 12 Pro video.

![Zrzut ekranu 2020-12-16 o 16 44 32](https://user-images.githubusercontent.com/23390884/102370966-fb27f200-3fbd-11eb-846f-fe90d629caab.png)

Looks like it is using PixelFormat - 645428784, and I am not able to determine what kind of format it is. 
MetalPetal is returning MTLPixelFormatInvalid and I am not able to render video from AVPlayer properly. Any hints?

**Comment by YuAo** [comment]
@psredzinski That looks like an compressed format. I think you should use `AVPlayerItemVideoOutput.init(pixelBufferAttributes: [String : Any]?)` and specify the pixel buffer's format type.

**Comment by psredzinski** [comment]
@YuAo That has solved the issue thanks.

Do you have in mind any release date for a new version of MetalPetal including all the changes? 1.14.0 was released in October. I have my cocoa pods setup like that right now:

pod 'MetalPetal/Swift', :git => 'https://github.com/MetalPetal/MetalPetal.git'

**Comment by YuAo** [comment]
> Do you have in mind any release date for a new version of MetalPetal including all the changes? 1.14.0 was released in October. I have my cocoa pods setup like that right now:

@psredzinski After we close this issue.

**Comment by gazadge** [comment]
> Hi, @gazadge thanks for the feedback!
> 
> Can you elaborate on 1 and 2? Is changing the working pixel format of `MTIContext` enough?
> 

Hey @YuAo ,

So on 1. and 2.:

I changed the following lines:
https://github.com/MetalPetal/MetalPetal/blob/07684fcb25d6a914e61e62e9dabeb03a6061451a/Frameworks/MetalPetal/MTICVPixelBufferPromise.m#L86-L88

to:
```
 case kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange:
 case kCVPixelFormatType_420YpCbCr10BiPlanarFullRange:
         return sRGB ? MTLPixelFormatBGR10_XR : MTLPixelFormatBGR10_XR_sRGB;
```

This was necessary to be able to keep the 10 bit dynamic range.

I think your change set in [07684fc](https://github.com/MetalPetal/MetalPetal/commit/07684fcb25d6a914e61e62e9dabeb03a6061451a) with this correction above would already be a great improvement to support kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange and kCVPixelFormatType_420YpCbCr10BiPlanarFullRange.

> And for
> 
> > Extending the APIs of MTIImageView so the colorSpace and wantsExtendedDynamicRangeContent properties of its CAMetalLayer can be customized
> 
> There's no public API for `MTKView` to change its `wantsExtendedDynamicRangeContent`. Are you suggesting that we force cast the `MTKView`'s layer to a `CAMetalLayer`?
> 

Rendering HDR in MTIImageView and MTIThreadSafeImageView will probably stay problematic until [wantsExtendedDynamicRangeContent](https://developer.apple.com/documentation/quartzcore/cametallayer/1478161-wantsextendeddynamicrangecontent) is not available on iOS, so now I think it's just probably better to keep that separated from the original issue. I started a thread on this [here](https://developer.apple.com/forums/thread/669781) to clarify what we can expect - @YuAo @dyah10 @psredzinski feel free to give an upvote if you're also interested in the outcome.

The force casting of MTKView's layer to `id<MTICAMetalLayer>` while also adding `wantsExtendedDynamicRangeContent` to MTICAMetalLayer protocol was only a workaround for me to test how `wantsExtendedDynamicRangeContent` would work on iOS. The result looks really good, but until this is not part of the public APIs we can't really get anywhere with it. 

> BTW, I think we should also expose wantsExtendedDynamicRangeContent for MTIThreadSafeImageView.
>

Absolutely! Once we'll be able to use `wantsExtendedDynamicRangeContent` on iOS too, then we should update both MTIImageView and MTIThreadSafeImageView.

So overall I think next we'll need this one linee change I described to resolve this issue and we might revisit the rendering part once there's proceeding on Apple's side to bring `wantsExtendedDynamicRangeContent` to iOS. @YuAo how does that sound to you?

**Comment by YuAo** [comment]
Hi @gazadge

For 
https://github.com/MetalPetal/MetalPetal/blob/07684fcb25d6a914e61e62e9dabeb03a6061451a/Frameworks/MetalPetal/MTICVPixelBufferPromise.m#L86-L88
this is intentional. The pixel format map here is only for rendering using CoreImage, and CoreImage does not support rendering to `MTLPixelFormatBGR10_XR` or `MTLPixelFormatBGR10_XR_sRGB`. So instead `MTLPixelFormatBGRA8Unorm`  is used here as a fallback.

I think we can close this issue for now and release a new version of MetalPetal. 

You are welcome to create a PR when we are able to use `wantsExtendedDynamicRangeContent` on iOS.

**Comment by romanOnelightapps** [comment]
Hi, @YuAo!

wantsExtendedDynamicRangeContent is available only for iOS 16 and it doesn’t work for me. Is it possible to make a fix for HDR videos for all iOS versions without using wantsExtendedDynamicRangeContent flag ?

Thanks!

**Comment by YuAo** [comment]
@romanOnelightapps No. That requires the use of private API.

**Comment by zachgibson** [comment]
Any updates on this? I'm trying to support HDR in my SwiftUI app and by default AVPlayer will display in HDR but when I use MetalPetal it's clamped and looks desaturated.
