### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by endanke** [MetalPetal/MetalPetal#219]
Hello!

I'm wondering if there's any specific reason why MetalPetal is not supported on tvOS?
Do you have plans to add support officially, or are there any blockers for including this platform?

I've made a fork with a commit where I've added tvOS 13.0 and the tests seems to work fine. If you think it's acceptable, I can make a PR:
[https://github.com/endanke/MetalPetal/commit/50cc4980a4ca864da9af60727f11df26342297b8](https://github.com/endanke/MetalPetal/commit/50cc4980a4ca864da9af60727f11df26342297b8)

(Although it still needs more in-depth testing, but I'm looking forward for your comments.)

**Comment by YuAo** [comment]
Thanks @endanke ! 
The main reason is that I do not have an AppleTV to test... Your commit looks good to me, I think you can open a PR.

**Comment by endanke** [comment]
Sounds good! I'll do some more testing with a real device and also update the readme, then make a PR afterwards.

I'm planning to use MetalPetal in a project which is primarily designed for Apple TV, so I'm happy to help with the support for this platform!
