### ISSUE TITLE
alpha type handling rule 

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#221]
Hey YuAo.  I'm wondering why most kernel classes asserts for alpha type. This is a very dangerous assert, because if for example you process .jpg image all is well if png is crashing. (MTIMPSKernel). Can you advise on how to avoid such mistakes? may be convert all input images to one alpha type? I created my kernel where allowed all kinds alpha type and it works well. I wonder why then this check?

        NSParameterAssert({
            /* Alpha Type Assert */
            BOOL canAcceptAlphaType = YES;
            for (MTIImage *image in inputImages) {
                if (![kernel.alphaTypeHandlingRule canAcceptAlphaType:image.alphaType]) {
                    canAcceptAlphaType = NO;
                    break;
                }
            }
            canAcceptAlphaType;
        });

Perhaps these are the basic points of image processing? I would be glad if they told me where to get acquainted with this, any links, books, I would be glad.

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
The alpha type assertion does not cause crash in release. In fact it catches suspicious alpha type handling scenarios for you.
For more about alpha types and alpha compositing, I suggest that you read this awesome interactive article created by Bartosz Ciechanowski: https://ciechanow.ski/alpha-compositing/
