### ISSUE TITLE
Image gets pixelated/Burst while zooming with pinchGesture

### ISSUE THREAD

**Issue by PeregrineFalcon95** [MetalPetal/MetalPetal#222]
Replace this paragraph with a short description of the incorrect behavior.

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version      | 1.14.0
 Integration Method     | SwiftPM
 Platform & Version      | iOS 14.0 / macOS 11.01
 Device                          | MacMini

### Steps to Reproduce
Firstly, Thank You for your extraordinary work. 
I've created one MTIImageView with size h:100, w:100, and added this inside a gesture enabled view. If I zoom the image, it gets bursted. I have also tried this with gesture enabled MTIImageView with out any view holding this view. I have tried .withCachePolicy( .persistent ) //.withCachePolicy(MTIImage.CachePolicy.transient ). But this doesn't seems to work. 

# Link to my example project: https://github.com/PeregrineFalcon95/MetalTest-issue-Report

### Expected behavior
Image should stay clear after zoom/scale like UIImageView. Also the size of a view with 10 pixel square inside it get scaled. 

### Actual behavior
After zooming, image gets bursted. Size of the view with red color, also gets bigger. 

Any assistance you can provide would be greatly appreciated.
Thank You.

**Comment by YuAo** [comment]
This is by design. `MTIImageView` always rasterize its content using a size of `bounds.size * contentScaleFactor`. The view or layer transform is applied to rasterized contents.

For `UIImageView` like behavior, you can:
1. Create a `MTIContext`
2. Use that `MTIContext` to create a `CGImage` from your filtered image.
3. Use an `UIImageView` to display that image.
