### ISSUE TITLE
MetalPetal like package dependency. 'MTIShaderLib.h' file not found

### ISSUE THREAD

**Issue by igoooreha** [MetalPetal/MetalPetal#223]
Hello, I add MetalPetal in my package like a dependency, in my package sources I implement custom filters, but when I trying to build it I got an error in .metal files on #include "MTIShaderLib.h". -  'MTIShaderLib.h' file not found. I tried to use different paths for MTIShaderLib.h, but nothing helped me, also I tried to add MTIShaderLib.h to Header Search Path(just drag and drop file to the header search path context window), any results. May be when you add package to another package you should implement additional settings? Thanks for your work.

**Comment by YuAo** [comment]
Please read README: https://github.com/MetalPetal/MetalPetal#build-custom-filter

**Comment by akshpreet-singh** [comment]
hi @YuAo Metal Search path Not show in my Project as like I example code .what I have to do
![Screenshot 2022-08-29 at 11 03 13 AM](https://user-images.githubusercontent.com/110809882/187129769-d7ba7449-a062-478c-b4f3-a29ee1c8dd04.png)

**Comment by YuAo** [comment]
@akshpreet-singh It only shows up when there're `.metal` files in your project.
