### ISSUE TITLE
Zoom in out Animation before transition

### ISSUE THREAD

**Issue by hiren6994** [MetalPetal/MetalPetal#224]
How to make input image zoom in and out and scale from x and scale from y before transition just like iMovie apple app?

**Comment by YuAo** [comment]
I think you can use a `MTITransformFilter`, set the viewport to the input image's extent.

**Comment by hiren6994** [comment]
have a code to do this animation, MTITransformFilter is used only transform image not a animation on this, I try but not animated, I want to scale in out input image and then make a transition on it,

**Comment by YuAo** [comment]
Could you be more specific? If you need an animation you can simply change the filter's parameter (in your case `transform`) over time.

And, here are some libraries that utilize MetalPetal to run transitions, for your reference:
https://github.com/YuAo/YUDisplacementTransition
https://github.com/alexiscn/MTTransitions

**Comment by hiren6994** [comment]
I use https://github.com/alexiscn/MTTransitions this code for transition photos to make a video, but in this transition, I need zoom in out effect like show in apple movie maker app, so I need a code to do this,
