### ISSUE TITLE
Blending live camera video with a video file

### ISSUE THREAD

**Issue by devAlikhani** [MetalPetal/MetalPetal#225]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Hi , thanks for this amazing lib
I want to blend a video file (mp4) with live camera , and then record the results
i couldn't find any example of this approach in Demo code , is it possible to do this with MetalPetal?

**Comment by YuAo** [comment]
Yes. You can use the `PlayerVideoOutput` to get the realtime video buffers from an `AVPlayer` then use a filter (maybe `MTIMultilayerCompositingFilter`) to blend that with your live camera feed.

`PlayerVideoOutput` is a part of the VideoIO framework. https://github.com/MetalPetal/VideoIO

**Comment by isamercan** [comment]
@YuAo can you give us a sample?

**Comment by YuAo** [comment]
@isamercan 

- Create a `PlayerVideoOutput` for your `AVPlayer` that plays the overlay video. In the callback, save the latest video frame image.

    ```swift
    self.playerOutput = PlayerVideoOutput(player: self.player) { [unowed self] videoFrame in
        self.currentVideoImage = MTIImage(cvPixelBuffer: pixelBuffer, alphaType: .alphaIsOne)
    }
    self.player.play()
    ```

- Use a `MultilayerCompositingFilter` to compose the `currentVideoImage` over the camera image. You can refer to the "CameraFilterView" and "MultilayerCompositingFilterView" examples.

    ```swift
    func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
        guard let pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return }
        let cameraImage =  MTIImage(cvPixelBuffer: pixelBuffer, alphaType: .alphaIsOne)
        let filter = MultilayerCompositingFilter()
        filter.inputBackgroundImage = cameraImage
        filter.layers = [
                MultilayerCompositingFilter.Layer(content: currentVideoImage)
                    .frame(..., layoutUnit: .pixel)
                    .blendMode(.normal)
        ]
        let imageToRender = filter.outputImage
        ...
    }
    ```

**Comment by isamercan** [comment]
@YuAo 
> ```swift
>    self.currentVideoImage = MTIImage(cvPixelBuffer: pixelBuffer, alphaType: .alphaIsOne)
> ```
when I tried to use the above line that The error I got this "MTIErrorUnsupportedCVPixelBufferFormat" so I create an UIImage extension

```swift
extension UIImage {
    public convenience init?(pixelBuffer: CVPixelBuffer) {
        var cgImage: CGImage?
        VTCreateCGImageFromCVPixelBuffer(pixelBuffer, options: nil, imageOut: &cgImage)
        guard let image = cgImage else {
            return nil
        }
        self.init(cgImage: image)
    }
}
```

Usage
> ```swift
> playerVideoOutput = PlayerVideoOutput(player: self.player) { videoFrame in
>            if let image = UIImage(pixelBuffer: videoFrame.pixelBuffer) {
 >              let mtiImage =  MTIImage(image: image)
 >            self.overlayFrame = mtiImage
 >      }
 >}
> ```
Now It works well.

It's unrelated to the topic, but I want to ask one question, I guess it's not possible to take pictures with the capturePipeline right now? Do you have any solution to this?

**Comment by YuAo** [comment]
About the "MTIErrorUnsupportedCVPixelBufferFormat" error:

You should assign a proper pixel format type to the `sourcePixelBufferAttributes` of `PlayerVideoOutput`, otherwise the `AVPlayer` is free to use any pixel format it wants.

https://developer.apple.com/documentation/avfoundation/avplayeritemvideooutput/1389231-init

```swift
let format = kCVPixelFormatType_32RGBA // For example, request a 32BGRA pixel format.
var configuration = PlayerVideoOutput.Configuration()
configuration.sourcePixelBufferAttributes  = [kCVPixelBufferPixelFormatTypeKey: format]
PlayerVideoOutput(player:..., configuration: configuration, ...)
```

--- 

For taking photos. You can use the `photoOutput` along with the `capturePhoto(with:..)` method of the `camera`.
Please see Apple's documentation for more information about configuring and using `AVCapturePhotoOutput`.

**Comment by isamercan** [comment]
@YuAo Im gonna try pixel formats. Thank you very much for this great information.

For taking photos. I'm going to create a new device for Photos on CapturePipeline and will use your own delegates.
