### ISSUE TITLE
How to encode/decode MTIImage？

### ISSUE THREAD

**Issue by StromanStroman** [MetalPetal/MetalPetal#227]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)
I want to save a MTIImage to disk,but it does not obey NSCoding.
Is there any way to save a MTIImage to disk?

**Comment by YuAo** [comment]
See https://github.com/MetalPetal/MetalPetal/issues/112
