### ISSUE TITLE
Generate App + MetalPetal

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#228]
Hello @YuAo 

I'm writing to inform you on behalf of the **Generate Team**, of our great appreciation for your library. 
For the last 2 years I've been developing the third version of our flagship app called **[Generate](https://apps.apple.com/app/id808563377)**, which initially started as a photo filter app written in ObjC supported by the GPUImage Library by Brad Larson back in 2014. We had great success until the point it was hard to maintain and evolve, leading to stalling development. Until we decided to move forward and re build the entire app supporting Metal. 

It's been almost two years since my first question in your repo (https://github.com/MetalPetal/MetalPetal/issues/52)
When we decided to take your library as our base of development. We have put great effort in leveraging MetalPetal to our needs, technical capabilities and limited knowledge in the topic, and thanks to your constant support answering questions and actively maintaining the library we were able to launch Generate v3 to the AppStore with lot's of great features. 

We appreciate the work you put in the your Library and look forward for more great advancements with MetalPetal.
Let me know if any of you, your team members or fellow github users would like full PRO access to Generate Features, just send me your Generate username.

http://www.generateapp.com/

**Comment by YuAo** [comment]
I'm glad to hear that MetalPetal helped you. And thanks for your kind offer!
