### ISSUE TITLE
How to MetalPetal in realtime

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#23]
Now that apple is releasing iOS 12 and macOS mojave and deprecating OPENGL ES is time to start using MetalPetal :) GPUImage wont be an option now.

I wonder what is the best guide to use MetalPetal in a realtime rendering setting to be able to take pictures and video in high quality. 

:)

**Comment by YuAo** [comment]
There's a readme for this repo, and a demo project too.
