### ISSUE TITLE
Passing MetalPetal "original" versus "modified" verts

### ISSUE THREAD

**Issue by smhk** [MetalPetal/MetalPetal#231]
I am going to mesh-transform an image.

I am confused: how do I give the "original" verts, and then the "modified" verts?

Example, I want the "original" verts to be a plain grid 1000 x 1000.

Now, I move many of the verts slightly. (Distorting the image.)

In fact how do I "tell" PetalMetal the original, and then modified, verts?

I do not really see how to use `MTIGeometry` `MTIVertices` in this case I'm afraid - sorry

Thank you very much.

**Comment by YuAo** [comment]
I think you can take a look at this: https://github.com/MetalPetal/MetalPetal/issues/144#issuecomment-650007386

**Comment by smhk** [comment]
Thank you so much ..  fantastic code example

BTW I have no problem at all building the mesh; 

but I am confused, how does it know the "original" mesh ?????

Does it just assume it is a perfectly regular 2D mesh?  As the "starting point" ??

I hope, my question makes sense.

**Comment by smhk** [comment]
BTW I appreciate that I can "shift them" in the vert shader.

But if it is a one-off operation, I would be interested to just build the distorted mesh.

Thank you

**Comment by smhk** [comment]
thanks @YuAo  that makes perfect sense.  the ForwardWarpFilter is a FANTASTIC code example.  fantastic
