### ISSUE TITLE
Is it possible at all to render with 3D verts ?

### ISSUE THREAD

**Issue by smhk** [MetalPetal/MetalPetal#232]
Looking at the fantastic GridMesh example,

```
for r in 0...vMeshCount {
   for c in 0...hMeshCount { ..
    let zee: Float = 0
    vertices.append(
      MTIVertex(
        position: SIMD4<Float>(x: .., y: .., z: zee, w: 1),
        textureCoordinate: currentPosition/size))
  }
}
```

I tried making the image "wavy from above" in 3D .. so, something like

    let zee: Float = sin( Float(c) / Float(hMeshCount) )

![Unknown](https://user-images.githubusercontent.com/3938526/109080133-a98a9a80-76c5-11eb-83d1-23545594d0b2.jpeg)

(Or do that in the vert shader.)

Of course, it doesn't work!  z must be from 0->1 or nothing is rendered. And it remains flat, not bendy.

Is there **any way at all**! that MetalPetal can render such a hemispatial object?  Note that there is only one mesh, no backsides, no occlusion, no lighting etc etc - a "near flat" object.

This would be incredibly convenient.

**Comment by YuAo** [comment]
MetalPetal is primarily designed for rendering things in 2D.

It is possible to render in 3D using `MTIRenderCommand`, however you'll need to write shaders to handle things like MVP(ModelViewProjection), shadows, etc. Note the depth attachment is not enabled when performing `MTIRenderCommand`s  currently, so no depth testing.

It is recommended that you use a 3D engine for rendering 3D objects. You can easily make MetalPetal work with a lot of engines, for example Apple's SceneKit: https://github.com/MetalPetal/MetalPetal/tree/master/Frameworks/MetalPetal/SceneKit

---

The effect you mentioned above can also be simulated in 2D with fragment shaders, examples:
https://www.shadertoy.com/view/MddGW2
https://www.shadertoy.com/view/MsX3DN
https://www.shadertoy.com/view/llj3Dz

**Comment by smhk** [comment]
Fully understood.  Thanks a million !
