### ISSUE TITLE
Is it possible to analyze the full screen in realtime?

### ISSUE THREAD

**Issue by mlostekk** [MetalPetal/MetalPetal#233]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

As asked above, i am wondering if this library also offers a convenient way to analyze / process the full visible screen of macox in realtime?

**Comment by YuAo** [comment]
There's no convenient way of capturing visible screen of macOS currently in MetalPetal. I think this is beyond what this library should do.
