### ISSUE TITLE
CIImage from a MTIImage ?

### ISSUE THREAD

**Issue by s4cha** [MetalPetal/MetalPetal#241]
Hello,
Excuse if this is a really dumb question. I'm trying to use a skin smoothing filter and our codebase use CIImages.
How would I get a CIImage back from the filter below ?

```swift
class MetalPetalSkinSmoothingFilter: Filter {

    var name: String = "MetalSkinSmoothing"
    private let filter = MTIHighPassSkinSmoothingFilter()

    func process(image: CIImage) -> CIImage {
        let mtimage = MTIImage(ciImage: image)
        filter.inputImage = mtimage
        return filter.outputImage! // Get a CIImage?
    }
}
```

Thanks a ton for pointing me to the right direction :)

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by s4cha** [comment]
Ok I've worked out this:

```swift
class MetalPetalSkinSmoothingFilter: Filter {

    var name: String = "MetalSkinSmoothing"
    private let filter = MTIHighPassSkinSmoothingFilter()
    let imageView = MTIImageView(frame: UIScreen.main.bounds)

    var ctx: MTIContext?

    init(amount: Float) {
        if let device = MTLCreateSystemDefaultDevice() {
            self.ctx = try? MTIContext(device: device)
        }
        filter.amount = amount
    }

    func process(image: CIImage) -> CIImage {
        guard let ctx = ctx else {
            return image
        }
        let mtimage = MTIImage(ciImage: image, isOpaque: true)
        filter.inputImage = mtimage
        let outputMTimage = filter.outputImage!
        do {
           return try ctx.makeCIImage(from: outputMTimage)
        } catch {
            return image
        }
    }
}
```

Just to be sure, is that the correct way to do this? 
Cheers :)

**Comment by YuAo** [comment]
Yes, this should work, though I have some doubt about GPU command synchronization here. Anyway, let me know if you encounter any problem.

**Comment by s4cha** [comment]
Awesome, Thanks  for taking a look :)
My first implementation was using [Lady](https://github.com/Limon-O-O/Lady) and CPU usage shot up 150%.
Now with MetalPetal it's only 40% and everything is smooth. \o/
