### ISSUE TITLE
Blur black bars?

### ISSUE THREAD

**Issue by maximtart** [MetalPetal/MetalPetal#243]
### Checklist
- [ x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Hi all,

sorry if its noob question.
But is it possible to fill black bars with a part of blurred video?
something like that:
from:
![image](https://user-images.githubusercontent.com/975675/114884943-daa66200-9e0e-11eb-9a14-0266dd15a2b9.png)

to:
![image](https://user-images.githubusercontent.com/975675/114884378-65d32800-9e0e-11eb-8822-d3b872da8e5e.png)

thank you for help.

**Comment by YuAo** [comment]
Here's an example for you to get started. Just replace `func renderVideo(at url: URL)` in the `VideoProcessorView.swift` example with the following code.
```
let asset = AVURLAsset(url: url, options: [AVURLAssetPreferPreciseDurationAndTimingKey: true])
let presentationSize = CGSize(width: 1280, height: 1280)
let cropFilter = MTICropFilter()
let blurFilter = MTIMPSGaussianBlurFilter()
blurFilter.radius = 50
let multilayerCompositingFilter = MultilayerCompositingFilter()
let videoComposition = MTIVideoComposition(asset: asset, context: renderContext, queue:
DispatchQueue.main, filter: { request in
    cropFilter.cropRegion = .pixel(AVMakeRect(aspectRatio: presentationSize, insideRect:
request.anySourceImage.extent))
    cropFilter.inputImage = request.anySourceImage
    let centerCroppedImage: MTIImage = cropFilter.outputImage!
    blurFilter.inputImage = centerCroppedImage
    multilayerCompositingFilter.inputBackgroundImage = blurFilter.outputImage!
    multilayerCompositingFilter.layers = [MultilayerCompositingFilter.Layer(content:
request.anySourceImage).frame(AVMakeRect(aspectRatio: request.anySourceImage.size,
insideRect: CGRect(origin: .zero, size: centerCroppedImage.size)), layoutUnit: .pixel)]
    return multilayerCompositingFilter.outputImage!
})
videoComposition.renderSize = presentationSize
let playerItem = AVPlayerItem(url: url)
playerItem.videoComposition = videoComposition.makeAVVideoComposition()
self.videoPlayer = AVPlayer(playerItem: playerItem)
self.videoPlayer?.play()
```

**Comment by VarinderSH** [comment]
Getting error for 

multilayerCompositingFilter.layers = [MultilayerCompositingFilter.Layer(content:
request.anySourceImage).frame(AVMakeRect(aspectRatio: request.anySourceImage.size,
insideRect: CGRect(origin: .zero, size: centerCroppedImage.size)), layoutUnit: .pixel)]

Cannot convert value of type 'MultilayerCompositingFilter.Layer' to expected element type 'Array<MTILayer>.ArrayLiteralElement' (aka 'MTILayer')

**Comment by YuAo** [comment]
@VarinderSH You should use `MultilayerCompositingFilter`(instead of `MTIMultilayerCompositingFilter`) with `MultilayerCompositingFilter.Layer`.
