### ISSUE TITLE
Reduce CPU usage for resolutionForImage

### ISSUE THREAD

**Issue by endanke** [MetalPetal/MetalPetal#245]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Version: 1.18.0
Platform: macOS

Hello!

I've been using MetalPetal in a custom Metal rendering setup. I'm not sure if this is the best approach, but I use `startTaskToRenderImage`  to render the output of my MetalPetal filters onto a texture inside a `drawInMTKView` loop, and then I used that output texture in further operations.

I've profiled my application with Instruments and noticed that currently the highest CPU usage comes from the `resolutionForImage` call which is used inside the `startTaskToRenderImage` function. 
(Attached image of the profiler.)
<img width="539" alt="Screenshot 2021-04-16 at 16 24 32" src="https://user-images.githubusercontent.com/2576246/115032228-c2e3e200-9ed1-11eb-9748-072cfd75717a.png">

I'm wondering if there's any way to reduce the load caused by this call? 
I might be using the setup incorrectly, but I'm also thinking if it would be possible to pass the resolution as a parameter, so it wouldn't need to request it in each call? (Since I already know the expected size of the output texture.)

**Comment by YuAo** [comment]
"resolution" here means the resolved result of the image promise not the dimension of the image. 

When using `MTKView`, if the image you are rendering does not change frequently, you should enable the `enableSetNeedsDisplay` of `MTKView`, and set `isPaused` to true, then trigger the view's update yourself.

You can also render the `MTIImage` to a `CGImage` though pixel buffers from a pool (this avoids frequent memory allocation for the CGImage) then use a plain `NSImageView` to display the rendered image. https://github.com/MetalPetal/MetalPetal/blob/4b72fc7f0e4dbd2acfd0f6f61e71ebf92b1b08a2/MetalPetalExamples/Shared/PixelBufferPoolBackedImageRenderer.swift#L20-L36

**Comment by endanke** [comment]
Oh "resolution" in that way makes a lot more sense. :D Thanks for the answer and also for the tips on the usage!

**Comment by YuAo** [comment]
You can also consider combining multiple filters (render passes) in to one if possible. 

Nevertheless the GPU command encoding process (what `startTaskToRenderImage` primarily does) shouldn't be a bottleneck. Typically it takes no more than a few milliseconds, unless you have an extremely large filter graph or you are doing some heavy image loadings (from CGImage, url, etc).
