### ISSUE TITLE
MTIColorMatrixFilter intensity effect problem

### ISSUE THREAD

**Issue by LeeCenY** [MetalPetal/MetalPetal#247]
### Checklist
- ✅   I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- ✅  I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

GPUImage : GPUImageColorMatrixFilter (Meet my ideal effect)
MetalPetal：MTIColorMatrixFilter

The effect of these two filters should be the same, right? But I use MTIColorMatrixFilter and the effect is not the same! The effect is similar when I change the intensity of the filter to 1, but it slowly becomes smaller and eventually becomes 0, and then it appears all white.

Modify the filter method in the example
https://github.com/MetalPetal/MetalPetal/blob/225fb64d42a58eb8ecc9f5b3b48399c6a920d41c/MetalPetalExamples/Shared/SimpleImageFilterView.swift#L19

    private func filter(_ image: MTIImage) throws -> CGImage {
        let matrixFilter = MTIColorMatrixFilter()
        
        let intensity = simd_float4(0, 0, 0, saturation)
        let inputRVector = simd_float4(0, 0, 0, 0)
        let inputGVector = simd_float4(0, 1, 0, 0)
        let inputBVector = simd_float4(0, 0, 1, 0)
        let inputBiasVector = simd_float4(0, 0, 0, 0)
        
        let matrix = matrix_float4x4(rows: [inputRVector,
                                            inputGVector,
                                            inputBVector,
                                            intensity])
        
        matrixFilter.colorMatrix = MTIColorMatrix(matrix: matrix, bias: inputBiasVector)
        matrixFilter.inputImage = image
        
        let filteredImage = matrixFilter.outputImage!
        let cgImage = try self.renderContext.makeCGImage(from: filteredImage)
        return cgImage
    }

**Comment by LeeCenY** [comment]
Sorry for my mistake, MTIColorMatrixFilter does not have intensity property.
Please, how can I have the intensity operation?

**Comment by YuAo** [comment]
You cannot directly change intensity for now. 

However,  however you can either:

A: Apply the intensity adjustment to the color matrix.

or

B: First apply the color matrix filter then use a normal blend filter to blend the original image and the image with color matrix adjustment. Set the intensity for the blend filter.

**Comment by LeeCenY** [comment]
Thanks, solution B can achieve the effect. Curious how solution A achieves

**Comment by YuAo** [comment]
For solution A:

I think you may need to first decompose the color matrix, interpolate the decomposed values with the identity values then recompose to a color matrix. Something similar to interpolating a CATransform3D matrix: https://github.com/b3ll/Decomposed

Or, perhaps a direct interpolation is good enough for you use case:
```
var result: MTIColorMatrix = MTIColorMatrix.identity
result.matrix.columns.0 = mix(SIMD4<Float>(1,0,0,0), self.matrix.columns.0, t:
intensity)
result.matrix.columns.1 = mix(SIMD4<Float>(0,1,0,0), self.matrix.columns.1, t:
intensity)
result.matrix.columns.2 = mix(SIMD4<Float>(0,0,1,0), self.matrix.columns.2, t:
intensity)
result.matrix.columns.3 = mix(SIMD4<Float>(0,0,0,1), self.matrix.columns.3, t:
intensity)
result.bias = mix(SIMD4<Float>.zero, self.bias, t: intensity)
```

**Comment by LeeCenY** [comment]
Thanks, I'll learn
