### ISSUE TITLE
SRGB problem when Use MTISCNSceneRenderer

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#248]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

Hey! I am having a problem rendering SCNScene using MTISCNSceneRenderer. My final picture is a little darker. It feels like an additional gamma effect is superimposed on it.

1 - I generate a picture using CIContext.
2 - I add this image in to SCNNode 
3 - render this using  MTISCNSceneRenderer.

I experimented, and found that this is related to both SRGB. If I create simply MTIImage from this source image, and do not specify MTKTextureLoaderOptionSRGB to NO I get the wrong result as in the case SCNScene using MTISCNSceneRenderer. 
If I set  MTKTextureLoaderOptionSRGB to YES everything goes right.

Is it possible to add property in to function

`- (MTIImage *)snapshotAtTime:(CFTimeInterval)time
                    viewport:(CGRect)viewport
                 pixelFormat:(MTLPixelFormat)pixelFormat
                    isOpaque:(BOOL)isOpaque;`
 
is SRGB or not ?

Below is a project you can run
[MetalPetalExample.zip](https://github.com/MetalPetal/MetalPetal/files/6403798/MetalPetalExample.zip)

Preview
![p](https://user-images.githubusercontent.com/29518174/116666982-11ef4400-a9b5-11eb-8ee2-a1f1173916fa.png)

Perhaps the problem is not yours,
Any hints on how to solve this problem, I will be very glad. Thank you for your attention.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version     - 1.19.0
 Integration Method    - CocoaPods
 Platform & Version     - 14.4.2
 Device                         - iPhone 12 Pro Max

### Steps to Reproduce
Run example project. Everything is ready there. Above, just the original in the center is what is obtained after rendering.

### Expected behavior
want the picture to be rendered as in the original

### Actual behavior
The picture is rendered with a certain gamma correction

**Comment by YuAo** [comment]
See https://github.com/MetalPetal/MetalPetal/issues/76

If you are using 1.19.0, you can also use `MTIRGBColorSpaceConversionFilter`
