### ISSUE TITLE
Saving filtered video

### ISSUE THREAD

**Issue by Umity** [MetalPetal/MetalPetal#249]
Hi, after hours of working I couldnt find a way to record the filtered video in the demo. Previously, i was able to save the filtered video but now it is swiftUI and couldnt do it.

this didnt work, saves non-filtered video:
```
func save(videoFileUrl: URL) {
            PHPhotoLibrary.shared().performChanges({
                PHAssetChangeRequest.creationRequestForAssetFromVideo(atFileURL: (videoPlayer?.currentItem?.asset as? AVURLAsset)!.url )
            }, completionHandler: { succeeded, error in
              guard error == nil, succeeded else {
                return
              }
        })
          }
```

**Comment by YuAo** [comment]
Please see README: https://github.com/MetalPetal/MetalPetal#process-video-files

**Comment by Umity** [comment]
Can you see what i am doing wrong?

`//
//  VideoProcessorView.swift
//  MetalPetalDemo
//
//  Created by YuAo on 2021/4/4.
//

import Foundation
import SwiftUI
import AVFoundation
import AVKit
import MetalPetal
import Photos
import VideoIO


struct VideoProcessorView: View {
    @State private var videoURL: URL?
    @State private var videoPlayer: AVPlayer?
    
    @State private var asset: AVAsset?
    @State private var videoComposition: VideoComposition<BlockBasedVideoCompositor>?
    private let context = try! MTIContext(device: MTLCreateSystemDefaultDevice()!)


    @StateObject private var renderContext = try! MTIContext(device: MTLCreateSystemDefaultDevice()!)

    var body: some View {
        Group {
            if let videoPlayer = videoPlayer {
                VideoPlayer(player: videoPlayer).toolbar(content: {
                 //
                  
                    Button("Save") {
                                       print("faking save...")
                        savePicker()
                                   }
                                
                    videoPicker
                   
                })
            } else {
              
                videoPicker
                    .roundedRectangleButtonStyle()
                    .largeControlSize()
                    .toolbar(content: { Spacer() })
            }
        }
        .inlineNavigationBarTitle("Video Processing")
    }
    
    private func renderVideo(at url: URL) {
        let asset = AVURLAsset(url: url, options: [AVURLAssetPreferPreciseDurationAndTimingKey: true])
        let presentationSize = asset.presentationVideoSize ?? CGSize(width: 720, height: 720)
        
        let pixellateFilter = MTIPixellateFilter()
        let grayScaleFilter = MTIColorLookupFilter()
        let definitionFilter = MTIMPSDefinitionFilter()
        definitionFilter.intensity = 0
        grayScaleFilter.inputColorLookupTable = MTIImage(contentsOf: Bundle.main.url(forResource: "ARN1", withExtension: "png")!, isOpaque: true)!
        
        
        grayScaleFilter.intensity = 1
    //    let dotScreenFilter = MTIDotScreenFilter()
        let blendWithMaskFilter = MTIBlendWithMaskFilter()
        blendWithMaskFilter.inputMask = MTIMask(content: RadialGradientImage.makeImage(size: presentationSize))
        
        let watermarkFilter = MultilayerCompositingFilter()
        let whiteSquare = MTIImage.white.resized(to: CGSize(width: presentationSize.width/10, height: presentationSize.width/10))!
        let roundCornerFilter = MTIRoundCornerFilter()
        roundCornerFilter.cornerRadius = MTICornerRadius(Float(whiteSquare.size.width/4))
        roundCornerFilter.cornerCurve = .continuous
        roundCornerFilter.inputImage = whiteSquare
        let watermarkImage = roundCornerFilter.outputImage!.withCachePolicy(.persistent)
        let mask = DemoImages.makeSymbolImage(named: "seal.fill", aspectFitIn: whiteSquare.size, padding: whiteSquare.size.width/10)
        let watermarkMaskImage = mask
        let watermarkMaskTransformFilter = MTITransformFilter()
        watermarkMaskTransformFilter.inputImage = watermarkMaskImage
        
        let videoComposition = MTIVideoComposition(asset: asset, context: renderContext, queue: DispatchQueue.main, filter: { request in
            watermarkMaskTransformFilter.transform = CATransform3DMakeRotation(CGFloat(request.compositionTime.seconds), 0, 0, 1)
            let pixellateScale = mix(SIMD2<Float>(50,50), SIMD2<Float>(1,1), t: min(Float(request.compositionTime.seconds), 1))
            pixellateFilter.scale.width = CGFloat(pixellateScale.x)
            pixellateFilter.scale.height = CGFloat(pixellateScale.y)
            watermarkFilter.layers = [MultilayerCompositingFilter.Layer(content: watermarkImage)
                                        .blendMode(.normal)
                                        .frame(CGRect(x: request.anySourceImage.size.width - watermarkImage.size.width - 16,
                                                      y: request.anySourceImage.size.height - watermarkImage.size.height - 16,
                                                      width: watermarkImage.size.width,
                                                      height: watermarkImage.size.height),
                                               layoutUnit: .pixel)
                                        .mask(MTIMask(content: watermarkMaskTransformFilter.outputImage!, component: .alpha, mode: .oneMinusMaskValue))]
            
            return FilterGraph.makeImage(builder: { output in
//                request.anySourceImage => blendWithMaskFilter.inputPorts.inputImage
//                request.anySourceImage => grayScaleFilter => dotScreenFilter => blendWithMaskFilter.inputPorts.inputBackgroundImage
//                blendWithMaskFilter => grayScaleFilter  => output
                request.anySourceImage => grayScaleFilter.inputPorts.inputImage

                 grayScaleFilter => definitionFilter => output
            })!
        })
        let playerItem = AVPlayerItem(url: url)
        
        
        
        self.videoComposition = VideoComposition(propertiesOf: asset)
        self.asset = asset
       
        
        
       
        playerItem.videoComposition = videoComposition.makeAVVideoComposition()
        self.videoPlayer = AVPlayer(playerItem: playerItem)
       // videoURL = (videoPlayer?.currentItem?.asset as? AVURLAsset)?.url
        self.videoPlayer?.play()
        
      //  self.videoComposition = videoComposition
     
    }
    
    private var videoPicker: some View {
        VideoPicker(title: "Choose Video") { url in
            self.videoURL = url
            self.renderVideo(at: url)
        }
    }
    
     func savePicker()  {
        guard let asset = self.asset, let videoComposition = self.videoComposition else {
            return
        }
    
        self.videoPlayer?.pause()
       
      
       
        print("real save")
        let outputURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("temp.mp4")
      

        var configuration = AssetExportSession.Configuration(fileType: AssetExportSession.fileType(for: outputURL)!, videoSettings: .h264(videoSize: videoComposition.renderSize/* CGSize(width: 1080, height: 1920)*/), audioSettings: .aac(channels: 2, sampleRate: 44100, bitRate: 128 * 1000))
        configuration.videoComposition = videoComposition.makeAVVideoComposition()
        
      //  let exporter = try! AssetExportSession(asset: asset, outputURL: outputURL, configuration: configuration)
        
        let exporter = try! AssetExportSession(asset: asset, outputURL: outputURL, configuration: configuration)
        exporter.export(progress: { progress in
            
        }, completion: { error in
            
        })
        
        
        
        
        
    }
}
`

**Comment by Umity** [comment]
@YuAo I am really stuck at exporting video, I believe the feature needs to be in the demo app.
And, I need help, if you provide an example, would be amazing.

**Comment by YuAo** [comment]
You should retain the exporter.
https://github.com/MetalPetal/MetalPetal/blob/0e244f7d6f0096b824234d063df08156e4781d21/MetalPetalDemo/VideoProcessorViewController.swift#L82-L115

**Comment by Umity** [comment]
I am facing a fatal error msg, if i use the below code, which i retained the exporter. I could not implement a handler on the composition variable line:
`        let composition = VideoComposition<BlockBasedVideoCompositor>(propertiesOf: asset)
        self.asset = asset
        self.videoComposition = composition`


and here is the full page code:
`
//
//  VideoProcessorView.swift
//  MetalPetalDemo
//
//  Created by YuAo on 2021/4/4.
//

import Foundation
import SwiftUI
import AVFoundation
import AVKit
import MetalPetal
import Photos
import VideoIO


struct VideoProcessorView: View {
    @State private var videoURL: URL?
    @State private var videoPlayer: AVPlayer?
    
    @State private var asset: AVAsset?
    @State private var videoComposition: VideoComposition<BlockBasedVideoCompositor>?
    @State private var exporter: AssetExportSession?
    private let context = try! MTIContext(device: MTLCreateSystemDefaultDevice()!)
    


    @StateObject private var renderContext = try! MTIContext(device: MTLCreateSystemDefaultDevice()!)

    var body: some View {
        Group {
            if let videoPlayer = videoPlayer {
                VideoPlayer(player: videoPlayer).toolbar(content: {
                 //
                  
                    Button("Save") {
                                       print("faking save...")
                        savePicker()
                                   }
                                
                    videoPicker
                   
                })
            } else {
              
                videoPicker
                    .roundedRectangleButtonStyle()
                    .largeControlSize()
                    .toolbar(content: { Spacer() })
            }
        }
        .inlineNavigationBarTitle("Video Processing")
    }
    
    private func renderVideo(at url: URL) {
        let asset = AVURLAsset(url: url, options: [AVURLAssetPreferPreciseDurationAndTimingKey: true])
        let presentationSize = asset.presentationVideoSize ?? CGSize(width: 720, height: 720)
        
        let pixellateFilter = MTIPixellateFilter()
        let grayScaleFilter = MTIColorLookupFilter()
        let definitionFilter = MTIMPSDefinitionFilter()
        definitionFilter.intensity = 0
        grayScaleFilter.inputColorLookupTable = MTIImage(contentsOf: Bundle.main.url(forResource: "ARN1", withExtension: "png")!, isOpaque: true)!
        
        
        grayScaleFilter.intensity = 1
    //    let dotScreenFilter = MTIDotScreenFilter()
        let blendWithMaskFilter = MTIBlendWithMaskFilter()
        blendWithMaskFilter.inputMask = MTIMask(content: RadialGradientImage.makeImage(size: presentationSize))
        
        let watermarkFilter = MultilayerCompositingFilter()
        let whiteSquare = MTIImage.white.resized(to: CGSize(width: presentationSize.width/10, height: presentationSize.width/10))!
        let roundCornerFilter = MTIRoundCornerFilter()
        roundCornerFilter.cornerRadius = MTICornerRadius(Float(whiteSquare.size.width/4))
        roundCornerFilter.cornerCurve = .continuous
        roundCornerFilter.inputImage = whiteSquare
        let watermarkImage = roundCornerFilter.outputImage!.withCachePolicy(.persistent)
        let mask = DemoImages.makeSymbolImage(named: "seal.fill", aspectFitIn: whiteSquare.size, padding: whiteSquare.size.width/10)
        let watermarkMaskImage = mask
        let watermarkMaskTransformFilter = MTITransformFilter()
        watermarkMaskTransformFilter.inputImage = watermarkMaskImage
        
        let videoComposition = MTIVideoComposition(asset: asset, context: renderContext, queue: DispatchQueue.main, filter: { request in
            
            
            
           
        
          
            
            
            watermarkMaskTransformFilter.transform = CATransform3DMakeRotation(CGFloat(request.compositionTime.seconds), 0, 0, 1)
            let pixellateScale = mix(SIMD2<Float>(50,50), SIMD2<Float>(1,1), t: min(Float(request.compositionTime.seconds), 1))
            pixellateFilter.scale.width = CGFloat(pixellateScale.x)
            pixellateFilter.scale.height = CGFloat(pixellateScale.y)
            watermarkFilter.layers = [MultilayerCompositingFilter.Layer(content: watermarkImage)
                                        .blendMode(.normal)
                                        .frame(CGRect(x: request.anySourceImage.size.width - watermarkImage.size.width - 16,
                                                      y: request.anySourceImage.size.height - watermarkImage.size.height - 16,
                                                      width: watermarkImage.size.width,
                                                      height: watermarkImage.size.height),
                                               layoutUnit: .pixel)
                                        .mask(MTIMask(content: watermarkMaskTransformFilter.outputImage!, component: .alpha, mode: .oneMinusMaskValue))]
            
            return FilterGraph.makeImage(builder: { output in
//                request.anySourceImage => blendWithMaskFilter.inputPorts.inputImage
//                request.anySourceImage => grayScaleFilter => dotScreenFilter => blendWithMaskFilter.inputPorts.inputBackgroundImage
//                blendWithMaskFilter => grayScaleFilter  => output
                request.anySourceImage => grayScaleFilter.inputPorts.inputImage

                 grayScaleFilter => definitionFilter => output
            })!
          
        })
        let playerItem = AVPlayerItem(url: url)
        
        

       
        
        
       
        let composition = VideoComposition<BlockBasedVideoCompositor>(propertiesOf: asset)
        self.asset = asset
        self.videoComposition = composition
        
       
        playerItem.videoComposition = videoComposition.makeAVVideoComposition()
        self.videoPlayer = AVPlayer(playerItem: playerItem)
       // videoURL = (videoPlayer?.currentItem?.asset as? AVURLAsset)?.url
        self.videoPlayer?.play()
        
       
        
     
    }
    
    private var videoPicker: some View {
        VideoPicker(title: "Choose Video") { url in
            self.videoURL = url
            self.renderVideo(at: url)
        }
    }
    
    func savePicker()  {
        guard let asset = self.asset, let videoComposition = self.videoComposition else {
            return
        }
    
        self.videoPlayer?.pause()
   
      
       
        print("real save")
       
        
        
     
                
                var textField: UITextField!
                let alertController = UIAlertController(title: NSLocalizedString("Exporting...", comment: ""), message: nil, preferredStyle: .alert)
                alertController.addTextField { tf in
                    tf.isEnabled = false
                    textField = tf
                }
               // self.present(alertController, animated: true)
                let fileManager = FileManager()
                let outputURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("temp.mp4")
                try? fileManager.removeItem(at: outputURL)
                
                var configuration = AssetExportSession.Configuration(fileType: AssetExportSession.fileType(for: outputURL)!, videoSettings: .h264(videoSize: videoComposition.renderSize), audioSettings: .aac(channels: 2, sampleRate: 44100, bitRate: 128 * 1000))
                configuration.videoComposition = videoComposition.makeAVVideoComposition()
                let exporter = try! AssetExportSession(asset: asset, outputURL: outputURL, configuration: configuration)
                exporter.export(progress: { p in
                    textField.text = p.localizedDescription
                }, completion: { error in
//                    self.dismiss(animated: true, completion: {
//                        if let error = error {
//                            Alert(error: error, confirmActionTitle: "OK").show(in: self)
//                        } else {
//                            let activityViewController = UIActivityViewController(activityItems: [outputURL], applicationActivities: nil)
//                            self.present(activityViewController, animated: true, completion: nil)
//                        }
//                    })
                })
                self.exporter = exporter
            }
        
        
        
        
        
    }


`

**Comment by Umity** [comment]
I changed to 
`  @State private var videoComposition: MTIVideoComposition?`

and 

` self.videoComposition = videoComposition`

but doesnt seem recording..

**Comment by YuAo** [comment]
> I am facing a fatal error msg

What is this error message?

Also, you said it did not work, what error did you get from the export session?

**Comment by YuAo** [comment]
I can't see where you save the file to camera roll. You just `print("exported")` without actually do anything to the exported file.

**Comment by Umity** [comment]
@YuAo yes made it
`ALAssetsLibrary().writeVideoAtPath(toSavedPhotosAlbum: outputURL, completionBlock: nil)`

whats the most proper way to export nowadays? fileExporter() ?

**Comment by YuAo** [comment]
> whats the most proper way to export nowadays? fileExporter() ?

Saving a video file to the camera roll? Photos.framework

**Comment by YuAo** [comment]
@Umity "Video Exporting" is added to the example project.
