### ISSUE TITLE
Distortion and Histograms

### ISSUE THREAD

**Issue by kallipigous** [MetalPetal/MetalPetal#25]
Do you have any examples of distortion filters or drawing histograms in metalPetal? I'm trying to translate filters from GPUImage and I'd like some examples of vertex shaders that move pixels about.

**Comment by NaichuanYang** [comment]
vertex VertexOut passthroughVertex(
        const device VertexIn * vertices [[ buffer(0) ]],
        uint vid [[ vertex_id ]]
    ) {
        VertexOut outVertex; //  see MTIShaderLib.h
        VertexIn inVertex = vertices[vid];
        outVertex.position = inVertex.position;
        outVertex.textureCoordinate = inVertex.textureCoordinate;
        return outVertex;
    }
// you can also see some examples in MultilayerCompositeShaders.metal

**Comment by YuAo** [comment]
We're working on a histogram display filter. Distortion filters can be easily implemented using custom vertex shader or fragment shader. You can generally translate the OpenGL shader code to metal shader code and subclass MTIUnaryImageRenderingFilter to use the shader.

**Comment by kallipigous** [comment]
Yes I've been playing with the passthrough vertex as an example but no luck so far. In open gl I used the glposition but neither vertexOut.position or vertexOut.texturecoordinates seems to work for me. I get weird results. That's why I was hoping for an example I could learn from in the code. So for example if I wanted to set the y value of a pixel to reference the pixel's luminance like an rgb parade http://martinhering.micro.blog/uploads/2018/f343fddcf4.jpg  I was hoping I could just set the position y value and leave the x as it was. Many thanks for a great framework.

**Comment by kallipigous** [comment]
ok for my specific requirements I've created metal coreimage Filters that allow me to create my histograms so it does not need to be done in Metal Petal.
