### ISSUE TITLE
Problem creating FilterGraph with non Unary filters

### ISSUE THREAD

**Issue by BenK1934** [MetalPetal/MetalPetal#251]
Hi 
Forgive me I'm a beginner, I'm trying to make a FilterGraph that includes  
let cropFilter = MTICropFilter() and let gradeFilter = MTIColorLookupFilter()
both are not working using  
 let filterOutputImage = FilterGraph.makeImage { output in
                image => cropFilter => gradeFilter => output
       }
Just wondering what the process is for creating a FIlterGraph for non unary filter?

Thanks for the wonderful Metal Petal!
Ben

**Comment by YuAo** [comment]
You can use `.inputPorts` to specify what input you'd like to use in the filter chain for non-unary filters.

https://github.com/MetalPetal/MetalPetal/blob/42f3bae0d1ec20a5346f41799132ef4ab78acfaf/MetalPetalExamples/Shared/VideoProcessorView.swift#L66-L71
