### ISSUE TITLE
Video Flicker when I pass AVMutableComposition with Multiple Video tracks

### ISSUE THREAD

**Issue by LakhdeepSingh92** [MetalPetal/MetalPetal#252]
<p>When i am creating the AVMutableComposition (inserting Multiple Video Tracks) and Pass it to the AVPlayer Item with MTIVideoComposition  then AVPlayer Flicker between the both Frames of Video track. I think when AVPlayer goes at timing of Second Video track then First Video Frame is not hide </p>

<p>  Need to  some improvements in  MTIMutableVideoComposition class .</p>

### Checklist
- [ ] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ ] If possible, I've reproduced the issue using the `master` branch of this repo
- [ ] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version      | e.g. 1.13.0
 Integration Method      | e.g. CocoaPods / SwiftPM
 Platform & Version      | e.g. iOS 14.0 / macOS 10.15
 Device                  | e.g. MacBook Pro 16' / iPhone X

### Steps to Reproduce
Replace this paragraph with an explanation of how to reproduce the incorrect behavior.

### Expected behavior
Describe what you expect to happen.

### Actual behavior
Describe or copy/paste the behavior you observe.

**Comment by YuAo** [comment]
> Need to some improvements in MTIMutableVideoComposition class .

Do you mean `MTIVideoComposition`, because there's no `MTIMutableVideoComposition`.

---

If you have multiple video tracks. Do not use `request.anySourceImage`. It is your responsibility to select the track/tracks to display using `request.sourceImages[trackID]`.
