### ISSUE TITLE
MTIRGBToneCurveFilter() example

### ISSUE THREAD

**Issue by Umity** [MetalPetal/MetalPetal#253]
Hi, I tried a lot but could not add tonecurve filter into my demo app,

where can i put the "rgbtonecurve" in my filter chain (which is below)? i tried rgbtonecurve.inputports.outputImage but it throws error.
let rgbtonecurve = MTIRGBToneCurveFilter()

return FilterGraph.makeImage(builder: { output in
                  request.anySourceImage => exposureFilter => lutFilter.inputPorts.inputImage
                    lutFilter =>  definitionFilter => output
                })!

**Comment by YuAo** [comment]
> where can i put the "rgbtonecurve" in my filter chain (which is below)? i tried rgbtonecurve.inputports.outputImage but it throws error.

What error did it throw?

I think you can add it the same way as you add the `lutFilter`.

**Comment by Umity** [comment]
I think it was telling i cant use => operator or something, 
i re-tried and got another unknown problem.

i updated my chain as:
`     request.anySourceImage => saturationFilter => exposureFilter =>  rgbtonecurve => contrastFilter => lutFilter.inputPorts.inputImage
                    
                    lutFilter =>  definitionFilter => output
                })!`


and these were about the tonecurve definitions
let rgbtonecurve = MTIRGBToneCurveFilter()
rgbtonecurve.rgbCompositeControlPoints = [MTIVector(floatValues: [0.0, 1.0, 2.0], count: 1)]

my xcode got insane after this, building was taking forever and i was cancelling it, it was telling indexing files. There was no fail because i had to cancel the operation. I could not figure out why.

**Comment by Umity** [comment]
OK, i could make it work. here is an example of .rgbcompositecontrolpoints;
  rgbtonecurve.rgbCompositeControlPoints = [MTIVector(value: CGPoint(x: 0, y: 0)), MTIVector(value: CGPoint(x: 0.25, y: 0.35)), MTIVector(value: CGPoint(x: 0.5, y: 0.5)), MTIVector(value: CGPoint(x: 1, y: 1))]. // this makes brighter shadows

But had to remove lut filter from my chain, how can i add it back with the RGBTonecurve filter?

return FilterGraph.makeImage(builder: { output in

request.anySourceImage => saturationFilter => exposureFilter => contrastFilter => rgbtonecurve.inputPorts.inputImage`
  rgbtonecurve => output

**Comment by Umity** [comment]
request.anySourceImage => saturationFilter => exposureFilter => contrastFilter => rgbtonecurve.inputPorts.inputImage
                    rgbtonecurve => lutFilter.inputPorts.inputImage
                    lutFilter => definitionFilter => output


this is working, is it correct way?

**Comment by YuAo** [comment]
>                   request.anySourceImage => saturationFilter => exposureFilter => contrastFilter => rgbtonecurve.inputPorts.inputImage
> 
>                     rgbtonecurve => lutFilter.inputPorts.inputImage
> 
>                     lutFilter => definitionFilter => output
> 
> 
> 
> 
> 
> this is working, is it correct way?

Yes
