### ISSUE TITLE
Memory pressure

### ISSUE THREAD

**Issue by Exocomp** [MetalPetal/MetalPetal#254]
I'm running into an out of memory issue which I'm hoping you can help with. Any help would be much appreciated.

I believe what is happing is too much work is being sent to the GPU and as a result too much memory is being used. Would you be able to help provide a mechanism to avoid the memory load issue.

I have a short video (a few seconds) which I'm processing, I just simply need to change the orientation of the CMSampleBuffer data.

```
if let cmSampleBuffer = assetReaderVideoOutput.copyNextSampleBuffer() {
...
       let outputImage = MTIImage.init(
            cvPixelBuffer: pixelBuffer,
            renderingAPI: .coreImage,
            alphaType: .alphaIsOne
        )
        .withCachePolicy(MTIImage.CachePolicy.transient)
        .oriented(orientation)
...
}
```

I noticed there is a `context.startTask` as well as `task.waitUntilCompleted()` would you be able to provide sample code of how to use it in regards with `MTIImage.init`.

Thanks.

Here is what I'm using:

 MetalPetal Version      | 1.21.1
 Integration Method     | SwiftPM
 Platform & Version      | iOS 14.5.1
 Device                          | iPhone 7 Plus

**Comment by YuAo** [comment]
If you are rendering in a loop, you may want to use a `autoreleasepool` and wait for GPU tasks to avoid too much memory usage / GPU works.

You can choose to use `task.waitUntilCompleted()` or use a semaphore with `context.startTask(...completion:)` to throttle GPU tasks.

```
let context = try MTIContext(device: MTLCreateSystemDefaultDevice()!)
let targetWidth: Int = ...
let targetHeight: Int = ...
let pixelBufferPool = try MTICVPixelBufferPool(pixelBufferWidth: targetWidth, pixelBufferHeight: targetHeight, pixelFormatType: kCVPixelFormatType_32BGRA, minimumBufferCount: 16)
while let sampleBuffer = readerOutput.copyNextSampleBuffer() {
    guard let pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else {
        continue
    }
    try autoreleasepool {
        let inputImage = MTIImage(cvPixelBuffer: pixelBuffer, alphaType: .alphaIsOne)
            .withCachePolicy(.transient)
            .oriented(orientation)
        let outputPixelBuffer = try pixelBufferPool.makePixelBuffer(allocationThreshold: 16)
        let task = try context.startTask(toRender: inputImage, to: outputPixelBuffer, sRGB: false)
        task.waitUntilCompleted()
        //use `outputPixelBuffer`
    }
}
```
