### ISSUE TITLE
Out of box implementation for polaroid filter

### ISSUE THREAD

**Issue by lingxiao** [MetalPetal/MetalPetal#257]
Awesome work guys! I was able to get it running with an existing SwiftUI project with minimal hassle. Right now I'm looking at `Class CapturePipeline` in `CameraFilterView`,  and I see it has many filters implemented out of the box. Would you guys be willing to implement a "polaroid" filter out of the box too? Example attached. I'm not sure how to interact with your hue and saturation API 
![photo-1563692040599-7e7d379d37b5](https://user-images.githubusercontent.com/1197405/123561135-c10d8900-d774-11eb-8f8d-d3a1b9404e7a.jpg)

**Comment by lingxiao** [comment]
The last sentence was a bit ambigous, I meant to say how to "compose" effects that's not enumerated in the `adjusting` function. For example I can do
```
                let filter = MTIColorLookupFilter()
                filter.inputColorLookupTable = DemoImages.colorLookupTable
                return { image, faces in
                    filter.inputImage = image
                    let ima = filter.outputImage!
                    let imb = ima
                        .adjusting(saturation: 0.9)
                        .adjusting(exposure: -1)
                        .adjusting(contrast: 1.5)                        
                    return imb
                }

```

But in so far as adjusting:
1. white balance
2. grain
3. split tone

I'm not sure if you have functions for such effects?

**Comment by YuAo** [comment]
You can compose filters by using modifiers (`adjusting(...)`) or make the image "go through" a filter object (like applying the `MTIColorLookupFilter` filter in the example).

We do not have white balance, grain and split tone filters currently. You'll need to implement them yourself or refer to https://github.com/MetalPetal/MetalPetal/issues/80 for alternatives.

**Comment by lingxiao** [comment]
@YuAo  ok great thanks. On a related note, how do you change the camera used ? (front vs backfacing). I see `Camera` instance is declared as so:
```
    private let camera: Camera = {
        var configurator = Camera.Configurator()
        configurator.videoConnectionConfigurator = { camera, connection in
            #if os(iOS)
            switch UIApplication.shared.windows.first(where: { $0.windowScene != nil })?.windowScene?.interfaceOrientation {
            case .landscapeLeft:
                connection.videoOrientation = .landscapeLeft
            case .landscapeRight:
                connection.videoOrientation = .landscapeRight
            case .portraitUpsideDown:
                connection.videoOrientation = .portraitUpsideDown
            default:
                connection.videoOrientation = .portrait
            }
            #else
            connection.videoOrientation = .portrait
            #endif
        }
                            
        let session_cam = Camera(captureSessionPreset: .hd1280x720, defaultCameraPosition: .front, configurator: configurator)
        return session_cam
    }()
```

so session_cam specifies `.front` by default, which i can change to `.back`. But what about during a video render session, is it possible to change the camera w/o dropping the rendered preview? or do I have to create a new instance of `CapturePipeline`?

**Comment by YuAo** [comment]
https://github.com/MetalPetal/VideoIO/blob/d3bb6590c0325f29323fd89652d77563f51d56cf/Sources/VideoIO/Camera.swift#L100

**Comment by lingxiao** [comment]
perfect thanks!
