### ISSUE TITLE
Can we use OpenGL .glsl file using this ?

### ISSUE THREAD

**Issue by atirek123** [MetalPetal/MetalPetal#259]
Hello,
 I am trying to use OpenGL file .glsl and convert it into Metal.
 So how can we do this?

**Comment by YuAo** [comment]
This is beyond the scope of this project.

I think it is possible by compiling GLSL to an intermediate representation, for example, [SPIR-V](https://www.khronos.org/registry/spir-v/), then [generate MSL shaders from SPIR-V](https://github.com/KhronosGroup/SPIRV-Cross).
