### ISSUE TITLE
Images look washed out when rendering to MTKView

### ISSUE THREAD

**Issue by ryanaw** [MetalPetal/MetalPetal#26]
For some reason rendering images to the `MTKView` makes them look washed out, I've tried setting both the `workingPixelFormat` to various things including sRGB. I've also tried setting the `colorPixelFormat` to different formats and seeing if that makes a difference. In fact, setting the `colorPixelFormat` on the `MTKView` to an sRGB format makes it even **more** washed out. It definitely has something to do with rendering to the MTKView, since if I just get an output image and put that into a UIImageView it looks fine. I'm wondering how to fix the washed out/desaturated colours when rendering to an `MTKView`?

Here's a look at what the problem is.
![img_0137](https://user-images.githubusercontent.com/2653708/41274660-373f5676-6dec-11e8-9238-644c14de2f21.jpg)
![img_0138](https://user-images.githubusercontent.com/2653708/41274663-3936c54a-6dec-11e8-93ec-4351ea9dde2f.jpg)

The first one is how the image should look, the second is the image rendering into an `MTKView` using an `MTIDrawableRenderingRequest`. I'm hoping there's a simple fix here...

**Comment by YuAo** [comment]
Can you place attach the original image here? Or try to load it using CIImage, then create a MTIImage from a CIImage using MTIImage(ciImage:isOpaque:)

**Comment by ryanaw** [comment]
Loading it from a CIImage seemed to fix it using `MTIImage(ciImage:isOpaque:)`. Thanks!

**Comment by YuAo** [comment]
It seems that the MTKTextureLoader cannot handle images in wide-color very well. However, CoreImage does that right thing. Would you please attach the original image here or send it to me(at)imyuao.com so that we can take a deep look at this issue.
