### ISSUE TITLE
Blend two videos using MTIVideoComposition

### ISSUE THREAD

**Issue by BambooCode** [MetalPetal/MetalPetal#260]
### Checklist
- [ X] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ X] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Hello, I'm trying to blend two videos (PiP) using `MultilayerCompositingFilter` from different sources, I inserted two tracks using `AVMutableComposition` and I'm passing an `AVAsset` with that two tracks but In MTIVideoComposition completion block I only get one key/value pair inside sourceImages dictionary. 

How can I blend two videos using `MTIVideoComposition` ? 

Thanks!

**Comment by YuAo** [comment]
That should work exactly as you described. Consider debugging your AVComposition object https://developer.apple.com/library/archive/technotes/tn2447/_index.html

**Comment by BambooCode** [comment]
When I debugging, I can see that when `makeTransformedSourceImage` method was called the first check pass with the first track but fail with the second track. Can not find sourceFrame with trackID into the request.

How can I add source frames to the `request`? Can you show me an example to use two videos with `MTIVideoComposition`?

Thanks in advance!

**Comment by YuAo** [comment]
```
let assetA = AVURLAsset(url: urlA, options: [AVURLAssetPreferPreciseDurationAndTimingKey: true])
let assetB = AVURLAsset(url: urlB, options: [AVURLAssetPreferPreciseDurationAndTimingKey: true])
let composition = AVMutableComposition()
let videoTrackA = composition.addMutableTrack(withMediaType: .video, preferredTrackID: composition.unusedTrackID())
try videoTrackA!.insertTimeRange(assetA.tracks(withMediaType: .video).first!.timeRange, of: assetA.tracks(withMediaType: .video).first!, at: .zero)
let videoTrackB = composition.addMutableTrack(withMediaType: .video, preferredTrackID: composition.unusedTrackID())
try videoTrackB!.insertTimeRange(assetB.tracks(withMediaType: .video).first!.timeRange, of: assetB.tracks(withMediaType: .video).first!, at: .zero)
let videoComposition = MTIVideoComposition(asset: composition, context: context, queue: .main, filter: { request in
    ...
})
```

**Comment by BambooCode** [comment]
with a lot of attempts, I got it.

Thanks!
