### ISSUE TITLE
MTIVideoComposition MTICVMetalIOSurfaceBridgeErrorDomain Error

### ISSUE THREAD

**Issue by amir-ardalanuk** [MetalPetal/MetalPetal#261]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)
Hi 
Thank you so much for being so supportive
I'm trying to create videoComposition with MTIVideoComposition but after I return output from filter I get this error: 
`failure	NSError	domain: "MTICVMetalIOSurfaceBridgeErrorDomain" - code: 10001	0x0000600002ec55c0`

I appreciate to help me to solve this issue. 

Thank you

**Comment by YuAo** [comment]
Does this happen on Simulators? 

The video composition system on iOS simulator does not always produce pixel buffers suitable for GPU (backed by `IOSurface`s).

**Comment by amir-ardalanuk** [comment]
@YuAo Yes, you right. It works on a real device.
Currently, I have a new issue. The Video transform is changed after video composition is added to the player item.
How can I merge this videoComposition with another one that I apply the correct transform on it?

**Comment by YuAo** [comment]
`MTIVideoComposition` automatically applies the preferred transform for each video track. 

If you'd like to add additional transform to the image you can use `MTITransformFilter`, here's a example:
https://github.com/MetalPetal/MetalPetal/blob/eb67c48060989c67ece5dc75fa811b2489dd9da8/Frameworks/MetalPetal/MTIVideoComposition.swift#L16-L25

**Comment by amir-ardalanuk** [comment]
@YuAo Thank you for replying.
Actually, I have my own videoCompoisiton that my editing instruction is added to it.
I want to add MTI's instruction generated with the makeAVVideoComposition method to my own videoComposition instruction.
How and What is the best way to merge these instructions?

**Comment by YuAo** [comment]
If you are using you own custom video compositor(`AVVideoCompositing` implementation), you can easily intergrate MetalPetal to your processing pipeline. You can create `MTIImage`s from `CVPixelBuffer`s and use `MTIContext` to render a `MTIImage` to a `CVPixelBuffer`.

If you are using the system default video compositor, I don't think there is a way to insert custom instructions to that.

**Comment by amir-ardalanuk** [comment]
@YuAo  Thank you. AVVideoCompositor is made and combines old changes with metal, and everything works well.
Thank you for helping, and your notices show me the correct way, and they were so usefull.
