### ISSUE TITLE
Unnecessary buffer allocation when recording / previewing camera capture?

### ISSUE THREAD

**Issue by JackYoustra** [MetalPetal/MetalPetal#265]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

The CIImage camera filter gets out of memory when using 4k, so I'm trying to figure out why that is. While I'm doing so, I've noticed that `PixelBufferBackedCGImageGenerator` creates a pixel buffer before rendering to it. The `CVPixelBuffer` is created on line 86 of `MTICVPixelBufferPool.m`. However, the only flag specified is the allocation threshold key, which made me wonder why [kCVPixelBufferMetalCompatibilityKey](https://developer.apple.com/documentation/corevideo/kcvpixelbuffermetalcompatibilitykey) isn't specified - how else could interop happen? It turns out that in MTIContext+Rendering.m line 237, a metal texture is created with newTextureWithCVImageBuffer (and presumably a GPU upload occurs).

My question is: why are there two copies in `PixelBufferBackedCGImageGenerator` when it seems like one copy to a pixel buffer with `kCVPixelBufferMetalCompatibilityKey` will do?

**Comment by JackYoustra** [comment]
Also, I found out the answer to my original question: inserting self.renderContext.reclaimResources() after line 248 in CameraFilterView fixes the 4k out-of-memory issue. Perhaps there's a better way with caching policy?

**Comment by YuAo** [comment]
`kCVPixelBufferMetalCompatibilityKey` is not required for Metal to create a mapped texture from a `CVPixelBuffer`. The requirement is: the `CVPixelBuffer` must be backed by an `IOSurface`.

https://github.com/MetalPetal/MetalPetal/blob/eb67c48060989c67ece5dc75fa811b2489dd9da8/Frameworks/MetalPetal/MTICVPixelBufferPool.m#L77

---

Also the core video texture bridge creates a live binding between the `CVPixelBuffer` and the `MTLTexture` object. The `CVPixelBuffer` itself is used for the texture storage. So no GPU upload and texture storage allocation here.
https://github.com/MetalPetal/MetalPetal/blob/eb67c48060989c67ece5dc75fa811b2489dd9da8/Frameworks/MetalPetal/MTIContext%2BRendering.m#L237

---

`MTIRenderContext.reclaimResources()` is recommended for rendering large images or in the situation where the intermediate textures have different sizes or formats between each render. Cache policy does not affect the generation of intermediate textures.
