### ISSUE TITLE
Not able to set background colour as CLEAR of MTIImageView.

### ISSUE THREAD

**Issue by vipulRajput** [MetalPetal/MetalPetal#266]
I'm trying to set background colour as clear of image view, like below:- 
...........
currentImageView = MTIImageView(frame: self.imageContainer.bounds)
currentImageView.backgroundColor = .clear
............

but as you can see this image, that black colour is covering the image..... in my case, I have to show something to the user, which is on background of  MTIImageView. 

<img width="403" alt="Screenshot 2021-08-05 at 12 58 31 PM" src="https://user-images.githubusercontent.com/35622379/128309980-016a148d-ff4e-4db5-bbbe-54798db7149b.png">

Anything on it ?

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
`imageView.isOpaque = false`?

**Comment by vipulRajput** [comment]
yeah, its there.

`currentImageView.image = MTIImage(ciImage: ciImage, isOpaque: false)`

and `currentImageView.isOpaque = false`

both lines of code are there.

**Comment by vipulRajput** [comment]
other than this, everything is fine, this is only blocker :(

**Comment by YuAo** [comment]
`imageView.clearColor = MTLClearColor(red: 0, green: 0, blue: 0, alpha: 0)` ?

**Comment by vipulRajput** [comment]
Thanks a lot man, really appreciate it :)
