### ISSUE TITLE
How to apply MTIColorMatrixFilter conditional? 

### ISSUE THREAD

**Issue by cleexiang** [MetalPetal/MetalPetal#267]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Problem:**
I would like to apply some filters when certain conditions are met. I have tried FilterGraph to apply filters, but I can not dynamic add filters by use it.

For example:
```
if condition1:
    add MTIBrightnessFilter()
else if confition2:
    add MTISaturationFilter()
else:
    add MTIContrastFilter()
```
Any help is much appreciated.

**Comment by YuAo** [comment]
How about:

```swift
var image: MTIImage? = ...
let filter = MTIContrastFilter()
filter.inputImage = image
image = filter.outputImage
switch condiation {
case a:
    let filter = MTIBrightnessFilter()
    filter.inputImage = image
    image = filter.outputImage
case b:
    let filter = MTISaturationFilter()
    filter.inputImage = image
    image = filter.outputImage
}
```

**Comment by cleexiang** [comment]
@YuAo Thanks!
