### ISSUE TITLE
 Crash when trying to get outputImage

### ISSUE THREAD

**Issue by spongemook** [MetalPetal/MetalPetal#269]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version      | 1.22.0
 Integration Method      | SwiftPM
 Platform & Version      | iOS 14.7.1
 Device                  | iPhone 12 mini, iPhone 12 mini Simulator

### Steps to Reproduce
```swift
let filter = MTIColorLookupFilter()
filter.inputImage = MTIImage(image: image, isOpaque: true)
filter.inputColorLookupTable = MTIImage(image: UIImage(named: "lookup_table_01")!)
let outputImage = filter.outputImage // Crash
```

### Expected behavior
get the outputImage.

### Actual behavior
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [kernel.alphaTypeHandlingRule _canHandleAlphaTypesInImages:images]'

**Comment by YuAo** [comment]
`inputColorLookupTable` needs to be an opaque image (MTIAlphaTypeAlphaIsOne). Use `MTIImage(image: ..., isOpaque: true)` for the color lookup table. More about alpha types: https://github.com/MetalPetal/MetalPetal/blob/master/README.md#alpha-types
