### ISSUE TITLE
[MetalPetal/Swift]: FilterGraph.makeImage severely limited by Xcode 12.5.1 compiler 

### ISSUE THREAD

**Issue by dayjer** [MetalPetal/MetalPetal#270]
FilterGraph.makeImage is no longer able to run with >= 7 operations/connections due to a compiler limitation.

```
        let brightnessFilter = MTIBrightnessFilter()
        let exposureFilter = MTIExposureFilter()
        let highlightShadowsFilter = MTIHighlightShadowFilter()
        let vibranceFilter = MTIVibranceFilter()
        let definitionFilter = MTIMPSDefinitionFilter()
        let image = FilterGraph.makeImage { output in
            inputImage =>
                brightnessFilter =>
                exposureFilter =>
                highlightShadowsFilter =>
                vibranceFilter =>
                definitionFilter =>
            output
        }
```

Results in a compiler error: 

`The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions`

but removing any 1 filter from the above code and it run just fine. I tried to work around it but without making the runtime code more inefficient, it doesn't appear to be possible. This is due to code preventing bypassing the operator '=>' in Filter.swift. i.e.

```
    static func add(connection: PortConnection) {
        precondition(contexts.count > 0, "No available PortConnectionsBuildingContext. You can only use `=>` operator in FilterGraph.makeImage or FilterGraph.connect function.")
        contexts[contexts.count - 1].connections.append(connection)
    }
```

Currently running 

  - MetalPetal/Core (1.22.0)
  - MetalPetal/Swift (1.22.0):
    - MetalPetal/Core
  via CocoaPods and using Xcode 12.5.1

**Comment by YuAo** [comment]
You can help the compiler out by explicitly mark the filters as `MTIUnaryFilter`:

```
let brightnessFilter: MTIUnaryFilter = MTIBrightnessFilter()
let exposureFilter: MTIUnaryFilter = MTIExposureFilter()
...
```

**Comment by YuAo** [comment]
This issue is resolved in Xcode 13.

**Comment by zachgibson** [comment]
Seeing this in Xcode 14.3 with >8 filters.
