### ISSUE TITLE
- (nullable MTIRenderTask *)startTaskToRenderImage:(MTIImage *)image toCVPixelBuffer:(CVPixelBufferRef)pixelBuffer sRGB:(BOOL)sRGB destinationAlphaType:(MTIAlphaType)destinationAlphaType error:(NSError * __autoreleasing *)inOutError completion:(nullable void (^)(MTIRenderTask *task))completion;

### ISSUE THREAD

**Issue by Wbnahqs** [MetalPetal/MetalPetal#271]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by Wbnahqs** [comment]
How to render MTIImage to pixelBuffer middle

**Comment by Wbnahqs** [comment]
pixelBuffer' size is 1080 1920

**Comment by Wbnahqs** [comment]
MTIImage size  1080 607

**Comment by YuAo** [comment]
You can use a MultilayerCompositingFilter, use a black 1920x1080 image as background and place the MTIImage as a layer in the middle then render the filter's output.
