### ISSUE TITLE
MTIFunctionDescriptor with String

### ISSUE THREAD

**Issue by fazal-e-majid** [MetalPetal/MetalPetal#275]
Currently MTIFunctionDescriptor can be instantiated with name of the shader in some bundle. would be great if we could pass the shader as a string as we do in OpenGL. It'll be more secure.

**Comment by YuAo** [comment]
You may use `MTILibrarySourceRegistration.registerLibrary(source:compileOptions:) -> URL` to register shader sources.

In fact, it's more secure when you use pre-complied shader libraries.

If you use shader source strings, the attacker will always be able to inject some logic / or inspect your app's memory to get your shader source, for example, swizzle the `-[MTIDevice newLibraryWithSource:...]`/`glShaderSource` method and print the arguments.

On the other hand, if you use `metallib`, your shader is complied to llvm-bitcode, it's very hard to analyze what your shader is doing and impossible to recover the source code form the bitcode.

**Comment by fazal-e-majid** [comment]
doing something like this, right ?
```
var librarySource = ""
        let sourceFileDirectory = URL(fileURLWithPath: String(#file)).deletingLastPathComponent().appendingPathComponent("../../Sources/MetalPetalObjectiveC")
        let headerURL = sourceFileDirectory.appendingPathComponent("include/MTIShaderLib.h")
        librarySource += try String(contentsOf: headerURL)
        librarySource += """
        
        using namespace metalpetal;
        
        fragment float4 testRender(
                                VertexOut vertexIn [[stage_in]],
                                texture2d<float, access::sample> sourceTexture [[texture(0)]],
                                sampler sourceSampler [[sampler(0)]],
                                constant float4 &color [[buffer(0)]]
                                ) {
            float4 textureColor = sourceTexture.sample(sourceSampler, vertexIn.textureCoordinate);
            return textureColor + color;
        }
        """
        let libraryURL = MTILibrarySourceRegistration.shared.registerLibrary(source: librarySource, compileOptions: nil)
        let renderKernel = MTIRenderPipelineKernel(vertexFunctionDescriptor: .passthroughVertex, fragmentFunctionDescriptor: MTIFunctionDescriptor(name: "testRender", libraryURL: libraryURL))
        let image = MTIImage(color: MTIColor(red: 0, green: 1, blue: 0, alpha: 1), sRGB: false, size: CGSize(width: 1, height: 1))
        let outputImage = renderKernel.apply(toInputImages: [image], parameters: ["color": SIMD4<Float>(1, 0, 0, 0)], outputTextureDimensions: image.dimensions, outputPixelFormat: .unspecified)
```
where I can also add `MTIShaderLib.h` directly in the librarySource (instead of creating url and then reading from that url) . because bundle returns nil when tried to get url of MTIShaderLib.h  `let url = Bundle.init(identifier: "org.cocoapods.MetalPetal")?.url(forResource: "MTIShaderLib.h", withExtension: nil) `

**Comment by YuAo** [comment]
Yes. There's currently no way to read the contents of `MTIShaderLib.h` directly. I think you may need to manually copy the content of that file for now, or maybe add a build script to do this automatically.

**Comment by fazal-e-majid** [comment]
Okay great. Thank you for the support you are providing @YuAo
