### ISSUE TITLE
Pool is out of buffers when NSOpenPanel is displayed

### ISSUE THREAD

**Issue by dsmurfin** [MetalPetal/MetalPetal#276]
I am using `PixelBufferPoolBackedImageRenderer` from the example project, along with VideoIO to capture live video/audio sampleBuffers. Everything is working well until I open an NSOpenPanel.

The following error is thrown:

<MTICVPixelBufferPool: 0x60000112e1c0>: Pool is out of buffers. Create a symbolic breakpoint of MTICVPixelBufferPoolIsOutOfBuffer to debug.

On macOS 11, the error above is logged 3 times. On macOS 12, after this error a series of additional errors is continually logged as buffers continue to be received.

The lines below are the source of the issue. I am slightly stuck as to how best to troubleshoot this further.

`let renderOutput = try self.imageRenderer.render(outputImage, using: renderContext)`

`let pixelBuffer = try pixelBufferPool.makePixelBuffer(allocationThreshold: 30)`

This issue can be created by adding the following to the example project (CameraFilterView.swift) on line 348, and toggling `fileImporterVisible`:

    .fileImporter(isPresented: $fileImporterVisible, allowedContentTypes: [.directory], allowsMultipleSelection: false) { result in
        do {
            let directory = try result.get()
            print("directory", directory)
        } catch {
            print("Import Failed")
        }
    }

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version      | 1.22.0
 Integration Method      | SwiftPM
 Platform & Version      | macOS 11, macOS 12
 Device                  | MacBook Pro 13' / MacBook Pro 15'

### Steps to Reproduce
Display an NSOpenPanel while sample buffers are being received.

### Expected behavior
Sample buffers continue to be processed.

### Actual behavior
See above.

**Comment by YuAo** [comment]
I think this is the expected behavior.

When you open a window modally on macOS, the application will run a modal event loop and refuse to perform any tasks that are not associated with the modal run loop. https://developer.apple.com/documentation/appkit/nsapplication/1428436-runmodal

The produced image cannot be consumed in the main runloop and that leads to the out of buffer error.

The suggestion is to stop the camera before opening any window modally or use the `begin(completionHandler:)` to present the panel. https://developer.apple.com/documentation/appkit/nssavepanel/1527007-begin

**Comment by dsmurfin** [comment]
Thank you! That makes a lot of sense. I will go ahead with this solution. Thanks for a great library!

**Comment by YuAo** [comment]
@dsmurfin 

Cannot reproduce the issue by adding a color picker in the `CameraFilterView`:
```
.toolbar(content: {
    Spacer()
    ColorPicker(selection: Binding<Color>(get: { .white }, set: { _ in }), label: {
        Text("Pick Color")
    })
})
.inlineNavigationBarTitle("Camera")
```

Or by using an `NSColorPanel`:
```
Button("Pick Color", action: {
    let colorPicker = NSColorPanel()
    let windowController = NSWindowController(window: colorPicker)
    windowController.showWindow(nil)
})
```

What kind of color picker are you using, can you attach a sample project?

**Comment by dsmurfin** [comment]
@YuAo 

Thanks for taking a look. I believe this is all the same issue I was seeing previously with an NSOpenPanel as that issue persisted even using a modeless option. The only solution I was able to use was to stop the camera. This seems problematic when simply choosing a color however.

Here is the simplest reproducer:

Add the following to line 31 of MetalPetalExamplesApp.swift

`Settings {
    VStack {
        ColorPicker("Fill", selection: $color, supportsOpacity: true)
        Rectangle()
            .foregroundColor(color)
            .frame(width: 100, height: 100)
    }
}`

and the following to line 23

`@State var color: Color = .red`

Launch the sample app, select the CameraView. Then Cmd+, to open Preferences. Select the Color Picker, then click and drag the mouse around the circle a couple of times. Reliably reproduces this issue.

It is also possible to reproduce by adding a 'ColorView.swift' containing the VStack above and the State color, and adding that directly to CameraView.swift on line 300 for instance.

Thanks for your time!
