### ISSUE TITLE
Curves are not working as expected.

### ISSUE THREAD

**Issue by fazal-e-majid** [MetalPetal/MetalPetal#277]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version      |  1.22.0
 Integration Method      | CocoaPods
 Platform & Version      | iOS 13.0+
 Device                  |  iPhone 11

### Steps to Reproduce
I’m trying to apply a photoshop adjustment curve (255x1 png) to an image with [this filter](https://github.com/fazal-e-majid/Curves/blob/main/MyAdjust.swift) and [shader](https://github.com/fazal-e-majid/Curves/blob/main/MyShaders.metal)

And this is how I’m using it:
```
let imageMTIImage = MTIImage(image: img, isOpaque: true)
let curveMTIImage = MTIImage(image: curveImg, isOpaque: true)
let mFilter = MyAdjust()
mFilter.inputImage = imageMTIImage
mFilter.curveImage = curveMTIImage
mFilter.intensity = 1.0
mtiImageView.image = mFilter.outputImage
```

### Expected behavior
on applying the filter on the image 
![org](https://user-images.githubusercontent.com/48935340/134774921-02b1928b-9500-4493-8df6-d98757ff7405.jpg)

using this [curve](https://github.com/fazal-e-majid/Curves/blob/main/shadows_positive_curve.png)

I used to get this result while using **gpuimage**:
![expected](https://user-images.githubusercontent.com/48935340/134774960-2fcac1fd-c184-475d-8c21-515e389a872f.jpg)

### Actual behavior
But this is what I’m getting in **MetalPetal**:
![actual](https://user-images.githubusercontent.com/48935340/134774968-b8a6b707-75ea-4264-b9d2-a4b02fee8cc1.jpg)

I don’t know what’s happening. I tried a lot but couldn’t get the desired result.
This is just one example, it’s happening with other curves as well.

@YuAo If you could take a look please, Thank you.

**Comment by YuAo** [comment]
The sample location in the shader is wrong.

Y should be `0.5` instead of `0`, for sampling the center of the pixel.

X should be `(color.r * 255.0 + 0.5)/256.0`. (Mapping `0 ~ 1` to texture coordinates `(0.5 ~ 255.5)/256`)
