### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by rorz** [MetalPetal/MetalPetal#28]
Hi there,

I'm currently exploring my options for live-image filtering on the Mac. As it's a new project I want to avoid using GPUImage (due to OpenGL's deprecation) and go with a Metal-based solution instead.

MetalPetal is an awesome project. I have run the demo on iOS and am excited by its possibilities. However, I've been unable to install it as a dependency (via Cocoapods) in a macOS project, and can't seem to see how to link the source manually, getting type in-declaration errors when I try to.

I'm therefore assuming that Mac isn't supported out-of-the-box... I also notice UIKit references in MTIImageView.

**Is there a way to get this going on Mac?**

I'm returning to Swift development after a 4-year hiatus so I'm probably not the person to update the library myself, but if it currently usable on Mac, is anyone able to point me towards how I could achieve this?

No worries if it's not possible right now.

Thanks again!

**Comment by YuAo** [comment]
It is possible to make this library work on macOS. `MTIImageView` and UIKit references is not the main problem, I've been using `#if __has_include(<UIKit/UIKit.h>)` (https://github.com/MetalPetal/MetalPetal/blob/master/Frameworks/MetalPetal/UI/MTIImageView.h).

The main problem here is the GPU architecture difference. Apple's mobile devices use an GPU architecture called TBDR(Tile Based Deferred Rendering), which is different from the desktop GPUs.

We do plan to make this work on macOS, but may not be very soon. Thanks for the suggestion and I'll let you know when there's something you can test around.

**Comment by YuAo** [comment]
https://github.com/MetalPetal/MetalPetal/commit/20599facee6b312e91842a8eeb777f00fbae42a6

Support macOS 10.13 +

You can use version 0.7.0, which is available with CocoaPods.

**Comment by YuAo** [comment]
Closing this issue. Open new issue if any farther problem is found.
