### ISSUE TITLE
Switch between filters  for video

### ISSUE THREAD

**Issue by mgstar1021** [MetalPetal/MetalPetal#284]
Hello, Thanks for your great works. I have a question for you. I wanna switch between filters while playing video, without replay from start but now sure how can accomplish or if possible with your library. Used AVPlayer to play video. Looking forward your response.

**Comment by YuAo** [comment]
You can refer to the `VideoProcessorView` in the example project.

https://github.com/MetalPetal/MetalPetal/blob/e1dfded0ce96348077cbca4ae42a5600f4de15a3/MetalPetalExamples/Shared/VideoProcessorView.swift#L52

The `filter` block is called for every video frame. You can apply whatever filters you like to the video frame.

You do not need to restart video playback to change filters.

**Comment by mgstar1021** [comment]
Thanks for your help.

**Comment by mgstar1021** [comment]
I'm very sorry for my stupid question but can you list some code here. I want to switch chained filters like instagram but don't know how to do it. for example, when press first button, apply pixalate filter, and press second button then apply blur filter while playing video, without restart playing.

**Comment by mgstar1021** [comment]
> You can refer to the `VideoProcessorView` in the example project.
> 
> https://github.com/MetalPetal/MetalPetal/blob/e1dfded0ce96348077cbca4ae42a5600f4de15a3/MetalPetalExamples/Shared/VideoProcessorView.swift#L52
> 
> The `filter` block is called for every video frame. You can apply whatever filters you like to the video frame.
> 
> You do not need to restart video playback to change filters.

I'm very sorry for my stupid question but can you list some code here. I want to switch chained filters like instagram but don't know how to do it. for example, when press first button, apply pixalate filter+blur filter, and when press second button then apply color filter + blur filter while playing video, without restart playing. 

Another question:
I do not have strong experience with Metal but I can make sense how to build structure to make video editing application. Normally extract frames from videooutput of AVPlayer, and process pixelbuffer in CADisplay, then display filtered frames in MTKView. But not sure how to make UML in case using MetalPetal. Do I not need to use MTKView, CADisplay in case using your library?

Thanks for your help.
