### ISSUE TITLE
MTITexturePool size problem

### ISSUE THREAD

**Issue by ccworld1000** [MetalPetal/MetalPetal#286]
MTITexturePool size problem

- (MTIReusableTexture *)newTextureWithDescriptor:(MTITextureDescriptor *)textureDescriptor error:(NSError * __autoreleasing *)error {
    [_lock lock];
    **// size maybe zero？maybe crash？
    // size有可能为0值]？可能会引起崩溃？**
    **NSUInteger size = [textureDescriptor heapTextureSizeAndAlignWithDevice:_device].size;**

### Checklist
- [ x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ x] If possible, I've reproduced the issue using the `master` branch of this repo
- [ x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
Can you attach a call stack trace of the crash?

**Comment by ccworld1000** [comment]
Just set the height in the size to 0
把size中的高度设为0就可以了

**Comment by ccworld1000** [comment]
Just set the height in the size to 0
把size中的高度设为0就可以了

**Comment by YuAo** [comment]
The height value must be greater than or equal to 1. For a 1D texture, the value must be 1. 

MetalPetal does not guard against texture size errors. 

There's currently no public API to get the device's maximum supported texture size. It is your responsibility to ensure the size / pixel format / buffer alignment of the texture is supported on the platform you'd like to deploy (by looking up the [Metal Feature Set Table](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf)).

**Comment by ccworld1000** [comment]
The change of external parameters may lead to the value of 0. You can increase the condition of filtering 1 to avoid crash
外部参数变化可能会导致0值,可以增加过滤1的条件,避免崩溃

**Comment by YuAo** [comment]
I do not want to create a "false trust" that the texture pool could handle invalid texture descriptors. Also not all textures are created with the texture pool.

Maybe a more proper place to check the texture dimension is in `MTIImageRenderingContext`, we can check the `promise.dimension` before resolving a promise. This should cover most of the "zero size image" cases if not all.

What do you think?

**Comment by ccworld1000** [comment]
It's up to you to make the decision. It may be a big change. I accidentally found it when I resized the window on the Mac. It's zero, and then it crashed.

这个决定权在你手中,改动起来可能比较大.我是在mac调整窗口大小偶然发现的,就是为零值情况,然后崩溃.
