### ISSUE TITLE
Using Operation

### ISSUE THREAD

**Issue by mgstar1021** [MetalPetal/MetalPetal#288]
Thanks for your many help!

I want to switch various filters to video real timely. I made some code but it's not flexible to use so how can I use => operation for MTIImage? For example, I am using below code to switch filters real timely.

> 
     let composition = MTIVideoComposition(asset: asset, context: renderContext, queue: DispatchQueue.main, filter: { [weak self] request in
            return FilterGraph.makeImage { output in
                let out = self?.processfilter(source: request.anySourceImage!)
                out! => output
          }!
     })

     private func processfilter(source: MTIImage) -> MTIImage? {
        switch flag {
        case 0:
            let pixellateFilter = MTIPixellateFilter()
            let dotScreenFilter = MTIDotScreenFilter()

            pixellateFilter.inputImage = source
            dotScreenFilter.inputImage = pixellateFilter.outputImage
            return dotScreenFilter.outputImage!
        case 1:
        }
        return nil
    }
> 

How can I exchange with specific operation(=>)? like below.

> 
     private func processfilter(source: MTIImage, outputPort: (ImageReceiverInputPort) -> Void) -> MTIImage? {
        switch flag {
        case 0:
            let pixellateFilter = MTIPixellateFilter()
            let dotScreenFilter = MTIDotScreenFilter()
            return source => pixellateFilter => dotScreenFilter => outputPort
        case 1:
        }
     }
>

**Comment by YuAo** [comment]
```
private func processfilter(source: MTIImage) -> MTIImage? {
    switch ... {
        case ...
        return FilterGraph.makeImage { output in
            return source => filterA => filterB => output
        }
    }
}
```
