### ISSUE TITLE
MTIChromaKeyBlendFilter usage - removing the chromakey from video 

### ISSUE THREAD

**Issue by multitudes** [MetalPetal/MetalPetal#289]
### Checklist
- [x ] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

## MTIChromaKeyBlendFilter

Hi Yu Ao, 

Thank you for this amazing library. 
I am a beginner with Metal.

I tried to check the other issues and sample code to try and understand how to use the `MTIChromaKeyBlendFilter` but everything I do doesn't seems to work. 

I have an animation video with a chroma key of a pink color. The color is correct, I checked in the assets as well, it corresponds to the pink used in the video.
What I want to achieve is to get the video transparent where the pink is shown. Later I want to use this for showing the video in ARKit and RealityKit.

I made a small test app and this is the code I tried.  What am I doing wrong?  
If you could point me in the correct direction it would be very appreciated
Thank you so much.

```swift
  let url = Bundle.main.url(forResource: fileName, withExtension: "mp4")

        let context = try! MTIContext(device: MTLCreateSystemDefaultDevice()!)
        let asset = AVAsset(url: url!)
        
        let chromaKeyBlendFilter = MTIChromaKeyBlendFilter()
        let color = MTIColor(red: 0.998, green: 0.0, blue: 0.996, alpha: 1) // this is the pink color which is the chroma key in the video
        chromaKeyBlendFilter.color = color
        chromaKeyBlendFilter.smoothing = 0.001
        chromaKeyBlendFilter.thresholdSensitivity = 0.475
 
        let composition = MTIVideoComposition(asset: asset, context: context, queue: DispatchQueue.main, filter: { request in
            guard let sourceImage = request.anySourceImage else {
                return MTIImage.black
            }
            return FilterGraph.makeImage(builder: { output in
                sourceImage => chromaKeyBlendFilter.inputPorts.inputImage => output
            })!
        })
        
        let playerItem = AVPlayerItem(asset: asset)
        playerItem.videoComposition = composition.makeAVVideoComposition()
        self.player = AVPlayer(playerItem: playerItem)
        //self.player.replaceCurrentItem(with: playerItem)
        self.player.volume = 0.2
        self.player.play()
        
```

The video looks like this:
![Screenshot 2021-11-24 at 19 03 23](https://user-images.githubusercontent.com/29355828/143292005-0fb39e9e-5d86-4f34-bfbe-936170597d40.png)

**Comment by YuAo** [comment]
You are directing the input image of the chromaKeyBlendFilter to the output.

The filter graph should be:

```
return FilterGraph.makeImage(builder: { output in
    sourceImage => chromaKeyBlendFilter.inputPorts.inputImage
    chromaKeyBlendFilter => output
})!
```

**Comment by multitudes** [comment]
Thank you so much for the quick reply.
I made it work and this is very exciting! 

I had tried the code before but crashed because of the missing background image. Quote:
> Also, the chromaKeyBlendFilter needs a background image (inputBackgroundImage). In your case you can use MTIImage(color: ..., sRGB: false, size: videoSize)

This was the missing piece of the puzzle.
I created then a transparent background color:  
`let backgroundColor = MTIColor(red: 0.0, green: 0.0, blue: 0, alpha: 0)`

It works now on the simulator. I will test it in RealityKit for my video material :)
This is the code again in case this can be of help to others:  

```swift
        let chromaKeyBlendFilter = MTIChromaKeyBlendFilter()
        let color = MTIColor(red: 0.998, green: 0.0, blue: 0.996, alpha: 1)
        //let backgroundColor = MTLClearColor(red: 0, green: 0, blue: 0, alpha: 0)
        let backgroundColor = MTIColor(red: 0.0, green: 0.0, blue: 0, alpha: 0)
        chromaKeyBlendFilter.color = color
        chromaKeyBlendFilter.smoothing = 0.001
        chromaKeyBlendFilter.thresholdSensitivity = 0.4//0.475
        chromaKeyBlendFilter.inputBackgroundImage = MTIImage(color: backgroundColor, sRGB: false, size: videoSize!)
        
        let composition = MTIVideoComposition(asset: asset, context: context, queue: DispatchQueue.main, filter: { request in
            guard let sourceImage = request.anySourceImage else {
                return MTIImage.black
            }
            return FilterGraph.makeImage(builder: { output in
                sourceImage => chromaKeyBlendFilter.inputPorts.inputImage
                chromaKeyBlendFilter => output
            })!
        })
```

Thank you again!
