### ISSUE TITLE
Possible to use MetalPetal in this case?

### ISSUE THREAD

**Issue by mgstar1021** [MetalPetal/MetalPetal#290]
Hello, I am sorry to ask you with my trouble but I already spent several days to make prototype using your library. Unfortunately I did not find satisfied solution yet to make what I want. I need to clone below app but not sure finally  whether I can archeive my goal using yours library.

features
- local video filtering
- face blur with Vision
- Overlay image and merge
- configure audio setting

At first I tried to do filtering but has many problems, so when apply filtering using MTIVideoComposition, and preview using AVPlayer, I need to change values real timely(ex, brightness) but AVPlayer doesn't preview real timely because  MTIVideoComposition doesn't update real timely as CADisplay. and so on...

How can I make UML to use MetalPetal, in order to implement what I want. What kind of components should I use?
If you can help me, I'm very thank to you!

**Comment by YuAo** [comment]
Assigning a new videoComposition to the player item makes AVPlayer refresh the preview.

```
let videoComposition = player.currentItem?.videoComposition
player.currentItem?.videoComposition = nil
player.currentItem?.videoComposition = videoComposition
```

- Face blur with Vision is similar to the `faceTrackingPixellate` effect in the example project.

- You can refer to the `MultilayerCompositingFilterView` demo for image overlay and composting.

**Comment by mgstar1021** [comment]
Thanks for your quick response! I can't resign assigned videoComposition because need to switch filters while playing same video. When run AVPlayer with videocomposition for previewing, and change filter property(ex, brightness), doesn't refresh relatively so that I don't want to use AVPlayer, How can I do then instead of using avplayer, video composition?

**Comment by YuAo** [comment]
I don't understand, what do you mean "it couldn't refresh real timely"? If you change the filter in the video composition block, the player reflects that change very quickly. 

For example, the `watermarkMaskTransformFilter` in the demo project changes its transform every frame, so it looks like the water mark is rotating.

**Comment by mgstar1021** [comment]
> 
       var filter: MTIMPSGaussianBlurFilter = MTIMPSGaussianBlurFilter()

        let composition = MTIVideoComposition(asset: asset, context: renderContext, queue: DispatchQueue.main, filter: { request in
            return FilterGraph.makeImage { output in
                request.anySourceImage! => self.filter => output
            }!
        })

        @IBAction func valueChanged(_ sender: UISlider) {
               filter.radius = sender.value
        }
> 

I don't think it's your fault. whenever change the value of slider, the result of effect should be shown immediately without any delay but if the video player rate is less than 1 and fps of video is low, then avplayer displays the filtering effect slowly.

so I am going to use the videooutput of video player instead of composition. I want to use MTImageView but I can't get callback at all. What am I wrong?

> 
        let player = AVPlayer(url: self.videoURL!)
        let output = PlayerVideoOutput(player: player) { videoFrame in
            print("output")
            let image = MTIImage(cvPixelBuffer: videoFrame.pixelBuffer, alphaType: MTIAlphaType.alphaIsOne)
            self.imageView.image = image
        }
        player.play()
> 

I tried myself using CADispayLink but doesn't show up anything. I can get pixel buffer correctly. Not sure what I am wrong.

> 
    internal func displayLinkDidRefresh(_ link: CADisplayLink) {
        if videoOutput.hasNewPixelBuffer(forItemTime: itemTime) {
            guard let pixelBuffer = videoOutput.copyPixelBuffer(forItemTime: itemTime, itemTimeForDisplay: nil) else {
                return
            }

            let image = MTIImage(cvPixelBuffer: pixelBuffer, alphaType: MTIAlphaType.alphaIsOne)
            self.imageView.image = image
        }
    }
> 

I'm very thanks for your help.

**Comment by YuAo** [comment]
1. Like I said before. You can reassign the video composition to make the player re-render itself. You can do this after the filter value changed.

    ```
    filter.radius = sender.value

    let videoComposition = player.currentItem?.videoComposition
    player.currentItem?.videoComposition = nil
    player.currentItem?.videoComposition = videoComposition
    ```

2. It's also ok to use `PlayerVideoOutput`, you can make the `PlayerVideoOutput` update using 

    ```
    playerVideoOutput.setNeedsUpdate()
    playerVideoOutput.updateIfNeeded()
    ```

    The problem with your code seems to be no one is keeping a strong reference to the `output`.

**Comment by mgstar1021** [comment]
Reassigning videocomposition doesn't work from above iOS13. Can you answer me for my third question?

**Comment by YuAo** [comment]
There seems to be no problem from what you've posted.

**Comment by mgstar1021** [comment]
> 
    internal lazy var imageView: MTIImageView = {
        let imageView = MTIImageView(frame: self.videoPlayerContainer.bounds)
        self.videoPlayerContainer.addSubview(imageView)
        return imageView
    }()

    internal lazy var displayLink: CADisplayLink = {
        let displayLink = CADisplayLink(target: self, selector: #selector(displayLinkDidRefresh(_:)))
        return displayLink
    }()

    internal lazy var videoOutput: AVPlayerItemVideoOutput = {
        let bufferAtrributes = [kCVPixelBufferPixelFormatTypeKey as String: NSNumber(value: kCVPixelFormatType_32ARGB),
                                kCVPixelBufferOpenGLCompatibilityKey as String: NSNumber(value: true),
                                kCVPixelBufferOpenGLESCompatibilityKey as String: NSNumber(value: true)]
//                                kCVPixelBufferWidthKey: NSNumber(value: Float(assetPreviewSize.width)),
//                                kCVPixelBufferHeightKey: NSNumber(value: Float(assetPreviewSize.height))]
        let videoOutput = AVPlayerItemVideoOutput(pixelBufferAttributes: bufferAtrributes)
        return videoOutput
    }()

    override func viewDidLoad() {
       let path = Bundle.main.path(forResource: "test-video", ofType:"mp4")
       let url = URL(fileURLWithPath: path)

        let asset = AVURLAsset(url: url, options: [AVURLAssetPreferPreciseDurationAndTimingKey: true])
        let playerItem = AVPlayerItem(asset: asset)
        playerItem.add(self.videoOutput)
        self.avPlayer.replaceCurrentItem(with: playerItem)

        self.displayLink.add(to: RunLoop.main, forMode: RunLoop.Mode.common)
    }

    @objc
    internal func displayLinkDidRefresh(_ link: CADisplayLink) {
        if videoOutput.hasNewPixelBuffer(forItemTime: itemTime) {
            guard let pixelBuffer = videoOutput.copyPixelBuffer(forItemTime: itemTime, itemTimeForDisplay: nil) else {
                return
            }

            let image = MTIImage(cvPixelBuffer: pixelBuffer, alphaType: MTIAlphaType.alphaIsOne)
            self.imageView.image = image
        }
    }
> 

It only shows first frame, also tried with MTIThreadSafeImageView. How can I fix it?

**Comment by YuAo** [comment]
I think that is the expected behavior, the player is not playing so it only shows the first frame.

**Comment by mgstar1021** [comment]
It's to only show you code and I may be missed to copy some lines, anyway I did updated again correctly, can you let me know please how can solve my problem.

**Comment by mgstar1021** [comment]
It was my fault, very basic problem, I missed to add player layer to view! Thanks for your help!!!
