### ISSUE TITLE
Supported pixel buffer formats

### ISSUE THREAD

**Issue by dsmurfin** [MetalPetal/MetalPetal#291]
Thanks again for such a great library.

Is there any reason that a CV422YpCbCr8 pixel format is not supported?

An error is returned from below when using this format:

`- (MTIRenderTask *)startTaskToRenderImage:(MTIImage *)image toCVPixelBuffer:(CVPixelBufferRef)pixelBuffer sRGB:(BOOL)sRGB error:(NSError * __autoreleasing *)inOutError completion:(void (^)(MTIRenderTask *))completion`

It doesn't seem to matter if I match the source format in this call either:

`            pixelBufferPool = try MTICVPixelBufferPool(pixelBufferWidth: Int(image.dimensions.width), pixelBufferHeight: Int(image.dimensions.height), pixelFormatType: kCVPixelFormatType_32BGRA, minimumBufferCount: 30)
`

### Checklist
- [X] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [X] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
`422YpCbCr8` pixel format is not supported. There's no public API to map a `422YpCbCr8` pixel buffer to a metal texture.

**Comment by dsmurfin** [comment]
Got you. Thank you. Then I will use VTPixelTransferSession to do the conversion first.
