### ISSUE TITLE
MTIImage 

### ISSUE THREAD

**Issue by mgstar1021** [MetalPetal/MetalPetal#294]
Hello, I am always getting black image when use MTIImage(cvPixelBuffer) functions.

> 
    @objc private func displayLinkDidRefresh(_ link: CADisplayLink) {
        let timeInterval = link.timestamp + link.duration
        let time = self._videoOutput.itemTime(forHostTime: timeInterval)

        if self._videoOutput.hasNewPixelBuffer(forItemTime: time),
           let pixelBuffer = self._videoOutput.copyPixelBuffer(forItemTime: time, itemTimeForDisplay: nil) {
            self._pixelBuffer = pixelBuffer
        }

        guard let buffer = _pixelBuffer else {
            return
        }
        
        let uiimage = UIImage(pixelBuffer: buffer)
       // let filtered = MTIImage(image: uiimage!)
        let filtered = MTIImage(cvPixelBuffer: buffer, alphaType: .alphaIsOne)
        self._imageView.image = filtered
    }
> 

If I make UIImage first, after create MTIImage, then it works, what is the problem?

**Comment by YuAo** [comment]
You set the environment variable `MTI_PRINT_ENABLED` to `1` to see if the MTIImageView encounters any error. 

The most likely reason here is that the pixel format of the pixel buffer is not supported. You can specify the pixel format of the video output using `AVPlayerItemVideoOutput.init(pixelBufferAttributes:)` https://developer.apple.com/documentation/avfoundation/avplayeritemvideooutput/1389231-init

**Comment by mgstar1021** [comment]
Thanks, It works.
