### ISSUE TITLE
Issue with static_framework and MetalPetal as a dependency

### ISSUE THREAD

**Issue by billychasen** [MetalPetal/MetalPetal#295]
Hello, I am using MetalPetal as a dependency in my pod, which has `static_framework = true`. When I add my pod to a new project, I get:

`[!] Using Swift static libraries with custom module maps is currently not supported. Please build MetalPetal as a framework or remove the custom module map.`

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version      | 1.23.0
 Integration Method      | CocoaPods
 Platform & Version      | iOS 12.0+
 Device                  | NA

**Comment by YuAo** [comment]
Please refer to https://github.com/CocoaPods/CocoaPods/issues/9023

**Comment by billychasen** [comment]
Thanks, unfortunately `use_frameworks! :linkage => :static` messes with other Pods in the project. I need to keep looking for a workaround.

**Comment by YuAo** [comment]
If you are not intend to implement any new `MTIImagePromise`, you can remove the module map file from the `podspec` file.

**Comment by billychasen** [comment]
great, thanks!
