### ISSUE TITLE
Distortion problem [失真问题]

### ISSUE THREAD

**Issue by ccworld1000** [MetalPetal/MetalPetal#296]
Large pictures are resized to very small, and the distortion is very serious. Are there any good methods or solutions?
Like the size 58x58 area, is it possible to have a smaller area?
 
[大图片resize到很小，失真很厉害，有那些好办法，或者解决方案吗？
好比大小58x58区域，有可能更小的区域？]

### Checklist
- [ x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by ccworld1000** [comment]
<img width="716" alt="red" src="https://user-images.githubusercontent.com/22360168/144700966-8cedb7f3-895c-4300-b40d-fc2134884111.png">

Like the red area?
好比红色区域？

**Comment by YuAo** [comment]
Are you talking about downsampling? 

There are several resampling algorithms that can somehow reduce the downsampling artifacts.

For example "lanczos". You can use `MPSImageLanczosScale` directly with MetalPetal.

```Swift
let scaleKernel = MTIMPSKernel(builder: { MPSImageLanczosScale(device: $0) })
let scaledImage = scaleKernel.apply(to: [image], parameters: [:], outputDimensions: MTITextureDimensions(cgSize: scaledSize), outputPixelFormat: .unspecified)
```

**Comment by ccworld1000** [comment]
Yes, it is downsampling. It seems that crash uses the above code again.
对的，就是降采样。好像又crash用上面的代码。

**Comment by ccworld1000** [comment]
let scaleKernel = MTIMPSKernel(builder: { MPSImageLanczosScale(device: $0) })
                    let scaledImage = scaleKernel.apply(toInputImages: [image1024], parameters: [:], outputTextureDimensions: MTITextureDimensions(width: SS, height: SS), outputPixelFormat: .unspecified)

**Comment by ccworld1000** [comment]
2021-12-06 21:27:17.445832+0800 CCPetalShow[2930:80282] *** Assertion failure in -[MTIMPSProcessingRecipe initWithKernel:inputImages:parameters:outputTextureDimensions:outputPixelFormat:], MTIMPSKernel.m:95
2021-12-06 21:27:17.554998+0800 CCPetalShow[2930:80282] [General] An uncaught exception was raised
2021-12-06 21:27:17.555168+0800 CCPetalShow[2930:80282] [General] Invalid parameter not satisfying: [kernel.alphaTypeHandlingRule _canHandleAlphaTypesInImages:inputImages]
2021-12-06 21:27:17.555351+0800 CCPetalShow[2930:80282] [General] (
	0   CoreFoundation                      0x00007fff205401db __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20279d92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20569352 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff213284d2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   MetalPetal                          0x00000001072fc9a6 -[MTIMPSProcessingRecipe initWithKernel:inputImages:parameters:outputTextureDimensions:outputPixelFormat:] + 390
	5   MetalPetal                          0x00000001072fd2bd -[MTIMPSKernel applyToInputImages:parameters:outputTextureDimensions:outputPixelFormat:] + 173
	6   CCPetalShow                         0x0000000106f3726f $s11CCPetalShow11ContentViewV6canvas33_EF0368C99E463417ECC0B4B6B5B61049LLQrvgySo7MTKViewCcfU_ + 5343
	7   CCPetalShow                         0x0000000106f406a1 $s11CCPetalShow12MetalKitViewV11CoordinatorC4draw2inySo7MTKViewC_tF + 81
	8   CCPetalShow                         0x0000000106f406f5 $s11CCPetalShow12MetalKitViewV11CoordinatorC4draw2inySo7MTKViewC_tFTo + 53
	9   MetalKit                            0x00007fff2e4d3efa -[MTKView draw] + 274
	10  MetalKit                            0x00007fff2e4d3dd9 __23-[MTKView __initCommon]_block_invoke + 42
	11  libdispatch.dylib                   0x00000001075a3264 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00000001075a60b8 _dispatch_continuation_pop + 577
	13  libdispatch.dylib                   0x00000001075bc64a _dispatch_source_invoke + 2115
	14  libdispatch.dylib                   0x00000001075b315e _dispatch_main_queue_callback_4CF + 630
	15  CoreFoundation                      0x00007fff20502f18 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x00007fff204c5112 __CFRunLoopRun + 2755
	17  CoreFoundation                      0x00007fff204c3f8c CFRunLoopRunSpecific + 563
	18  HIToolbox                           0x00007fff2870ba83 RunCurrentEventLoopInMode + 292
	19  HIToolbox                           0x00007fff2870b7e5 ReceiveNextEventCommon + 587
	20  HIToolbox                           0x00007fff2870b583 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	21  AppKit                              0x00007fff22ccd172 _DPSNextEvent + 864
	22  AppKit                              0x00007fff22ccb945 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
	23  AppKit                              0x00007fff22cbdc69 -[NSApplication run] + 586
	24  AppKit                              0x00007fff22c91e6c NSApplicationMain + 816
	25  SwiftUI                             0x00007fff41cd094d $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_pFTf4e_nAA07TestingdG0C_Tg5 + 100
	26  SwiftUI                             0x00007fff4250215c $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 162
	27  SwiftUI                             0x00007fff420ebd31 $s7SwiftUI3AppPAAE4mainyyFZ + 61
	28  CCPetalShow                         0x0000000106f3d3fe $s11CCPetalShow0aB3AppV5$mainyyFZ + 30
	29  CCPetalShow                         0x0000000106f3d479 main + 9
	30  libdyld.dylib                       0x00007fff203e9f3d start + 1
)
2021-12-06 21:27:17.558785+0800 CCPetalShow[2930:80282] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [kernel.alphaTypeHandlingRule _canHandleAlphaTypesInImages:inputImages]'

**Comment by ccworld1000** [comment]
2021-12-06 21:27:17.445832+0800 CCPetalShow[2930:80282] *** Assertion failure in -[MTIMPSProcessingRecipe initWithKernel:inputImages:parameters:outputTextureDimensions:outputPixelFormat:], MTIMPSKernel.m:95
2021-12-06 21:27:17.554998+0800 CCPetalShow[2930:80282] [General] An uncaught exception was raised
2021-12-06 21:27:17.555168+0800 CCPetalShow[2930:80282] [General] Invalid parameter not satisfying: [kernel.alphaTypeHandlingRule _canHandleAlphaTypesInImages:inputImages]
2021-12-06 21:27:17.555351+0800 CCPetalShow[2930:80282] [General] (
	0   CoreFoundation                      0x00007fff205401db __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20279d92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20569352 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff213284d2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   MetalPetal                          0x00000001072fc9a6 -[MTIMPSProcessingRecipe initWithKernel:inputImages:parameters:outputTextureDimensions:outputPixelFormat:] + 390
	5   MetalPetal                          0x00000001072fd2bd -[MTIMPSKernel applyToInputImages:parameters:outputTextureDimensions:outputPixelFormat:] + 173
	6   CCPetalShow                         0x0000000106f3726f $s11CCPetalShow11ContentViewV6canvas33_EF0368C99E463417ECC0B4B6B5B61049LLQrvgySo7MTKViewCcfU_ + 5343
	7   CCPetalShow                         0x0000000106f406a1 $s11CCPetalShow12MetalKitViewV11CoordinatorC4draw2inySo7MTKViewC_tF + 81
	8   CCPetalShow                         0x0000000106f406f5 $s11CCPetalShow12MetalKitViewV11CoordinatorC4draw2inySo7MTKViewC_tFTo + 53
	9   MetalKit                            0x00007fff2e4d3efa -[MTKView draw] + 274
	10  MetalKit                            0x00007fff2e4d3dd9 __23-[MTKView __initCommon]_block_invoke + 42
	11  libdispatch.dylib                   0x00000001075a3264 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00000001075a60b8 _dispatch_continuation_pop + 577
	13  libdispatch.dylib                   0x00000001075bc64a _dispatch_source_invoke + 2115
	14  libdispatch.dylib                   0x00000001075b315e _dispatch_main_queue_callback_4CF + 630
	15  CoreFoundation                      0x00007fff20502f18 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x00007fff204c5112 __CFRunLoopRun + 2755
	17  CoreFoundation                      0x00007fff204c3f8c CFRunLoopRunSpecific + 563
	18  HIToolbox                           0x00007fff2870ba83 RunCurrentEventLoopInMode + 292
	19  HIToolbox                           0x00007fff2870b7e5 ReceiveNextEventCommon + 587
	20  HIToolbox                           0x00007fff2870b583 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	21  AppKit                              0x00007fff22ccd172 _DPSNextEvent + 864
	22  AppKit                              0x00007fff22ccb945 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
	23  AppKit                              0x00007fff22cbdc69 -[NSApplication run] + 586
	24  AppKit                              0x00007fff22c91e6c NSApplicationMain + 816
	25  SwiftUI                             0x00007fff41cd094d $s7SwiftUI6runAppys5NeverOSo21NSApplicationDelegate_pFTf4e_nAA07TestingdG0C_Tg5 + 100
	26  SwiftUI                             0x00007fff4250215c $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 162
	27  SwiftUI                             0x00007fff420ebd31 $s7SwiftUI3AppPAAE4mainyyFZ + 61
	28  CCPetalShow                         0x0000000106f3d3fe $s11CCPetalShow0aB3AppV5$mainyyFZ + 30
	29  CCPetalShow                         0x0000000106f3d479 main + 9
	30  libdyld.dylib                       0x00007fff203e9f3d start + 1
)
2021-12-06 21:27:17.558785+0800 CCPetalShow[2930:80282] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [kernel.alphaTypeHandlingRule _canHandleAlphaTypesInImages:inputImages]'

**Comment by ccworld1000** [comment]
Crash here "_canhandlealphatypesinimages"
崩溃在这里"_canHandleAlphaTypesInImages"

**Comment by ccworld1000** [comment]
MTIMPSKernel -> NSParameterAssert([kernel.alphaTypeHandlingRule _canHandleAlphaTypesInImages:inputImages]);

**Comment by ccworld1000** [comment]
The problem of downsampling may not be easy to solve. At present, it seems to be a common problem. It is expected to scale one of them 20x20, which is equivalent to almost no content, except for the specific color picture.

降采样这个问题可能不好解决，这个目前好像是共性问题。期望缩放其中之一20x20，相当于内容差不多都没了，除了一些特定滴颜色图片。

**Comment by YuAo** [comment]
Please read: https://github.com/MetalPetal/MetalPetal#alpha-types

**Comment by ccworld1000** [comment]
The effect seems to be average
效果貌似也一般般

**Comment by YuAo** [comment]
That's just a direction you may want to look at.  You may want to try some other resample algorithms, learn about their concepts, pros and cons.

Applying a lowpass filter before downsample may help with the "aliasing" artifact.

You can also choose to write your own resample algorithm.

**Comment by ccworld1000** [comment]
I mainly use, ha ha, this may be a very difficult topic, beyond the limit.
我主要是用，哈哈，这也许是非常困难的话题，超出界限。
