### ISSUE TITLE
Apply MTIMPSGaussianBlurFilter to image with inputMask 

### ISSUE THREAD

**Issue by DanielZanchi** [MetalPetal/MetalPetal#297]
I'm trying to apply a **_MTIMPSGaussianBlurFilter_** to an image with an **inputMask** but it seems to be available only for **_MTIHexagonalBokehBlurFilter_**

Any solution on how to apply it with a mask?

**Comment by DanielZanchi** [comment]
for now I'm doing this in this way. I'm pretty sure there a better, more efficient way:
`    func getBlurImage(fromMask mask: UIImage, withRadius radius: Float) {
        guard let image = originalImage else { return }
        let inputImage = MTIImage(image: image, isOpaque: true)
        
        let invertColorFilter = MTIColorInvertFilter()
        invertColorFilter.inputImage = MTIImage(image: mask, isOpaque: true)
        let newMask = invertColorFilter.outputImage
        
        // Get the part of the image where I want to apply the blur fliter
        let blendMaskFilter = MTIBlendWithMaskFilter()
        blendMaskFilter.inputBackgroundImage = MTIImage(color: MTIColor.clear, sRGB: false, size: inputImage.size)
        blendMaskFilter.inputMask = MTIMask(content: newMask!)
        blendMaskFilter.inputImage = inputImage
        let imageToBlur = blendMaskFilter.outputImage
        // ---------------------------------------

        // apply the blur filter
        let blurFilter = MTIMPSGaussianBlurFilter()
        blurFilter.radius = radius
        blurFilter.inputImage = imageToBlur
        let blurredImage = blurFilter.outputImage
        // ----------------------------

        //Put the background back
        let blendFilter = MTIBlendFilter(blendMode: .normal)
        blendFilter.inputBackgroundImage = inputImage
        blendFilter.inputImage = blurredImage
        blendFilter.intensity = 1.0
        
        
        let outputImage = try! self.getContext().makeCGImage(from: blendFilter.outputImage!)
        self.delegate?.updateBlurredPhoto(image: UIImage(cgImage: outputImage))`

**Comment by YuAo** [comment]
`MTIMPSGaussianBlurFilter` uses metal performance shaders directly. It does not support any mask.

About your current approach:

1. You can pick a `mode` for `MTIMask` so the `MTIColorInvertFilter` is not necessary.

2. You can arrange filters this way:
    ```
     input → MTIMPSGaussianBlurFilter  ⤵︎
       mask(mode: .oneMinusMaskValue) → MTIBlendWithMaskFilter → output
                                input  ⤴︎
    ```

**Comment by DanielZanchi** [comment]
@YuAo  Thank you for the reply.
I changed it to this:

```
    func getBlurImage(fromMask mask: UIImage?) {
        guard let image = originalImage else {
            self.delegate?.updateBlurredPhoto(image: nil);
            return
        }
        guard let mask = getMask(mask: mask) else {
            self.delegate?.updateBlurredPhoto(image: nil);
            return
        }
        let inputImage = MTIImage(image: image, isOpaque: true)
        
        // apply the blur filter (MTIMPSGaussianBlurFilter)
        let blurredImage = getImageWithFilter(inputImage: inputImage)

        let blendMaskFilter = MTIBlendWithMaskFilter()
        blendMaskFilter.inputImage = blurredImage
        blendMaskFilter.inputMask = MTIMask(content: mask, component: .red, mode: .oneMinusMaskValue)
        blendMaskFilter.inputBackgroundImage = inputImage
        
        if let outputImage = blendMaskFilter.outputImage {
            do {
                let filteredImage = try self.getContext().makeCGImage(from: outputImage)
                let image = UIImage(cgImage: filteredImage)
                DispatchQueue.main.async {
                    self.delegate?.updateBlurredPhoto(image: image)
                }
            } catch {
                print(error)
                self.delegate?.updateBlurredPhoto(image: nil)
            }
        }
    }
```
    
Here is where I apply the filter:
```
    private func getImageWithFilter(inputImage: MTIImage) -> MTIImage? {
        switch self.blurType {
        case .bokeh:
            let bokehFilter = MTIHexagonalBokehBlurFilter()
            bokehFilter.inputImage = inputImage
            bokehFilter.radius = self.radius
            return bokehFilter.outputImage
        case .gaussian:
            let gaussianFilter = MTIMPSGaussianBlurFilter()
            gaussianFilter.inputImage = inputImage
            gaussianFilter.radius = radius
            return gaussianFilter.outputImage
        }
    }
```

**Comment by YuAo** [comment]
It's better to use two different routines for hexagonal bokeh and gaussian blur. 

Firstly the `mask` of hexagonal bokeh filter comes for free. It's more efficient to use that mask than using a blend with mask filter afterwards. 

Secondly, the mask of hexagonal bokeh controls the "Circle of Confusion" directly resulting in better visual result.
