### ISSUE TITLE
Video overlay on a video

### ISSUE THREAD

**Issue by Umity** [MetalPetal/MetalPetal#302]
Hi, I know how to use MultilayerCompositingFilter and adding images over a video, with a preferred blend mode. 

My question is, how can i use a video file as an overlay, with blending mode option, over a video. Lets say, I have a few seconds of snow overlay video file and I'd like to use it over a selected video file. Which method would be more appropriate?

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
- Create an `AVComposition` with two video tracks, one for the background, one for snowflakes. 
- Create a `MTIVideoComposition` with that two track asset, you can access the two tracks' image using `request.sourceImages` in the `filter` block.

**Comment by Umity** [comment]
Thank you, will try it on weekend
