### ISSUE TITLE
HSL - here we go again!

### ISSUE THREAD

**Issue by Umity** [MetalPetal/MetalPetal#304]
Hi, first off, happy new year to everyone. And have an amazing new year, MetalPetal. 

I tried my best to find a solution for a HSL filter and couldnt be successful. I made flexmonkey's hsl filter with the MetalPetal ( @YuAo suggested this filter)  but the filter is causing very unfortunate banding. It is so bad.. On the other hand, that filter is using a deprecated API. 

So, my question is how can we achieve a nice smooth HSL filter? 

Or, do you see any problem on this filter?
https://github.com/FlexMonkey/Filterpedia/blob/master/Filterpedia/customFilters/MultiBandHSV.swift

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by Umity** [comment]
I also would like to bring this into your attention;
https://stackoverflow.com/questions/69859674/swift-ios-core-image-with-metal-kernel-strange-kernel-behavior
@YuAo  is it possible if you can check this algorithm to see if it really working without problem (swift one)?

**Comment by YuAo** [comment]
Sorry, I do not have much experience on HSL filters.

The swift algorithm seems reasonable. You can use a CGContext to draw an image into a BGRA buffer and apply the algorithm on the image buffer to see the result before porting that to GPU shader code.

You may also want to refer to open source image processing softwares, for example GIMP.  https://gitlab.gnome.org/GNOME/gegl/-/blob/f4b308386c2a429a828ffc04277a3da4eaac9629/operations/workshop/selective-hue-saturation.c

**Comment by Umity** [comment]
Thanks Yao. How can I do that? Is there a tutorial about it?

And about the GIMP one, I dont know how to port it to MetalPetal.

**Comment by YuAo** [comment]
For applying the swift algorithm using a CGContext: https://www.google.com/search?&ie=UTF-8&q=CGContext+bitmap+modification

The GIMP seems to use this instead of the selective-hue-saturation: https://gitlab.gnome.org/GNOME/gimp/-/blob/3c0e21e4bf5dcaff6f8835111ce1203ef289a39a/app/operations/gimpoperationhuesaturation.c

For GEGL operations to shader, you need to first understand how the operation works.  There's typically a `while`/`for` loop that process the color value for each pixel (in the `gimp_operation_hue_saturation_process` function). If you are not familiar with shader/GPU debug you can first port the C code to Swift, and use the "CGContext image processing" technique to debug/verify the algorithm.

**Comment by Umity** [comment]
Do you think can i convert with cicolorkernel to swift? I couldnt find a good example...

**Comment by YuAo** [comment]
There's no way of directly converting the code. CIColorKernel is just a function that processes on each pixel of an image. You should be able to rewrite the logic in Swift.

**Comment by deluxefx** [comment]
I wish i could..

**Comment by Umity** [comment]
I wish I could.. I hope to find an example tutorial or something...

**Comment by sampil** [comment]
Hi!
I requested the HSL feature couple years ago, then I struggled myself. 
Now, I'd love to share the result as my possible investment in the MetalPetal Project, which literally made my world a better place 💖
[SAMHsl.metal.zip](https://github.com/MetalPetal/MetalPetal/files/7903648/SAMHsl.metal.zip)

**Comment by Umity** [comment]
@sampil wow! This is amazing! Thank you so much. Can i ask whats samHsl6??? Sorry, I am not good at metal.

And i created a swift class for this metal shader. Attaching here
[SAMHsl.swift.zip](https://github.com/MetalPetal/MetalPetal/files/7913651/SAMHsl.swift.zip)

@YuAo this hsl filter looks great and you may want to add it to the project.


.

**Comment by YuAo** [comment]
Thanks @Unmity. I prefer not to add more "non standard" algorithms / filters to the library. Also the "MultiBandHSV" algorithm in the "Filterpedia" repo is GPL licensed.

**Comment by fazal-e-majid** [comment]
@Umity @sampil I'm trying use the filter but I'm getting white screen. can you take a look at this [project](https://github.com/fazal-e-majid/MyHSLDemo) and help me fix this ?
Thank you!
