### ISSUE TITLE
Saving display p3 images

### ISSUE THREAD

**Issue by Umity** [MetalPetal/MetalPetal#305]
Hi,

I am trying to save displayP3 color-space images, but it seems somehow they are being converted to sRGB. What is so interesting is the saved image's color-space is displayP3. 

Here is an example image: https://www.wide-gamut.com/assets/test/image-red-P3.jpg

if your device supports displayP3, then you should be able to see "W" in the image. 
I am importing this to MetalPetal, everything looks good in the app but when saved, there is no W anymore if you look at the output in Photos app. Why is that?

**Comment by YuAo** [comment]
https://github.com/MetalPetal/MetalPetal#color-spaces

**Comment by Umity** [comment]
I read. Can you import this https://www.wide-gamut.com/assets/test/image-red-P3.jpg
and save with the "W" on it or not?

I am sorry but I could not understand why i can't export a displayp3 image without losing details but in same time keeping the image as displayp3 colorspace.

**Comment by Umity** [comment]
I mistakenly forgot to add the option when saving the original image.. So, it is my mistake.
 if var image2 = MTIImage(contentsOf: url, options: MTICGImageLoadingOptions.init(colorSpace: CGColorSpace(name: CGColorSpace.displayP3)), isOpaque: false) {
