### ISSUE TITLE
SpriteKit Example

### ISSUE THREAD

**Issue by ashikenshin** [MetalPetal/MetalPetal#306]
Thank you for this library. 

I'm not a very experienced programmer and wanted to use this for games on iOS using Spritekit but have no idea how to start. A simple example would really help.

Thank you in advance

**Comment by YuAo** [comment]
You can find an example in the smoke test.
https://github.com/MetalPetal/MetalPetal/blob/58b226325e52ee13d18e869f28912522dc476ca1/Tests/MetalPetalTests/RenderTests.swift#L1512-L1533

**Comment by ashikenshin** [comment]
Thank you, I didn't check that part. I'll check it out and close this issue.
