### ISSUE TITLE
Why MTIChromaKeyBlendFilter removes white colored pixels also in video?

### ISSUE THREAD

**Issue by Coder-ACJHP** [MetalPetal/MetalPetal#311]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Hi @YuAo ,
I am using your awesome framework to remove black color from overlay videos and I faced a problem with videos containing white pixels like smoke effect or white glitch effects so I wonder  @how to avoid removing white pixels while using ChromeKey filter with AVMutableVideoComposition, my filter parameters look like this:
```
  let chromaKeyBlendFilter = MTIChromaKeyBlendFilter()
  chromaKeyBlendFilter.color = MTIColor(red: 0.0, green: 0.0, blue: 0, alpha: 1) // black color
  chromaKeyBlendFilter.smoothing = 0.25
  chromaKeyBlendFilter.thresholdSensitivity = 0.05
  chromaKeyBlendFilter.inputBackgroundImage = .init(image: backgroundImage).unpremultiplyingAlpha()
  ```
  Also tried change black color with 0 alpha but filter also removing white pixels.
  Can you advice me a way to fix this issue please?

**Comment by YuAo** [comment]
The "MTIChromaKeyBlendFilter", as its name suggests, makes use of chroma information of a color. "White" and "Black" differs in luminance channel only, so this is not a use case of "MTIChromaKeyBlendFilter".

For your case, I think you can try the "Screen" blend mode.

**Comment by Coder-ACJHP** [comment]
Thanks for quick replay, 
Actually I never saw it, let me try using it and inform you.

**Comment by Coder-ACJHP** [comment]
Hi again @YuAo 👋🏻
As you advised me to use `MTIBlendFilter(blendMode: .screen)` I implemented it and worked like charm,
Thank you for your efforts
