### ISSUE TITLE
UI Thread Choking When Setting LUT Intensity With Slider

### ISSUE THREAD

**Issue by zachgibson** [MetalPetal/MetalPetal#312]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Hello, I am applying a color lookup table filter to an image and changing intensity via a Slider. Sometimes performance is great, but with other images the main thread gets blocked and the UI drops frames. I can post a code snippet but I'm using MetalPetal's example SwiftUI code to do this.

**Comment by zachgibson** [comment]
It seems like maybe this happens when the image is really high resolution?

**Comment by zachgibson** [comment]
Here's my Struct:

```swift
struct EditPhotoView: View {
    @Binding var originalImage: UIImage
    @State private var lut = "aries-lut"
    @State private var renderContext = try! MTIContext(device: MTLCreateSystemDefaultDevice()!)
    @State private var intensity: Float = 1
    
    private func filter() throws -> CGImage {
        let filter = MTIColorLookupFilter()
        let image = MTIImage(image: originalImage, isOpaque: true)
        filter.inputImage = image
        filter.intensity = intensity
        filter.inputColorLookupTable = MTIImage(image: UIImage(named: lut)!, isOpaque: true)
        let outputImage = filter.outputImage!
        let cgImage = try self.renderContext.makeCGImage(from: outputImage)
        return cgImage
    }
    
    var body: some View {
        NavigationView {
            ZStack {
                Color("BackgroundColor")
                    .ignoresSafeArea()
                Group {
                    switch Result(catching: {
                        try filter()
                    }) {
                    case .success(let image):
                        VStack {
                            ZoomableScrollView {
                                Image(uiImage: UIImage(cgImage: image))
                                    .resizable()
                                    .aspectRatio(contentMode: .fit)
                            }
                            VStack(alignment: .leading) {
                                Text("Intensity of Aries LUT: \(intensity, specifier: "%.2f")")
                                Slider(value: $intensity, in: 0...1)
                            }
                            .padding()
                        }
                    case .failure(let error):
                        Text(error.localizedDescription)
                    }
                }
            }
            .navigationBarTitleDisplayMode(.inline)
        }
    }
}
```

**Comment by YuAo** [comment]
The situation here is that the `cgImage` you get from `makeCGImage` is backed by a newly allocated `CVPixelBuffer` and the GPU performs the render asynchronously. When you use that image in your SwiftUI view, the image needs to be displayed so the UI waits for the GPU to complete the work.

The whole process consists of the following steps:

1. Create a `CVPixelBuffer` for the final image. (Memory allocation)
2. Convert the input CGImage to a GPU texture. (Memory copy)
3. Encode work for GPU. (Super fast with Metal)
4. Create a `CGImage` backed by the `CVPixelBuffer` and return the `CGImage`. (Almost free)
5. UI waits for the GPU to finish its work and converts the image to a proper display format if needed.

For high resolution images, the GPU may need extra time to finish the work, and step 1 and 2 is quite costly.

--- 

You can consider:

- Render a screen size image for preview. Render the full resolution when your user wants to export the photo.
- Make the render more "Main Thread Friendly"
    - Do not recreate the input MTIImage each time, cache the result of `MTIImage(image: originalImage, isOpaque: true)`. (for `step 2`)
    - Use a CVPixelBufferPool instead of directly `makeCGImage`, this saves time for memory allocation, see https://github.com/MetalPetal/MetalPetal/blob/58b226325e52ee13d18e869f28912522dc476ca1/MetalPetalExamples/Shared/PixelBufferPoolBackedImageRenderer.swift  (for `step 1`)
    - Throttle and wait for the GPU in a separate queue. (for `step 5`)

**Comment by zachgibson** [comment]
Wow, thank you for such a detailed and informative breakdown. I’m eager to try these optimizations out. Also props to you for making such a useful library.
