### ISSUE TITLE
Can MetalPetal integrate Effects (particle, sks files) in buffer frame video?

### ISSUE THREAD

**Issue by vfa-khangls** [MetalPetal/MetalPetal#313]
First, I apologize for my limited English.
I have a big problem when I want to do a project about video effects like Tiktok.
This application allows users to track the object they want, then add an overlay effect and finally export them to a new video.
I'm currently using ReplayKit to record the screen, which makes me play the video for 2 minutes from start to finish.
How can I put effects inside buffer each frame and output them like tiktok is doing.
Really appreciate if you can help me.

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
You can use `MTISKSceneRenderer` to generate `MTIImage`s from a `SKScene`. https://github.com/MetalPetal/MetalPetal/blob/6c398f2f099638d4c1efb6b3614df00f5a317848/Frameworks/MetalPetal/SpriteKit/MTISKSceneRenderer.h

Use `MTIVideoComposition` to compose the scene with your video. You can find the usage of `MTIVideoComposition` in the example project.

**Comment by vfa-khangls** [comment]
> You can use `MTISKSceneRenderer` to generate `MTIImage`s from a `SKScene`. https://github.com/MetalPetal/MetalPetal/blob/6c398f2f099638d4c1efb6b3614df00f5a317848/Frameworks/MetalPetal/SpriteKit/MTISKSceneRenderer.h
> 
> Use `MTIVideoComposition` to compose the scene with your video. You can find the usage of `MTIVideoComposition` in the example project.

Thank you very much, I will try that way.

**Comment by vfa-khangls** [comment]
Dear @YuAo ,
I have tried your recommended solution.

**Comment by vfa-khangls** [comment]
Dear @YuAo ,
I have tried your recommended solution.

**Comment by vfa-khangls** [comment]
Dear @YuAo ,
I have tried your recommended solution and I have some issues to need help.
My integate code:
**Step 1: Use MTISKSceneRrnderer to render MTIImages with Timer repeat 24 times / second. (24fps)**
 `let mtiImage = self.sksceneRender.snapshot(atTime: CFAbsoluteTimeGetCurrent(), viewport: self.view.frame, pixelFormat: .rgba8Unorm_srgb, isOpaque: false)
 self.mtiimagesSource.append(mtiImage)
 `
 **Step 2: Use VideoComposition to compose**
 `  let watermarkFilter = MultilayerCompositingFilter()
    
        videoComposition = MTIVideoComposition(asset: videoAsset!, context: renderContext!, queue: DispatchQueue.main, filter: { [weak self] request in
            guard let self = self else { return MTIImage.black }
            
            guard let sourceImage = request.anySourceImage else { return MTIImage.black }
            var layers : [MultilayerCompositingFilter.Layer] = []
            
            if self.frameRunning < self.boxs.count {
                let watermarkMaskImage = self.mtiimagesSource[self.frameRunning]
                let watermarkMaskTransformFilter = MTITransformFilter()
                watermarkMaskTransformFilter.inputImage = watermarkMaskImage
                layers = [MultilayerCompositingFilter.Layer(content: watermarkMaskImage)
                            .blendMode(.normal)
                            .frame(screenRect, layoutUnit: .pixel)
                            .mask(MTIMask(content: watermarkMaskTransformFilter.outputImage!, component: .alpha, mode: .normal))]
                
            } else {
                print("END")
                self.frameRunning = 0
            }
            
            watermarkFilter.layers = layers
            
            self.frameRunning += 1
                        
            return FilterGraph.makeImage(builder: { output in
                sourceImage => watermarkFilter.inputPorts.inputBackgroundImage
                watermarkFilter => output
            })!
        })`
            
Issue 1: Get a crash (image below)
`[renderer updateAtTime:_frameTime];`
<img width="1188" alt="Screen Shot 2022-04-07 at 09 56 08" src="https://user-images.githubusercontent.com/83194792/162111318-3d4378f4-952d-4830-a9f7-10aa4e2830be.png">

Issue 2: If I change time parameter CFAbsoluteTimeGetCurrent() to specitif time like below ( 24fps)
`time = 0.0
time = 0.041666666666666664
time = 0.08333333333333333
time = 0.125
time = 0.16666666666666666
time = 0.20833333333333334
time = 0.25
time = 0.2916666666666667
time = 0.3333333333333333
time = 0.375
time = 0.4166666666666667
time = 0.4583333333333333
time = 0.5
time = 0.5416666666666666
time = 0.5833333333333334
time = 0.625
time = 0.6666666666666666
time = 0.7083333333333334
time = 0.75
time = 0.7916666666666666
time = 0.835
time = 0.8766666666666667
time = 0.9183333333333333
time = 0.96
time = 1.0016666666666667`
I success compose and export video. But nothing Nodes, effect, emitter of my SKScene into video ?

**Comment by YuAo** [comment]
I don't quite understand your code. Why do you use a transform filter without a transform? Why do you mask the layer? 

Nevertheless, here's a naive approach:

```swift
// Example Project
// VideoProcessorView.swift 
// func updateVideoURL(_ url: URL) {

let asset = AVURLAsset(url: url, options: [AVURLAssetPreferPreciseDurationAndTimingKey: true])

let sparkScene = SKScene(size: CGSize(width: 512, height: 512))
let circle = SKShapeNode(circleOfRadius: 16)
circle.lineWidth = 0
circle.fillColor = .black
circle.position = CGPoint(x: 256, y: 256)
sparkScene.addChild(circle)
let node = SKEmitterNode(fileNamed: "spark.sks")!
node.position = CGPoint(x: 256, y: 256)
sparkScene.addChild(node)
let skRenderer = MTISKSceneRenderer(device: renderContext.device)
skRenderer.scene = sparkScene

let compositingFilter = MultilayerCompositingFilter()

var startTime: TimeInterval?

let videoComposition = MTIVideoComposition(asset: asset, context: renderContext, queue: DispatchQueue.main, filter: { request in
    guard let sourceImage = request.anySourceImage else {
        return MTIImage.black
    }
    
    if startTime == nil {
        startTime = CACurrentMediaTime()
    }
    
    let sceneImage = skRenderer.snapshot(atTime: startTime! + request.compositionTime.seconds, viewport: CGRect(x: 0, y: 0, width: 512, height: 512), pixelFormat: .bgra8Unorm, isOpaque: false)
    
    compositingFilter.layers = [
        MultilayerCompositingFilter.Layer(content: sceneImage)
    ]
    
    compositingFilter.inputBackgroundImage = sourceImage
    return compositingFilter.outputImage!
})
            
let playerItem = AVPlayerItem(asset: asset)
playerItem.videoComposition = videoComposition.makeAVVideoComposition()
self.videoComposition = videoComposition
videoAsset = asset
videoPlayer = AVPlayer(playerItem: playerItem)
videoPlayer?.play()
```

I'm not a SpriteKit expert. But, as far as I know (I might be wrong here), you can't do "random time rendering" in SpriteKit for now (iOS 15). The frame time needs to be near `CACurrentMediaTime()` and the it can only go forward. If you use my code without any modification you'll notice that the sparks freeze when you seek the video backward (or the video is re-played from the start). You may want to rebuild the renderer and the scene if a "wayback in time" is detected.

**Comment by vfa-khangls** [comment]
Dear Mr. @YuAo,
I really appreciate your help with my project! Thank you so much!
