### ISSUE TITLE
Imported Video quality is pretty bad

### ISSUE THREAD

**Issue by Umity** [MetalPetal/MetalPetal#316]
Hi,

 I am not sure if this is related to colorspace or not. But i shot a video with my mirrorless camera, 100mb/s datarate 4k and imported it and the quality is very bad, a lot of bandings. Is this colorspace related issue or iOS doing some kind of compression? 

here is the file i am talking about if you need to test: https://drive.google.com/file/d/1jtOqEGrpdJVlPESiDWrJpb74a-EP5tVB/view?usp=sharing

How can i increase the quality?

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
I can't see any quality drop processing your video in the MetalPetal example app.
![IMG_A8B6B0C54834-1](https://user-images.githubusercontent.com/1234944/161185556-6de1fad7-0be5-4d55-aae5-15d9059837ae.jpeg)

**Comment by Umity** [comment]
Hello @YuAo 

Theres a drop, a bad one. Lets take a look together;
Lets add LUT filter to the example app.
` let lutFilter = MTIColorLookupFilter()
                lutFilter.intensity = 1
                lutFilter.inputColorLookupTable = MTIImage(contentsOf: Bundle.main.url(forResource: "3", withExtension: "png")!, isOpaque: true)!`

and change to this:
`return FilterGraph.makeImage(builder: { output in
                    sourceImage => blendWithMaskFilter.inputPorts.inputImage
                    sourceImage =>/* grayScaleFilter => *//*dotScreenFilter =>*/
                   lutFilter.inputPorts.inputImage
                    lutFilter =>/*blendWithMaskFilter.inputPorts.inputBackgroundImage
                    blendWithMaskFilter =>*/ /*pixellateFilter =>*/ watermarkFilter.inputPorts.inputBackgroundImage
                    watermarkFilter => output
                })!`

Copy this lut into the project:
https://drive.google.com/file/d/1zP9Yzu4s20sfQr6Hb0YGYrJy75x4iVzP/view?usp=sharing
It is a strong filter, i know but the aim is to show you what i am talking about. 

here is my screenshot:
https://i.imgur.com/7Pp5nFa.png
**things get worse when you apply other filters over LUT filter, a lot of banding.** 


I dont think this is about colorspace issue (of course not sure). It seems to me iOS is "secretly" applying a compressing or something? How can we prevent this?

**Comment by Umity** [comment]
and here is the same LUT and applied on finalcut
https://i.imgur.com/UAJ1i6w.png

this is the expected result.

**Comment by Umity** [comment]
Also, when you export the video, the bitrate is between 10-15k. A big drop from 100k?

**Comment by YuAo** [comment]
I don't think it's something related to MetalPetal. I take a screenshot of the video played by the system player on iPhone SE, then apply the LUT using Photoshop on my Mac. The result has branding issue too. 

Closing this issue for now. I'll take a closer look at this later when I have more time.

---

For the bitrate drop, you can assign an averageBitRate value to the export settings.

**Comment by YuAo** [comment]
I did a side by side compare of the video processed using MetalPetal on macOS and your screenshot of Final Cut Pro.

<img width="1616" alt="Screen Shot 2022-04-06 at 14 12 58" src="https://user-images.githubusercontent.com/1234944/161917890-2a978759-4e76-4d50-ba5f-5941dd247dc7.png">

The preview in MetalPetal looks sharper than that in Final Cut Pro. I do not own a copy of Final Cut Pro. I guess that the screenshot you posted is somehow smoothed so it looks less sharper and the branding is not obvious?

Can you post a screenshot of the video played in Final Cut Pro without adding any filter?

**Comment by Umity** [comment]
@YuAo Hi, no, there is no any other filter i applied.
