### ISSUE TITLE
How to chain a CoreImageFilter in FilterGraph.makeImage

### ISSUE THREAD

**Issue by Tolecen** [MetalPetal/MetalPetal#317]
### Checklist
- [ x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

I want to chain a CoreImage Filter like "CIBloom". I know how to use it independently like this:
` let outImage =  MTICoreImageKernel.image(byProcessing: [inputImage], using: { inputs in
            let extent = inputs[0].extent
            return inputs[0].clampedToExtent().applyingFilter("CIBloom",parameters:[kCIInputIntensityKey:value,kCIInputRadiusKey:radius]).cropped(to: extent)
        }, outputDimensions: self.originMtiImage.dimensions)`

But how to chain it in FilterGraph.makeImage, for example:

`let image = FilterGraph.makeImage{ output in
            inputImage => exposureFilter => saturationFilter => clarityFilter => "CIBloom" => ouput
        }!`

Especially "CIBloom" needs clampedToExtent and cropped(to: extent) , so I am not sure how to use it.

**Comment by YuAo** [comment]
You need to wrap the Core Image processing part using `MTIUnaryFilter` protocol. You can refer to the implementation of `MTICoreImageUnaryFilter`.

**Comment by Tolecen** [comment]
Thanks! Got it
