### ISSUE TITLE
请教瘦脸的 Shader 用 Metal 怎么实现呢

### ISSUE THREAD

**Issue by Tolecen** [MetalPetal/MetalPetal#318]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

想用 MetalPetal 实现一下瘦脸的功能，但是 Metal 小白，不知如何去写，找到了一个旧的 GPUImage 的实现，在这个链接[https://www.jianshu.com/p/7e6911f9bd7d](https://www.jianshu.com/p/7e6911f9bd7d) ，请求大神有没有可能转成 Metal 的用在 MetalPetal 里呢？如果可以应该怎么实现呢？

**Comment by YuAo** [comment]
直接把glsl改写成msl就可以，人脸关键点的float数组可以用MTIVector来传，其他没什么要注意的，按文档写自定义滤镜就可以。这里不提供对shader转换的支持。
