### ISSUE TITLE
MTIVector的数组怎么传入Metal

### ISSUE THREAD

**Issue by Tolecen** [MetalPetal/MetalPetal#319]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

比如有三个点组成的数组 (1,2), (3,9), (2,4) 怎么传入 metal kernel 呢....

`kernel void ttestfacethinKernel(texture2d<half, access::sample> inputTexture [[texture(0)]],
                                  texture2d<half, access::write> outputTexture [[texture(1)]],
                             constant float *faceIntensity [[buffer(0)]],
                              ????? *facePoints [[buffer(1)]],
                             uint2 gid [[thread_position_in_grid]])`

比如上面 ??? 那里我该怎么写这个参数，才能接收到传入的数组... 试了好多一直不行...

**Comment by YuAo** [comment]
**App**

```swift
let points: [Float] = [1,2,3,9,2,4]
let vector = MTIVector(floatValues: points, count: UInt(points.count))
kernel.apply(toInputImages: ..., parameters: ["facePoints": vector], outputTextureDimensions: ..., outputPixelFormat: ...)
```

**Shader**

```metal
kernel void test(const device float *facePoints [[buffer(0)]]) { ... }
```
或
```metal
kernel void test(const device float2 *facePoints [[buffer(0)]]) { ... }
```

因为 float * 和 float2 * 内存排布刚好一样。

---

建议你先读一下这个：https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf

**Comment by Tolecen** [comment]
感谢，已明白~
