### ISSUE TITLE
Support Photoshop curves with MTIRGBToneCurveFilter

### ISSUE THREAD

**Issue by kallipigous** [MetalPetal/MetalPetal#32]
It looks like the MTIRGBToneCurveFilter is very similar to GPUImage's curveToneFilter, but it's not clear to me how to generate the MTIVectors needed for it to work. Are there any plans to include a photoshop curves (acv) parser in the future?

**Comment by YuAo** [comment]
Implement a photoshop acv parser should be very simple. You can find the acv file specification here: https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/ , search for Curves.

Here's one I created years ago, not sure if it still works, should be a good starting point for you. It uses `CIVector`s, but it should be trivial for you to replace that with `MTIVector`s.

[VIPhotoshopCurvesData.zip](https://github.com/MetalPetal/MetalPetal/files/2161751/VIPhotoshopCurvesData.zip)

**Comment by kallipigous** [comment]
Great. Many thanks. I’ll take a look.

**Comment by kallipigous** [comment]
I converted the class for MTIVeccor today but sadly it crashes MetalPetal. I get this  warning 

`newBufferWithBytesNoCopy:pointer 0x1050a6c10 is not 4096 byte aligned.'

**Comment by YuAo** [comment]
Any file name and line number you can provide?

**Comment by kallipigous** [comment]
An update worked. Sorry I was using the metalPetalDemo files and it was not updating the pod, just defaulting to the local code. I refreshed the pods and it jumped into life. 

Here's the version that works if anyone needs it. 

[VIPhotoshopCurvesData.zip](https://github.com/MetalPetal/MetalPetal/files/2257977/VIPhotoshopCurvesData.zip)
