### ISSUE TITLE
 The effect of playing the alpha video, the light is a black shadow   

### ISSUE THREAD

**Issue by kule123** [MetalPetal/MetalPetal#327]
How to deal with it
The effect of playing the alpha video, the light is a black shadow   ！

https://user-images.githubusercontent.com/11805288/182309591-5eab62e9-192f-479c-ae6b-cad83c2aa2d6.MP4

https://user-images.githubusercontent.com/11805288/182309610-eda7170d-9abd-4520-9638-2f0f5e1e5829.mp4

thanks

**Comment by kule123** [comment]
solve

**Comment by anonUser-lab** [comment]
@kule123  how did u solve this can you explain .
