### ISSUE TITLE
Dynamically chaining filters from array

### ISSUE THREAD

**Issue by ibprojects** [MetalPetal/MetalPetal#328]
Hello @YuAo and everyone using this great framework,

I have an array of different filters stored as [MTIFilter] and I'd like to loop through the array and hook the filters together. 

```
for filter in filters {
   filter.inputImage = previousFilter.outputImage // filter.inputImage is unavailable
}
```

Sorry if I've overlooked something, but what is the best way to dynamically add a `filter.outputImages` to a `previousFilter.inputImage`?

Thank you for your time!
Ian

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by akshpreet-singh** [comment]
Hello, @ibprojects have you find any solution Please tell me
