### ISSUE TITLE
Question regarding MTIThreadSafeImageView

### ISSUE THREAD

**Issue by codeslaw** [MetalPetal/MetalPetal#329]
HI! Thanks for the excellent library, currently making use of it for an AI-enhanced camera project. 
I'm wondering what the drawbacks of using `MTIThreadSafeImageView` are vs. `MTIImageView`, as they pertain to the warning present in the implementation:

```/// An image view that immediately draws its `image` on the calling thread. Most of the custom properties can be accessed from any thread safely. It's recommanded to use the `MTIImageView` which draws it's content on the main thread instead of this view.```

With even with the most basic possible pipeline using `MTIImageView`, eg. 
```swift
func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
        guard let pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else {
            return
        }
        let inputImage = MTIImage(cvPixelBuffer: buffer, alphaType: .alphaIsOne)
        DispatchQueue.main.async {
             self.feedView.image = inputImage
        }
    }
```
I see a significant hit to frame rate (bounces around 45-55 when targeting 60). When switching to `MTIThreadSafeImageView`, I get a solid 60fps with no variability.

Is this expected, or is it likely due to pressure on the main thread elsewhere in your opinion? If I move forward with the thread safe version, are there any caveats I should be aware of?

Cheers!

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
The main drawback of `MTIThreadSafeImageView` is that it renders the `MTIImage` immediately which may result in unnecessary renders. `MTIImageView` utilizes the `setNeedsDisplay` mechanism.

> Is this expected, or is it likely due to pressure on the main thread elsewhere in your opinion? 

I think it's likely due to pressure on the main thread elsewhere. You should able to achieve 60fps using `MTIImageView`.

> If I move forward with the thread safe version, are there any caveats I should be aware of?

I think its ok to use `MTIThreadSafeImageView` for your case.
