### ISSUE TITLE
Wrong vertex shader effect on real device

### ISSUE THREAD

**Issue by veewis** [MetalPetal/MetalPetal#333]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

I wrote a simple vertex shader for the transformation as follows. It works fine on the simulator. But on the real device, behind the resulting image, there are a lot of reduced original image, what is the reason for this?
``` 
// vertex shader
vertex VertexOut cameraVertex(
                              const device VertexIn * vertices [[ buffer(0) ]],
                              uint vid [[ vertex_id ]],
                              constant float4x4 & matrix [[ buffer(1) ]]
                              ) {
    VertexOut outVertex;
    VertexIn inVertex = vertices[vid];
    outVertex.position = matrix * inVertex.position;
    outVertex.textureCoordinate = inVertex.textureCoordinate;
    return outVertex;
}
```

```
//  get output image method
- (MTIImage *)outputImage {
    if (!self.inputImage) {
        return nil;
    }
    
    simd_float4x4 value = {
        simd_make_float4(0.5, 0, 0, 0),
        simd_make_float4(0, 0.5, 0, 0),
        simd_make_float4(0, 0, 1.0, 0),
        simd_make_float4(0, 0, 0, 1.0)
    };
    
    MTIVector *vector = [MTIVector vectorWithFloat4x4:value];
    return [self.class.kernel applyToInputImages:@[self.inputImage] parameters:@{
        @"matrix": vector
    } outputTextureDimensions:self.inputImage.dimensions outputPixelFormat:self.outputPixelFormat];
}
```
![demo](https://user-images.githubusercontent.com/113662209/190567908-a18449a6-7cf6-4b9d-983e-ef67d185ab45.jpg)

**Comment by YuAo** [comment]
If your shader does not draw every pixel of the output texture. You should set the output descriptor's load action to `MTLLoadActionClear`  so that the gpu can clear the texture for you. The default load action in MetalPetal is `MTLLoadActionDontCare` so pixels that are not written to are garbage values.

**Comment by veewis** [comment]
@YuAo Thank you very much. You solved my problem.
