### ISSUE TITLE
去背景，给文字着色

### ISSUE THREAD

**Issue by JackyHe2882** [MetalPetal/MetalPetal#334]
Hello @YuAo 
MetalPetal is very good, thank you very much. Here are my questions, and I hope to get your guidance.

I have a picture of calligraphy font. How to change the background of the picture with MetalPetal to achieve the purpose of character deduction, and how to only modify the text color while keeping the background color unchanged.
您好 @YuAo ,
MetalPetal非常棒，非常感谢。下面是我的问题，希望能得到您的指导。
我有一张书法字体图片，如何用MetalPetal实现换掉图片背景，达到扣字的目的，如何只修改文字颜色，而保持背景颜色不变。

**Comment by YuAo** [comment]
This is off-topic, nevertheless, you can:

A. Try extracting the text based on color lightness if it's darker text on lighter background or vice visa.
B. You can also try using a text rectangle detector to first find the region of the text in your image. And limit your filter to operate only on the text region.
