### ISSUE TITLE
Transparent image has black edges after transformation by MTITransformFilter

### ISSUE THREAD

**Issue by veewis** [MetalPetal/MetalPetal#335]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

When I transform a transparent image with MTITransformFilter, the resulting image has a black edge. How can I remove the black edge?

In the sample image below, you can see the black edge on the left side of the model's hair.
![transform1](https://user-images.githubusercontent.com/113662209/191672836-26c0a2d1-4f38-419c-8a65-4731b17ebb0a.jpg)

**Comment by YuAo** [comment]
Make sure that you are using the correct alpha types. https://github.com/MetalPetal/MetalPetal#alpha-types

**Comment by veewis** [comment]
The `alphaType` of my inputImage is `MTIAlphaTypeNonPremultiplied` , I use `- (MTIImage *) after imageByPremultiplyingAlpha` method make an MTIImage with `MTIAlphaTypePremultiplied`, but the two are the same as a result, there are black edges.

**Comment by veewis** [comment]
I found the cause of the error, I selected the wrong `alphaType` when generating `MTIImage`, so the image passed in already has a problem. Thank you very much.
