### ISSUE TITLE
超大图的全尺寸输出

### ISSUE THREAD

**Issue by Tolecen** [MetalPetal/MetalPetal#336]
尝试超大图输出，比如  8064*6048，renderContext.makeCGImage 和 PixelBufferPoolBackedImageRenderer 的 render 都会造成内存的暴涨，内存稍微小点的手机比如 4G 内存的都可能直接挂掉，6G 的有时也悬，有没有什么更好的方法呢？想实现的需求是 先把 MTIImage 转成 UIImage 继续处理，所以我试了上面两种先转 CGImage 的，有没有什么更好的不会有那么大内存暴涨的方式来做这件事呢？

原图打了zip在这个链接 [下载原图](https://cowtransfer.com/s/3fcc22dc316546)，不过任何这种图都会有这个问题。

感谢您的时间，期待有更好的建议~

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by Tolecen** [comment]
我用 FilterGraph.makeImage 串了多个 filter，例如 mtiHighlightShadowFilter => mtiBloomFilter => tiltShiftFilter，发现如果里面某一个是MTIUnaryFilter，他是用 CIFilter 实现的，这个内存差不多是不用 MTIUnaryFilter 的两倍，似乎 MTIUnaryFilter 自己又用掉一块？

**Comment by YuAo** [comment]
CIFilter 的内存由 CIContext 管理，所以你可能需要看看如何减少 CoreImage 渲染过程的内存使用。

你可以通过 MTIContext.coreImageContext 来访问 MetalPetal 内部的 CIContext；
可以使用 MTIContextOptions.coreImageContextOptions 来指定此 CIContext 的初始化选项；

通常情况下 CIContext 的 WorkingFormat 是 RGBAh 内存占用会比较多， 你可以尝试设置 kCIContextWorkingFormat 为 RGBA8。

---

目前没有其他方式来优化内存使用。看你的 filter 链，似乎也不能把图切成小块分别处理。

如果你需要连续处理多张大图的话，每次处理完一张图都需要等 GPU 完成以避免有多张要处理的图在 GPU 的处理队列中，即：使用 MTIRenderTask 的 waitUntilCompleted 方法。然后调用 MTIContext.reclaimResources 来释放渲染过程中使用的内存。也要注意合理使用 autoreleasepool。
