### ISSUE TITLE
Incorrect origin used when outputImageSize is supplied for MTICoreImageUnaryFilter

### ISSUE THREAD

**Issue by endanke** [MetalPetal/MetalPetal#338]
Replace this paragraph with a short description of the incorrect behavior.

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version      | 1.24.2
 Integration Method      | SwiftPM
 Platform & Version      |  macOS 12.5.1
 Device                  | MacBook Air (M1, 2020)

### Steps to Reproduce

Using a `MTICoreImageUnaryFilter` with a `CIKaleidoscope` filter input and specifying `outputImageSize`.

### Expected behavior

The image is positioned in the center.

### Actual behavior

The output is positioned differently than in 1.24.0.

I suspect the change in https://github.com/MetalPetal/MetalPetal/pull/314 has some side-effects on my setup which changed the origin of the output image. I understand that the PR should be fixing an issue related to positioning, but I'm not sure how am I supposed to supply the information about the origin before the filter is applied.

This is how the correct output looked with 1.24.0:

<img width="500" alt="Screenshot 2022-10-22 at 11 33 09" src="https://user-images.githubusercontent.com/2576246/197329754-21e1a6ab-a46e-40ee-aabd-a10e689fd08b.png">

Now with 1.24.2:

<img width="500" alt="Screenshot 2022-10-22 at 11 34 08" src="https://user-images.githubusercontent.com/2576246/197329755-27e42491-1261-424a-bbd6-cfa74410639b.png">

If I don't supply `outputImageSize` then the origin is correct, but the aspect ratio of the image is not:

<img width="500" alt="Screenshot 2022-10-22 at 11 37 30" src="https://user-images.githubusercontent.com/2576246/197329905-20754e51-7cfc-417f-8910-637aa6aa7884.png">

**Comment by YuAo** [comment]
Hi, @endanke. Can you please try #322 and see if it fixed this?

**Comment by endanke** [comment]
@YuAo yes it does, thanks! 
I wonder if instead of reverting, could we supply the origin of the output as a parameter for `MTICoreImageUnaryFilter` same way as it's done for `outputImageSize`? And if it's not defined the it would use the original implementation.

**Comment by YuAo** [comment]
@endanke MTIImage does not have the concept of an origin. I think it's better to supply the origin of the output in CoreImage's domain. For example, you can use the "apply transform" function of a CIImage to adjust its origin.

```
MTICoreImageKernel.image(byProcessing: [ciImage], using: { images in
                let input = images.first!
                ciFilter.inputImage = input
                let filteredImage = ciFilter.outputImage!
                return filteredImage.apply(.init(translationX: x, y: y))
            }, outputDimensions: ...)
```
