### ISSUE TITLE
Apply a background image/blur to a video

### ISSUE THREAD

**Issue by noho501** [MetalPetal/MetalPetal#340]
### Checklist
- [x ] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x ] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

Hi all,
I have a question. Is it possible to make blurred video background (or image) then save a new video? Something like that:

![310005815_415460560749469_6808951995841546742_n](https://user-images.githubusercontent.com/35057759/200343437-019010fe-a8f6-4e66-a143-971cb941da64.jpg)

Thank you for help.

**Comment by YuAo** [comment]
MetalPetal has everything you need to render that effect. However, you'll have to find a way to segment the main subject from the background. One option here is to use `VNGeneratePersonSegmentationRequest`.

**Comment by noho501** [comment]
> MetalPetal has everything you need to render that effect. However, you'll have to find a way to segment the main subject from the background. One option here is to use `VNGeneratePersonSegmentationRequest`.

Hi @YuAo Can I pay you to help me resolve this task?
