### ISSUE TITLE
Can you help me with swift implementation with compute kernel

### ISSUE THREAD

**Issue by sabrysmk** [MetalPetal/MetalPetal#341]
i tried to write swift file for my fisheye kernel but stuck on error  

-[MTLRenderPipelineDescriptorInternal setFragmentFunction:]:3062: failed assertion `fragmentFunction functionType is not a MTLFunctionTypeFragment.'

This is my kernel 
```
namespace metalpetal {
        kernel void fisheyeMTI(texture2d<half, access::read> input [[texture(0)]],
                            texture2d<half, access::write> output [[texture(1)]],
                            const device float& modifier [[buffer(0)]],
                            uint2 gid [[thread_position_in_grid]])
        {
            half2 size = half2(half(output.get_width()), half(output.get_height()));
            half2 uv = half2(gid) * 2 / size - half2(1);

            half d = length(uv) / (2 - modifier);
            half z = sqrt(1 - d * d);
            half r = atan2(d, z) / 3.14159;
            half phi = atan2(uv.y, uv.x);

            uv = half2(r * cos(phi) + 0.5, r * sin(phi) + 0.5);
            half4 value = input.read(uint2(uv * size) + 1);
            output.write(value, gid);
        }
}
```

and this is my swift class

```
class MTIFisheye: MTIUnaryImageRenderingFilter {
    
    var modifier: Float = 0.5 // 0...1
    
    override var parameters: [String : Any] {
        return ["modifier": modifier]
    }

    override class func fragmentFunctionDescriptor() -> MTIFunctionDescriptor {
        return MTIFunctionDescriptor(name: "metalpetal::fisheyeMTI", in: .main)
    }
}
```
I know that the error in MTIUnaryImageRenderingFilter.
But can't find a swift example of compute kernel 

      You can use a compute kernel in MetalPetal, there's no need to convert that to a fragment shader. Note that MetalPetal uses the last texture as compute kernel output, so all you need to do is swapping the texture binding index.

For example:
https://github.com/MetalPetal/MetalPetal/blob/d3d0ce85a89f1da5b113b4aea69a173f2c465203/Frameworks/MetalPetal/Shaders/Shaders.metal#L474-L489

---

For your question:

> but it's not working as original kernel.
> What I am missing here?

Looks like this should be a ` - `.

```
return half4(color + noise * (intensity));
                  ~~~ 
```

_Originally posted by @YuAo in https://github.com/MetalPetal/MetalPetal/issues/321#issuecomment-1139720671_

**Comment by YuAo** [comment]
You need to use a compute pipeline kernel.

```swift
struct FishEye {
    static let kernel = MTIComputePipelineKernel(computeFunctionDescriptor: MTIFunctionDescriptor(name: ..., in: .main))
}
let outputImage = FishEye.kernel.apply(toInputImages:..., parameters: ["modifier": ...], ...)
```

**Comment by sabrysmk** [comment]
> You need to use a compute pipeline kernel.
> 
> ```swift
> struct FishEye {
>     static let kernel = MTIComputePipelineKernel(computeFunctionDescriptor: MTIFunctionDescriptor(name: ..., in: .main))
> }
> let outputImage = FishEye.kernel.apply(toInputImages:..., parameters: ["modifier": ...], ...)
> ```

Thank you very much. Have a good day.
