### ISSUE TITLE
How to achieve Whites & Blacks adjustment similar to Lightroom

### ISSUE THREAD

**Issue by twomedia** [MetalPetal/MetalPetal#343]
I've been trying to write my own metal shader to achieve a whites & blacks adjustment similar to Lightroom with no success so far. Any advice, guidance or resource that you think can help would be greatly appreciated 🙏

Thanks!

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by zachgibson** [comment]
@twomedia any luck?

**Comment by zachgibson** [comment]
@YuAo do you have any pointers or references for how to achieve a shader like this?

**Comment by rdev** [comment]
@twomedia @zachgibson `CIToneCurve`'s edges will get you _basically_ there, but there isn't really an industry standard consensus on how HSWB adjustments work (and I looked hard)
Every editor implements these in their own way, if you put Lightroom and it's 3 nearest competitors together - they won't give you identical results on those sliders

Here's a very rough performance nightmare example (mid points hidden and are interpolated linearly between first and last):

https://github.com/MetalPetal/MetalPetal/assets/8418866/b5e109f9-5fac-45d1-8aad-3b0565b7bff2

Most non-color adjustments (and a fair amount of color ones) in standard editing software are basically achievable by a properly controlled tone curve

**Comment by twomedia** [comment]
Thanks for your input here. We've sidelined this feature for the meantime, but in the future I think your suggestion to use a Tone Curve, potentially coupled with some other adjustments, will do the trick. Thanks so much 😊

**Comment by zachgibson** [comment]
@rdev this is great ty! Somehow missed the notification for this but yeah for my purposes I think this will do just fine.
