### ISSUE TITLE
How to apply filter on saved video and save it again using MetalPetal ? [Urgent] 

### ISSUE THREAD

**Issue by commando24** [MetalPetal/MetalPetal#35]
I am using AVFoundation to apply filter on video . But its taking to much time like 30 seconds for 45 seconds video. Can anyone tell me how to use this framework ?

**Comment by YuAo** [comment]
You need to use AVAssetReader and writer. Here’s an example for you https://github.com/rs/SDAVAssetExportSession . It also has a delegate method where you can insert your render code.

**Comment by commando24** [comment]
@YuAo sorry to interrupt But can you please guide me or provide me a simple code to write in the delegate method ?

**Comment by YuAo** [comment]
All you need to do is to process the video buffer in the delegate method. 
You may want to look at MetalPetal's CameraViewController demo.

Something like:

```
- (void)exportSession:(SDAVAssetExportSession *)exportSession renderFrame:(CVPixelBufferRef)pixelBuffer withPresentationTime:(CMTime)presentationTime toBuffer:(CVPixelBufferRef)renderBuffer {
        MTIImage *inputImage = [[MTIImage alloc] initWithCVPixelBuffer:pixelBuffer alphaType:MTIAlphaTypeAlphaIsOne];
        self.filter.inputImage = inputImage;
        MTIImage *outputImage = self.filter.outputImage;
        NSError *error;
        [self.context renderImage:outputImage toCVPixelBuffer:renderBuffer error:&error];
}
```

Things about using `SDAVAssetExportSession` are not good topics here. You may want to create a question on "stackoverflow".

**Comment by commando24** [comment]
@YuAo thanks for your help. But my reason to use MetalPetal still not fullfilled. I thought using this will reduce video processing time but it's not . Can you tell me why this is happening ? Like we are using GPU for video processing but still its time same result as CPU.

**Comment by YuAo** [comment]
I think it’s better to create a sample project demonstrating the issue you’ve encountered. And post a question about what you’re doing / what is your expectation on a Q&A site like stackoverflow. So people can discuss the question in a more open and efficient way.
