### ISSUE TITLE
How to use AVVideoCompositionCoreAnimationTool to add sticker and text layer on video ?

### ISSUE THREAD

**Issue by VarinderSH** [MetalPetal/MetalPetal#352]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

**Comment by YuAo** [comment]
MetalPetal does not support `AVVideoCompositionCoreAnimationTool`. If you'd like to process video files you can use `MTIVideoComposition`.

**Comment by VarinderSH** [comment]
But how to add text, gif and sticker on video using MTIVideoComposition,  Any code example ?

**Comment by YuAo** [comment]
Please see #320
