### ISSUE TITLE
Create MTIMask from MLMultiArray? (for Dynamic Masks)

### ISSUE THREAD

**Issue by vjdaemp** [MetalPetal/MetalPetal#353]
I am currently experimenting with the Video processing function of the demo app. In the code block that creates the `MTIVideoComposition`, I made modifications to apply a filter with a dynamic mask.  I achieved this by replacing the `inputMask` of the `MTIBlendWithMaskFilter` each frame. 

My issue is that I am using CoreML to generate the dynamic mask, and it takes too much processing time to convert the mask to MTIMask. The CoreML model outputs a `MLMultiArray`. This needs to be converted to a UIImage -> MTIImage -> MTIMask.  The ideal solution is to update my CoreML model to output `CVPixelBuffer` and let the CoreML handle the conversion. However, I was wondering if there is any way that MetalPetal can support creating an `MTIMask` directly from a `MLMultiArray`. 

For example:
```
 let videoComposition = MTIVideoComposition(asset: originalAsset, context: renderContext, queue: DispatchQueue.global(qos:.userInitiated), filter: { request in

     // Update `.inputMask` for my `MTIBlendWithMaskFilter` here
})
```

Would appreciate your input regarding whether this is possible - or if you have an idea for an alternative solution to support dynamic masks! Thanks!

**Comment by YuAo** [comment]
No. You should use a `CVPixelBuffer`. If you do not want to update your CoreML model you can use `MLMultiArray. withUnsafeBytes` to access the buffer pointer and copy the buffer's content to a `CVPixelBuffer`.
