### ISSUE TITLE
Video Processing Memory Management Issue?

### ISSUE THREAD

**Issue by vjdaemp** [MetalPetal/MetalPetal#356]
"Video Processing" functionality in demo app may have memory management issue when video is looped.

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [ x I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version      | latest
 Integration Method      | demo app
 Platform & Version      | iOS 16.3.1
 Device                  | iPhone 14 pro

### Steps to Reproduce
Make the following modifications to `VideoProcessorView`:
* Change `videoPlayer` from `AVPlayer` to `AVQueuePlayer`
* Create `AVPlayerLooper` using `videoPlayer` and `playerItem`

```
            let playerItem = AVPlayerItem(asset: asset)
            playerItem.videoComposition = videoComposition.makeAVVideoComposition()
            self.videoComposition = videoComposition
            videoAsset = asset
            videoPlayer = AVQueuePlayer(playerItem: playerItem)
            playbackLooper = AVPlayerLooper.init(player: videoPlayer!, templateItem: playerItem)
            videoPlayer?.play()
```

### Expected behavior
I would expect memory footprint to remain relatively constant after each video loop occurs.

### Actual behavior
For the first two video loops, the memory foot print increases dramatically for each new loop. Then after this, the memory footprint remains constant for subsequent loops.

<img width="593" alt="Screenshot 2023-03-13 at 5 13 13 PM" src="https://user-images.githubusercontent.com/12041809/224866586-461dba8e-1c86-4c9e-81c0-d1f0a145699e.png">

@YuAo Is this memory behavior expected when introducing looping w/ the added MetalPetal effects? When the video processing effects are removed (and only the looping is added) the memory stays constant after each loop.

**Comment by YuAo** [comment]
The AVPlayerLooper may create and cache player items for gapless looping. You can verify this by inspecting the memory graph, and see if there're 3 player items.

**Comment by vjdaemp** [comment]
Thank you @YuAo
