### ISSUE TITLE
How to use metal-petal in Mac OS

### ISSUE THREAD

**Issue by seonghun-yang** [MetalPetal/MetalPetal#357]
### Checklist
- [ O ] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [ O ] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

AppKit
Xcode 14.2
IOS 16.3
IPhone X
minimum deploy target IOS 13, Mac OS 10.15

Very thanks for Metal-Petal.

I adapt metal-petal to my IOS app and it's very well work

And, I install metal-petal framework to my Mac OS app  using SPM and cocoapods

But, MTIImageView is not recognized in  my app.

How to use metal-petal in my Mac App ?

Thanks for you effort.

**Comment by YuAo** [comment]
MTIImageView is not available on macOS currently. You can create a CGImage from a MTIImage then use a NSImageView to display that image.

**Comment by seonghun-yang** [comment]
Very Thanks for your reply. I will adapt it to my app

**Comment by YuAo** [comment]
You can use the [PixelBufferPoolBackedImageRenderer](https://github.com/MetalPetal/MetalPetal/blob/f9b78897bd4214bb097f352a1bde0a4f4a1e2ddb/MetalPetalExamples/Shared/PixelBufferPoolBackedImageRenderer.swift) from the example project to get a CGImage along with a CVPixelBuffer from a MTIImage. It's more efficient by utilizing a CVPixelBufferPool.
