### ISSUE TITLE
iOS 16 Error: use of undeclared identifier 'metalpetal'

### ISSUE THREAD

**Issue by fazal-e-majid** [MetalPetal/MetalPetal#360]
hay @YuAo !

Shaders are throwing error on iOS 16 while working perfectly on other iOS versions. Here is a demo project [https://github.com/fazal-e-majid/MPDemo](https://github.com/fazal-e-majid/MPDemo)
Please have a look into the demo project. Thanks

### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] If possible, I've reproduced the issue using the `master` branch of this repo
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

### Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 MetalPetal Version      |  1.25.2
 Integration Method      |  CocoaPods
 Platform & Version      |  iOS 16+
 Device                  | MacBook Pro 15' / iPhone 11 + Simulator

### Steps to Reproduce
Create any of your custom filters the way I did in the demo project. It would run on iOS 16+.

### Expected behavior
should give an output.

### Actual behavior
It is returning nil.

**Comment by YuAo** [comment]
You need to update your `MTIShaderLib.swift` to match the corresponding version of MetalPetal. 

It's recommended to use a `.metal` file and `#include "MTIShaderLib.h"` if you are using CocoaPods.

**Comment by fazal-e-majid** [comment]
I prefer using that in the form of string with my custom shader.

Thanks @YuAo that did the job.
