### ISSUE TITLE
Adding a 3D LUT (.cube file) to a MTLTexture?

### ISSUE THREAD

**Issue by latenitefilms** [MetalPetal/MetalPetal#377]
### Checklist
- [x] I've read the [README](https://github.com/MetalPetal/MetalPetal/blob/master/README.md)
- [x] I've searched for [existing GitHub issues](https://github.com/MetalPetal/MetalPetal/issues)

I am currently playing around with [FxPlug](https://developer.apple.com/documentation/professional_video_applications/fxplug?language=objc) - the effects engine for Apple's Final Cut Pro and Motion.

I am currently exploring if I can use MetalPetal to apply a 3D LUT (i.e. a `.cube` file) to a `MTLTexture` in Swift.

It looks like I might be able to use `MTIColorLookupFilter()` to apply a LUT - but it looks like it only accepts a LUT as a `MTIImage` - not a LUT file.

So I'd need to use something like [CocoaLUT](https://github.com/Neil20170220/CocoaLUT) to convert the LUT file into an image. It looks like CocoaLUT can also generate Core Image Filters ([VVLUT1DFilter](https://github.com/videovillage/VVLUT1DFilter) / CIColorCube) from LUTs.

Have anyone played with using file-based LUTs with MetalPetal? Any words of wisdom?

**Comment by ronan18** [comment]
I used CocoaLUT to get a CI image filter from a .cube file:
```
let lut: LUT = LUT(from: Bundle.main.url(forResource: "TestLUT", withExtension: "cube")!)!
let cifilter = lut.coreImageFilterWithCurrentColorSpace()
```

Then to process the LUT:
```
  let filter = MTICoreImageUnaryFilter()
  filter.filter = cifilter
 filter.inputImage = inputImage
let result = filter.outputImage
```

**Comment by latenitefilms** [comment]
Amazing, thank you! Will check it out!

**Comment by rdev** [comment]
@latenitefilms you can use this function to load a `.cube` LUT into an `MTIImage` that can be used with the built-in `MTIColorLookupFilter`

```swift
import Foundation
import MetalPetal

func loadCubeLUT(from url: URL) -> MTIImage? {
  do {
    let data = try Data(contentsOf: url)
    let lines = String(data: data, encoding: .utf8)?.components(separatedBy: .newlines)
    var size = 0
    var values: [Float] = []

    for line in lines ?? [] {
      if line.hasPrefix("#") { continue }

      if line.lowercased().contains("lut_3d_size") {
        let components = line.components(separatedBy: " ")
        size = Int(components.last ?? "") ?? 0
      } else if !line.isEmpty {
        let components = line.components(separatedBy: " ").compactMap { Float($0) }
        values.append(contentsOf: components)
      }
    }

    guard size > 0, values.count == size * size * size * 3 else { return nil }

    // Expand the values to include alpha channel (1.0 for all entries)
    var rgbaValues: [Float] = []
    for i in stride(from: 0, to: values.count, by: 3) {
      rgbaValues.append(contentsOf: [values[i], values[i + 1], values[i + 2], 1.0])
    }

    let dataPointer = rgbaValues.withUnsafeBufferPointer { UnsafeRawPointer($0.baseAddress!) }
    let lutTextureDescriptor = MTLTextureDescriptor()
    lutTextureDescriptor.textureType = .type3D
    lutTextureDescriptor.pixelFormat = .rgba32Float
    lutTextureDescriptor.width = size
    lutTextureDescriptor.height = size
    lutTextureDescriptor.depth = size
    lutTextureDescriptor.usage = [.shaderRead, .shaderWrite]

    guard let device = MTLCreateSystemDefaultDevice(),
          let lutTexture = device.makeTexture(descriptor: lutTextureDescriptor)
    else {
      return nil
    }

    let region = MTLRegionMake3D(0, 0, 0, size, size, size)
    lutTexture.replace(region: region, mipmapLevel: 0, slice: 0, withBytes: dataPointer, bytesPerRow: size * 4 * MemoryLayout<Float>.size, bytesPerImage: size * size * 4 * MemoryLayout<Float>.size)

    return MTIImage(texture: lutTexture, alphaType: .alphaIsOne)
  } catch {
    print("Error loading .cube file: \(error)")
    return nil
  }
}
```

**Comment by latenitefilms** [comment]
Amazing, thank you very much!

**Comment by sagarthecoder** [comment]
Any update about this?
CocoaLut doesn't provide SPM support.
How to load cube file to use in  Lookup filter?
