### ISSUE TITLE
App crashing when loading filters

### ISSUE THREAD

**Issue by GustasBr** [MetalPetal/MetalPetal#38]
All of the questions were answered by YuAo and all of the solutions worked for me so I will ask one more about technical stuff.

I have photo editing application which is based on MetalPetal framework. The main question is why this application crashes for people who have iPhone 7 or iPhone 8 and better one. But for mine iPhone SE and my friend iPhone 6 it's working just great. It crashes when application starts loading 9 filters. I'm applying them on the same picture and then I'm keeping 9 UIImages.  Maybe the problem is memory? On my main screen with filters memory is around 100mb for me. (on iPhone SE)
For bigger screens it's 150mb. I don't know about iPhone 8 Plus.
I'm using unwind segues so after editing memory is always normal. Around 30-40mb.

Is it possible to do something to make it work great for every device?

P.S I'm using image compression tools. Size of the image is from 100kb to 1mb after compressing. And I edit only compressed images.

I don't know if it's necessary but there's my code. (Result after MetalPetal is GREAT. The only problem is that it's crashing for someone...)
`guard let thumbnail2 = original else { return }
        guard let cgImage = thumbnail2.cgImage else { return }
        guard let lookupimage1 = UIImage(named: "lookup_amatorka.png") else { return }
        guard let cgImage1 = lookupimage1.cgImage else { return }
        let filter1 = MTIColorLookupFilter()
        
        filter1.inputImage = MTIImage(cgImage: cgImage, options: [MTKTextureLoader.Option.SRGB: false]) // cia
        filter1.inputColorLookupTable = MTIImage(cgImage: cgImage1, options: [MTKTextureLoader.Option.SRGB: false]) // cia
        filter1.intensity = 0.6 // cia
        
        
        if let device = MTLCreateSystemDefaultDevice(),
            let outputImage = filter1.outputImage { //cia
            do {
                let context = try MTIContext(device: device)
                let filteredImage = try context.makeCGImage(from: outputImage)
                
                image1 = UIImage(cgImage: filteredImage)
                context.reclaimResources()
            } catch {
                print(error)
            }`

Any help would be appreciated. I hope this question is normal.

Thank you.

**Comment by YuAo** [comment]
Any crash log/report? We are currently using MetalPetal in very intensively and we have not encountered any similar problem.

**Comment by GustasBr** [comment]
@YuAo As I said I can't tell you the problem because I only have iPhone SE and Metal don't work with xCode Simulators. (I did some research on google they said it's normal). 

Also, I can't tell pixel size because it depends from the user what image he is editing. On my device every single image is working no matter if the size is big or not. 

Anyway, if you mentioned maybe there's any option how to handle HD images?
But something is really weird for me. I sent low resolution image for my friend and she said that it's still crashing on her iPhone 8. 

I'm really confused, buddy.

**Comment by YuAo** [comment]
Can't help if you cannot get any possible leads or crash reports. If you cannot get a test device, maybe you can try a third party crash report collect tool, for example https://fabric.io/
