### ISSUE TITLE
App crashing when loading filters

### ISSUE THREAD

**Issue by GustasBr** [MetalPetal/MetalPetal#39]
Good evening everyone.

Since my last topic was closed I'm creating the new one with additional information. 
Here's the link to me previous topic with the same problem: [https://github.com/MetalPetal/MetalPetal/issues/38](url)

I have photo editing application which is based on MetalPetal framework. The main question is why this application crashes for people who have iPhone 7 or iPhone 8 and better one. But for mine iPhone SE and my friend iPhone 6 it's working just great. 

UPDATE: 
Now I can tell you that **this problem is 100% not because of the memory.** I simply can't even IMAGINE why application crashes on iPhone 7 but works great on my iPhone SE.

So now I will tell you all the details to make sure you understand how everything works. 
First of all, user picks image from the camera roll. Then he sends it to another screen which is the main screen. (in my case viewController). Then there's one imageView which is the main one and 9 buttons. When user clicks on the button then filter is applied to UIImage. (You can see the example image1 which is UIImage) and then this UIImage is applied to imageView ( which is called in my case "pagrindinis". ( Also you can notice that I'm checking if user clicks on the filter the first time or not. Just to save memory when user clicks only on one filter and when he clicks again then there's no need to apply filter again because we already have UIImage. But that's not important I guess. )

**So, the problem is that somehow something is not working when I'm trying to apply filter on UIImage. (You can see the error that application found nil while unwrapping.)**

Maybe now there's any chance to help me? I would appreciate any help because you guys rock!

Now there's a screenshots of my error (first image) and the code where I apply image. ALSO, I will add code snippets to be easier to understand. 

![screen shot 2018-08-17 at 18 10 13](https://user-images.githubusercontent.com/18195248/44288369-cdf59880-a278-11e8-8d5f-1abd26641490.png)
![screen shot 2018-08-17 at 23 44 05](https://user-images.githubusercontent.com/18195248/44288379-d2ba4c80-a278-11e8-97fd-9cf4012138db.png)

My code snippet where I apply filter with MetalPetal:
`func pirmas() {
        guard let thumbnail2 = original else { return } // "original" is my UIImage from camera roll
        guard let cgImage = thumbnail2.cgImage else { return }
    guard let lookupimage1 = UIImage(named: "lookup_amatorka.png") else { return } // my lookup 
    guard let cgImage1 = lookupimage1.cgImage else { return }
    let filter1 = MTIColorLookupFilter()
    
    filter1.inputImage = MTIImage(cgImage: cgImage, options: [MTKTextureLoader.Option.SRGB: false]) 
    filter1.inputColorLookupTable = MTIImage(cgImage: cgImage1, options: [MTKTextureLoader.Option.SRGB: false]) 
    filter1.intensity = 0.6 
    
    
    if let device = MTLCreateSystemDefaultDevice(),
    let outputImage = filter1.outputImage { //cia
        do {
            let context = try MTIContext(device: device)
            let filteredImage = try context.makeCGImage(from: outputImage)
            image1 = UIImage(cgImage: filteredImage) // here's UIImage which I use later 
            
        } catch {
            print(error)
        }
    }
}`

Here you can see code snippet where I apply filter when user clicks on the button:
` @IBAction func teal1(_ sender: Any) {
        if firstTime == false {
            pirmas() // Here I call function which you can see above
            firstTime = true
        }
        self.pagrindinis.image = image1! // Here I get ERROR that my UIImage is nil
        pavadinimas = 1
}`

Someone please tell me why this solution is working with iPhone SE and iPhone 6 but not with iPhone 7 and higher.

If you need more information please tell me. I will tell you everything. 

Thank you so much!!!

**Comment by YuAo** [comment]
You need to figure out why the image is nil. Step into the pirmas function and see where it quits, or does it run into the catch block and what is the error it prints out.

**Comment by GustasBr** [comment]
@YuAo Excuse me for the new topic. It’s new for me. 
Speaking about the problem, I can’t understand how iPhone model can affect that image is nil?

**Comment by YuAo** [comment]
Can you debug? Step into the pirmas function and see where it quits, or does it run into the catch block and what is the error it prints out.
The iPhone model is not important, you should first figure out how your code executes.

**Comment by GustasBr** [comment]
@YuAo
I believe there's not much what I can do with this problem. I guess there's a problem with this framework. Did you tried colorlookuptables by yourself on iPhone 7 or 8?

For me, it's not crashing anymore but it still don't work on iPhone 7.

**Comment by YuAo** [comment]
We have all models of iPhone from 5s to X tested. Works perfectly. Maybe you can attach a sample project to demonstrate the problem?

**Comment by GustasBr** [comment]
@YuAo Oh then I'm confused. 

Yes, that would be perfect. Here's my sample project: 
[SimplyPerf.zip](https://github.com/MetalPetal/MetalPetal/files/2313700/SimplyPerf.zip)

**Comment by YuAo** [comment]
Two problems.

1. There's a problem about the color lookup table image. It uses a 16bpc(bit per component) pixel format. The `MTKTextureLoader` may not be able to load a cgimage in 16bpc format.

2. The color lookup table should be marked as `alphaIsOne`. Because it does not contain any transparent or semi-transparent pixel. This will save a unpremultiply operation.

I re-exported the color lookup table, make it a 8bpc, 72pixel/inch png image. And added the alpha type notation to your code. The modified project is attached. Everything should work fine now.

[SimplyPerf 2.zip](https://github.com/MetalPetal/MetalPetal/files/2313986/SimplyPerf.2.zip)
