### ISSUE TITLE
Any plans to add synchronised audio recording to Recorder

### ISSUE THREAD

**Issue by kallipigous** [MetalPetal/MetalPetal#40]
It would be lovely to be able to record audio along with the processed video. Are there any examples of that using the assetwriter with MetalPetal that does that?

**Comment by kallipigous** [comment]
I managed to adapt GPUImage's version to Metal petal and it seems to work.

**Comment by omarojo** [comment]
wow.. thats great.
share share :)



Omar Juarez • MDM. BSc.
Interactive Developer
omarojo.com

**Comment by kallipigous** [comment]
Will do. I just need to organize it a bit.

**Comment by kallipigous** [comment]
Here's a simplified version of the four classes I use for using filters and recording video and audio using metalPetal. GPUImage does some fancy timecode checking to make sure audio and video are in sync but I just append the audio and video as it arrives it seems to be fine. Perhapse with significant processing it will get out of sync,

[metalPetalVideoRecording.zip](https://github.com/MetalPetal/MetalPetal/files/2337282/metalPetalVideoRecording.zip)

**Comment by omarojo** [comment]
@kallipigous hey man just wanted to say thank you very much for sharing your implementation. It works pretty nice. Will see later when using other filters but so far so good :)

**Comment by kallipigous** [comment]
Lovely. Let me know if you spot anything. It seems to work for me processing with a long array of filters.
