### ISSUE TITLE
Bytes per row for initWithBitmapData assertion

### ISSUE THREAD

**Issue by SerjPridestar** [MetalPetal/MetalPetal#42]
Hello!

I had an old implementation of generating a video from a set of images using UIImages and CoreGraphics. I thought of improving performance by using Metal, and luckily stumbled upon your project!

The problem I'm facing is that a user picks a set of images from an ImagePicker and I get a set of `PHAssets` I request the `Data` of these `PHAssets` so that I could use as little memory as possible, moreover, `MTIImgage` could be initialized with `Data` given that you provide the `height` `width` `bytesPerRow` `pixelFormat` and `alphaInfo`. 

So I made this class:

```
class BitmapData {
	let data: Data
	let width: Int
	let height: Int

	var bytesPerRow: Int {
		return data.count / height
	}

	init(data: Data, width: Int, height: Int) {
		self.data = data
		self.width = width
		self.height = height
	}
} 
```

Now for bytesPerRow I realized there is an Assertion that:

`NSParameterAssert(data.length == height * bytesPerRow);`

As you can see from `BitmapData`, I made it into a computed variable to calculate that exactly. However, since this value must be an int, it loses some of its value if the result is a float/double and the assertion is never met. So here I'm stuck wondering, is the image data I'm using wrong? Is the constructor not supposed to be used in this use case? Or am I supposed to fetch the data in a different way? If you could please shed some light on this would be very grateful. Thank you!

PS: You might be wondering why I don't initialize a `CIImage` and construct a `MTIImage` from the `CIImage`. This is because I want to conserve as much memory as possible. As I want to improve the number of pictures that get drawn on a video, so I thought constructing a `MTIImage` from `Data` is the best and most optimized way of achieving this. Correct me if I'm wrong please.

**Comment by YuAo** [comment]
The data of a PHAsset is not bitmap data. It's the compressed image data with a JPG/PNG/GIF... container. So you cannot use the bitmap data constructor with it.

I think the idea of using `CIImage` is a ok.

You can also try to decode the image data yourself. One way to do that is generate a `CGImageRef` from the image data using `ImageIO.framework`. There's a piece of code in `-[MTIImageProperties initWithImageSource:index]` which does the similar work. (Data/URL -> CGImageSourceRef -> CGImageRef -> MTIImage). BTW, the `CGImageRef` constructor of the `MTIImage` uses `MTKTextureLoader` internally.

You can compare the costs(execution time/memory) of the two methods mentioned above, and choose the best that fits your needs.
