### ISSUE TITLE
Applying Transform Filter

### ISSUE THREAD

**Issue by SerjPridestar** [MetalPetal/MetalPetal#44]
The `outputImage` of a Transform Filter remains the same size of the `inputImage`. Is this an expected result? Because I expected the `outputImage` size to be bigger or smaller according to the Transform applied. 

Reading the code, I saw that it may be intentional since the `MTIRenderPassOutputDescriptor` and `MTIRenderCommand` are constructed with `inputImage` size. However, if that's the case how do you scale images to be bigger or smaller accordingly using MetalPetal?

ps: I was also wondering if it might be annoying for you to answer these questions here instead of Stackoverflow. I read the Contributing guidelines and I didn't see anything talking about asking questions or what type of issues are allowed to be opened here on Github. Thank you again much appreciated!

**Comment by YuAo** [comment]
The transform filter SHOULD have at least two output modes. 1. Output a image with the size of the input image. 2. Output a image with the size of the Minimum Enclosing Rectangle of the transformed image.

Currently only mode 1 is implemented.

I’ll try to add some other output modes to the transform filter, stay tuned.

**Comment by SerjPridestar** [comment]
Hello @YuAo, I was wondering if I could help out with the additional output modes? I have never implemented Metal code, but I'm pretty sure I could pull it off with some direction and guidance. I'll gladly work on it and submit a Pull Request

**Comment by YuAo** [comment]
Added a `viewport` property on the transform filter. See 30a46e86d675b819ee74496fc5d11dca7febb922

If you'd like to use the Minimum Enclosing Rectangle mode. Set the `viewport` property to the filter's `minimumEnclosingViewport` property after you set the `transform`.

**Comment by SerjPridestar** [comment]
@YuAo I will read over the code and try out the new output mode right now! No need for thanking me I did absolutely nothing. Thank you for implementing it and thank you for the great work you have done! <3
