### ISSUE TITLE
Running on iOS 10 simulator issue

### ISSUE THREAD

**Issue by iOS-altima** [MetalPetal/MetalPetal#45]
I know that iOS simulator doesn't support Metal.
But I need to test other features on iOS 10 simulator and can't start app. 
On iOS 11 and iOS 12 simulators app starts.

I get this error:

```
dyld: Library not loaded: /System/Library/Frameworks/MetalPerformanceShaders.framework/MetalPerformanceShaders
  Referenced from: /Users/Igor/Library/Developer/CoreSimulator/Devices/D3924F1D-AC68-4A71-BBDB-710DDB67948D/data/Containers/Bundle/Application/3A2F03A1-17E4-4128-B1D4-067A9C66B230/Unfold.app/Frameworks/MetalPetal.framework/MetalPetal
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/MetalPerformanceShaders.framework/MetalPerformanceShaders: mach-o, but not built for iOS simulator
```
 How can I fix this?

**Comment by erpapa** [comment]
simulator is not support.

**Comment by YuAo** [comment]
There seems no easy fix for this issue. Apple did not ship "MetalPerformanceShaders.framework" with the iOS 10 simulator. The only way to resolve this issue is try not to link that framework, which involves  lots of code change and conditional compile directives.
I'll look into this when time permits.

**Comment by iOS-altima** [comment]
Thank you!

**Comment by iOS-altima** [comment]
@YuAo Check, please, could https://github.com/xmartlabs/MetalPerformanceShadersProxy be useful for this fix?

**Comment by YuAo** [comment]
Nop.

**Comment by YuAo** [comment]
No.

**Comment by YuAo** [comment]
Fixed. (in version 0.9.5)

**Comment by YuAo** [comment]
Fixed. (in version 0.9.5)

**Comment by iOS-altima** [comment]
Thank you!
