### ISSUE TITLE
Using non-default samplers

### ISSUE THREAD

**Issue by obs1dium** [MetalPetal/MetalPetal#47]
I've been playing around with the lens blur filter and noticed that it tends to produce ugly artifacts near the image edges, especially when using a large blur radius.
Using samplers with their address mode set to 'mirror repeat' alleviates this.
However, simply setting the input images sampler is insufficient, as the filter generates intermediate images which appear to fall back to the default sampler.
I tried two things:
- explicitly 'forwarding' the input image's sampler in the filter to the intermediate images, i.e. calling imageWithSamplerDescriptor a bunch of times
- replacing the samplers in the shader code by 'properly' configured ones

Both approaches worked, but maybe there's a better way?

**Comment by YuAo** [comment]
Lens blur filter is not so much tuned so there may be other problems. The main idea is based on https://colinbarrebrisebois.com/2017/04/18/hexagonal-bokeh-blur-revisited/

I think both way is ok. I personally prefer the “fowarding” way. It gives the caller an opportunity to choose a different address mode (maybe clamp_to_edge works well too?)

You can send pull requests if you’d like to refine the lens blur filter.

**Comment by obs1dium** [comment]
I think 'clamp to edge' is the default, 'mirrored repeat' is really the only address mode that minimized edge artifacts for me.

**Comment by YuAo** [comment]
The default sampler address mode of MTIImage is “clamp to zero”. We think this is the most logical default address mode - when you read a pixel outside a image you get zero.

**Comment by obs1dium** [comment]
Ah, you're right, I was looking at the Metal language specs, not the MTISamplerDescriptor implementation.
