### ISSUE TITLE
Crash on Applying Overlay Filter

### ISSUE THREAD

**Issue by ayon115** [MetalPetal/MetalPetal#51]
I am trying to apply Overlay filter on a video with Metal Petal. Here's my code snippet. 

    `let mtiWatermarkImage = MTIImage(ciImage: waterMarkImage, isOpaque: false)
                let mtiFilter = MTIBlendFilter(blendMode: .overlay)
                mtiFilter.inputImage = mtiWatermarkImage

                let vcom = AVMutableVideoComposition(asset: composition) { request in
                    let source = MTIImage(ciImage: request.sourceImage, isOpaque: true)
                    mtiFilter.inputBackgroundImage = source
                    do {
                        if let output = mtiFilter.outputImage  {
                            let image = try mtiContext.makeCIImage(from: output)
                            request.finish(with: image, context: nil)
                        }
                    } catch let error {
                        request.finish(with: error)
                    }
                }`

It  crashes and throws the following error

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: { BOOL canAcceptAlphaType = YES; for (MTIImage *image in command.images) { if (![command.kernel.alphaTypeHandlingRule canAcceptAlphaType:image.alphaType]) { canAcceptAlphaType = NO; break; } } canAcceptAlphaType; }'

Can anyone enlighten me, what's wrong ?
Thanks in advance.

**Comment by YuAo** [comment]
Blend filters only accept images with unpremultiplied alpha. However a non-opaque CIImage based MTIImage's alpha type is premultiplied. You can either create the `MTIImage` with `MTICIImageRenderingOptions` and set the `alphaMode` to be `CIRenderDestinationAlphaUnpremultiplied`, or use `mtiWatermarkImage.imageByUnpremultiplyingAlpha()` to get a `MTIImage` with unpremultiplied alpha.

**Comment by ayon115** [comment]
Thank you very much @YuAo . Really appreciate your input on this.

**Comment by ayon115** [comment]
Sorry to bother again. It works after I made both images unpremultiplyingAlpha. And processing time is pretty good. But problem is, after exporting is complete, the result video is just black screen. Xcode shows this error, "Cannot render image (with an input Metal texture) using a opengles3 context".

**Comment by YuAo** [comment]
Try to pass the mtiContext.coreImageContext to request.finish(with: image, context: ...).

**Comment by ayon115** [comment]
Hi @YuAo, I am having a problem regarding my last conversation. I am using this to apply filter on video and things is pretty fast and working as expected for landscape videos. However, I am having a weird issue when I process any portrait mode video from iOS camera. It's throwing the following error when trying to generate CIImage from MTIImage. 

```
source extent = 0.0,0.0,304.0,541.0
transformed src size 304.0,541.0
mtl op size 304.0,541.0
extent after mtl processing = 0.0,0.0,304.0,541.0
2018-11-11 23:00:03.619519+0600 NewsHom[3942:152229] [api] -[CIContext(CIRenderDestination) _startTaskToRender:toDestination:forPrepareRender:error:] The image extent and destination extent do not intersect.
error = Error Domain=CIContextStartTask Code=4 "(null)" UserInfo={CINonLocalizedDescriptionKey=The image extent and destination extent do not intersect.}
```

My code snippet is below. 

```
let vcom = AVMutableVideoComposition(asset: composition) { request in
                    let sourceImage = MTIImage(ciImage: request.sourceImage.transformed(by: transform)).unpremultiplyingAlpha()
                    self.printRect(rect: sourceImage.extent)
                    print("transformed src size \(sourceImage.size.width),\(sourceImage.size.height)")
                    mtiFilter.inputBackgroundImage = sourceImage
                    do {
                        if let output = mtiFilter.outputImage  {
                            print("mtl op size \(output.size.width),\(output.size.height)")
                            self.printRect(rect: output.extent)
                            let image = try mtiContext.makeCIImage(from: output)
                            request.finish(with: image, context: mtiContext.coreImageContext)
                        }
                    } catch let error {
                        print("error = \(error)")
                        request.finish(with: error)
                    }
                }

```

I would really appreciate any help.

**Comment by HazarathReddy** [comment]
Hello,

I am also getting same issue 


**Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: { BOOL canAcceptAlphaType = YES; for (MTIImage *image in command.images) { if (![command.kernel.alphaTypeHandlingRule canAcceptAlphaType:image.alphaType]) { canAcceptAlphaType = NO; break; } } canAcceptAlphaType; }**


Here is my code

`  let input = MTIImage(ciImage: renderImg!)
            
            let filter = MTISaturationFilter()
            filter.saturation = 0
            filter.inputImage = input
            
            let outputImage = filter.outputImage`

**Comment by YuAo** [comment]
You need to handle the alpha type of your input image. Please see the alpha type section of the readme document. If your input image is opaque, it’s recommended to create the MTIImage with `isOpaque: false`. If it’s not opaque you may need to `unpremultiplingAlpha()`.
