### ISSUE TITLE
How to access the drawInMTKView cycle from MTIImageView class

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#53]
In your Demo "ImageRendererViewController.m" you use the method `draw(in view: MTKView)`
in order to re-draw the filtered image and have an animation (ie. saturationAndInvertTestOutputImage() ).  For that to work, you use a `MTKView`

But in the `CameraViewController.m` you use `MTIImageView` for rendering the frames by simply assigning the _.image_ var to it. 

I wanna use MTIImageView both for Camera Frames and Static images. But in order to animate on every draw cycle my static Images, I need to access the `drawInMTKView` method somehow. 

Is it possible if you add a callback or delegate method to `MTIImageView` so we can subscribe to each draw cycle ? :)

**Comment by YuAo** [comment]
`MTIImageView` is designed to display a `MTIImage` like a `UIImageView`. The internal render view (`MTKView`) is set to paused, so even if you can access the `drawInMTKView` method in `MTIImageView`, it will not be called at a fixed interval.

If you'd like to animate something you can use a `CADisplayLink`, or just like the `ImageRendererViewController` demo, use a `MTKView` directly. As you can see in the demo it is also very easy to render a `MTIImage` to the `MTKView`.
