### ISSUE TITLE
Image rendered from Camera Roll photo in wrong orientation

### ISSUE THREAD

**Issue by zhuhuihuihui** [MetalPetal/MetalPetal#54]
I'm getting different result rendering image locally and from camera roll. Very strange, I've confirmed that they're both showing correctly in a standard UIImageView

Here's the code to create and render MTIImage
```
// IMG_0059.jpg is camera roll photo exported as jpg format
let testImage = UIImage(named: "IMG_0059.jpg")!
self.testMTIImage = MTIImage(cgImage: testImage.cgImage!, options: [MTKTextureLoader.Option.SRGB: false], isOpaque: false)

public func draw(in view: MTKView) {
        do {
            try autoreleasepool {
                try self.context?.render(testMTIImage, toDrawableWithRequest: renderRequest)
            }
        } catch {
            print(error)
        }
    }
```

When UIImage is loaded locally, the result in correct orientation like this:
![](https://i.imgur.com/mt87leR.jpg)

When UIImage is loaded from camera roll, like this,
`self.testMTIImage = MTIImage(cgImage: /**UIImage from camera roll*/, options: [MTKTextureLoader.Option.SRGB: false], isOpaque: false)`
the result is rotated: 
![](https://i.imgur.com/fFQ596k.jpg)

**Comment by YuAo** [comment]
`UIImage`s have an `imageOrientation` property while `CGImage`s do not. So if you use the `cgImage` of an `UIImage` directly you may lose the orientation info.

It's not a problem with MetalPetal. If you simply use an `UIImage`'s `cgImage` to create another `UIImage` (`let image = UIImage(cgImage: testImage.cgImage)`) the result should be the same.

To fix the problem. You can:
A. Rotate the `cgImage` to the correct orientation before send it to MetalPetal.
B. Use a image filter to do the rotation (`MTITransformFilter` or `MTIUnaryImageRenderingFilter`).
C. Create a `CIImage` with `kCIImageProperties` correctly set and use that `CIImage` to create a `MTIImage`.

**Comment by omarojo** [comment]
@zhuhuihuihui I had the same issue, but looking into StackOverflow found this. 
You can create a ***UIImage+OrientationFix.swift*** file with the following and call .fixOrientation() before 
using your image.cgImage in MetalPetal.

**ie.**
```
var myImage = ...your UIImage from Camera Roll
myImage = myImage.fixOrientation()
var mtiLibStill = MTIImage(cgImage: myImage.cgImage!, isOpaque: true)
```

***UIImage+OrientationFix.swift***
```
import Foundation
import UIKit


public extension UIImage {
    
    /// Extension to fix orientation of an UIImage without EXIF
    func fixOrientation() -> UIImage {
        
        guard let cgImage = cgImage else { return self }
        
        if imageOrientation == .up { return self }
        
        var transform = CGAffineTransform.identity
        
        switch imageOrientation {
            
        case .down, .downMirrored:
            transform = transform.translatedBy(x: size.width, y: size.height)
            transform = transform.rotated(by: CGFloat(Double.pi))
            
        case .left, .leftMirrored:
            transform = transform.translatedBy(x: size.width, y: 0)
            transform = transform.rotated(by: CGFloat(Double.pi/2))
            
        case .right, .rightMirrored:
            transform = transform.translatedBy(x: 0, y: size.height)
            transform = transform.rotated(by: CGFloat(-Double.pi/2))
            
        case .up, .upMirrored:
            break
        }
        
        switch imageOrientation {
            
        case .upMirrored, .downMirrored:
            transform.translatedBy(x: size.width, y: 0)
            transform.scaledBy(x: -1, y: 1)
            
        case .leftMirrored, .rightMirrored:
            transform.translatedBy(x: size.height, y: 0)
            transform.scaledBy(x: -1, y: 1)
            
        case .up, .down, .left, .right:
            break
        }
        
        if let ctx = CGContext(data: nil, width: Int(size.width), height: Int(size.height), bitsPerComponent: cgImage.bitsPerComponent, bytesPerRow: 0, space: cgImage.colorSpace!, bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) {
            
            ctx.concatenate(transform)
            
            switch imageOrientation {
                
            case .left, .leftMirrored, .right, .rightMirrored:
                ctx.draw(cgImage, in: CGRect(x: 0, y: 0, width: size.height, height: size.width))
                
            default:
                ctx.draw(cgImage, in: CGRect(x: 0, y: 0, width: size.width, height: size.height))
            }
            
            if let finalImage = ctx.makeImage() {
                return (UIImage(cgImage: finalImage))
            }
        }
        
        // something failed -- return original
        return self
    }
}
```

**Comment by zhuhuihuihui** [comment]
@omarojo yeah, that's exactly what happened.

For people who are experiencing the same issue. If you're using 'UIImagePickerController' to get photos from camera roll, there's a chance that the image returned will be in wrong orientation. However if you just load that image into 'UIImageView', you won't notice it because 'UIImageView' somehow handles the orientation automatically for you. But if you're loading it into MTKView using MetalPetal, it does not handle the orientation issue automatically.

Ref:
https://stackoverflow.com/questions/5427656/ios-uiimagepickercontroller-result-image-orientation-after-upload

**Comment by YuAo** [comment]
Added a helper method in the latest version of MetalPetal.

```Objective-C
// Objective-C
MTIImage *orientedImage = [image imageByApplyingCGOrientation:orientation];
```
```Swift
// Swift
let orientedImage = image.oriented(orientation)
```
