### ISSUE TITLE
How to use this framework to create Instagram like filters

### ISSUE THREAD

**Issue by zhuhuihuihui** [MetalPetal/MetalPetal#55]
I've tried bunch of different filters. But none of them works like instagram filters directly. I believe it is possible to create instagram like filters using this framework. Any suggestions? 

Thanks!

**Comment by YuAo** [comment]
Instagram filters are more likely the combination of many basic operations. (color adjustments, overlays, algorithms like CLAHE, etc).

MetalPetal contains these basic operations. How to combine them to create wonderful filters is totally up to you.

You can start with "Color Adjustments" by using a color lookup table (with `MTIColorLookupFilter`). 
Refs:
https://github.com/MetalPetal/MetalPetal/blob/master/MetalPetalDemo/CameraViewController.m
https://developer.nvidia.com/gpugems/GPUGems2/gpugems2_chapter24.html
