### ISSUE TITLE
8 Warnings

### ISSUE THREAD

**Issue by iOS-altima** [MetalPetal/MetalPetal#57]
Hi! I have 8 warnings like:
no rule to process file '<my path>/Frameworks/MetalPetal/Shaders/BlendingShaders.metal' of type 'sourcecode.metal' for architecture 'x86_64' (in target 'MetalPetal')

Could you fix this or provide any suggestions?

**Comment by YuAo** [comment]
Xcode does not compile the .metal files for the simulator. You can safely ignore these warnings, since metal code won't run on a simulator.

**Comment by iOS-altima** [comment]
@YuAo I tried, not, app won't work in this case.
I found such solution:
https://stackoverflow.com/questions/46254475/ignore-metal-files-when-building-for-ios-simulator-target
But it requires changes in code.
What do you think, about of implementing this solution?
We keep our project free of any warnings and this 8 warnings quite ennoying.

**Comment by evanxlh** [comment]
I just removed `.metal` files from the `Compile Sources`, and it seems to work well.
