### ISSUE TITLE
Crashing when applying multiple filters

### ISSUE THREAD

**Issue by GustasBr** [MetalPetal/MetalPetal#58]
The only problem I have now is that I can't apply two built in filters on the same photo at the time. 
I think it's just that I'm doing something wrong. Here's how I do it:

```
`guard let originalPhotoEffectOne = original else { return }
        guard let cgImage = originalPhotoEffectOne.cgImage else { return }
        let filter1 = MTISaturationFilter()
        filter1.saturation = 0 
        filter1.inputImage = MTIImage(cgImage: cgImage, options: [MTKTextureLoader.Option.SRGB: false]) 
        if let device = MTLCreateSystemDefaultDevice(),
            let outputImage = filter1.outputImage { 
            do {
                let context = try MTIContext(device: device)
                let filteredImage = try context.makeCGImage(from: outputImage)
                let image1: UIImage? = UIImage(cgImage: filteredImage)
            } catch {
                print(error)
            }
        }
```
        
        guard let photoEffectTwo = image1 else { return }
        guard let cgImage2 = photoEffectOne.cgImage else { return }
        let filter2 = MTIExposureFilter()
        filter2.exposure = 0.8
        filter2.inputImage = MTIImage(cgImage: cgImage2, options: [MTKTextureLoader.Option.SRGB: false]) // cia
        
        if let device = MTLCreateSystemDefaultDevice(),
            let outputImage = filter2.outputImage { //cia
            do {
                let context = try MTIContext(device: device)
                let filteredImage = try context.makeCGImage(from: outputImage)
                let image1: UIImage? = UIImage(cgImage: filteredImage)
            } catch {
                print(error)
            }
        }`

**Comment by YuAo** [comment]
Where does the code crash? Any error message?

**Comment by GustasBr** [comment]
I only get Thread 1: Signal SIGABRT. My all of the outlets are connected so I don't know why it's crashing on this. If I'm editing only one time then everything works fine. Anyway, it's hard to understand this issue so I added my project. 
[SimplyPerf 2.zip](https://github.com/MetalPetal/MetalPetal/files/2708948/SimplyPerf.2.zip)


Also, one more question. (i don't want to spam ant add other new thread)
I'm using color lookups in all of my apps and it looks great. But sometimes ( i'm not saying that always, it depends from the picture i'm editing ) you can see what happens with colours in photo. What can cause this issue? When I'm creating colour lookups on Photoshop or any other program the same options looks good with the same picture. I would understand if both on the computer and phone app would be the same result but on computer everything is fine while on mobile sometimes this happens. (maybe color lookup render options is bad?) 
ColorLookup table rendering options:
Image format: PSD
Color space: sRGB
Bit depth: 8bits/component
Resolution: 72 pixels per inch
File format: PNG
Depth: 16

Photo: 
![img_1067](https://user-images.githubusercontent.com/18195248/50425547-f7a37980-0881-11e9-9b63-aef9eab3e208.jpg)

Anyway, if it's impossible to fix then it's alright. Thank you YuAo that you helped me in the past to make everything work. Happy holidays! <3

**Comment by YuAo** [comment]
I suggest you to add an "Exception Breakpoint", and update MetalPetal to the newest version.

The project triggers a NSParameterAssert, which indicates you there's some alpha type handling problem. Specifically, the color lookup filter only accepts non-premultiplied alpha type image, how ever the input image here may have a premultiplied alpha.

You can easily fix this problem by adding `.unpremultiplyingAlpha()` to the input image you generated.
`filter4.inputImage = MTIImage(cgImage: cgImage2, options: [MTKTextureLoader.Option.SRGB: false]).unpremultiplyingAlpha()`

If you believe that all your input images is opaque (do not have an alpha channel), you can use `MTIImage(cgImage: CGImage, options: [MTKTextureLoader.Option : Any]? = nil, isOpaque: Bool)`  to create image and set the isOpaque to true.

---

The color lookup table problem is weird. I run the demo project and everything looks fine here. Can you attach the source/unprocessed image of the photo you posted above? And another suggestion is to make a 8-bit depth color lookup table image.

**Comment by YuAo** [comment]
I've exported the color lookup table to Photoshop and apply it to the image you provided. Got the same  buggy result. It seems there's something wrong with the color lookup table image itself. There are visible artifacts along each color lookup plane, these edges should be smooth. Did you resize or compress the color lookup table?
*Yours*
<img width="452" alt="screen shot 2018-12-27 at 10 39 46 am" src="https://user-images.githubusercontent.com/1234944/50463039-1dd13280-09c4-11e9-8a24-1c3987f9768f.png">
*Should-be*
<img width="442" alt="screen shot 2018-12-27 at 10 43 08 am" src="https://user-images.githubusercontent.com/1234944/50463063-37727a00-09c4-11e9-9545-82c085f2ce46.png">

---
Exposure, contrast, saturation are in-fact color matrix operations. Ref https://docs.rainmeter.net/tips/colormatrix-guide/

**Comment by GustasBr** [comment]
@YuAo Also, how I could manage my memory when applying multiple filters? I think I'm using really bad technique when doing something like that below. When I'm playing with low resolution photo it's alright but when saving a full resolution photo then I get memory issues.

`func mainTask(completion: (_ success: Bool) -> Void) {
        // Do something
        guard let thumbnail2 = image else { return }
        guard let cgImage = thumbnail2.cgImage else { return }
        
        guard let lookupimage1 = UIImage(named: "lookup_\(photoOption.filter).png") else { return }
        guard let cgImage1 = lookupimage1.cgImage else { return }
        let filter1 = MTIColorLookupFilter()
        
        filter1.inputImage = MTIImage(cgImage: cgImage, options: [MTKTextureLoader.Option.SRGB: false]) // cia
        filter1.inputColorLookupTable = MTIImage(cgImage: cgImage1, options: [MTKTextureLoader.Option.SRGB: false], alphaType: .alphaIsOne) // cia
        filter1.intensity = photoOption.intensity
        
        
        if let device = MTLCreateSystemDefaultDevice(),
            let outputImage = filter1.outputImage { //cia
            do {
                let context = try MTIContext(device: device)
                let filteredImage = try context.makeCGImage(from: outputImage)
                image1 = UIImage(cgImage: filteredImage)
                
            } catch {
                print(error)
            }
        }
        // Call completion, when finished, success or faliure
        completion(true)
    }
    func firstTask(completion: (_ success: Bool) -> Void) {
        // Do something
        guard let originalPhotoEffectOne = image1 else { return }
        guard let cgImage2 = originalPhotoEffectOne.cgImage else { return }
        let filter7 = MTIHighPassSkinSmoothingFilter()
        filter7.amount = photoOption.skin
        filter7.inputImage = MTIImage(cgImage: cgImage2, options: [MTKTextureLoader.Option.SRGB: false]).unpremultiplyingAlpha()
        if let device = MTLCreateSystemDefaultDevice(),
            let outputImage = filter7.outputImage {
            do {
                let context = try MTIContext(device: device)
                let filteredImage = try context.makeCGImage(from: outputImage)
                image1 = UIImage(cgImage: filteredImage)
            } catch {
                print(error)
            }
        }
        // Call completion, when finished, success or faliure
        completion(true)
    }
    
    func secondTask(completion: (_ success: Bool) -> Void) {
        guard let originalPhotoEffectOne2 = image1 else { return }
        guard let cgImage4 = originalPhotoEffectOne2.cgImage else { return }
        let filter2 = MTISaturationFilter()
        filter2.saturation = photoOption.saturation
        filter2.inputImage = MTIImage(cgImage: cgImage4, options: [MTKTextureLoader.Option.SRGB: false]).unpremultiplyingAlpha()
        if let device = MTLCreateSystemDefaultDevice(),
            let outputImage = filter2.outputImage {
            do {
                let context = try MTIContext(device: device)
                let filteredImage = try context.makeCGImage(from: outputImage)
                image1 = UIImage(cgImage: filteredImage)
            } catch {
                print(error)
            }
        }
        completion(true)
    }
    func thirdTask(completion: (_ success: Bool) -> Void) {
        guard let originalPhotoEffectOne3 = image1 else { return }
        guard let cgImage5 = originalPhotoEffectOne3.cgImage else { return }
        let filter3 = MTIContrastFilter()
        filter3.contrast = photoOption.contrast
        filter3.inputImage = MTIImage(cgImage: cgImage5, options: [MTKTextureLoader.Option.SRGB: false]).unpremultiplyingAlpha()
        if let device = MTLCreateSystemDefaultDevice(),
            let outputImage = filter3.outputImage {
            do {
                let context = try MTIContext(device: device)
                let filteredImage = try context.makeCGImage(from: outputImage)
                image1 = UIImage(cgImage: filteredImage)
            } catch {
                print(error)
            }
        }
        completion(true)
    }
    func fourthTask(completion: (_ success: Bool) -> Void) {
        guard let originalPhotoEffectOne4 = image1 else { return }
        guard let cgImage6 = originalPhotoEffectOne4.cgImage else { return }
        let filter4 = MTIBrightnessFilter()
        filter4.brightness = photoOption.brightness
        filter4.inputImage = MTIImage(cgImage: cgImage6, options: [MTKTextureLoader.Option.SRGB: false]).unpremultiplyingAlpha()
        if let device = MTLCreateSystemDefaultDevice(),
            let outputImage = filter4.outputImage {
            do {
                let context = try MTIContext(device: device)
                let filteredImage = try context.makeCGImage(from: outputImage)
                image1 = UIImage(cgImage: filteredImage)
            } catch {
                print(error)
            }
        }
        
        completion(true)
    }
    func final() {
        guard let originalPhotoEffectOne5 = image1 else { return }
        guard let cgImage7 = originalPhotoEffectOne5.cgImage else { return }
        let filter5 = MTIVibranceFilter()
        filter5.amount = photoOption.vibrance
        filter5.inputImage = MTIImage(cgImage: cgImage7, options: [MTKTextureLoader.Option.SRGB: false]).unpremultiplyingAlpha()
        if let device = MTLCreateSystemDefaultDevice(),
            let outputImage = filter5.outputImage {
            do {
                let context = try MTIContext(device: device)
                let filteredImage = try context.makeCGImage(from: outputImage)
                image1 = UIImage(cgImage: filteredImage)
                let activityVC = UIActivityViewController(activityItems: [image1], applicationActivities: nil)
                activityVC.popoverPresentationController?.sourceView = self.view
                
                self.present(activityVC, animated: true, completion: nil)
                
            } catch {
                print(error)
            }
        }
    }
    
    @objc func highResPressed (sender: UIButton)
    {
        mainTask { (success) -> Void in
            if success {
                // do second task if success
                firstTask { (success) -> Void in
                    if success {
                        // do second task if success
                        secondTask { (success) -> Void in
                            if success {
                                // do second task if success
                                thirdTask { (success) -> Void in
                                    if success {
                                        // do second task if success
                                        fourthTask { (success) -> Void in
                                            if success {
                                                // do second task if success
                                                final()
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }`

**Comment by YuAo** [comment]
The trick here is try not to render if possible. You render every task to a CGImage, that makes MetalPetal hard to reuse the intermediate texture (because you render them out and create CGImages). You can try to make you tasks create `MTIImage`s instead of `CGImage`s, and render that `MTIImage` only if you need to save the image to disk or display that image on your UI. After each render you can call `reclaimResources()` on your context to release any unused intermediate texture.

**Comment by GustasBr** [comment]
> The trick here is try not to render if possible. You render every task to a CGImage, that makes MetalPetal hard to reuse the intermediate texture (because you render them out and create CGImages). You can try to make you tasks create MTIImages instead of CGImages, and render that MTIImage only if you need to save the image to disk or display that image on your UI. After each render you can call reclaimResources() on your context to release any unused intermediate texture.

Amazing.. Works like a charm! Thank you so much, I hope I will not bother you more with my questions.
