### ISSUE TITLE
Failed to render image (Fritz.ai)

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#63]
Hi YuAo, 

Im trying to render CVPixelBuffers coming from a style transfer framework called Fritz.ai
```
func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
     let image = FritzVisionImage(buffer: sampleBuffer)
     model.predict(image) { (stylizedBuffer, error) in
        guard let stylizedBuffer = stylizedBuffer else { return }
        var outputImage =   MTIImage.init(cvPixelBuffer: stylizedBuffer, alphaType: .alphaIsOne)
        DispatchQueue.main.async(execute: {
            self.renderView?.image = outputImage
        })
     }
}
```

I can preview **stylizedBuffer** in the Xcode debugger and the image looks fine. But once I try to render, it fails. 

`<MTIImageView: 0x141dbf580; frame = (0 0; 375 812); autoresize = W+H; layer = <CALayer: 0x282bf0ec0>>: Failed to render image <MTIImage: 0x283187200; width = 480; height = 640; depth = 1; cachePolicy = 1; promise = <MTICVPixelBufferPromise: 0x2808864e0>> - Error Domain=MTICVMetalTextureBridgeErrorDomain Code=10001 "(null)"`

Any idea what could be the reasons it cant render ?

**Comment by YuAo** [comment]
If you lookup `MTICVMetalTextureBridgeErrorDomain`, you'll see error `1001` is `ImageBufferIsNotBackedByIOSurface`.

It seems the pixel buffer is not backed by an IOSurface, so it cannot be used to create a metal texture directly.

You can try using the CoreImage to render that buffer. Using `MTIImage.init(cvPixelBuffer pixelBuffer: CVPixelBuffer, renderingAPI: MTICVPixelBufferRenderingAPI, alphaType: MTIAlphaType)`, and pass `.coreImage` to the renderingAPI parameter.

Or you can use `VTCreateCGImageFromCVPixelBuffer` to create a `CGImage` from the pixel buffer and use the `CGImage` to create a `MTIImage`.

**Comment by omarojo** [comment]
Thank you 👍 ... I used:

MTIImage(cvPixelBuffer: pixelBuffer, options: MTICVPixelBufferRenderingOptions.init(renderingAPI: MTICVPixelBufferRenderingAPI(rawValue: 2)!, sRGB: false), alphaType: .alphaIsOne)

That worked fine.
I wonder if that is less efficient or if it affects negatively the performance. Im using an iPhoneX and runs pretty well. But I just wonder...

**Comment by YuAo** [comment]
Yes it is less efficient than a IOSurface backed pixel buffer. But you should still be able to run that in real-time.

BTW, you can use `.coreImage` instead of the raw value thing `MTICVPixelBufferRenderingAPI(rawValue: 2)!`
