### ISSUE TITLE
Any plans to add ARKit compatibility

### ISSUE THREAD

**Issue by migueliOS** [MetalPetal/MetalPetal#65]
Is there any way to integrate something similar to this
https://developer.apple.com/documentation/arkit/displaying_an_ar_experience_with_metal

Or 
https://developer.apple.com/documentation/arkit/creating_face-based_ar_experiences

**Comment by YuAo** [comment]
MetalPetal is not going to develop to a full feature 3d engine. 
However it is very easy to integrate SceneKit with MetalPetal. You can use SceneKit to render the ar scene, for every frame you can tell SceneKit to render that scene to a CVPixelBuffer. Then you can use the CVPixelBuffer with MetalPetal.

Here's a sample scene renderer that render a SCNScene to a CVPixelBuffer.
[MTISCNSceneRenderer.zip](https://github.com/MetalPetal/MetalPetal/files/2873864/MTISCNSceneRenderer.zip)

I'll consider adding this to the framework.

**Comment by migueliOS** [comment]
That sounds great, thank you.  I will play with this proposal and see how it goes.

**Comment by YuAo** [comment]
The idea is very similar with https://github.com/YuAo/YUSCNSceneCIRenderExtension , for your reference, but it comes with Metal.

**Comment by YuAo** [comment]
Integrated SceneKit support into the framework. 58abfe1f79ba673f7804c28ba9c8b04765fefcec

After a few lines of code, we are able to directly integrate SceneKit's renderer into MetalPetal. You can now create a MTIImage from the SCNScene directly, without using a pixel buffer. Better performance and memory usage.

See the "Working with SceneKit" demo. https://github.com/MetalPetal/MetalPetal/blob/master/MetalPetalDemo/SceneKitViewController.swift

**Comment by migueliOS** [comment]
That is amazing. Thank you, cant wait to try it.
