### ISSUE TITLE
Is it possible do Download Filters from the cloud ?

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#66]
I was wondering if there is a way to implement Metal Shaders downloaded from a server. 
Im trying to get my head around how .metal files work. but Im not sure if this could be possible. Any insights or ideas for a possible implementation ?

**Comment by YuAo** [comment]
It is possible. You can download the `.metallib` contains the shader from the server. You can even download a `.js` file and load the filter logic in that file. See https://github.com/MetalPetal/MetalPetalJS

**Comment by YuAo** [comment]
@omarojo I updated the MetalPetalJS project with the downloadable renderer demo.
