### ISSUE TITLE
MTIColorLookupFilter error result

### ISSUE THREAD

**Issue by hoangdado** [MetalPetal/MetalPetal#67]
I test the MTIColorLookupFilter with the default lookup image [lookup.png](https://github.com/BradLarson/GPUImage/blob/master/framework/Resources/lookup.png) on Iphone 6 iOS 9.3.1 but the result image was strange as below image. When I tried to test on Iphone 6 iOS 12.0 the result was correct as I expected. Please help me to fix it!
![photo_2019-02-25_10-00-45](https://user-images.githubusercontent.com/3702592/53311780-d0e6db00-38e4-11e9-9ea5-9eb0946b9ca7.jpg)

**Comment by YuAo** [comment]
The “MTKTextureLoader” load images upside down on iOS9. You can use the custom texture loader in MetalPetal to fix this. See 
https://github.com/MetalPetal/MetalPetal/blob/master/Frameworks/MetalPetal/MTITextureLoaderForiOS9.h
