### ISSUE TITLE
Convert SurfaceBlur kernel to custom filter in MetalPetal

### ISSUE THREAD

**Issue by ZkHaider** [MetalPetal/MetalPetal#68]
How would I go about converting the following custom kernel to a metal petal filter in a pipeline?

```c++
float normpdf(in float x, in float sigma)
{
    return 0.39894*exp(-0.5*x*x/(sigma*sigma))/sigma;
}

float normpdf3(in vec3 v, in float sigma)
{
    return 0.39894*exp(-0.5*dot(v,v)/(sigma*sigma))/sigma;
}

kernel vec4 filterKernel(sampler inputImage, float bsigma) {
    const int SAMPLES_COUNT = MACRO_SAMPLES_COUNT;

    float GAUSSIAN_WEIGHTS[SAMPLES_COUNT];
    MACRO_SETUP_GAUSSIAN_WEIGHTS
    /*
        float sigma = float(kSize);
        for (int j = 0; j <= kSize; ++j)
        {
            GAUSSIAN_WEIGHTS[kSize+j] = GAUSSIAN_WEIGHTS[kSize-j] = normpdf(float(j), sigma);
        }
    */

    const int kSize = (SAMPLES_COUNT-1)/2;
    vec3 finalColor = vec3(0.0);

    vec3 c = sample(inputImage,samplerCoord(inputImage)).rgb;

    float Z = 0.0;

    vec3 cc;
    float factor;
    float bZ = 1.0/normpdf(0.0, bsigma);

    for (int i=-kSize; i <= kSize; ++i)
    {
        for (int j=-kSize; j <= kSize; ++j)
        {
            cc = sample(inputImage,samplerTransform(inputImage, destCoord().xy + vec2(float(i),float(j)))).rgb;
            factor = normpdf3(cc-c, bsigma)*bZ*GAUSSIAN_WEIGHTS[kSize+j]*GAUSSIAN_WEIGHTS[kSize+i];
            Z += factor;
            finalColor += factor*cc;
        }
    }

    return vec4(finalColor/Z, 1.0);
}
```

☝️ The following kernel exists in your old repo `Vivid` and I'd like to move into a `.metal` file. You were also computing the gaussian weights during runtime and injecting it via a string which is probably not efficient.

**Comment by ZkHaider** [comment]
@YuAo how would you suggest I go about tackling this myself?

**Comment by YuAo** [comment]
You can try to just convert the shader code to metal shader code. Subclass MTIUnaryImageRenderingFilter. Using `MTIVector` to pass GAUSSIAN_WEIGHTS as `device float *`.
 Pass SAMPLES_COUNT as Int32. To improve performance, consider using function constants to pass the SAMPLES_COUNT value.

**Comment by ZkHaider** [comment]
I believe a `CIColorKernel` is different from say `fragment float4 function(...)` in Metal. Wouldn't the performance be subpar in a fragment shader given the two for loops you are utilizing?

Thanks for the update YuAo.

**Comment by YuAo** [comment]
For the first question, yes, however they share the same idea. A `CIColorKernel` and a fragment shader both run once per pixel, and you need to return the new color for that pixel.

For the second one, the two loops will be a performance subpar, unless you made the loop counter `kSize` a function constant. Making the loop counter a function constant allows the back-end shader compiler aware of the loop count and compile the specialized function when you create the render pipeline.

**Comment by YuAo** [comment]
@ZkHaider take a look at https://github.com/MetalPetal/SurfaceBlur
