### ISSUE TITLE
Custom Filter: parameters() method in Swift wont get called

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#69]
Im making a custom filter subclassing **MTIUnaryImageRenderingFilter**
But the parameters method is not called like in the Pixellate example.

Im getting: 
```validateFunctionArguments:3469: failed assertion `Fragment Function(prismoj): missing buffer binding at index 0 for time[0].'```

Here's the filter class:

import UIKit
import MetalPetal
```
class G8PrismOJ_sh: MTIUnaryImageRenderingFilter {
    var time: Float
 
    override init() {
        time = Float(1.0)
        super.init()
    }

    override class func fragmentFunctionDescriptor() -> MTIFunctionDescriptor {
        let bundle = Bundle(for: G8PrismOJ_sh.self)
        let metalLibraryUrl = bundle.url(forResource: "default", withExtension: "metallib")
        return MTIFunctionDescriptor(name: "prismoj", libraryURL: metalLibraryUrl)
    }

    func parameters() -> [String : Any?] {
        return [
        "time": MTIVector(x: time, y: time)
        ]
    }
}
```

I actually would like to pass **time** as a Float but I dont know if it will get accepted by the shader.
But anyways, the parameters() function is not called, maybe Im translating wrong from ObjC to Swift based in the Pixellate example.

**Comment by YuAo** [comment]
The `parameters` is a "property" not a method.

**Comment by omarojo** [comment]
So right !!! Thank you :)
