### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by YuAo** [MetalPetal/MetalPetal#70]
- [x] Parameter passing
- [ ] SRGB/LinearRGB #62 
- [x] More examples and screenshots
- [x] SceneKit integration
- [x] iOS 9 texture loader
- [x] JavaScript extension

**Comment by orchidfire** [comment]
Could you add an example in documentation where you iterate over pixels with Metal?

**Comment by YuAo** [comment]
@orchidfire You can do that by subclassing `MTIUnaryImageRenderingFilter`, provide your own shader function to modify pixels. https://github.com/MetalPetal/MetalPetal#simple-single-input--output-filters 

```Swift
//Swift

class CustomFilter: MTIUnaryImageRenderingFilter {   
    override class func fragmentFunctionDescriptor() -> MTIFunctionDescriptor {
        return MTIFunctionDescriptor(name: "yourShader", libraryURL: MTIDefaultLibraryURLForBundle(Bundle.main))
    }
}
```

```cpp
// Shader

#include "MTIShaderLib.h"
using namespace metalpetal;

fragment float4 yourShader( 
        VertexOut vertexIn [[ stage_in ]],
        texture2d<float, access::sample> colorTexture [[ texture(0) ]],
        sampler colorSampler [[ sampler(0) ]]) 
{
    float4 color = colorTexture.sample(colorSampler, vertexIn.textureCoordinate);
    //modify color
    return color;
}
```

**Comment by vjdaemp** [comment]
Could you please add example to register a custom `MTIBlendMode` ?

**Comment by YuAo** [comment]
@vjdaemp The suggestion is to use `MTIBlendFunctionDescriptors(blendFormula:)` to create a `MTIBlendFunctionDescriptors` object and use that to register you custom blend using `MTIBlendModes.registerBlendMode(_:with:)`.

Be sure to call `MTIBlendModes.registerBlendMode(_:with:)` before you perform any rendering.

Here's the documentation of blend formula: https://github.com/MetalPetal/MetalPetal/blob/b2777373279529371e8b77d9344c67e09037f67b/Frameworks/MetalPetal/MTIBlendModes.h#L68-L93

Here's a example: https://github.com/MetalPetal/MetalPetal/blob/b2777373279529371e8b77d9344c67e09037f67b/Tests/MetalPetalTests/RenderTests.swift#L1012-L1019

**Comment by vjdaemp** [comment]
Thank you @YuAo , that helped me get custom `MTIBlendMode` working.
