### ISSUE TITLE
Bulge Distort Feature Request

### ISSUE THREAD

**Issue by MarkShippen** [MetalPetal/MetalPetal#71]
Hi, 

I would like to request a new type of filter for "Bulge Distortion".

Basically the filter is broke into 2 filters

Bulge FIlter 1
==========

Input a point & radius onto an image where by all pixels within the radius stretch towards or away from the centre point based on a factor which adjusts the stretchiness of the bulge based on distance from the centre

Input Parameters
-------------------
1) Radius - FLOAT  Length
2) Centre - POINT -  Centre of circle - X & Y within the image
3) Scale - FLOAT - Amount to Distort the image Range ( -1 to 1) - .... 0 would have no effect on the image ( negative range stretches image towards the centre ) - ( positive range stretches image away from centre )

-------------------------------------------------------------------

Bulge Filter 2 
===========
Instead of distorting inside the radius along towards the centre point like filter 1, Filter 2 distorts the image along a line that runs through the centre point. See Bulge Filter 2 in diagram link below to show of the bulge effect runs along the line and not the centre.

1) Radius - FLOAT  Length
2) Centre - POINT -  Centre of circle - X & Y within the image
3) Scale - FLOAT - Amount to Distort the image Range ( -1 to 1) - .... 0 would have no effect on the image ( negative range stretches image towards the line ) - ( positive range stretches image away from line )
4) Angle - FLOAT - Degrees amount to adjust the line through the centre ( SEE Pink Line in Bulge Filter 2 on Diagram )

See Diagram [https://imgur.com/a/6Kk3JEy](url) for visual representation of the 2 filters.

For reference Filter 1 Operates exactly the way the Buldge Filter works in the GPUImageBulgeDistortionFilter filter on  Brad Larsons GPUImage [https://github.com/BradLarson/GPUImage](url) 

Keep up the good Work!

Regards
Mark

**Comment by YuAo** [comment]
We already have the "Bulge FIlter 1" https://github.com/MetalPetal/MetalPetal/blob/master/Frameworks/MetalPetal/Filters/MTIBulgeDistortionFilter.h

**Comment by MarkShippen** [comment]
Oh Yeah, Great! I see it was added 15 days ago ... Would it be possible to make the 2nd Filter on the request? ( Bulge along a line instead of the centre of the radius )?

**Comment by YuAo** [comment]
Super busy these days. Will look into that when time permits. However it is easy to implement that yourself if you could just follow the implementation of MTIBulgeDistortionFilter and do some math.

**Comment by YuAo** [comment]
@MarkShippen 

I'm not sure about adding the `Bulge Filter 2` filter to the MetalPetal library. It is more like a filter fits your particular needs than a "general"/"standard" filter. For now, I think it's better to implement this filter in your own app/library.

Nevertheless, here's the shader code you need.

```

    fragment float4 bulgeDistortion(VertexOut vertexIn [[stage_in]],
                                    texture2d<float, access::sample> sourceTexture [[texture(0)]],
                                    sampler sourceSampler [[sampler(0)]],
                                    constant float & scale [[ buffer(0) ]],
                                    constant float & radius [[ buffer(1) ]],
                                    constant float2 & center [[ buffer(2) ]]
                                    constant float & angle [[ buffer(3) ]]) {
        float2 textureSize = float2(sourceTexture.get_width(), sourceTexture.get_height());
        float2 textureCoordinate = vertexIn.textureCoordinate;
        
        float2 texturePixelCoordinate = textureCoordinate * textureSize;
        float dist = distance(texturePixelCoordinate, center);
        
        if (dist < radius) {
            texturePixelCoordinate -= center;
            float cr = cos(angle);
            float sr = sin(angle);
            float2x2 rotm = float2x2(float2(cr,-sr),float2(sr,cr));
            
            texturePixelCoordinate = rotm * texturePixelCoordinate;
            
            float r = sqrt(radius * radius - texturePixelCoordinate.x * texturePixelCoordinate.x);
            float d = abs(texturePixelCoordinate.y);
            float percent = 1.0 - ((r - d) / r) * scale;
            texturePixelCoordinate.y *= percent;
            
            texturePixelCoordinate = texturePixelCoordinate * rotm;
            
            texturePixelCoordinate += center;
            textureCoordinate = texturePixelCoordinate / textureSize;
        }
        
        return sourceTexture.sample(sourceSampler, textureCoordinate);
    }
```

**Comment by MarkShippen** [comment]
Ok, Thanks Really appreciate it!
