### ISSUE TITLE
Is possible to render to MTLTexture?

### ISSUE THREAD

**Issue by XieLinhua** [MetalPetal/MetalPetal#72]
Hello, MetalPetal is a high performance image filter. Currently, it supports to render to CVPixelBuffer, render to MTKView.  I try to render to MTLTexture, but I failed. Could you please give me any suggestions? 

Many thanks!

**Comment by YuAo** [comment]
With the current implementation, the best way to get the `MTLTexture` from a `MTIImage` is to first render that image to a `CVPixelBuffer`, then create a `MTLTexture` from the `CVPixelBuffer` using `IOSurface`.

```
let ioSurface = CVPixelBufferGetIOSurface(pixelBuffer)
let texture = device.makeTexture(descriptor: desc, iosurface: iosurface, plane: 0)
```

There's some overhead, but should be very low.

BTW. Can you explain your use case here? How you'd like to use the texture? Maybe we can find a more suitable/efficient way.

**Comment by EvanXieCN** [comment]
@YuAo Thanks for your so quick reply.  My use case is: I use **MetalPetal** to add filters for the camera 4K CVPixelBuffer output, then render filtered MTIImage to the SCNNode material texture. 

For example:

```
    let descriptor = MTLTextureDescriptor.texture2DDescriptor(pixelFormat: .bgra8Unorm, width: 3840, height: 2160, mipmapped: true)
        descriptor.usage = [.renderTarget, .shaderRead, .shaderWrite]
        sphereTexture = device.makeTexture(descriptor: descriptor)
        
        let sphere = SCNSphere(radius: 5)
        sphere.segmentCount = 90
        sphereNode.geometry = sphere
        sphereNode.geometry?.firstMaterial?.diffuse.contents = sphereTexture
        sphereNode.geometry?.firstMaterial?.isDoubleSided = false
        sphereNode.geometry?.firstMaterial?.cullMode = .front
        sphereNode.position = SCNVector3(x: 0, y: 0, z: 0)
        scene.rootNode.addChildNode(sphereNode)
```

When MetalPetal finishes filtering pixelbuffer, then render to sphereTexture, the SCNView can display the final effect.

**Comment by YuAo** [comment]
Based on your use case. I think you can follow the suggestion I made. The `CVPixelBufferGetIOSurface ` and the `makeTexture` call should be very fast. Closing this issue for now.
