### ISSUE TITLE
[MTIVertex]Can I custom the vertices data passing to vertex shader?

### ISSUE THREAD

**Issue by EvanXieCN** [MetalPetal/MetalPetal#73]
MTIVertex contains `position` and `textureCoordinate `, in my case, I need add one more component `color`, is it possible? 
```
struct MTIVertex {
    vector_float4 position;
    vector_float2 textureCoordinate;
};
```

**Comment by YuAo** [comment]
Yes, just create a class that implements `MTIGeometry` protocol. Use `MTIRenderCommand` to create draw calls and `MTIRenderCommand.imagesByPerformingRenderCommands(....)` to filter image.

See `MTIVertex`'s implementation for reference.

**Comment by EvanXieCN** [comment]
@YuAo Thank you very much.
