### ISSUE TITLE
Best way to export the recorded video with the metal filter applied?

### ISSUE THREAD

**Issue by AA-BMDI** [MetalPetal/MetalPetal#74]
How do I export my video with the metal petal filter applied in a .mp4 file? I'm not too sure where to start.

**Comment by YuAo** [comment]
Just like how you would do it normally with `AVAssetReader` and `AVAssetWriter`. Apply filter to the pixel buffer the asset reader reads out and send the filtered buffer to the asset writer.

Or use something like https://github.com/rs/SDAVAssetExportSession which has a delegate callback for you to apply your filter while export the video.

Or use `AVAssetExportSession`with `-[AVVideoComposition videoCompositionWithAsset:applyingCIFiltersWithHandler:]` and process the `CIImage` with MetalPetal.

**Comment by AA-BMDI** [comment]
> Just like how you would do it normally with `AVAssetReader` and `AVAssetWriter`. Apply filter to the pixel buffer the asset reader reads out and send the filtered buffer to the asset writer.
> 
> Or use something like https://github.com/rs/SDAVAssetExportSession which has a delegate callback for you to apply your filter while export the video.
> 
> Or use `AVAssetExportSession`with `-[AVVideoComposition videoCompositionWithAsset:applyingCIFiltersWithHandler:]` and process the `CIImage` with MetalPetal.

Is there an example in the demo project codebase? Or do you have something you could share?

**Comment by YuAo** [comment]
No. What we are using for video read/write is close source currently, I can not share that here.

https://github.com/rs/SDAVAssetExportSession is a good example. You just need to implement the delegate method `- (void)exportSession:(SDAVAssetExportSession *)exportSession renderFrame:(CVPixelBufferRef)pixelBuffer withPresentationTime:(CMTime)presentationTime toBuffer:(CVPixelBufferRef)renderBuffer`
