### ISSUE TITLE
Main thread issues

### ISSUE THREAD

**Issue by AA-BMDI** [MetalPetal/MetalPetal#75]
Essentially, as you know, in the AVCaptureVideoDataOutputSampleBufferDelegate, we apply the MTIFilter to the sample buffer, and set the MTIImageView image as the filter output image. And we do the image set on the main thread as seen below. 
` DispatchQueue.main.async {
            self.renderView?.image = renderedImage
        }`

My issue is, whenever we use a collection view with horizontal scrolling on top of the Metal Image View, when the user interacts with the collection view (.ie scrolls), it freezes the setting of the MTIImage to the MTIImageView, and the video then appears to the user as if it is freezing. Do you guys have a solution for this? Or a work around?

**Comment by AA-BMDI** [comment]
@YuAo Could you give a bit more of an example for rendering in the background?

**Comment by YuAo** [comment]
Oh. You use a CADisplayLink! Did you set the runloop mode to include UITrackingRunloopMode? See: https://stackoverflow.com/questions/2524347/cadisplaylink-stops-updating-when-uiscrollview-scrolled

**Comment by AA-BMDI** [comment]
@YuAo , you're a hero. thanks.solved.
