### ISSUE TITLE
The image from SceneKit is darker than normal

### ISSUE THREAD

**Issue by protosse** [MetalPetal/MetalPetal#76]
i try to integrate SceneKit's renderer into MetalPetal and follow the demo https://github.com/MetalPetal/MetalPetal/blob/master/MetalPetalDemo/SceneKitViewController.swift
this is my code, i use ARSCNView
``` Swift
    func session(_ session: ARSession, didUpdate frame: ARFrame) {
        let rect = CGRect(x: 0, y: 0, width: 1080, height: 1920)
        let sceneImage = self.sceneRenderer.snapshot(atTime: frame.timestamp, viewport: rect, pixelFormat: MTLPixelFormat.unspecified, isOpaque: false).unpremultiplyingAlpha()
        renderView.image = sceneImage
    }
```
but i found the image is darker than normal.
![IMG_1511](https://user-images.githubusercontent.com/30048222/55871996-7668bc00-5bbe-11e9-8e1a-c2047b4bfa5b.PNG)
the normal image:
![IMG_1512](https://user-images.githubusercontent.com/30048222/55872101-bcbe1b00-5bbe-11e9-8e09-a96ad26fa783.PNG)

**Comment by YuAo** [comment]
How about setting the pixel format to `bgra8Unorm_srgb`?

**Comment by protosse** [comment]
> How about setting the pixel format to `bgra8Unorm_srgb`?

same result.

**Comment by protosse** [comment]
later i change the renderView to GPUImageView, it is also darker.
```Swift
    func session(_ session: ARSession, didUpdate frame: ARFrame) {
        let rect = CGRect(x: 0, y: 0, width: 1080, height: 1920)
        try? self.sceneRenderer.render(atTime: frame.timestamp, viewport: rect) { buffer in
            let image = CIImage(cvImageBuffer: buffer)
            let ref = CIContext(options: nil).createCGImage(image, from: image.extent)
            let picture = GPUImagePicture(cgImage: ref)
            picture?.processImage()
            picture?.addTarget(self.gpuRenderView)
        }
    }
```

**Comment by YuAo** [comment]
Can you attach a demo project?

**Comment by protosse** [comment]
> Can you attach a demo project?

[ARKitGPUImage.zip](https://github.com/MetalPetal/MetalPetal/files/3067112/ARKitGPUImage.zip)

**Comment by YuAo** [comment]
SceneKit renders the scene in a linear rgb color space. You need to set the renderView's color pixel format to `bgra8Unorm_srgb`. 
```
renderView.colorPixelFormat = .bgra8Unorm_srgb
```

Or add the `MTILinearToSRGBToneCurveFilter` to the scene renderer output image.
