### ISSUE TITLE
Recommended way to share 'Time' uniform to filters

### ISSUE THREAD

**Issue by omarojo** [MetalPetal/MetalPetal#78]
Is very common for filters to require  'time' uniform to perform animations. 
What Im doing is creating a Singleton that runs a **CADisplayLink** and increments a **time** property, so that any filter class can access it from anywhere. 

**My problem:**  this works great for most of my filters, except one that internally in metal shading language runs Noise and random functions etc.. for some reason this filter runs great in iPhoneX and XSMax, but in **iPhone6** it makes the CADisplayLink to stop triggering, or triggers rarely, as well as freezing the UI. 

I tried setting the displaylink mode to **RunLoop.Mode.tracking**, setting that won't trigger not even once. 

Here is my Singleton

```
import UIKit
class G8Global: NSObject {
    static let shared = G8Global()
    public var time = 0.0;
    private var displayLink: CADisplayLink?
    
    private override init(){ //private because that way the class can only be initialized by itself.
        super.init()
        self.displayLink = CADisplayLink(target: self, selector: #selector(displayLinkDidRefresh(link:)))
        self.displayLink?.preferredFramesPerSecond = 30
        displayLink?.add(to: RunLoop.main, forMode: RunLoop.Mode.common)        
    }
    @objc func displayLinkDidRefresh(link: CADisplayLink) {
        self.time += 0.03
        print(time)
    }
    func invalidateTime(){
        displayLink?.invalidate()
    }
}
```
From my filter classes I only do `G8Global.shared.time` to get the current time.
But I have no idea what is my shader doing that causes the displayLink to hang, only in iPhone6 and only with that shader.

Do you have any suggestion on how to provide Time to the uniforms ?

**Comment by YuAo** [comment]
Make sure you pass the time to shader as Float not Double.

**Comment by omarojo** [comment]
@YuAo Im definitely passing it as Float
```
let tVal = G8Global.shared.time
glitch1Filter.time = Float(tVal)
```

```
class G8Glitch1_sh: MTIUnaryImageRenderingFilter {
    var time: Float
    
    override init() {
        time = Float(0.0)
        super.init()
    }
    . . . .
    
    override var parameters:[String : Any] {
        return [
            "time": time
        ]
    }
    
}
```

**Comment by YuAo** [comment]
Is the display link stop triggering or just there's something wrong with the filter?

**Comment by omarojo** [comment]
I believe is the DisplayLink having issues with the Main Thread. It stops triggering, then as soon as I switch to a different filter it resumes triggering. The Filter renders, because I can see myself in the camera moving even tho the displaylink is not updating time, so the filter is rendering but with a static time value. 

I tried using a **Timer** instead of a displaylink, instantiating in the init() method of the singleton.
```
DispatchQueue.main.async {
            self.timer = Timer.scheduledTimer(timeInterval: 0.03 , target: self, selector: #selector(self.timerTriggerd), userInfo: nil, repeats: true)
        }
```

That animates my filter with no issues. Except that.. if I touch the UI, then it freezes, specially a carousel scrollView. And wont trigger back until I deactivate the filter. 

As reference here is the shader: https://gist.github.com/omarojo/6c9eaee96b76b15fb532f76bef713c72

This is very weird.

**Comment by YuAo** [comment]
The suggestion is to run a GPU frame capture to profile your shader.

**Comment by omarojo** [comment]
Using the Timer instead of the DisplayLink Im able to make the filter render nicely.
(**with** the issue mentioned above)

and this is what I see in the Profiler. 
![image](https://user-images.githubusercontent.com/995265/56091229-0332a480-5e61-11e9-961e-9a42d8085daf.png)

it looks like almost 40ms versus ~5ms of other filters. and (Tiler, Renderer, Device) Utilization goes to 100% instantly. Could that be causing the RunLoop.main to get all messed up? 

I clicked the little "camera" icon in Xcode to see if I can get a Profile, but It hangs . What I find odd is that exactly the same shader code in OpenGL and WebGL runs fine in iPhone6.

**Comment by YuAo** [comment]
Looks like it is a shader performance issue. Try optimize your shader.

For instance: 
- Make a `half` (instead of `float`) version of `random`, `noise3D`, `snoise3D`, etc. Maybe modify the whole shader to use half precision.
- Making sure that metal `fast-math` is on.
- `bnR` and `bnR2` can share the same sample result, you do not need to call sample for both `bnR` and `bnR2`, you can save the sample result for `bnR` and use that in calculating `bnR2`
- Find a way to make the GPU frame capture work, and profile the shader in detail.

You can also attach your filter graph here, maybe we can find something unusual. You can get the filter graph by performing a quick look on the output `MTIImage` object.

**Comment by omarojo** [comment]
So I reduced the Camera FPS to 30fps (it was 60fps) 
and used a different Noise Function I found online. Now it works (DisplayLink doesnt freeze), but at 30fps :(

I will now try modifying the entire shader to `half` instead of `float` + those suggestions you mentioned. 

I'll report back.

**Comment by YuAo** [comment]
On the GPU side Metal and OpenGL should be at a same performance level with the same shader. But it's hard to make sure that your OpenGL and Metal shader compiles to the same GPU code. (e.g. OpenGL ES has precision qualifier, but Metal use `half` or `float`.)

Metal just gives you more options to optimize your render and the main performance boost with Metal happens on the CPU side.
