### ISSUE TITLE
Get Single Color Channel

### ISSUE THREAD

**Issue by onurgenes** [MetalPetal/MetalPetal#79]
Hello there,

I am trying to get R, G and B channels of image for compositing later.

This is what I've currently tried:

```swift
let options = MTIContextOptions()
        
guard let device = MTLCreateSystemDefaultDevice(), let context = try? MTIContext(device: device, options: options) else {
    return
}
        
imageView.context = context
        
guard let eximage = UIImage(named: "example") else { return }
guard let examp = CIImage(image: eximage) else { return }
let image: MTIImage = MTIImage(ciImage: examp).unpremultiplyingAlpha()

let filter = MTIRGBToneCurveFilter()
filter.blueControlPoints = [MTIVector(value: CGPoint(x: 0, y: 0)), MTIVector(value: CGPoint(x: 0, y: 0))]
filter.redControlPoints = [MTIVector(value: CGPoint(x: 0, y: 0)), MTIVector(value: CGPoint(x: 0, y: 0))]
filter.greenControlPoints = [MTIVector(value: CGPoint(x: 0, y: 0)), MTIVector(value: CGPoint(x: 1, y: 0))]
filter.inputImage = image
        
let filter2 = MTIRGBToneCurveFilter()
filter2.blueControlPoints = [MTIVector(value: CGPoint(x: 0, y: 0)), MTIVector(value: CGPoint(x: 1, y: 0))]
filter2.redControlPoints = [MTIVector(value: CGPoint(x: 0, y: 0)), MTIVector(value: CGPoint(x: 0, y: 0))]
filter2.greenControlPoints = [MTIVector(value: CGPoint(x: 0, y: 0)), MTIVector(value: CGPoint(x: 0, y: 0))]
filter2.inputImage = image
        
let filter3 = MTIRGBToneCurveFilter()
filter3.blueControlPoints = [MTIVector(value: CGPoint(x: 0, y: 0)), MTIVector(value: CGPoint(x: 0, y: 0))]
filter3.redControlPoints = [MTIVector(value: CGPoint(x: 0, y: 0)), MTIVector(value: CGPoint(x: 1, y: 1))]
filter3.greenControlPoints = [MTIVector(value: CGPoint(x: 0, y: 0)), MTIVector(value: CGPoint(x: 0, y: 0))]
filter3.inputImage = image
        
guard let outputImage = filter.outputImage else { return }
guard let outputImage2 = filter2.outputImage else { return }
guard let outputImage3 = filter3.outputImage else { return }
        
let compositeFilter = MTIMultilayerCompositingFilter()
compositeFilter.layers = [MTILayer(content: outputImage, contentRegion: CGRect(x: 0, y: 0, width: outputImage.size.width, height: outputImage.size.height), compositingMask: nil, layoutUnit: .pixel, position: CGPoint(x: 0, y: 0), size: outputImage.size, rotation: 0, opacity: 1, blendMode: .normal),
MTILayer(content: outputImage2, contentRegion: CGRect(x: 0, y: 0, width: outputImage2.size.width, height: outputImage2.size.height), compositingMask: nil, layoutUnit: .pixel, position: CGPoint(x: 0, y: 0), size: outputImage2.size, rotation: 0, opacity: 1, blendMode: .softLight),
MTILayer(content: outputImage3, contentRegion: CGRect(x: 0, y: 0, width: outputImage3.size.width, height: outputImage3.size.height), compositingMask: nil, layoutUnit: .pixel, position: CGPoint(x: 0, y: 0), size: outputImage3.size, rotation: 0, opacity: 1, blendMode: .softLight)]
compositeFilter.inputBackgroundImage = image
guard let compositeImage = compositeFilter.outputImage else { return }
imageView.image = outputImage
```

Am I missing something? Or are there any simpler method for this?

Thanks in advance.

**Comment by YuAo** [comment]
You can write a custom filter to do all these works in one filter.

Looks like subclassing the `MTIUnaryImageRenderingFilter` should fit your needs.
https://github.com/MetalPetal/MetalPetal#simple-single-input--output-filters

Your shader code can be something like this:

```
#include <metal_stdlib>
#include "MTIShaderLib.h"

using namespace metal;

  fragment float4 yourEffect(VertexOut vertexIn [[stage_in]],
                            texture2d<float, access::sample> sourceTexture [[texture(0)]],
                            sampler sourceSampler [[sampler(0)]]) {
        float3 color = sourceTexture.sample(sourceSampler, vertexIn.textureCoordinate).rgb;
        float output;
        output = softLightBlendSingleChannel(color.r, color.g);
        output = softLightBlendSingleChannel(output, color.b);
        return float4(float3(output), 1.0);
  }
```

**Comment by onurgenes** [comment]
This is my main function for testing:

```swift
let options = MTIContextOptions()
guard let device = MTLCreateSystemDefaultDevice(), let context = try? MTIContext(device: device, options: options) else {
    return
}
let kernel = MTIRenderPipelineKernel(vertexFunctionDescriptor: MTIFunctionDescriptor(name: MTIFilterPassthroughVertexFunctionName),
                                     fragmentFunctionDescriptor: MTIFunctionDescriptor(name: "splitChannel"),
                                     vertexDescriptor: nil,
                                     colorAttachmentCount: 3,
                                     alphaTypeHandlingRule: .general)
guard let image = UIImage(named: "example") else { return }
guard let ciimage = CIImage(image: image) else { return }
let mtiImage = MTIImage(ciImage: ciimage).unpremultiplyingAlpha()
let outputImages = kernel.apply(toInputImages: [mtiImage],
                                parameters: [:],
                                outputDescriptors: [MTIRenderPassOutputDescriptor(dimensions: MTITextureDimensions(cgSize: image.size), pixelFormat: MTLPixelFormat.r8Unorm),
                                                    MTIRenderPassOutputDescriptor(dimensions: MTITextureDimensions(cgSize: image.size), pixelFormat: MTLPixelFormat.r8Unorm),
                                                    MTIRenderPassOutputDescriptor(dimensions: MTITextureDimensions(cgSize: image.size), pixelFormat: MTLPixelFormat.r8Unorm)])

do {
    for image in outputImages {
        let outImage = try context.makeCGImage(from: image)
        let usableImage = UIImage(cgImage: outImage)
        print(usableImage)
    }
} catch {
    print(error)
}
```

And this is `SplitChannelOutput.metal`:

```metal
#include <metal_stdlib>
#include "MTIShaderLib.h"

using namespace metal;

typedef struct {
    float4 r [[color(0)]];
    float4 g [[color(1)]];
    float4 b [[color(2)]];
} SplitChannelOutput;

fragment SplitChannelOutput splitChannel(metalpetal::VertexOut vertexIn [[ stage_in ]],
                                         texture2d<float, access::sample> colorTexture [[ texture(0) ]],
                                         sampler colorSampler [[ sampler(0) ]]) {
    float4 color = colorTexture.sample(colorSampler, vertexIn.textureCoordinate);
    SplitChannelOutput output;
    output.r = float4(float3(color.r), 1.0);
    output.g = float4(float3(color.g), 1.0);
    output.b = float4(float3(color.b), 1.0);
    return output;
}
```

When I use this, I get: `MTIErrorFunctionNotFound`. Am I missing something here?

**Comment by YuAo** [comment]
You need to specify the library url of the custom shader function. Typically the compiled shader library is called default.metallib and placed in the main bundle.  You can also use the MTIDefaultLibraryURLForBundle function.

By default MetalPetal only search the default shader library in its framework bundle.

**Comment by YuAo** [comment]
Also if you change the pixel format to r8Unorm you should also change the output color type in your SplitChannelOutput from float4 to float. A pixel in the r8Unorm texture can only have one color component.

**Comment by onurgenes** [comment]
What should I use as default for this?

**Comment by YuAo** [comment]
I think you can just write MTIFunctionDescriptor(name: “splitChannel”, libraryURL: MTIDefaultLibraryURLForBundle(.main))

**Comment by onurgenes** [comment]
Yes, I made it work but it just returns RED image.

This is the final function:

```swift
let options = MTIContextOptions()
guard let device = MTLCreateSystemDefaultDevice(), let context = try? MTIContext(device: device, options: options) else {
    return
}

let kernel = MTIRenderPipelineKernel(vertexFunctionDescriptor: MTIFunctionDescriptor(name: MTIFilterPassthroughVertexFunctionName),
                                     fragmentFunctionDescriptor: MTIFunctionDescriptor(name: "splitChannel",
                                                                                       libraryURL: MTIDefaultLibraryURLForBundle(.main)),
                                     vertexDescriptor: nil,
                                     colorAttachmentCount: 3,
                                     alphaTypeHandlingRule: .general)
guard let image = UIImage(named: "example") else { return }
guard let ciimage = CIImage(image: image) else { return }
let mtiImage = MTIImage(ciImage: ciimage).unpremultiplyingAlpha()
let outputImages = kernel.apply(toInputImages: [mtiImage],
                                parameters: [:],
                                outputDescriptors: [MTIRenderPassOutputDescriptor(dimensions: MTITextureDimensions(cgSize: image.size), pixelFormat: MTLPixelFormat.r8Unorm),
                                                    MTIRenderPassOutputDescriptor(dimensions: MTITextureDimensions(cgSize: image.size), pixelFormat: MTLPixelFormat.r8Unorm),
                                                    MTIRenderPassOutputDescriptor(dimensions: MTITextureDimensions(cgSize: image.size), pixelFormat: .r8Unorm)])

do {
    for image in outputImages {
        let outImage = try context.makeCGImage(from: image)
        let usableImage = UIImage(cgImage: outImage)
        print(usableImage)
    }
} catch {
    print(error)
}
```

**Comment by YuAo** [comment]
Because each output image only contains one color component so it cannot be color image. How the image look does not matter, its red because the renderer stores the channel data to the output image’s r channel, as the pixel format implies “R8”. The benefits here is the r8 image only takes 1/4 memory of the bgra8 image.

**Comment by onurgenes** [comment]
Understood. But I need Red, Green and Blue channels separately because I will combine them to make a kind of Glitch effect. I've tried bgra8 but it returned `fragment shader color output does not have enough components for the pixel format (MTLPixelFormatBGRA8Unorm)`.

I couldn't make it work. 😅

**Comment by YuAo** [comment]
Once you finish processing each channel of the image, you can write another custom shader to take all the 3 one channel images and merge them to a color image.

Or if you prefer convenience over performance, you can use `MTLPixelFormatBGRA8Unorm` pixel format, and change the output pixel type of SplitChannelOutput back to float4. And write each channel to the corresponding color component. Like `output.r.r = color.r; output.r.a = 1.0; output.g.g = color.g; output.g.a = 1.0; .....`

**Comment by onurgenes** [comment]
I made it work. Thanks for your support. I appreciate it. 🎉

**Comment by CaichaoGitHub** [comment]
> You can write a custom filter to do all these works in one filter.
> 
> Looks like subclassing the `MTIUnaryImageRenderingFilter` should fit your needs. https://github.com/MetalPetal/MetalPetal#simple-single-input--output-filters
> 
> Your shader code can be something like this:
> 
> ```
> #include <metal_stdlib>
> #include "MTIShaderLib.h"
> 
> using namespace metal;
> 
>   fragment float4 yourEffect(VertexOut vertexIn [[stage_in]],
>                             texture2d<float, access::sample> sourceTexture [[texture(0)]],
>                             sampler sourceSampler [[sampler(0)]]) {
>         float3 color = sourceTexture.sample(sourceSampler, vertexIn.textureCoordinate).rgb;
>         float output;
>         output = softLightBlendSingleChannel(color.r, color.g);
>         output = softLightBlendSingleChannel(output, color.b);
>         return float4(float3(output), 1.0);
>   }
> ```
> 
> However, if you really need to split the channels. You can create a multi-output filter:
> 
> 1. Create a shader function writes to multiple render target.
> 
> ```
> typedef struct {
>             float4 r [[color(0)]];
>             float4 g [[color(1)]];
>             float4 b [[color(2)]];
> } SplitChannelOutput;
>         
> fragment SplitChannelOutput splitChannel(VertexOut vertexIn [[ stage_in ]],
>                                                        texture2d<float, access::sample> colorTexture [[ texture(0) ]],
>                                                        sampler colorSampler [[ sampler(0) ]]) {
>             float4 color = colorTexture.sample(colorSampler, vertexIn.textureCoordinate);
>             SplitChannelOutput output;
>             output.r = float4(float3(color.r), 1.0);
>             output.g = float4(float3(color.g), 1.0);
>             output.b = float4(float3(color.b), 1.0);
>             return output;
> }
> ```
> 
> 2. Create a `MTIRenderPipelineKernel`, set the `colorAttachmentCount` to `3`.
> 3. Using the `MTIRenderPipelineKernel` to apply the shader to an image and get multiple images out. Be sure to create `3` `MTIRenderPassOutputDescriptor`s.
> 
> You can refer to the "hexagonalBokehBlurAlpha" shader function in `MTIHexagonalBokehBlurFilter`.
> 
> And consider using `MTLPixelFormatR8Unorm` pixel format for the single channel image, and using `float` instead of `float4` in the `SplitChannelOutput`

how about create A RGB Texture ?  i found the metal pixel formats don't support RGB or BGR format , how could i convert the RGBA to RGB ? any suggestions ?

**Comment by YuAo** [comment]
@CaichaoGitHub You can use the `vImage.framework` https://developer.apple.com/documentation/accelerate/conversion
