### ISSUE TITLE
Couple more filters

### ISSUE THREAD

**Issue by sampil** [MetalPetal/MetalPetal#80]
Dear Author, hi!

Thank you so much for the great library! It incredibly efficient and fast, is working with sliders on-the fly and perfectly mixing 5+ filters with no lags!

I currently use 7 Metal Petal Filters in my App, but I miss some of (conventional) standard filters in awesome MetalPetal:
(This names are common for many apps, including Lightroom and VSCO)
1) Shadows (Highlights filter looks great using MTIExposureFilter though)
2) Grain (tried to play with Pixellate and Dot screen, failed)
3) White balance: Temperature and Hue
4) HSL: Adjusting Hue, Saturation and Lightness for each of 6 colours

Maybe MetalPetal already supports those actions, in that case please help to find out MP filters names. If I need to mix some of MP filters to achieve the goal, could you please give me a hint?
Or, maybe, custom filters must be implemented. Where to start from in that case?

Anyway, I am absolutely sure that having above mentioned tools built in Metal Petal could become a huge leap forward for this fantastic framework!

**Comment by YuAo** [comment]
Highlight/Shadow: There's no "standard" implementation for this filter. Apple's Photo App / Photoshop / Google's Snapseed / GPUImage / CoreImage they use different algorithms. It's hard to decide which one is more "standard", and what exactly the algorithm is. Anyway, there's an experimental brach "shadowhighlight", you can grab the MTIMPSShadowHighlightFilter and give it a try. https://github.com/MetalPetal/MetalPetal/blob/shadowhighlight/Frameworks/MetalPetal/Filters/MTIMPSShadowHighlightFilter.h

Grain: Many different implementations. See: https://www.shadertoy.com/results?query=grain 
And you can grab a shader an turn that into MetalPetal filter very easily. See https://github.com/MetalPetal/MetalPetal#build-custom-filter

White balance: Will consider. You can use the GPUImage's shader for now: https://github.com/BradLarson/GPUImage3/blob/master/framework/Source/Operations/WhiteBalance.metal

HSL: Will consider.

**Comment by sampil** [comment]
Wow, that was a journey!
Despite all your concrete instructions, I used to do a lot! Hopefully, this experience will help the MetalPetal development!

Firstly I faced that it is hard to pull the **shawhighlights branch of MetalPetal** using cocoapods. My steps:
1. Remove master MetalPetal using cocoapods
2. Download MetalPetal shadowshighlights branch
3. Copy Frameworks directory content to my project, groups creation is on
4. Create Bridging Header file using instructions from internet
5. #import "MetalPetal.h" inside Bridging Header
6. Change all lines of MetalPetal.h to style #import "MTIComputePipeline.h"
7. Build. Success! now MTIMPSShadowHighlightFilter is available!

Unfortunately, changing the shadows property of MTIMPSShadowHighlightFilter did not change anything. As workaround, I apply values to the highlights property with "-" sign, works well. So, shadows is done!

**Next, white balance: temperature and hue.**

I took this implementation as you advised: https://github.com/BradLarson/GPUImage3/blob/master/framework/Source/Operations/WhiteBalance.metal
But it uses different parameters and different type "half4". Intuitively, i rewrote this chunk of code to correspond other MetalPetal shaders:

`#include "MTIShaderLib.h"
#include <metal_stdlib>

using namespace metal;
using namespace metalpetal;

namespace metalpetal {
    namespace whitebalance {
        fragment float4 whiteBalance(VertexOut vertexIn [[stage_in]],
                                    texture2d<float, access::sample> sourceTexture [[texture(0)]],
                                    constant float &temperature [[buffer(0)]],
                                    constant float &hue [[buffer(1)]])
        {
            float3 warmFilter = float3(0.93, 0.54, 0.0);
            
            float3x3 RGBtoYIQ = float3x3(float3(0.299, 0.587, 0.114), float3(0.596, -0.274, -0.322), float3(0.212, -0.523, 0.311));
            float3x3 YIQtoRGB = float3x3(float3(1.0, 0.956, 0.621), float3(1.0, -0.272, -0.647), float3(1.0, -1.105, 1.702));
            
            
            constexpr sampler quadSampler;
            float4 color = sourceTexture.sample(quadSampler, vertexIn.textureCoordinate);
            
            float3 yiq = RGBtoYIQ * color.rgb; //adjusting tint
            yiq.b = clamp(yiq.b + hue*0.5226*0.1, -0.5226, 0.5226);
            float3 rgb = YIQtoRGB * yiq;
            
            float3 processed = float3(
                                    (rgb.r < 0.5 ? (2.0 * rgb.r * warmFilter.r) : (1.0 - 2.0 * (1.0 - rgb.r) * (1.0 - warmFilter.r))), //adjusting temperature
                                    (rgb.g < 0.5 ? (2.0 * rgb.g * warmFilter.g) : (1.0 - 2.0 * (1.0 - rgb.g) * (1.0 - warmFilter.g))),
                                    (rgb.b < 0.5 ? (2.0 * rgb.b * warmFilter.b) : (1.0 - 2.0 * (1.0 - rgb.b) * (1.0 - warmFilter.b))));
            return float4(mix(rgb, processed, temperature), color.a);
        }
    }
}`

And also created a swift class to manage this shader:

`class MTIWhiteBalanceFilter: MTIUnaryImageRenderingFilter {
    var temperature: Float = 0
    var hue: Float = 0
    
    override var parameters: [String : Any] {
        return ["temperature": temperature, "hue" : hue]
    }
    
    override class func fragmentFunctionDescriptor() -> MTIFunctionDescriptor {
        return MTIFunctionDescriptor(name: "whiteBalance", libraryURL: MTIDefaultLibraryURLForBundle(Bundle.main))
    }
}`

Everything works great! Now looking forward to the Grain filter. Thank you again! I'm ready to comment all details and to help anyone on the same path!

**Comment by YuAo** [comment]
You can just grab the shader and the code from the shawhighlights branch and make them your custom shader. It's not recommended to use the whole shawhighlights branch code, because it's not updated to catch up with the master branch.

For the white balance filter, you can use half type, you can change the fragment shader's return type to `half4` and the sourceTexture's type to  `texture2d<half, access::sample>`. In fact, it is more efficient to use half instead of float.

**Comment by sampil** [comment]
Thanks for guidelines. Keeping MP inside CocoaPods sounds reasonable. Unfortunately, my first try to use MTIMPSShadowHighlightFilter filter and my white balance shader as custom filters, failed. I'm planning to come back to this issue later and use MetalPetal's source code directly for now. 

As for the Grain filter. I coped with this trial, using the following way:

1. Create sample noise texture, for example using http://www.noisetexturegenerator.com/
2. Using copies of small texture create a 1000x1000 pixels (or more if needed) noise .png texture
3. Drop the file inside the app
4. Create MTIImage from the noise texture. I tried different ways, this one seems to be the best
```
private let grainMTImage: MTIImage = {
        if let cgImageGrain = UIImage(named: "noise1000.png")?.cgImage {
            let ciImageGrain = CIImage(cgImage: cgImageGrain)
            return MTIImage(ciImage: ciImageGrain).unpremultiplyingAlpha()
        } else {
            return MTIImage.transparent
        }
}()
```
5. Use BlendFilter with overlay blend mode: set Photo as backgroundImage and grainMTImage as inputImage. Intensity also may be adjusted.
6. Profit, 95% similar effect as VSCO

**Comment by YuAo** [comment]
@sampil Added CoreImage filter support on the master branch. You can now directly inject CoreImage filters to your MetalPetal filter chain. That means you have all these filters available https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html

Commit & API: https://github.com/MetalPetal/MetalPetal/commit/bd45bad73a2cd5c7798cb7cd2a19289abffe24f3

And here's an implementation of your 4th requested filter (HSL): 
https://flexmonkey.blogspot.com/2016/03/creating-selective-hsl-adjustment.html
https://github.com/FlexMonkey/Filterpedia/blob/master/Filterpedia/customFilters/MultiBandHSV.swift

Closing this issue now.

**Comment by Umity** [comment]
I am sorry to re-open this but i tried the HSL filter and the result was not good at all. It is causing a lot of harsh bandings. My instinct says that we should convert the from rgb to hsl/hsv then after the adjustmennts, we should convert back to rgb. Do you see any solution on this?

**Comment by ChanakyaHirpara** [comment]
> Thanks for guidelines. Keeping MP inside CocoaPods sounds reasonable. Unfortunately, my first try to use MTIMPSShadowHighlightFilter filter and my white balance shader as custom filters, failed. I'm planning to come back to this issue later and use MetalPetal's source code directly for now.
> 
> As for the Grain filter. I coped with this trial, using the following way:
> 
> 1. Create sample noise texture, for example using http://www.noisetexturegenerator.com/
> 2. Using copies of small texture create a 1000x1000 pixels (or more if needed) noise .png texture
> 3. Drop the file inside the app
> 4. Create MTIImage from the noise texture. I tried different ways, this one seems to be the best
> 
> ```
> private let grainMTImage: MTIImage = {
>         if let cgImageGrain = UIImage(named: "noise1000.png")?.cgImage {
>             let ciImageGrain = CIImage(cgImage: cgImageGrain)
>             return MTIImage(ciImage: ciImageGrain).unpremultiplyingAlpha()
>         } else {
>             return MTIImage.transparent
>         }
> }()
> ```
> 
>  5. Use BlendFilter with overlay blend mode: set Photo as backgroundImage and grainMTImage as inputImage. Intensity also may be adjusted.
> 6. Profit, 95% similar effect as VSCO

Hi Sampil,
Do you have reference source code so that I can understand it how you implemented grain filter.

Thank you
