### ISSUE TITLE
Usage Q - Render to MTLImage?

### ISSUE THREAD

**Issue by vade** [MetalPetal/MetalPetal#84]
Hello

Firstly, thank you for this project!

I have an existing metal app and I'd love to integrate MetalPetal filters, and I dont see an obvious way to 'render to a texture'. I have an existing texture I'd love to process via an existing command encoder / command buffer.

Im new to MetalPetal, so apologies If I don't see an obvious mechanism. Ive attempted to use a MTIImageRenderingContext to resolve the output of a filter to a texture, but received a 

`Context is peformaning a render-releated operation without aquiring the renderingLock.'` 

Error.

The code:

Create a context , image rendering context and a filter:
```
self.metalPetalContext = MTIContext(device: MTLCreateSystemDefaultDevice()!)
self.metalPetalImageRenderingContext = MTIImageRenderingContext(context: self.metalPetalContext)
self.metalPetalBilateralFilter = MTISurfaceBlurFilter(radius: 11)
```

Create a MTIImage from an existing image and process it through the filter:

```
let inputMTIDepthImage = MTIImage(texture: depthTexture!, alphaType: .alphaIsOne)
self.metalPetalBilateralFilter.inputImage = inputMTIDepthImage
do {
    let imageResolutionPromise = try self.metalPetalImageRenderingContext.resolution(for: self.metalPetalBilateralFilter.outputImage!)

    ... <<< receive error on the last line
}

```

**Comment by YuAo** [comment]
See https://github.com/MetalPetal/MetalPetal/issues/72

**Comment by YuAo** [comment]
Hi @vade 

Added a method to render to a texture.
https://github.com/MetalPetal/MetalPetal/commit/1ec18c5f58e5e49c264904fbf86f64b6762ab070

You may want to use the master branch to try this feature.

```
pod 'MetalPetal/Swift', :git => 'https://github.com/MetalPetal/MetalPetal.git'
```
