### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by vjdaemp** [MetalPetal/MetalPetal#85]
When running the latest sample application using the Instruments "Leaks" tool, there are over 1,000 memory leaks reported after opening the "Static Image Rendering" example. This occurred when running the app on device (iPhone XS).

Is this a known issue?

**Comment by YuAo** [comment]
It does not seem to be an issue. I believe it is a false positive report. 
https://forums.developer.apple.com/thread/115120
