### ISSUE TITLE
Alternative to may thread rendering

### ISSUE THREAD

**Issue by AllardDevDesign** [MetalPetal/MetalPetal#87]
Currently in the AVCaptureVideoDataOutputSampleBufferDelegate, I take the sample buffer, apply a filter, and render it to a MTIImageView on the main thread. This method however can drop frames and cause the rendering to lag slightly when the main thread becomes blocked. Is there an alternative way of rendering a camera video feed a view that doesn't require main thread?

**Comment by YuAo** [comment]
Yes. Instead of using MTIImageView, you can use a custom view with a CAMetalLayer.

CAMetalLayer can be accessed from non-main threads. You can use the MTIContext’s “render to drawable” method to perform the rendering. Just be sure not to modify any view related thing in the non-main thread.

**Comment by omarojo** [comment]
Wow.. i didnt know this could happen.
Would it be wise to add that to the framework ?

**Comment by YuAo** [comment]
@AllardDevDesign @omarojo 
Added an image view (`MTIThreadSafeImageView`) that does exactly what I said. You can give it a try. 
https://github.com/MetalPetal/MetalPetal/commit/eff5bc29a6b62d25a8cb74a0386830c447e42d8b

**Comment by AllardDevDesign** [comment]
Could you give some instructions for best practice of using this MTIThreadSafeImageView

**Comment by YuAo** [comment]
Just use it like a normal `MTIImageView` except you can set its image on any thread and the view renders its image immediately unlike the `MTIImageView`'s `setNeedsDisplay` mechanism.

**Comment by omarojo** [comment]
for some reason Im getting
```
MetalPetalDev/GenerateMetal-iOS/Pods/MetalPetal/Frameworks/MetalPetal/UI/MTIThreadSafeImageView.m:208
2019-06-19 17:37:55.740102-0700 GenerateMetal-iOS[759:155043] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Context is nil.'
*** First throw call stack:
```
But Im pretty sure Im assigning a `context` value to the `myrenderView.context`
before trying to render anything.

**Comment by YuAo** [comment]
@omarojo yes, nice catch. Fixed in the latest commit.
