### ISSUE TITLE
using Text 

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#89]
Hi, can I integrate SCNText to generate text using this lib? If you know the easier ways of rendering text to texture, I would be very happy if you share it. thanks for the answer.

**Comment by YuAo** [comment]
You may want to use a text layout manager and core graphics to render a pice of text to a CGImage, then create a MTIImage using the CGImage.

Here's a pice of code that may help.

```
static func renderSingleLineAttributedText(_ text: NSAttributedString, maximumBoundingSize: CGSize) throws -> MTIImage {
        let scale: CGFloat = 1.0
        let textStorage = NSTextStorage(attributedString: text)
        let layoutManager = NSLayoutManager()
        layoutManager.allowsNonContiguousLayout = true
        textStorage.addLayoutManager(layoutManager)
        let textContainer = NSTextContainer(size: maximumBoundingSize)
        textContainer.lineBreakMode = .byTruncatingTail
        textContainer.maximumNumberOfLines = 1
        textContainer.lineFragmentPadding = 0
        layoutManager.addTextContainer(textContainer)
        let range = layoutManager.glyphRange(for: textContainer)
        let usedRect = layoutManager.usedRect(for: textContainer).integral
        UIGraphicsBeginImageContextWithOptions(usedRect.size, false, scale)
        layoutManager.ensureLayout(for: textContainer)
        layoutManager.drawGlyphs(forGlyphRange: range, at: usedRect.origin)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        guard let cgImage = image?.cgImage else {
            throw Error.imageRenderFailure
        }
        return MTIImage(cgImage: cgImage, options: [.SRGB: false], isOpaque: false).unpremultiplyingAlpha()
    }
```

**Comment by alyfreym** [comment]
Hi, reading the documentation I saw this  extension
`extension MDLMesh {
    @available(iOS 9.0, *)
    public convenience init(scnGeometry: SCNGeometry)
    @available(iOS 10.0, *)
    public convenience init(scnGeometry: SCNGeometry, bufferAllocator: MDLMeshBufferAllocator?)
}`
 I had an idea, is it possible to write my own filter that will generate text, overriding pipeline coding methods? Short:
`   let text = SCNText(string: "WORLD", extrusionDepth: 0.0)
        text.font = UIFont.systemFont(ofSize: 50.0, weight: .bold)`

`let mesh = try! MTKMesh(mesh: MDLMesh(scnGeometry: text, bufferAllocator: MTKMeshBufferAllocator(device: device)), device: device)` 

And then use it to filter. This will allow rendering the text only on GPU, is very important to me, having a Vertex data, I can add a fire effect around the outline of the text. If it is possible, you can tell me please how to integrate this function in the framework?

**Comment by YuAo** [comment]
It is possible but requires a lot of work.

1. We'll need to inspect the `MTKMesh`, find out its vertex data layout, attributes, etc.
2. MetalPetal really focuses on 2D image processing, so the default render pipeline does not include the setup for depth buffer. New MTIKernel implementation or modifications to the current render pipeline kernel is needed to render the depth properly.
3. We may need to apply some sort of modal view transform to the mesh to fit it in the canvas. Maybe we'll need a camera system.

The suggestion is to render the SCNText is to place it in a SCNScene, using `SCNTechnique` to work with the vertex data and add your custom shader and effect. With `MTISCNSceneRenderer` you are able to create `MTIImage`s from the scene.

**Comment by alyfreym** [comment]
Yes, I noticed that you have integration with SceneKit, but in SCNRenderer missing Multi-Sampling, so when i render text,  edges is jagged((. Thank you for your reply.

**Comment by YuAo** [comment]
It seems that you can enable multisample for your text node using SCNTechnique. You can specify a lot of render settings including `samples` (The number of samples per pixel for enabling multisampled rendering for the drawing pass. Defaults to 1).

https://developer.apple.com/documentation/scenekit/scntechnique

**Comment by alyfreym** [comment]
Thanks for the reply, I will work on it.
