### ISSUE TITLE
Feature request:  Shadows/Highlights

### ISSUE THREAD

**Issue by vjdaemp** [MetalPetal/MetalPetal#91]
Any reason why Shadows/Highlights is not merged into master?

Disregard: I just saw that there is another issue open for this, #80

**Comment by gpapoyan95** [comment]
@vjdaemp here is my solution for Highlights/Shadows using MetalPetal

`//
//  HighlightShadow.metal
//  TNoize
//
//  Created by Gagik Papoyan on 10/16/20.
//  Copyright © 2020 Gagik Papoyan. All rights reserved.
//

#include "MTIShaderLib.h"
#include <metal_stdlib>
#include "OperationShaderTypes.h"

using namespace metal;
using namespace metalpetal;

fragment float4 highlightShadowFragment(VertexOut vertexIn [[stage_in]],
                                texture2d<float, access::sample> inputTexture [[texture(0)]],
                                constant float & shadows [[ buffer(1) ]],
                                constant float & highlights [[ buffer(2) ]])
{
    constexpr sampler quadSampler;
    float4 color = inputTexture.sample(quadSampler, vertexIn.textureCoordinate);
    
    float luminance = dot(color.rgb, float3(0.3, 0.3, 0.3));

    //(shadows+1.0) changed to just shadows:
    float shadow = clamp((pow(luminance, 1.0/shadows) + (-0.76)*pow(luminance, 2.0/shadows)) - luminance, 0.0, 1.0);
    float highlight = clamp((1.0 - (pow(1.0-luminance, 1.0/(2.0-highlights)) + (-0.8)*pow(1.0-luminance, 2.0/(2.0-highlights)))) - luminance, -1.0, 0.0);
    float3 result = float3(0.0, 0.0, 0.0) + ((luminance + shadow + highlight) - 0.0) * ((color.rgb - float3(0.0, 0.0, 0.0))/(luminance - 0.0));
    // blend toward white if highlights is more than 1
    float contrastedLuminance = ((luminance - 0.5) * 1.5) + 0.5;
    float whiteInterp = contrastedLuminance*contrastedLuminance*contrastedLuminance;
    float whiteTarget = clamp(highlights, 1.0, 2.0) - 1.0;
    result = mix(result, float3(1.0), whiteInterp*whiteTarget);

    // blend toward black if shadows is less than 1
    float invContrastedLuminance = 1.0 - contrastedLuminance;
    float blackInterp = invContrastedLuminance*invContrastedLuminance*invContrastedLuminance;
    float blackTarget = 1.0 - clamp(shadows, 0.0, 1.0);
    result = mix(result, float3(0.0), blackInterp*blackTarget);
    
    return float4(result.rgb, color.a);
}
`
And here is swift class

`//
//  HighlighShadowFilter.swift
//  TNoize
//
//  Created by Gagik Papoyan on 10/16/20.
//  Copyright © 2020 Gagik Papoyan. All rights reserved.
//

import Foundation
import MetalPetal

public class HighlightShadowFilter: MTIUnaryImageRenderingFilter {
    
    var shadows:Float = 0.0
    var highlights:Float = 1.0
    
    public override var parameters: [String : Any] {
        return ["shadows": shadows, "highlights" : highlights]
    }
        
    public override class func fragmentFunctionDescriptor() -> MTIFunctionDescriptor {
        return MTIFunctionDescriptor(name: "highlightShadowFragment", libraryURL: MTIDefaultLibraryURLForBundle(Bundle.main))
    }
}
`

**Comment by YuAo** [comment]
https://github.com/MetalPetal/HighlightShadow
