### ISSUE TITLE
Lookup Filter

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#92]
Hi, I'm trying to use MTIColorLookupFilter,  but the result is wrong, can you tell me what's wrong? I uploaded  Color Lookup Table image.
![Polaroid Time Zero (Expired) 5 +](https://user-images.githubusercontent.com/29518174/60593933-3b40e800-9dbd-11e9-987f-cb6d6640f840.png)

`  let cg = UIImage(named: "lookup")!.cgImage! 
  let filter = MTIColorLookupFilter()
 filter.inputColorLookupTable = MTIImage(cgImage: cg, options: [MTKTextureLoader.Option.SRGB : true]).unpremultiplyingAlpha()                 
   filter.inputImage = inputImage`

**Comment by alyfreym** [comment]
Result 
![IMG_6164](https://user-images.githubusercontent.com/29518174/60594168-c3bf8880-9dbd-11e9-86ed-da9f2fa66284.jpg)

**Comment by YuAo** [comment]
We do not currently support this kind of color lookup table. 

The supported CLUT types are:

- 2D square. Like this one: https://github.com/MetalPetal/MetalPetal/blob/master/MetalPetalDemo/Assets.xcassets/ColorLookup512.imageset/lookup.png
- 2D horizontal. Like this one: https://github.com/MetalPetal/MetalPetal/blob/master/MetalPetalDemo/Assets.xcassets/ColorTableGraded.imageset/ColorTableGraded.png
- 2D vertical.

BTW, here's a tool we use to generate identity color lookup tables.  https://github.com/YuAo/IdentityCLUTImageGenerator

**Comment by alyfreym** [comment]
Is it possible to convert it into 2D square format?

**Comment by YuAo** [comment]
Yes, you can just re-apply the effect to a 2d square identity color lookup table image.

**Comment by alyfreym** [comment]
Thank you, I did it.
