### ISSUE TITLE
CGImage Rendering problem

### ISSUE THREAD

**Issue by alyfreym** [MetalPetal/MetalPetal#95]
HI!. I had a problem with the image rendering in `MTIImageView.` 1 - I load CGImage from URL. I get an error with some images - `NSLocalizedDescription=Image decoding failed, MTKTextureLoaderErrorKey=Image decoding failed`. (I attached this file it's called - error_image.PNG). Some images are rendered but not correctly. (I attached this file it's called - problem_image.HEIC). problem image I loading using this code - `MTIImage(cgImage: cgImage, options: [:], isOpaque: true)`. I made a screenshot of this problem, see below. 
![IMG_4B31F183340C-1](https://user-images.githubusercontent.com/29518174/61274753-d5ddf580-a7c5-11e9-90b0-53b2feb8e880.jpeg)

`I attached all the original resources in the archive.`
[resources.zip](https://github.com/MetalPetal/MetalPetal/files/3395828/resources.zip)

I ran some tests and found out if I create - 1 - `CIImage` from my `CGImage` and 2 - `init` `MTIImage` from `CIImage`.  In all cases, everything works well. I think that I should show certain parameters in `MTIImage (MTKTextureLoaderOption)  options` Can you please tell me if this is a problem?

**Comment by YuAo** [comment]
The first image has 16 bit color depth and the `MTKTextureLoader` can not decode the image. So `MTKTextureLoaderErrorKey=Image decoding failed` is reported.

The second image looks fine on my iPhone X running iOS 12.3.1. The MTIImage is created from a cgImage which is created from an UIImage.

---

You can resolve these kind of problems by implementing your own texture loader by conforming to the `MTITextureLoader` protocol. An example is `MTITextureLoaderForiOS9`.

For the `MTKTextureLoaderOption`, if you do not know what is `sRGB` and `linearRGB` and how to use them in a reasonable way, you the `[.SRGB: false]` option is recommended.

**Comment by alyfreym** [comment]
Thank you very much!

**Comment by larryonoff** [comment]
@YuAo I just faced with the same issue as for the second picture ("blued" image) that @alyfreym. So that my image is also "blued", after applying any `MTIFilter`

My input parameters are as recommended

```swift
MTIImage(
  cgImage: cgImage,
  options: [.SRGB : false],
  isOpaque: true
)
```

See affected `CGImage` print info below:
```
<CGImage 0x10a4c9500> (DP)
	<<CGColorSpace 0x2838121c0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)>
		width = 375, height = 375, bpc = 8, bpp = 32, row bytes = 1504 
		kCGImageAlphaPremultipliedFirst | 0 (default byte order)  | kCGImagePixelFormatPacked 
		is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? Yes
```

After some investigation I've found that the issue occurs with the following `CGImage` properties: `kCGImageAlphaPremultipliedFirst | 0 (default byte order)  | kCGImagePixelFormatPacked`

Wrap into `CIImage` works fine, except it really slows the performance. It's not acceptable for our application since we apply range of `MTIFilter` at once on e.g. slider change.

**Comment by larryonoff** [comment]
@YuAo I've solved the issue by converting from `kCGImageAlphaPremultipliedFirst` to `kCGImageAlphaPremultipliedLast`. It would be great doing it on the library level.

PS. Strange fact that issue disappears after copying the affected image into another Photo library.

**Comment by larryonoff** [comment]
It looks that `kCGImageAlphaPremultipliedFirst` is not the only reason. `(default byte order)` also causes the problem

**Comment by YuAo** [comment]
We wanted to build the texture loading system as thin as possible, so most of the texture loading in MetalPetal is done by `MTKTextureLoader` directly.

As more and more issues raise (#147 #95 #133 #26 ). I think it's time to consider a fallback mechanism.

@larryonoff 
For now, you can replace the texture loader in MetalPetal by setting the `defaultTextureLoaderClass`:
```
MTIContextOptions.defaultTextureLoaderClass = CustomTextureLoaderClass
``` 

Your texture loader needs to conform to the `MTITextureLoader` protocol.

Here's a reference implementation: https://github.com/MetalPetal/MetalPetal/blob/717360e71745df73a3bd2c65e6373143de83a260/Frameworks/MetalPetal/MTITextureLoaderForiOS9.m

**Comment by larryonoff** [comment]
@YuAo thank you for the reply! Looking forward for the updated default texture loader

**Comment by seadiem** [comment]
> We wanted to build the texture loading system as thin as possible, so most of the texture loading in MetalPetal is done by `MTKTextureLoader` directly.
> 
> As more and more issues raise (#147 #95 #133 #26 ). I think it's time to consider a fallback mechanism.
> 
> @larryonoff
> For now, you can replace the texture loader in MetalPetal by setting the `defaultTextureLoaderClass`:
> 
> ```
> MTIContextOptions.defaultTextureLoaderClass = CustomTextureLoaderClass
> ```
> 
> Your texture loader needs to conform to the `MTITextureLoader` protocol.
> 
> Here's a reference implementation: https://github.com/MetalPetal/MetalPetal/blob/717360e71745df73a3bd2c65e6373143de83a260/Frameworks/MetalPetal/MTITextureLoaderForiOS9.m

It worth to send a bug report to Apple
