### ISSUE TITLE
Black line in MTIImageView when display images.

### ISSUE THREAD

**Issue by donobono** [MetalPetal/MetalPetal#96]
HI.. I had a problem with the images rendering in MTIImageView.
Sometimes, when I display images, black line appear like attached screen.

![IMG_8387](https://user-images.githubusercontent.com/1480551/61346860-8d8e0880-a895-11e9-9343-9ee2e90025fc.JPG)

![IMG_8389](https://user-images.githubusercontent.com/1480551/61347163-d85c5000-a896-11e9-8509-7e5149ca136c.JPG)

I attach all source code for this test, please check this problem.
[MTTest.zip](https://github.com/MetalPetal/MetalPetal/files/3400147/MTTest.zip)

**Comment by YuAo** [comment]
The reason for the dark line is a little complicated. I'll use an example here: 
- The image you'd like to display is 448x248 pixels.
- The MTIImageView is 414x738 points on iPhone X, that is 1242 * 2214 pixels.
- The MTIImageView try to use as few pixels as possible to draw on the screen. In this case, the drawable size will be 448 x 799 pixels.
- The image will be placed in the center of the drawable, so the image's y is (799 - 248)/2 = 275.5
- There's half pixel here. The sampler may sample right on the edge of the image, the result will be a mix of the image's edge pixel value, and the pixel value of side the image.
- The default sampler's address mode is clamp to zero. Any samples that are outside the image will be black. So there's a gray line.

Here's a simple fix, change the address mode of the sampler to `.clampToEdge`
```
imageView.image = mtiImage.withSamplerDescriptor(.defaultSamplerDescriptor(with: .clampToEdge))
```

**Comment by donobono** [comment]
@YuAo 
Wow.. Solved!! 
Thank you so much!!

**Comment by vjdaemp** [comment]
@YuAo  I am also observing the "black line" when displaying image in `MTIImageView`. However, the fix to change the address mode of the sample to `.clampToEdge` did not work for me.

Below is my code related to `MTIImageView`:

```
finalImage.isUserInteractionEnabled = true
finalImage.isOpaque = false
finalImage.clearColor = MTLClearColor.init(red: 0, green: 0, blue: 0, alpha: 0)
finalImage.image = result.withSamplerDescriptor(.defaultSamplerDescriptor(with: .clampToEdge))
```

Is there another property that I have to set in addition to the ones that I have set?

Thanks

**Comment by YuAo** [comment]
@vjdaemp How about setting the background color of the image view to `clear`? Does the black line appear when you create a CGImage from the `finalImage`.

**Comment by vjdaemp** [comment]
@YuAo Setting the background color of the `MTIImageView` does not help. The black line **does not** appear when `CGImage` is created from the `finalImage`.

**Comment by vjdaemp** [comment]
@YuAo  I added a sample project that replicates the error.  After you tap the "Button", you will see the black line around borders on photo.

![IMG_4828](https://user-images.githubusercontent.com/12041809/80038908-8a7b1500-84c4-11ea-9f09-89f03d0660bb.PNG)

[Sample.zip](https://github.com/MetalPetal/MetalPetal/files/4519227/Sample.zip)

**Comment by YuAo** [comment]
@vjdaemp Looks like a problem with your `resizeImageWithAspectFit` method.

`CGImage`s can only have integer width and height (`size_t CGImageGetWidth(CGImageRef image)` returns `size_t`).  If you give the graphics renderer non-integer width and height the renderer will try to do some interpolation with the image border to make it **looks like** it has non-integer width and height.

Adding the `ceil` or `floor` to the width and height to ensure sharp borders.

```
// line 88
let rect = CGRect(x: 0, y: 0, width: ceil(newSize.width), height: ceil(newSize.height))
```

**Comment by vjdaemp** [comment]
@YuAo Thank you very much for the detailed response. I overlooked the error in my image resizing code. After using the ceil function to ensure integer width and height, I no longer observed the black line. The additional details about `premultiplyingAlpha` is great to know and will help in future.
