### ISSUE TITLE
Demo cannot build on Mac OS 10.14

### ISSUE THREAD

**Issue by ychding11** [MetalPetal/MetalPetal#97]

**Comment by YuAo** [comment]
Any error information? Screenshots?

**Comment by ychding11** [comment]
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'MetalPetalDemo')

**Comment by ychding11** [comment]
There is no MacOS target in xcodeproj file.

**Comment by YuAo** [comment]
MetalPetal is supported on macOS 10.13+ with Xcode 10.0+. The compiler you are using does not support Swift 5.0, you need to upgrade Xcode.

The demo project is for iOS. No demo is provided for macOS currently.
